### ISSUE TITLE
Update text that displays on deposit form when collection manager sets visibility

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1002]
The fix for #697 results in the text that is displayed saying either

"The files in your deposit will be downloadable by stanford."
OR 
"The files in your deposit will be downloadable by world."

See Design Doc for the various scenarios: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.n5g71obk0sxl

These should say

"The files in your deposit will be downloadable by Stanford community members only."
OR
"The files in your deposit will be downloadable by anyone."

**Comment by amyehodge** [comment]
@astridu I'd like this statement to be a bit more obvious in the interface. Can you suggest a different font or format? 

Here's how it looks currently:

![Screen Shot 2021-02-02 at 3.20.58 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/88169342-a820-49cc-b4ad-bec75c5f0730)

**Comment by astridu** [comment]
Is this noticeable enough, or do you think it needs some asterisks around it? I could also put an arrow icon next to it to call it out.
![image](https://user-images.githubusercontent.com/42216982/106686901-093acd80-6580-11eb-9a13-de32b60c7609.png)

**Comment by amyehodge** [comment]
@astridu Let's not do asterisks. I'm fine with this. Thanks.
