### ISSUE TITLE
When a user deposits a collection, they should be taken to the collection view page, not the dashboard.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1003]
This would mimic the behavior of depositing an item, after which the user is taken to the item view page.

**Comment by jcoyne** [comment]
@amyehodge should this be the behavior for any user depositing a collection?  A "manager" is a role within a collection, so it's a bit confusing about why "manager" is called out explicitly.

**Comment by amyehodge** [comment]
Only managers can deposit a collection is why it's called out specifically. So, in this case, any user who deposits a collection is really the same as any user. (Just to be clear, this is about depositing a collection, not depositing an item into a collection.)

**Comment by jcoyne** [comment]
@amyehodge currently anyone in the `dlss:hydrus-app-collection-creators` workgroup can create collections. I don't think this is the same as managers.

**Comment by amyehodge** [comment]
@jcoyne Excellent point. So, to clarify -- when any user clicks the deposit button for a collection, for either the initial deposit of a collection or a new version, they should be taken to the collection view page, not the dashboard. I have changed "Manager" to "user" in the ticket title.
