### ISSUE TITLE
When manager allows depositor to choose a license, the manager's selection for the default should display as the default for the user

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1004]
Some discussion on #837.

**Comment by jermnelson** [comment]
Hi @amyehodge, could you confirm that this issue is still a bug? I am unable to replicate it both locally and on stage. Thanks!

**Comment by amyehodge** [comment]
Yes. See collection https://sul-h2-stage.stanford.edu/collections/182 which is set for ODC-By-1.0. When I create an item in that collection, I see this, with CC-1.0 as the default.

![Screen Shot 2021-02-11 at 11 06 21 AM](https://user-images.githubusercontent.com/5558511/107685831-53dfd800-6c59-11eb-970f-0553da16e9bf.png)
