### ISSUE TITLE
Approvals should be visible on the dashboard both to collection reviewers and to collection managers

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1005]
I submitted the item in the February Review Collection at the bottom of this screenshot for approval a little while ago and it is not showing up in the Approvals table. In fact, this table hasn't updated in quite a while (at least days) and I know I've submitted more items for approval in that time. There is an item called "Submitted for your approval" (https://sul-h2-stage.stanford.edu/works/168) in the New Review Collection that should also be showing up in this table.

**Comment by amyehodge** [comment]
I initially thought this was a failure of the table to update, but after talking with @mjgiarlo, it may be that the manager is not set to be able to see this table or these items. This may be fallout from #661 (totally my guess, not @mjgiarlo 's).

**Comment by mjgiarlo** [comment]
I suspect we need to tweak this query to include both collection reviewers *and* collection managers: https://github.com/sul-dlss/happy-heron/blob/main/app/controllers/dashboards_controller.rb#L13-L15
