### ISSUE TITLE
Minor update to the text alignment in header

### ISSUE THREAD

**Issue by astridu** [sul-dlss/happy-heron#1014]
Could we update the text alignment in the header?
1. Put a • between Help and Logout. 
2. Right align Help/Logout with the Terms of Deposit.
![image](https://user-images.githubusercontent.com/42216982/106979466-38357880-6713-11eb-97e3-1d8a4a09ff8e.png)

**Comment by amyehodge** [comment]
The format of the header of changed so this ticket is no longer relevant.
