### ISSUE TITLE
Prevent unauthorized users from depositing

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/happy-heron#102]
Admit the user if:

* in `dlss:hydrus-app-adminstrators` LDAP workgroup
* in `dlss:hydrus-app-collection-creators` LDAP workgroup
* assigned reviewer role to one or more collections in the application (not yet implemented)
* assigned depositor role to one or more collections in the application (not yet implemented)

If the user is admitted, they see the dashboard. (What the dashboard renders depends on what roles are assigned to the user in the database.) 

If the user is not admitted, they get the [contact form modal](https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/428680772) loaded over the front page.

To do this:
* Grab groups from Shibboleth/WebAuth
* Denote authorized groups in config (shared_configs)
* Use ActionPolicy to authorize individual actions

See current Argo repo or hydra_etd repo for examples.

Rationale: We plan to use a combination of LDAP groups and application database records to determine what a user can access. We think we only need the one LDAP group to gate what happens when a user signs in.

**Comment by mjgiarlo** [comment]
@amyehodge How do you feel about how we described this issue? If it sounds OK to you, can you create the `dlss:h2-app-users` group and add yourself and us and others to it?

**Comment by justinlittman** [comment]
Blocked until here back from @amyehodge.

**Comment by amyehodge** [comment]
@mjgiarlo I'm not sure I'm fully understanding this. So, in H2 we will manage users by a workgroup. This means to give someone access to H2 we must both 1) assign that person to this workgroup AND 2) assign them the correct privileges? We currently manage collection creators via a workgroup. 

Does that mean we will need two different workgroups (one a subset of the other, perhaps)? Or can that be done in a single step if the workgroups are nested?

And for a depositor who wants access to say, Stanford Research Data Collection, I will need to assign them to the workgroup and then also assign them depositor privileges in the collection record within H2? Or if I give them depositor collections to the right collection, with the workgroup automatically pick them up?

**Comment by mjgiarlo** [comment]
@amyehodge let's chat about this as a group. if we don't have time for it during our meeting tomorrow, let's create a one-off meeting to chat. cc: @jcoyne @peetucket

**Comment by jmartin-sul** [comment]
(i only assigned this because i was implementing what i thought might be part of it in the course of working on #107, but haven't done that much toward it, and will check in at standup to see if i should continue doing what i'm doing)
