### ISSUE TITLE
Add Terms of Deposit link to header on all pages

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1022]
See example in wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/428088403

When clicked, this should bring up the Terms of Deposit modal.

**Comment by mjgiarlo** [comment]
@peetucket @amyehodge When I browse to https://sul-h2-stage.stanford.edu/, I see this link in the header and it renders the modal. Can we close this or is there more work to be done? (Trying to clear out Review/QA tickets that may not need to be in Review/QA.)

**Comment by amyehodge** [comment]
@mjgiarlo I thought the same thing about this ticket yesterday, but never got around to sending a note about it. Looks good to me.
