### ISSUE TITLE
Create modal for return user with draft in progress

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1023]
Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.h2zjcerd6r6x
Wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/418179458

**Comment by jcoyne** [comment]
I'm unclear as to when this should appear.  Do we want it every time they come to the dashboard?

**Comment by amyehodge** [comment]
This should appear any time a user logs in if they have at least one item or collection in progress. We should display the title for the most recent one and link to that item. Only the most recent work should display, and they should not receive any further notices, even if they have multiple works in progress.

**Comment by jcoyne** [comment]
The problem is that, they didn't log in on the page where this is displaying, so it's not "any time a user logs in".   They might have gone directly to an edit page, and on the way had to log in.  Would you want to show this on an edit page too?

**Comment by amyehodge** [comment]
Ah, I see. No. Let's say "Any time a user logs in from the home page". Does that work?

**Comment by jcoyne** [comment]
I think we can do that.  What if they have multiple drafts in progress? Do you want one window after another to pop-up?

**Comment by amyehodge** [comment]
Nope. Just one window for the most recent one.

**Comment by amyehodge** [comment]
@jcoyne I'm not seeing this funcationality. I have a draft in progress. I log out. When I log back in, I am not presented with the modal.
