### ISSUE TITLE
Add tooltips to the Work Type modal

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1030]
These are the little blue circles with the white "i" in them.

Note that the "which collection will you deposit to" part that is in the tooltips doc does not exist in the work type modal (just the first use modal), so you don't need to worry about that one here.

See Tooltips doc for text: https://docs.google.com/document/d/1gjvqYXmwMpMGWTdZynoHtxDgQVTt9fGn7QGVE4uhXXQ/edit#heading=h.v2a0c7kuvnie

See wireframes for locations: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/431445056

**Comment by jcoyne** [comment]
@amyehodge I don't think that's the correct wireframe screen.

**Comment by amyehodge** [comment]
@jcoyne this looks like the right wireframe to me. Maybe the confusion is that the appropriate section of the tooltips document describes both this modal and the first use modal -- some of which does not apply here.
