### ISSUE TITLE
Set title, default citation, and related published works fields to text area

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1032]
Make the title, default citation, and related published works fields set to text area

Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.m9amxw2cnrun

**Comment by jcoyne** [comment]
@amyehodge can you specify if they are expandable to multi-line or single line?  See https://github.com/sul-dlss/happy-heron/issues/791 some fields like "contact email" and "URL" can not be multi-line.

**Comment by amyehodge** [comment]
@astridu Can you help with this question?

**Comment by astridu** [comment]
Multi-line for all of them except e-mail and URL. Thanks!

**Comment by amyehodge** [comment]
@jcoyne and @astridu Can we get the title, default citation, and related published works fields se to text area? That seemed to be an easier fix previously and would address the biggest issues on this page, I think. Thanks.
