### ISSUE TITLE
Add share icon to dashboard and item show pages and link to pop-up with sharing options

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1034]
Dashboard
Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#bookmark=id.g59mgj5tg7vn
Wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/433047903

Item view page
Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.p9kk10jd9f3x
Wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/420930436

**Comment by amyehodge** [comment]
@justinlittman and @jcoyne I'm just now seeing that this ticket appears to overlap with #427.

**Comment by justinlittman** [comment]
@amyehodge @astridu I've spend several hours working on implementing this, but encountered some difficulties. This is similar to a [Bootstrap popover](https://getbootstrap.com/docs/5.0/components/popovers/#overview) but the Bootstrap popover is primarily intended to include text content, not HTML. While I can get it to render HTML, it doesn't render some components (e.g., buttons) and handle dynamic actions (e.g., copy to clipboard).

After discussion with @jcoyne, we concluded that getting this to work as designed will require a custom component. This is a significant amount of work, especially to get the accessibility correct.

I would suggest that this is a minor feature and not worth the effort. As an alternative, we might just consider putting a copy icon next to the PURL, allowing the user to copy the PURL and place into a tweet (or equivalent). Thoughts?

**Comment by amyehodge** [comment]
@justinlittman Thanks for delving into this. The Cite link in the tables actually already has a copy link for the full citation. I'm wondering if we could put a copy link for the PURL alone in there? Or maybe we don't need that. The easy access to the social media was the point here. 

@hannahfrost Do you have any thoughts/opinions on this? Maybe in the end this would be better as a feature on the PURL page itself (whenever Access Team has time). ??

**Comment by justinlittman** [comment]
A copy link to the PURL alone would be easy (but also happy to go with nothing).

**Comment by amyehodge** [comment]
@justinlittman I talked to @astridu about this. Let's just put the copy icon next to the PURL instead of the share button and have that copy the PURL link.
