### ISSUE TITLE
Add SUNet ID lookup for adding collection participants to collection edit page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1036]
When a collection manager types in a SUNet ID to the entry fields for manager, depositor, or reviewer, the IDs should retrieve available information about the person so that the manager can verify they are entering the correct user. I'd like to see name, title, and SUNet returned, something like the way the Stanford Workgroup manager functions:

![Screen Shot 2021-02-05 at 5.05.29 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/5d528faa-25f9-4bf2-8a5b-fd204a2d1aaf)

though the button to add is maybe not necessary. I'm totally willing to further discuss the details of how this might work and how we can get something both useful for users and easily doable.

**Comment by jcoyne** [comment]
I'm not sure we have access to this information or how we can get access to it.

**Comment by jcoyne** [comment]
I believe we need access to the Person API (https://uit.stanford.edu/developers/apis/person) to implement this. 
https://uit.stanford.edu/developers/apis/getting-started

**Comment by jcoyne** [comment]
I opened a serviceNow ticket: RITM00181912 https://stanford.service-now.com/it_services?sys_id=60924ff88728b0d09b23bbb9cebb3563&id=ticket&table=sc_req_item

**Comment by jcoyne** [comment]
Now changing tack to retrieve this via https://accountws.stanford.edu (e.g. `curl https://accountws.stanford.edu/accounts/jcoyne85`) However, we need a cert signed first:
https://github.com/sul-dlss/operations-tasks/issues/2636

**Comment by jcoyne** [comment]
We now have a way of retrieving this information (see https://github.com/sul-dlss/happy-heron/pull/1766) do we have a design for what this should look like on the page?

**Comment by amyehodge** [comment]
@astridu Can you assist with this? I don't believe we mocked up anything for us yet. One option is that these appear in a pop-up window like the example I have above works.

**Comment by astridu** [comment]
Proposed design
![image](https://user-images.githubusercontent.com/42216982/124982424-86fd7c00-dfeb-11eb-95c7-014a7caccb12.png)

**Comment by jcoyne** [comment]
We aren't doing a search for a user in this case. We are just looking up the name of the user id (sunet) we typed in. So the design above isn't going to work.

**Comment by amyehodge** [comment]
@jcoyne That's my mistake. This takes the request a step further and I didn't register that when @astridu passed this by me.

I think the actions will look like this:
1. user types in a complete SUNet ID (or what they think is)
2. user clicks a button that says "search" or something like that
3. if it's a valid SUNet ID, information related to that user is returned --  name, title, department -- so that the user can verify it's the correct ID 
4. if it's not a valid SUNet ID, nothing is returned and the user needs to figure out what the actual ID to enter should be.

@jcoyne does that sound like what you were thinking?

**Comment by jcoyne** [comment]
Yes.

**Comment by jcoyne** [comment]
@astridu have you been able to work on the updated design for reviewers/managers/depositor field that includes the names?

**Comment by astridu** [comment]
@jcoyne @amyehodge Let me know if this will work.
1. When user first arrives on this page, they see the lookup boxes. 
![image](https://user-images.githubusercontent.com/42216982/125869007-5c4f399c-23af-4d4c-8f4a-245f0fed3b66.png)

2. When user enters a SUNet and clicks the magnifying glass, search results are returned in a small box below the search box.  User can click the 'Add' button next to the user if that is the correct user. Otherwise, they can search again.
![image](https://user-images.githubusercontent.com/42216982/125869046-3962f07e-2ac0-4fdf-a660-27e11648cc04.png)

3. Once user has at least 1 manager and 1 depositor, the '+Add another...' button appears for both
![image](https://user-images.githubusercontent.com/42216982/125869180-6abc9238-8ab1-4d0e-a712-076eee23f6c9.png)

4. If they click '+Add another...' they'll see the search box appear, and they can use it as they did before. 
![image](https://user-images.githubusercontent.com/42216982/125869898-b88bfa0c-e0b3-48d0-ab54-04d481cecd6b.png)

**Comment by jcoyne** [comment]
@astridu should there be a way to remove managers and depositors?

**Comment by amyehodge** [comment]
@jcoyne Good point. Trash can icons by each entry, perhaps?

And what happens when there is no match? Someone might enter "stacemaples" but this should not return a result because it's an alias, not a real SUNet ID. The real ID is "maples". @jcoyne I think the plan is to only search for real SUNet ID and only return the exact match. If you don't get what you thought because you did not enter a real SUNet or the correct one, then you need to go figure out what the correct one should be. Which makes me a think that a link to Stanford Who in this section might be helpful, in case you don't have the right ID. So, text that says "Find a SUNet ID" perhaps, linking to https://stanford.rimeto.io/.

**Comment by amyehodge** [comment]
@astridu We're also going to want this in the reviewers section.

**Comment by astridu** [comment]
If no match returns, then they would see something like this:
![image](https://user-images.githubusercontent.com/42216982/125986615-5dee9230-299c-4707-9d86-7c9b316956e9.png)

**Comment by astridu** [comment]
I updated the mockups above w/trash cans. If they delete the only manager/depositor listed, clicking the trash icon should remove that person and then display the search box so user can enter in another name.

**Comment by astridu** [comment]
Reviewers
![image](https://user-images.githubusercontent.com/42216982/125987708-95ce2b19-86b4-442f-be06-c0f5b195d621.png)

**Comment by amyehodge** [comment]
@jcoyne Do you have further questions here or is this one ready for the Ready column?

**Comment by jcoyne** [comment]
@amyehodge this is already in the "in progress column" it just got stalled for a few weeks on the designs. We're able to continue with it now.

**Comment by jcoyne** [comment]
@astridu we don't want that text that says "Separate each one with a comma and a space..." in the reviewers section, do we?

**Comment by amyehodge** [comment]
@jcoyne no, we don't want that text if each one is in its own box.
