### ISSUE TITLE
Cannot create a draft collection with an invalid or missing email address

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#1044]
You should be able to create a draft collection without submitting any data, but new validation code prevents this from happening with no user interface clues.

To reproduce:

1. Create a new collection.
2. Fill in only the title.  Click "Save as Draft".
3. It doesn't seem to do anything (but if you look at the rails console, you will see it returned a 422 and re-rendered the page but no messages).  
4. Click "Save as Draft" again and get an exception.

I believe this is because the collection object is not returning as valid from the `DraftCollectionForm` causing the 422 from here: https://github.com/sul-dlss/happy-heron/blob/main/app/controllers/collections_controller.rb#L31-L35

The `DraftCollectionForm` needs to allow the entering of no email addresses to be valid (at the draft level) so it can be saved: https://github.com/sul-dlss/happy-heron/blob/main/app/forms/draft_collection_form.rb#L41-L47

**Comment by amyehodge** [comment]
Confirmed -- except that I can't see the rails console or the exception. Both times it seems not to do anything. After the second time the save as draft and deposit buttons are greyed out. I can only click cancel and am warned as I should be that changes will not be saved. The collection does not show up on the dashboard, so I assume it was not saved.
