### ISSUE TITLE
Support a list of licenses that can’t be chosen but can be displayed

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1047]
This is necessary for migrating content from Hydrus that has licenses that we are not supporting in H2.

When items with unsupported licenses are migrated, the depositor should see the license they previously chosen, e.g. a CC 3.0 license, displayed on the item show page. When the user versions this item, they will be required to choose one of the valid H2 license options in order to be able to deposit the new version.

Content in draft that has a license assigned will be required to choose a new license, unless that license was set by the collection manager already.

**Comment by amyehodge** [comment]
Just as an FYI, for the case of collection settings, we are okay mapping over any required license or default license option to the new version of the license, because this doesn't actually change the license on any existing works. All existing works will maintain their existing license, and all new works will be required to choose based on the updated license settings. We'll include this update to the licenses in our communications out to collection managers when we launch H2.

**Comment by amyehodge** [comment]
These are the licenses that should be displayable but not selectable:
The 3.0 versions of these:
CC BY
CC BY-SA
CC BY-ND
CC BY-NC
CC BY-NC-SA
CC BY-NC-ND (edited)

**Comment by jcoyne** [comment]
Use the SPDX identifiers for these please: https://spdx.org/licenses/  (e.g. CC-BY-3.0)
