### ISSUE TITLE
Update home page design

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1048]
See wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/444274365
See Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.5ixukddz43wy

**Comment by amyehodge** [comment]
@hannahfrost Please put the embed code for the newsletter signup on this ticket. Thanks!

**Comment by hannahfrost** [comment]
The code for the Mailchimp sign-up form is below. I've included the line of text "Sign up for our newsletter" in the form. This format should match the layout in the wireframes, but there are other form formatting options to try if need be.


<link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; width:100%;}
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://stanford.us20.list-manage.com/subscribe/post?u=139e1b2d3df8f8cacd77c8160&amp;id=4f4148a871" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<label for="mce-EMAIL">Sign up for our newsletter</label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_139e1b2d3df8f8cacd77c8160_4f4148a871" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
