### ISSUE TITLE
When a collection is in draft state, include "Draft" after the collection title in the admin table on the dashboard

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1049]

**Comment by jcoyne** [comment]
@astridu do you have input on font/size/color/style here?

**Comment by astridu** [comment]
Same font as the collection title but in italics. 
![image](https://user-images.githubusercontent.com/42216982/108136457-f25fa500-706e-11eb-9545-373917a56aef.png)

**Comment by amyehodge** [comment]
@astridu That's not the location where I want these. I want them next to the collection titles in this table:

![Screen Shot 2021-02-16 at 4 09 12 PM](https://user-images.githubusercontent.com/5558511/108137729-55523b80-7071-11eb-8439-621264da6419.png)

**Comment by astridu** [comment]
Sorry, in that case, just use italicized body text. For example,

[gates](#) _Draft_

**Comment by jcoyne** [comment]
@amyehodge  Do we need to differentiate between first draft and version draft or should we treat both the same?

**Comment by amyehodge** [comment]
If it's fairly easy to designate these as "Draft" and "Version draft" (or" Ver. Draft" perhaps, or even "V. Draft" if there are space constraints), that would be extra helpful. The number of the version is not needed. 

But just "Draft" for all cases would be sufficient. Thanks, @jcoyne
