### ISSUE TITLE
Add the ability to revert/discard an already saved collection in the database to the previous state it had when last deposited

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#1055]
Refer to #858, which is the equivalent functionality for reverting a work

Needs a new collection form design, currently in process

**Comment by amyehodge** [comment]
Related to #794, #1110, #1112

**Comment by jcoyne** [comment]
The equivalent work for a work was done in #1101

**Comment by amyehodge** [comment]
This seems to be working now.
