### ISSUE TITLE
Fix that saves the default citation option to whatever the user chose is no longer working

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1060]
This was implemented in #660 and was working, but now is not.

**Comment by jcoyne** [comment]
@amyehodge Can you explain what you did to determine this isn't working. I'm not sure I'm able to duplicate.

**Comment by amyehodge** [comment]
I created a new item, choosing to have the default citation off. I saved this as a draft, then opened up the edit form again to make changes and the default citation was set for on. It should have still showed as off.

**Comment by jcoyne** [comment]
@amyehodge If you just set it to off and didn't actually do any customization, then it automatically sets it back to auto the next time you load your page.   If does remember if you disable and provide something.

**Comment by amyehodge** [comment]
@jcoyne Dang. I knew that. Thank you so much for keeping an eye on me. I'm closing this ticket.
