### ISSUE TITLE
Add text and link to work edit form in the license section to "Get help selecting a license"

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1061]
Wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/428088403

Link to https://library.stanford.edu/research/stanford-digital-repository/faqs/sdr-license-options (Note: this link will not be published until H2 is publicly available, so it will give you a 404 right now, but it's correct.)

**Comment by jcoyne** [comment]
@amyehodge I see the link, but what text are you referring to?

**Comment by amyehodge** [comment]
The text should say "Get help selecting a license"

![Screen Shot 2021-02-11 at 2 08 39 PM](https://user-images.githubusercontent.com/5558511/107704763-a7125480-6c72-11eb-9633-3d161f0ad1b6.png)

**Comment by jcoyne** [comment]
Oh, just the link text. Got it, I though there was might be some other text in addition to the link.

**Comment by amyehodge** [comment]
@jcoyne Nope. That's it. Easy peasy.
