### ISSUE TITLE
Ensure that only signed in administrators can visit /queues

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#107]
See the Devise authN / authZ example in the [Sidekiq docs](https://github.com/mperham/sidekiq/wiki/Monitoring#devise):

```ruby
# config/routes.rb
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'
end
```

We don't currently have such an `#admin?` method to call on users but this seems to be a lightweight approach to take. May be blocked by #102, or we can re-work this to use legit WebAuth groups once #102 is done.

**Comment by jmartin-sul** [comment]
I had some trouble with the approach suggested by the Sidekiq docs, where the `current_user` hadn't been loaded before `routes.rb` ran, leading to a failure to authorize even a legit admin user (discovered by setting some breakpoints in `routes.rb` and `application_controller.rb`, then running request specs).

It's possible there was some other Devise configuration I was missing, but after discussing w/ @jcoyne just before lunch, I went with his suggestion to do what dor-services-app does, and use puppet to set things up to restrict access to the `/queues` path before the request even makes it to the app.
