### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#1073]
See https://app.circleci.com/pipelines/github/sul-dlss/happy-heron/1981/workflows/e461466a-713e-4be1-adb5-13addba175b1/jobs/8007 for an example.

Seems to be (almost) always be `spec/features/delete_draft_collection_spec.rb` or `spec/features/delete_draft_work_spec.rb`, potentially due to Hotwire changes in #922, but that may just be a coincidence that they started appearing then.

It looks like for some reason clicking delete is trying to delete an already deleted work/collection
e.g.
```
Failure/Error: work = Work.find(params[:id])

ActiveRecord::RecordNotFound:
  Couldn't find Work with 'id'=146
./app/controllers/works_controller.rb:78:in `delete_button'
```

**Comment by jcoyne** [comment]
@peetucket how will we know if/when this is done?

**Comment by peetucket** [comment]
Has it been actively occurring recently?  I haven't been actively developing in H2 for over a week (vacay and 1st responder) but it used to be about every other build would fail in CI, which was pretty annoying.  If it's not happening often enough to bug people, I would just close it.
