### ISSUE TITLE
Missing icon on work type modal

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#1087]
On Firefox on mac

<img width="869" alt="Screen Shot 2021-02-16 at 8 16 21 AM" src="https://user-images.githubusercontent.com/92044/108074916-5a8e9680-702f-11eb-97a2-3c9e21aca46d.png">

Seems to be due to this style:
```
.work-types a.collapsed::after {
    content: '\f054';
}
```

**Comment by mjgiarlo** [comment]
FWIW, I also see this on Firefox (85.0) on Ubuntu. (I do not see it on Brave/Chrome/Chromium on Ubuntu.)

**Comment by mjgiarlo** [comment]
Moved to backlog. @amyehodge Do you think this is Ready-worthy? If so, could you prioritize this? If not, feel free to leave in backlog.

**Comment by amyehodge** [comment]
I don't see this on Firefox on my Mac. I'm not overly concerned about this, so I'm going to leave it in the backlog for now.

**Comment by jcoyne** [comment]
I believe this is because this style depends on the "Fontawesome" font face, which we are not loading.
