### ISSUE TITLE
Delete on additional Author row not working

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/happy-heron#1091]
When editing a Work, adding a new author contributor works but clicking on the delete button does not remove the Author. 

![Screen Shot 2021-02-16 at 12 20 26 PM](https://user-images.githubusercontent.com/71847/108111163-8de21d00-7051-11eb-9694-01f4b98bdac7.png)

**Comment by amyehodge** [comment]
This seems to be happening in the "Authors to include in citation" section but not the "additional contributors (optional)" section.

**Comment by jcoyne** [comment]
```
Error invoking action "click->nested-form#removeAssociation"

 DOMException: Element.closest: '' is not a valid selector 

 
Object { identifier: "nested-form", controller: {…}, element: section
, index: 0, event: click }
application.js:269
    handleError application.js:269
    handleError context.js:101
    invokeWithEvent binding.js:82
```
