### ISSUE TITLE
Remove error message at top of page for embargo dates needing to be in the future.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1094]
This error message displays properly inline in the work edit form:

![Screen Shot 2021-02-16 at 11.35.05 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/d1dc32be-5a39-4a95-bd8b-ddb2fec44d7a)

so, should be removed from the top of the page:

  ![Screen Shot 2021-02-16 at 11.34.15 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/cd6ce29f-a062-4a79-8fb1-9d8b37d55318)

**Comment by jcoyne** [comment]
This should happen automatically when #1384 is fixed.

**Comment by jcoyne** [comment]
@amyehodge are you able to re-review this and see if it's still an issue? I've deployed the latest code to stage which has the fix for #1384.

**Comment by amyehodge** [comment]
Yep, this looks good. Closing.
