### ISSUE TITLE
For work edit page tooltips, add missing line to keywords tooltip 

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1113]
First, the tooltip for the keywords should read:
Tooltip text: Keywords should reflect significant concepts related to the deposit. At least one entry is required. If you would like to enter your department affiliation, please do so under the Contributors section and choose "Department" for the role term.

The first line of the above is missing.

Secondly, the Tooltip for the License information -- the last one in the document -- is missing entirely.

See Tooltips doc for text: https://docs.google.com/document/d/1gjvqYXmwMpMGWTdZynoHtxDgQVTt9fGn7QGVE4uhXXQ/edit#heading=h.v2a0c7kuvnie

See wireframes for locations: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/431445056

**Comment by jermnelson** [comment]
Hi @amyehodge, could you point to the work you're not seeing the license tooltip? I just captured the following screen-shot on H2 stage and the license tooltip is present (https://sul-h2-stage.stanford.edu/works/3/edit) :

<img width="1704" alt="Screen Shot 2021-02-17 at 12 59 23 PM" src="https://user-images.githubusercontent.com/71847/108260957-2e067780-7120-11eb-9958-a0bd608bfb61.png">

Thanks!

**Comment by amyehodge** [comment]
@jermnelson I'm at a loss. I'm seeing it now. So, there's just the one missing bit for the keywords. I'll update the ticket title.

**Comment by jermnelson** [comment]
> @jermnelson I'm at a loss. I'm seeing it now. So, there's just the one missing bit for the keywords. I'll update the ticket title.

@amyehodge no worries; maybe a browser cache issue? PR #1116 was just merged so closing this issue.
