### ISSUE TITLE
Discarding item draft should take you to the collection deposits list page, not the dashboard

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1149]
This is for both initial drafts of items before the first deposit and the version drafts. In either case when discarding, user is taken to the dashboard and should be taken to the collection deposits list page.

**Comment by jcoyne** [comment]
@amyehodge if the depositor came from the dashboard and they discard a draft, won't they be surprised to end on the deposits list page? Especially if they can't see any other deposits in that collection?

**Comment by amyehodge** [comment]
I have found it very jarring to be dumped back on the dashboard page at this point. Users in testing also seemed to be a bit surprised by that. When thinking about where else they might land, this seemed the most logical place to me. @astridu, do you have any thoughts on this?

**Comment by astridu** [comment]
It could go either way, but if users are finding it jarring to end up back at the Dashboard, where there is little context for what they just did, it would be better if they all landed on the page with the list of deposits.
