### ISSUE TITLE
Add access validations

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#115]
Ensure access is a member of the set
```
stanford
world
```

**Comment by mjgiarlo** [comment]
@jcoyne If we want to validate enums backed by a db constraint, we could do something like this: https://github.com/rails/rails/issues/13971#issuecomment-383905807 Acceptable solution? Or OK to have ArgumentError raised on unexpected values?

**Comment by jcoyne** [comment]
that would work. How challenging would it be to add a new value to the enum (probably not a factor for `access`, but might be for other enum fields.)?

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> that would work.

Which? The solution in that GitHub thread? Or being OK with `ArgumentError` getting raised?

> How challenging would it be to add a new value to the enum (probably not a factor for `access`, but might be for other enum fields.)?

Not challenging. We'd just need to write a new migration with the proper Postgres-flavored SQL. Something like:

```sql
ALTER TYPE work_access ADD VALUE 'cdl';
```

**Comment by jcoyne** [comment]
I think we can be okay with an argument error.  As we'd never need this sort of validation to show a message in the UI.

**Comment by mjgiarlo** [comment]
@jcoyne awesome, thanks! Closing this issue then.
