### ISSUE TITLE
Log the actual user in the history table

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1150]
Looks like content creator is being logged. For example on https://sul-h2-stage.stanford.edu/works/25, I made changes today, but the history table shows this as tjlane.
![Screen Shot 2021-02-19 at 9.57.50 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/39b0682f-3eea-4742-83d9-fabcac3d7f71)

**Comment by aaron-collier** [comment]
@amyehodge is this still a valid issue? It looks like the work cited above is no longer valid.

**Comment by amyehodge** [comment]
@aaron-collier That was a migrated item that has since been wiped, I would guess. But, yes, last I checked it was still a valid problem. It was happening all over, not just this item. Hard to check for sure right now because of the outage.

**Comment by aaron-collier** [comment]
I just edited an object: https://sul-h2-stage.stanford.edu/works/17962

and I see my information there.

![Screen Shot 2021-06-18 at 9.50.28 AM.png](https://images.zenhubusercontent.com/5cd34fcc78dbc64ff177a010/7b7f4757-0d1b-424a-a8ad-72762cba2581)

The order is odd and the content creator (suntzu) appears tagged in the "deposit completed" step... Hmmm

**Comment by aaron-collier** [comment]
@amyehodge Can you verify after your recent testing that lead to the ticket about logging too many changes that your user was appropriately tagged. I think this is closable (as written) but want to make sure. Thanks.

**Comment by amyehodge** [comment]
Yes, the user was properly tagged. Agreed that this ticket is closable.
