### ISSUE TITLE
Agreement to Terms of Deposit doesn't save when versioning an item

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1152]
I opened a new version of https://sul-h2-stage.stanford.edu/works/281/edit# and made one small change in the file description and saved as a draft. The Terms of Deposit box was unchecked, so I checked that as well. When I opened this item to edit again, the Terms box was unchecked.

**Comment by amyehodge** [comment]
@hannahfrost I'm wondering if this is actually the preferred way for this to work. This way, if anyone wants to version any migrated content, they will have to agree to the new terms of deposit. Does that make sense?

**Comment by hannahfrost** [comment]
Yes, I think that does make sense @amyehodge

**Comment by amyehodge** [comment]
So, we don't want to migrate over the agreement to the Terms of Deposit -- we want to make people re-agree when they version migrated content. However, there is still an issue on this ticket that once re-agreed to and saved, that box was unchecked again when I went to re-version the item.

**Comment by jcoyne** [comment]
Once they check the box and submit a draft or a version it should stay checked forever.

**Comment by jcoyne** [comment]
>  there is still an issue on this ticket that once re-agreed to and saved, that box was unchecked again when I went to re-version the item. 

I'm not able to duplicate this behavior. @amyehodge Can you provide instruction on how I get to this state?

**Comment by amyehodge** [comment]
I have been unable to replicate this this morning as well. Closing.
