### ISSUE TITLE
Display error message for license inline with form field and remove display at top of page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1153]
I was trying to deposit a migrated item with an old license. Initially, the validation shows that it's okay:

![Screen Shot 2021-02-19 at 10.15.19 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/79350512-773a-4d87-80fb-723018c6e41e)

But then when I try to deposit, no error is displayed inline, but when I scroll to the top I see ![Screen Shot 2021-02-19 at 10.17.54 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/2080e487-dbcc-43f0-b7ea-9ca15af02a8b)

In this state none of the green/red validation boxes are showing either, so it's confusing.

![Screen Shot 2021-02-19 at 10.19.27 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/1f31545a-809d-480a-94c8-0ce8c49274a2)

**Comment by amyehodge** [comment]
I just rechecked what's going on in these cases, and I'm no longer seeing the error message at the top of the page, but there is still no error shown inline in the form either. 

This time, when I attempted to submit a new version for deposit with everything filled in correctly except that I left the unsupported license chosen, the page reloaded with my "what's changing" note gone and my agreement to the Terms unchecked again, and no error messages are displayed, so the user has no idea what's going on here.

**Comment by jcoyne** [comment]
The error message now doesn't show at all, so there's no feedback to the user about why this won't deposit.
