### ISSUE TITLE
Import item and collection history with hydrus items

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1157]

**Comment by jcoyne** [comment]
@amyehodge Can you say more about why this is a requirement?   Is this something we absolutely need?  It will introduce a lot of complexity and will make the import process much slower (which increases the probability of encountering a failure before completing).

Hydrus doesn't store item history in the database the same way we get some of the other Hydrus values, so we'd need a completely different way of retrieving this information (from the Fedora 3 history).

**Comment by amyehodge** [comment]
@jcoyne This came up in a discussion @hannahfrost and I had this afternoon. Perhaps we can talk about this at migration planning on Monday as well. A small group of people use this a lot, but we suspect not a lot of people do. I'm wondering if there is a convenient way to link to the hydrus history elsewhere, like Argo, though this will not be useful for those who do not have argo access. Or to at least indicate that the item has history before migration into H2 at a minimum. Otherwise an item with 4 versions and no history seems a bit odd.

**Comment by jcoyne** [comment]
It will still have a history in Argo which will be identical to what it has now.  The only thing we couldn't do is allow a user to revert to a previous version.
