### ISSUE TITLE
Homepage accessibility - add alt text to icons

### ISSUE THREAD

**Issue by astridu** [sul-dlss/happy-heron#1164]
Please add this alt text to the who/what/why/when icons on the homepage:
who: "Who can deposit icon"
what: "What can I deposit icon"
why: "Why should I deposit icon"
when: "When should I deposit icon"

**Comment by jcoyne** [comment]
@astridu could we use `aria-hidden="true"` instead?  This is a recommended strategy for purely decorative icons. The alt text you've proposed is largely duplicative of the headings just below.

**Comment by astridu** [comment]
Yes, good idea. Thank you!
