### ISSUE TITLE
User with depositor access is unable to log in to H2

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1168]
I added user vijoy (that's his primary SUNet ID, not an alias) to two collections in H2 and he was unable to access H2. He attempted logging out and back in and that did not work either. This is the screenshot he sent me of the error message:

![image](https://user-images.githubusercontent.com/5558511/108907356-d744e600-75d6-11eb-8ad9-2f7df5e99fe2.png)

**Comment by jcoyne** [comment]
@amyehodge currently the dashboard access (`DashboardPolicy#show?`) is restricted to:
* a person who is in the administrator group 
* a person who is in the collection creator group
* a person who has existing deposits
* a person who reviews any collection.  


This seems overly restrictive right now, because I believe the intention would be someone like vijoy would go through the "first time user" workflow.  Since we haven't built the first time user workflow, we may need to adjust this policy.

**Comment by amyehodge** [comment]
I think your third bullet should anyone who has been listed as a depositor on a collection. They can't have deposits until they've logged in and created them.

@hannahfrost can chime in if I'm missing something, but I think we *do* want to be this restrictive. While we don't have that first-time workflow built yet, users will enter at the H2 dashboard similarly to what happens right now for Hydrus. While we had once thought we would loosen up access controls to hydrus, we find this system works very well and is not particularly onerous -- and in fact helps us engage with users and understand their needs. We want to keep it this way.

**Comment by amyehodge** [comment]
Vijoy has additionally reported that while he has logged out and in several times, he still can't get in through the button on the home page above. HOWEVER, he was able to click on the link in the email invitation he received and access this page directly without getting the error:

![Screen Shot 2021-02-23 at 2.43.30 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/a9667232-ef69-43b5-a677-986b0ddbe2e7)

I'm suspicious that this email message has not found his name in the directory and inserted it. Is there possibly something going on with recognizing his SUNet?

**Comment by jcoyne** [comment]
@amyehodge I think we didn't want to let people who have not created a deposit to go to the dashboard until they went through the "first time user workflow" that is why it was so restrictive as to bar people who had no deposits.  If you want, we can change it to allow anyone who is a depositor until we get around to making the first time user workflow.

**Comment by jcoyne** [comment]
The problem with the email is that since he hasn't yet logged into the system, we have not yet recorded his name.  Typically this is done when the person signs in for the first time.  It would maybe be possible for us to query this information from the LDAP server, but I don't know how we would get access to that or who we should ask.

**Comment by amyehodge** [comment]
@jcoyne ah, I see your point about access to the dashboard. Though I don't understand fully why noone else had this problem. But I'll set that aside for now. I agree that if that particular requirement to already have a deposit to see the dashboard is the problem, we need to change it for now, since it's unclear when the first time user workflow will get implemented.

The name in the email is an interesting chicken/egg problem. Normally, depositors are added to a collection (or managers to a collection) before they first log in. So, it sounds like in most cases that initial email to new people will not have a user name. If your suggestion of retrieving from LDAP does not have a straightforward solution, then perhaps we can get placeholder text for when the name is not found -- "Dear New Depositor" or "Dear New Manager" or "Dear New Reviewer".

**Comment by amyehodge** [comment]
@jcoyne Making sure it's clear that my response to the above suggestion to "If you want, we can change it to allow anyone who is a depositor until we get around to making the first time user workflow." is yes, please.

**Comment by jcoyne** [comment]
@amyehodge how about opening a new issue for the blank name, that's something apart from not being able to log in.

**Comment by jcoyne** [comment]
@amyehodge presumably we want anyone who is a collection manager to be able to go to the dashboard too (this is not currently permitted)

**Comment by amyehodge** [comment]
@jcoyne I'm really confused at how if this is the case, only one person on Monday had problems getting into the app.

**Comment by jcoyne** [comment]
@amyehodge would everyone else have been in the administrator or collection creator groups?

**Comment by amyehodge** [comment]
No. Most people were also only entered as depositors on the same two collections. This was the only user reporting these issues.

**Comment by amyehodge** [comment]
So, I've checked and there were 6 people I added to the two collections as depositors who are not showing up on either dlss:hydrus-app-collection-creators or dlls:hydrus-app-administrators:

vijoy (Vijoy Abraham)
thalassa (Amanda Whitmire)
juliets (Julie Sweetkind-Singer)
juliejw (Julie Williamsen)
mmarosti (Matt Marostica)
pschreur (Phil Schreur)

I have confirmed that at least thalassa and pschreur were able to get to the dashboard. I actually thought thalassa had collection creator status, but she is not listed in that workgroup for some reason.
