### ISSUE TITLE
Discard draft button should not be displayed on collections that have never been deposited

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1192]
See https://sul-h2-stage.stanford.edu/collections/500/edit

This button should only be present on collections that have been previously deposited.

![Screen Shot 2021-02-24 at 2.41.19 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/87f06b93-0a2d-48b2-a883-9070d7fb7dac)

**Comment by jcoyne** [comment]
@amyehodge this button completely deletes the collection when it hasn't been deposited.  Do we want to remove that feature?

**Comment by amyehodge** [comment]
Sorry, I got confused on this point. This is fine.
