### ISSUE TITLE
Migrate all background jobs to Sneakers

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#1205]
Since we're using Sneakers to run some background jobs (queued outside of h2), we may as well make all background jobs run on sneakers, and then we can drop the sidekiq dependency.

**Comment by mjgiarlo** [comment]
@sul-dlss/infrastructure-team discussed this on 3/9/2021 and we decided to kick the can down the road until we gain more experience with RabbitMQ and are actively engaged in H2 work.
