### ISSUE TITLE
User should be presented with the single collection edit form with all details and settings until the first version of the collection has completed deposit

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1250]
If a user starts a collection and saves a draft and then returns to edit the details, as long as the title, description, and email validate, they can deposit the collection, even if they have not properly completed settings. @peetucket and I created multiple collections this way that then did not have the required license set, resulting in bad data that prevented us from creating items in the collection.

To be discussed at stand-up on Mar 4 to see if this approach will work.

Note: When done, please add back the "Save as Draft" button on first draft collections that was removed in #1253

**Comment by peetucket** [comment]
One possible solution is to use the single collection form up until the first version is successfully deposited, at which point all the settings are guaranteed to have been reviewed and valid.  We already get the single form when you first click "Create a new collection".
