### ISSUE TITLE
Confirm mapping updates to fix failing tests

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#1254]
Working on the mapping changes in #1251 and we have the following questions:

In `types_to_resource_types.yml` in that PR:
- "Text" no longer has a mapping when no subtype is selected, which fails to give us a MODs resource type, which causes this test to fail: `rspec ./spec/services/types_generator_spec.rb:109`: https://github.com/sul-dlss/happy-heron/blob/type-mapping-update-take2/spec/services/types_generator_spec.rb#L105-L129 ... see the previous top level Text mapping here: https://github.com/sul-dlss/happy-heron/blob/main/config/mappings/types_to_resource_types.yml#L1-L6
- The "Video" element seemed improperly nested, we fixed it in this commit on the PR, does this make sense? https://github.com/sul-dlss/happy-heron/pull/1251/commits/af2d348a4afe6350e80503cf99037a7d1ba64b71
- The "Video" subtypes seems to have a lot of non-video type subtypes (like "3D model"), just verifying this is correct.  Though I just noticed the UI allows for this, so maybe it is.

In `types_to_genres.yml`:
- When the top level type and sub-type both have the same genre (e.g. "Image / Image"), this currently duplicates the genre in the mapping.  Is this intended? This causes this test to fail `rspec ./spec/services/types_generator_spec.rb:72`: https://github.com/sul-dlss/happy-heron/blob/type-mapping-update-take2/spec/services/types_generator_spec.rb#L69-L103  For example, note that the top level Image type has genre "Pictures": https://github.com/sul-dlss/happy-heron/blob/type-mapping-update-take2/config/mappings/types_to_genres.yml#L933-L939 and so does the "Image" subtype: https://github.com/sul-dlss/happy-heron/blob/type-mapping-update-take2/config/mappings/types_to_genres.yml#L1192-L1197
 
This causes this type of mapping for an "Image / Image" with duplicated genres : 

```
[{"structuredValue":[{"value":"Image","type":"type"},{"value":"Image","type":"subtype"}],"type":"resource type","source":{"value":"Stanford self-deposit resource types"}},{"value":"Pictures","type":"genre","uri":"http://id.loc.gov/authorities/genreForms/gf2017027251","source":{"code":"lcgft"}},{"value":"Pictures","type":"genre","uri":"http://id.loc.gov/authorities/genreForms/gf2017027251","source":{"code":"lcgft"}},{"value":"still image","type":"resource type","source":{"value":"MODS resource types"}}]
```

**Comment by arcadiafalcone** [comment]
`types_to_resource_types.yml`
Both Text and Video were missing types so I fixed them and added it to the pull request. Video nesting looks good. The mappings include all possible combinations, however unlikely.

`types_to_genres.yml`
There should not be duplicate genre terms. All of the Image subtypes are mapped to Pictures as well as to a more specific term if available - does that mean Pictures (and the equivalents for the other types) should be removed from all of the mappings? The resource type mapping does this repetition as well.

**Comment by peetucket** [comment]
> `types_to_resource_types.yml`
> Both Text and Video were missing types so I fixed them and added it to the pull request. Video nesting looks good. The mappings include all possible combinations, however unlikely.
> 

Great, thanks!

> `types_to_genres.yml`
> There should not be duplicate genre terms. All of the Image subtypes are mapped to Pictures as well as to a more specific term if available - does that mean Pictures (and the equivalents for the other types) should be removed from all of the mappings? The resource type mapping does this repetition as well.

Hmm, yes I think if I just remove the "Picture" genre from each subtype, then this will deal with all scenarios, because in order to select a subtype of Image, you *must* select the top level Image type, which would give 
"Picture" by default.  Any more specific non Picture types would then be additive.  I just tested this theory by removing it from the "Image" subtype, and the test passed.  Let me take a stab at the others.

**Comment by peetucket** [comment]
I guess the only time this wouldn't work is if we had a scenario like this:

1. A top level type should have one genre(s).
2. A subtype should have entirely different genre(s), but NOT the one at the top level.

In this case, we'd want the mappings to have all of the duplicates like you set it up for "Image" but then we'd need to change to code to not add the top level type genre(s) to the sub-type genre(s) when doing the mappings (like it does now).

**Comment by arcadiafalcone** [comment]
I don't think there would be any instances of that, because the user must select a type, and the subtype mappings are based on that type. It's additive in that the object would get the genre(s) associated with the type, and also get any distinct genre(s) associated with the subtype. I can't think of any cases when we would want to "subtract" the top-level mapping based on the subtype.

**Comment by peetucket** [comment]
Great, this means no code change, and a much smaller, less duplicative .yml file for the mappings.

Do you know if this happens with other genre mappings other than `Image`?  I'm removing all of the duplicated `Picture` mappings from the image subtypes which fixes the tests, but our tests are not comprehensive, so there may be other dupes in there.

**Comment by arcadiafalcone** [comment]
Yes, it's true for many others. For resource type, it's all except for Music and Other. For genre, the exceptions are Mixed Materials, Other, Software/Code, and Text. All other subtypes duplicate the type mapping.

**Comment by peetucket** [comment]
HMMM... well this would actually be pretty easy to handle in the code too.  We can simply "uniquify" the array of genres before completing the mapping and it will automatically eliminate dupes.  But perhaps we should remove the dupes from the YAML just to be clean about it.   Do you mind taking a stab at the others with another commit? I did "Image".  Be sure to pull the branch before committing to it or else you may have a conflict with my changes.

**Comment by peetucket** [comment]
I believe the work in #1251 should have completed this ticket, and I'm closing this.
