### ISSUE TITLE
Still seeing the error reported in #1222.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1265]
#1222
"If user is editing collection settings or collection details, clicking away from those tabs should display the error message that changes will be lost. I tried this on both settings and details edit pages. I made a change to the form and didn't save it and then clicked "Deposits" and was taken to deposits. Then when I clicked back to the Details or Settings links, I was on the view pages and the changes had not been saved."

**Comment by jcoyne** [comment]
Did you make a change before attempting to navigate away? It only warns you if you've attempted to make a change that would not be saved.

**Comment by jcoyne** [comment]
I did the very thing you described and wasn't able to reproduce that.  Is there a time you can show me?

**Comment by amyehodge** [comment]
Maybe I tested this too soon and it wasn't deployed it. I was just going to make you a video and it worked perfectly.
