### ISSUE TITLE
Add "year" placeholder text to year boxes in the publication and creation date fields

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1275]
A user reported confusion because the year fields for dates do not have "year" in them the same way that "month" and "day" are present in the other fields.

![Screen Shot 2021-03-09 at 2.07.54 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/c2b1e0ca-13dd-423f-9173-da0f4074ca1c)

**Comment by jcoyne** [comment]
add the html attribute `placeholder="year"`
