### ISSUE TITLE
Collections that have a required license set as 'no license' should have that setting migrated.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1280]
After reviewing all the migrated collections and their settings, I discovered that in all cases, collections that had selected a required license and that required license is set to "no license" did not have the "no license" option migrated. This results in all of these collections missing the required license assignment.

**Comment by amyehodge** [comment]
Related to #1252

**Comment by jcoyne** [comment]
@amyehodge can you give an example druid of a collection that is in this scenario?  I'm not able to find one like this in hydrus by doing the following query:

```
jq 'select(.license_option == "fixed") | .license' collections.jsonl| sort|uniq
"cc-by"
"cc-by-nc"
"cc-by-nc-nd"
"cc-by-nc-sa"
"cc-by-nd"
"odc-odbl"
```

**Comment by jcoyne** [comment]
I see those as `"license_option":"none","license":"none"`, which I wasn't interpreting as a "required" license. 

You get that in Hydrus by doing:
<img width="600" alt="Screen Shot 2021-05-11 at 10 20 00 AM" src="https://user-images.githubusercontent.com/92044/117841188-74accf00-b242-11eb-90fb-d82094d029e2.png">

But i would think a required license of "none" would be 
<img width="670" alt="Screen Shot 2021-05-11 at 10 21 06 AM" src="https://user-images.githubusercontent.com/92044/117841355-9ad26f00-b242-11eb-959c-a7cd2dc2bb62.png">


I'm not sure if this distinction is important.

**Comment by amyehodge** [comment]
@jcoyne thanks for pointing this out. We appear not to have accounted for this Hydrus option. I'll talk with @hannahfrost about the best way to deal with these, but they are generating a problem in H2. Back to you soon, hopefully, with a solution.

**Comment by hannahfrost** [comment]
@amyehodge This sounds right to me.  Also, I never noticed that Hydrus has two ways of requiring no license. Does H2?

**Comment by amyehodge** [comment]
@hannahfrost No, it doesn't. We removed the plain "no license" check box in H2.
