### ISSUE TITLE
Correct migration issues that are causing collection records to include activities like the one below.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1281]
It's not clear to me if these are errors in the migration that need to be addressed so that these don't show up, or if they just need to be more understandable.

![Screen Shot 2021-03-11 at 1.37.40 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/c16294d6-4367-40b8-a549-f9643c1479ca)

If these are important for the users to see in the log, then we should make them understandable to the user.

See https://sul-h2-stage.stanford.edu/collections/664 for an example.

**Comment by jcoyne** [comment]
This is just a missing translation value in here: https://github.com/sul-dlss/happy-heron/blob/main/config/locales/en.yml#L10-L17
