### ISSUE TITLE
Validate URL for optional related content links for collections.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1283]
I was allowed to deposit a collection like this:

![Screen Shot 2021-03-12 at 8.12.30 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/f5e512b7-a25e-44b5-b4f7-251041a1cbe6)

**Comment by amyehodge** [comment]
The issue here is that the link on the PURL then does not display correctly.

**Comment by amyehodge** [comment]
Alternate suggestion: display a sample URL in the box that is in the correct format, such as https://sdr.stanford.edu.

**Comment by jcoyne** [comment]
Also do the item page in the same manner.
