### ISSUE TITLE
[Uber] ticket to gather workflows that combine Hydrus and Argo that need an H2 solution

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#1291]
We have a few workflows that involve Hydrus and Argo together. We need to work out how to handle these workflows in a post-Hydrus world.

**There are two kinds of Hydrus + Argo workflows:**

1. Start in Hydrus, pick up in Argo, never come back to Hydrus
2. Start in Hydrus, pick up in Argo, continue to make changes in both

**Workflows currently in category 1 (do not come back to Hydrus):**

1. Acquisitions department: Deposit in Hydrus, add catkey + serials metadata in Argo
2. Large data deposit: Enter metadata in Hydrus, manage files via Preassembly/Argo
3. Making rights more restrictive (Hydrus only allows rights to get less restrictive)

Why you can't edit these items again in Hydrus: a Hydrus edit will overwrite the Argo-originated changes. In all of these workflows we need workflows to not edit in Hydrus again.

Possible solution: continue to allow deposit in H2, but provide way to lock H2 record from further edits. This would also solve a problem we have with Hydrus, where people bookmark their item URLs and continue to edit, thus overriding the Argo-made changes.

**Workflows currently in category 2 (continue to edit in both systems)**

Workflows in category 2 appear to be special in their own ways, needing their own solutions.

1. Change the Hydrus collection

This is currently done by editing the item RELS-EXT in Argo, then the user can edit in Hydrus again

Possible solution: make it possible to change the collection in H2 itself: https://github.com/sul-dlss/happy-heron/issues/1054

2. Change the depositor sunet id

This is currently done by editing the item roleMetadata (which exists for Hydrus items but otherwise is an APO-only field). Then in Hydrus the new person with sunet id that was entered can edit the item

Possible solution: make it possible to change the depositor on an item in H2 itself. Or allow multiple collaborators to edit an item.

3. Prevent the depositor from editing ever again after deposit

This is an unusual use case but comes up when data is deposited to accompany an ETD. In these cases the Registrar has requested that the data not be modifiable, just as the ETD itself is not modifiable once filed. We are currently handling this case by changing the roleMetadata to remove the depositor's sunet id and replace it with an administrator's (such as myself as Repository Manager) sunet id.

Possible solution: Permanently lock the item in the H2 interface. Versioning would still be permitted for administrative actions such as an embargo release, but the depositor should never be allowed change the content. 

4. More complex interactions

For example, this item has been edited multiple times in both systems: https://argo.stanford.edu/view/gb129dk1428 It is a dataset, managed by SUL staff, that has files added to it on a regular basis (perhaps annually). The workflow seems to be:

- deposit files (Hydrus)
- add catkey and refresh metadata (Argo)
- deposit more files (Hydrus) 
- add catkey again and refresh metadata again (Argo)
- repeat

Possible solution: ???? It might be possible for users to continue to deposit in H2 and then update in Argo repeatedly, but we'd need to make sure the systems are in sync in terms of version numbering. A new version in Argo somehow has to get reflected in the version number in H2.

In this use case the problem users seem to be trying to solve is this: in Hydrus, you can add files to an object by simply uploading more files via the Hydrus form. This is much simpler than adding files via Preassembly, where to add new files you need to download all previously deposited files and reaccession them again alongside the new files.

**Additional considerations**

To move off of Hydrus to H2, we need to support these workflows or provide alternatives that can be isolated into one or the other system.

**Comment by andrewjbtw** [comment]
No, but I need to update it since we have new workflows. I've removed a couple that we've since solved.

**Comment by amyehodge** [comment]
@andrewjbtw Is there work here that you think is ready to be done that would make sense in the upcoming work cycle?

**Comment by amyehodge** [comment]
Noting that we also implemented a way to change the deposit owner and to lock items in H2 as solutions to #2 and #3. More about this was covered in staff workflows research.
