### ISSUE TITLE
Neither collection or item deposits are completing

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1293]
I tested creating a new collection this morning and creating a new item in an existing collection and neither one of these processes is completing. 

![StuckDeposits.gif](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/440bd004-0754-465b-9846-ad9f9745e04d)

The item deposit produced a honeybadger error.

We can't do beta testing if these things aren't working.

**Comment by amyehodge** [comment]
Here's the honeybadger report from the email (I'm not seeing a ticket that was generated from this):

Error detected in: happy-heron (stage)

Full report at https://app.honeybadger.io/projects/77112/faults/78457297

RuntimeError: There was an error with your request: {"id":"bad_request","message":"{\"accession\"=>true, \"type\"=>\"http://cocina.sul.stanford.edu/models/object.jsonld\", \"label\"=>\"Amy's test data deposit\", \"version\"=>1, \"access\"=>{\"access\"=>\"world\", \"download\"=>\"world\"}, \"administrative\"=>{\"hasAdminPolicy\"=>\"druid:zw306xn5593\", \"partOfProject\"=>\"H2\"}, \"description\"=>{\"title\"=>[{\"value\"=>\"Amy's test data deposit\"}], \"contributor\"=>[], \"event\"=>[{\"type\"=>\"creation\", \"date\"=>[{\"value\"=>\"2019/2020\", \"encoding\"=>{\"code\"=>\"edtf\"}}]}], \"form\"=>[{\"structuredValue\"=>[{\"value\"=>\"Data\", \"type\"=>\"type\"}, {\"value\"=>\"Tabular data\", \"type\"=>\"subtype\"}], \"type\"=>\"resource type\", \"source\"=>{\"value\"=>\"Stanford self-deposit resource types\"}}, {\"value\"=>\"Data sets\", \"type\"=>\"genre\", \"uri\"=>\"https://id.loc.gov/authorities/genreForms/gf2018026119\", \"source\"=>{\"code\"=>\"lcgft\"}}, {\"value\"=>\"dataset\", \"type\"=>\"genre\", \"source\"=>{\"code\"=>\"local\"}}, {\"value\"=>\"Tables (data)\", \"type\"=>\"genre\", \"uri\"=>\"http://id.loc.gov/authorities/genreForms/gf2014026186\", \"source\"=>{\"code\"=>\"lcgft\"}}, {\"value\"=>\"MODS resource types\", \"type\"=>\"resource type\", \"source\"=>nil}, {\"value\"=>\"text\", \"type\"=>\"resource type\", \"source\"=>{\"value\"=>\"MODS resource types\"}}], \"note\"=>[{\"value\"=>\"This is an abstract\", \"type\"=>\"summary\"}, {\"value\"=>\"Hodge, A. (2021). Amy's test data deposit. Stanford Digital Repository. Available at :link:\", \"type\"=>\"preferred citation\"}, {\"value\"=>\"amyhodge@stanford.edu\", \"type\"=>\"contact\", \"displayLabel\"=>\"Contact\"}], \"subject\"=>[{\"value\"=>\"keyword\", \"type\"=>\"topic\"}, {\"value\"=>\"another keyword\", \"type\"=>\"topic\"}], \"relatedResource\"=>[]}, \"identification\"=>{\"sourceId\"=>\"hydrus:object-13253\"}, \"structural\"=>{\"contains\"=>[{\"type\"=>\"http://cocina.sul.stanford.edu/models/resources/file.jsonld\", \"label\"=>\"This is my data file\", \"version\"=>1, \"structural\"=>{\"contains\"=>[{\"type\"=>\"http://cocina.sul.stanford.edu/models/file.jsonld\", \"label\"=>\"This is my data file\", \"filename\"=>\"test.txt\", \"size\"=>11, \"version\"=>1, \"hasMimeType\"=>\"text/plain\", \"externalIdentifier\"=>\"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTh0Snc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e250905a777b0c94ed830798485e2b3ac8c19d2c\", \"hasMessageDigests\"=>[{\"type\"=>\"md5\", \"digest\"=>\"63b8812b0c05722a9d6c51cbd2bfb54b\"}, {\"type\"=>\"sha1\", \"digest\"=>\"5d39343e4bb48abd97f759828282f5ebbac56c5e\"}], \"access\"=>{\"access\"=>\"world\", \"download\"=>\"world\"}, \"administrative\"=>{\"publish\"=>true, \"sdrPreserve\"=>true, \"shelve\"=>true}}]}}], \"isMemberOf\"=>[\"druid:rm901qm7678\"]}} isn't one of in #/paths/~1v1~1resources/post/requestBody/content/application~1json/schema"}

Summary

Trace

**Comment by amyehodge** [comment]
@hannahfrost FYI for beta testing.

**Comment by jmartin-sul** [comment]
we've disabled the descriptive metadata roundtrip validation flag, which fixes this issue in the short term and allows beta testing to proceed.

as follow on work, we'll
* add a specific flag for disabling roundtrip validation only for H2 (to allow stricter checking for everything else sooner, see sul-dlss/dor-services-app#2583)
* enable roundtrip validation in DSA for everything besides H2
* fix the bad H2 descriptive metadata mappings
* re-enable roundtrip checking for H2
