### ISSUE TITLE
Include a way for H2 administrators to easily view an item if they have the druid

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1298]
My suggestion here would be to provide a search box on the site for administrators that can be searched by druid to make it easy for administrators who have a druid to go directly to the item page.

The background here is that in hydrus we have not been able to do this either, but because the URLs for the works are constructed using the druid, which is assigned as basically the first step in creating a new item, administrators could simply construct the URL from scratch to get to the page they wanted. 

With H2, the URLs are not constructed this way, so we no longer have either a search or a structured URL with a druid that allows us to easily go to the view page for a work.

If there is another solution other than a druid search that will make it easy to get to an item when you have a druid, I'm happy to discuss other options.

**Comment by jcoyne** [comment]
Put this by the "All Collections" table on the dashboard.
