### ISSUE TITLE
Additional managers listed when a collection is created need to receive the notification

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1302]
Currently, when a collection manager creates a new collection and includes additional managers at that time -- as opposed to adding them in later -- those additional managers are not receiving the email notifications that they have been added to the collection. They should be receiving this notification: https://docs.google.com/document/d/1TZVILUrORI25kRZyUZ70vMQYo90Ngp_tqCI7BdU_VyQ/edit#heading=h.wm12u0xf3u0l

This notification IS being properly sent when additional managers are added to an already deposited collection.

**Comment by jcoyne** [comment]
This is for the "You have been added as a manager" message when the collections is created.
