### ISSUE TITLE
Embargo release of H2 item does not appear to have completed fully 

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1313]
[happy-heron/stage] Occurred: StateMachines::InvalidTransition (#77580929)

Error detected in: happy-heron (stage)

Full report at https://app.honeybadger.io/projects/77112/faults/77580929

StateMachines::InvalidTransition: Cannot transition state via :deposit_complete from :deposited (Reason(s): State cannot transition via "deposit complete")

Summary

Hostname: sul-h2-stage.stanford.edu

Context

druid: druid:zz089gd7593
object: gid://happy-heron/Work/13258
Trace

app/jobs/deposit_status_job.rb:27:in `block in work`
app/jobs/deposit_status_job.rb:22:in `work`

**Comment by amyehodge** [comment]
Hannah had set this item for an embargo release today. 

Andrew indicated that the release looks successful, Argo-side: https://argo-stage.stanford.edu/view/druid:zz089gd7593

**Comment by jcoyne** [comment]
I'm not sure I understand what I should do to reproduce this error.

**Comment by amyehodge** [comment]
@jcoyne We need to create an item and set an embargo date in the future, then see what happens when the embargo date has passed. Let me know if I can help with this, perhaps by creating the item.

**Comment by jcoyne** [comment]
@amyehodge and then what do you do once the date has passed?  Does this error get triggered in the background?

**Comment by takeit** [comment]
Hey, nice project but note that @takeit is my username here and I get the notifications everytime you mention it 😃

**Comment by amyehodge** [comment]
@jcoyne If I remember correctly, when the date passed on this item, instead of depositing and showing as complete in the app, it triggered this error and looked like it wasn't deposited. However, Argo showed it as complete. It's been a while, so I can't quite recall the full cycle here. I will set up a new item again to test this.

**Comment by amyehodge** [comment]
> Hey, nice project but note that @takeit is my username here and I get the notifications everytime you mention it 😃

@takeit apologies. I'll try to avoid pasting in that bit of the error message in the future!

**Comment by takeit** [comment]
> > Hey, nice project but note that @takeit is my username here and I get the notifications everytime you mention it 😃
> 
> @takeit apologies. I'll try to avoid pasting in that bit of the error message in the future!

No worries! Thanks! Good luck guys!
