### ISSUE TITLE
Date/time stamps should use Stanford local time

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1335]
Hannah reported that she created a collection at 9:44pm on March 9, 2021 and the Collection Created and Last Saved dates on the view page show Mar 10, 2021 at 5:44am. 

Option: If it is difficult to do the conversion to Stanford local time, displaying the time zone these are in (presumably GMT? UTC?) would make them make a lot more sense.

**Comment by jcoyne** [comment]
How about in the time zone that the viewers computer is using?

**Comment by amyehodge** [comment]
@jcoyne To be clear, whether that person is the depositor or a manager or an admin like me or Hannah? That's another option, but one I thought we had discarded as either too difficult or confusing? If not, that would perhaps be the best option.

Regardless of what we choose, we should display the time zone.
