### ISSUE TITLE
Columns in the tables on the item view page should be aligned. 

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1336]
See wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/420930436

Currently, these are a bit all over the place. See https://sul-h2-stage.stanford.edu/works/13373 for an example.

**Comment by jcoyne** [comment]
@amyehodge the link https://sul-h2-stage.stanford.edu/works/13373 no longer works.

**Comment by amyehodge** [comment]
@jcoyne Try this one: https://sul-h2-stage.stanford.edu/works/17893

**Comment by jcoyne** [comment]
What I'm seeing here is that each table is optimizing for the data that is contained within it.  
<img width="1144" alt="Screen Shot 2021-06-09 at 10 20 13 AM" src="https://user-images.githubusercontent.com/92044/121382560-5652f580-c90c-11eb-9c2a-0c7a95125ad2.png">


If we made them all the same dimensions, certain things like the filenames in the second table would wrap, making them hard to read.  Some of the tables have field labels in the first column an others have data in the first column, so this is going to be tricky to find a place to split that works great for every situation. 

If we want to proceed we need to determine an appropriate break point not only at a super wide width, but also at smaller dimensions too (e.g tablet and phone).

**Comment by amyehodge** [comment]
@hannahfrost reported this issue and may want to weigh in.

Some of the tables appear to align currently. For example, Description and Terms of Use seem to line up. Could we get the Release data and visibility table between those two tables to line up with them?

Could we get Authors and Contributors table and the Dates table to line up with each other?

@astridu what do you think?

**Comment by astridu** [comment]
It definitely looks a bit neater if that second column is aligned between all the sections. 
![image](https://user-images.githubusercontent.com/42216982/125368062-47f26200-e32e-11eb-898f-5642b4b7eaa0.png)

**Comment by jcoyne** [comment]
@astridu do we need to define that breakpoint at the different supported screen sizes or do we say 25% regardless?

**Comment by astridu** [comment]
@jcoyne I don't think we need to define additional breakpoints. Most people will be using this app on their desktop or laptop.

Yes, let's include the file table. It just looks neater overall to have that second column align. Thank you!

**Comment by jcoyne** [comment]
@astridu We use bootstrap which has breakpoints for six classes of devices: extra small, small, medium, large, or extra large devices .   We can't not use them if we're using bootstrap, so we need to define what the breakpoint should be at each size device.

**Comment by astridu** [comment]
@jcoyne I'm not sure how to do this. Can you make a suggestion?

**Comment by jcoyne** [comment]
@astridu sorry for being confusing, I guess we should just try it at 25% for every screen size and then adjust as necessary.

**Comment by amyehodge** [comment]
@jcoyne @astridu Is this ready for the Ready column? Thanks.

**Comment by astridu** [comment]
Yes from me.
