### ISSUE TITLE
Display approximate dates as "ca. [date]"

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1339]
These currently display with a question mark behind them. 
A single approximate date should read "ca. 1492"
An approximate data range should read as one of the following, depending on whether one or both dates are approximate:
- ca. 1492 - ca. 1529
- ca. 1492 - 1529
- ca 1492 - ca. 1529

**Comment by jcoyne** [comment]
FYI, the curent display is using the EDTF specification for dates http://www.loc.gov/standards/datetime/ (but we can convert that into displaying something else).

**Comment by arcadiafalcone** [comment]
Date display logic expects w3cdtf dates (unless the date is before the year 1000).

**Comment by jcoyne** [comment]
@arcadiafalcone what display logic are you referring to?

**Comment by arcadiafalcone** [comment]
@jcoyne I was thinking of mods_display.

**Comment by jcoyne** [comment]
@arcadiafalcone I think Amy is just talking about in the H2 app, which doesn't use mods at all. It just has a database column with a EDTF date/range in it.  Currently we're just printing out that value without applying any formatting.

**Comment by amyehodge** [comment]
@jcoyne is right -- I just mean the display in the app. It's currently a bit confusing in that it doesn't match to Stanford time (the local time for most users) and it doesn't tell you what time zone it is.
