### ISSUE TITLE
Expand what is allowed for email addresses

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1340]
I was unable to deposit an item because of the email address "HMS-Library@lists.stanford.edu". 

 ![Screen Shot 2021-04-20 at 4.59.56 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/f8555e53-f9a2-47b6-9d20-db8cd88ff58e)

It passed an initial round of validation when I changed it to lowercase letters, but then still had trouble when I tried to deposit until I removed the period between "lists" and "stanford". 

We should allow capital letters, dashes (in case they aren't allowed, though I think that's okay), and multiple dots in the second part of the address.

**Comment by jcoyne** [comment]
Do you also want it expanded to support emails like `коля@пример.рф`?

**Comment by amyehodge** [comment]
Is this a question about supporting different character sets for other languages? I haven't had anyone request to be able to do something like that. Since users have to be Stanford affiliates, it seems to me reasonable that they should have an email address that is in the character set used for English. I'm willing to hear arguments against this. (@hannahfrost?)
