### ISSUE TITLE
When user clicks on the edit icon on the collection settings page for the "Terms of use and licenses" section, they should be taken to that section of the edit page.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1342]
I clicked on the edit icon for the review workflow settings and the edit page loaded at the top and I had to scroll to find it.

**Comment by jcoyne** [comment]
Can you point out where the workflow settings are on the item view page? I'm not seeing it. I'm looking at https://sul-h2-stage.stanford.edu/works/13343 and not seeing "workflow" anywhere.

**Comment by amyehodge** [comment]
@jcoyne I was talking about the pencil in this section, but of course when I tested it just now it worked fine -- took me to the correct section. 

![Screen Shot 2021-04-21 at 1 50 20 PM](https://user-images.githubusercontent.com/5558511/115598624-74e32b80-a28f-11eb-8c4e-d423148993ef.png)

I'll double check it again later and if I continue not to be able to reproduce this, I'll close it.

**Comment by jcoyne** [comment]
@amyehodge is that on a collection?

**Comment by amyehodge** [comment]
Ah yes, sorry.

**Comment by jcoyne** [comment]
No worries.

**Comment by amyehodge** [comment]
@jcoyne I am able to reproduce this issue for only the "Terms of use and licenses" section, which loads to the top of the page. I'll make the title of this more specific.
