### ISSUE TITLE
Allow migrated hydrus objects to be versioned.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1346]
I am unable to version either an object created in H2 or an object migrated to H2 from Hydrus. Deposits hang with the “Deposit in progress” displayed and the icon spinning.

**Comment by amyehodge** [comment]
Note an attempt to version migrated content produced this error: #1341

**Comment by jcoyne** [comment]
I think this because we moved objects from Hydrus production into h2 stage.  The stage environment only migrated the "hydrus" part of it, not the preserved object.   This wouldn't be a problem in the production environment.

**Comment by amyehodge** [comment]
@jcoyne This would still leave the inability to version the H2-originated objects. This is also currently not working. 

Also, how/when can we do this testing in the production environment? Sooner is better than later, and we can't wait for the 1.0 release to production to test something so critical.

**Comment by jcoyne** [comment]
It might be easiest to track these two problems if they are separate into different issues. I suspect there are different considerations for each case.

**Comment by amyehodge** [comment]
@jcoyne This one is now just for the migrated content. I have created a new issue for the H2-originated content, which I just verified is not working. See #1350.

**Comment by andrewjbtw** [comment]
I think the problem with migrated objects is that our SDR -stage and -prod environments store entirely separate druids in Fedora. So the migration has brought the prod druids into H2's list of druids, but not any further into SDR's stage environment. To set up a fully functional stage migration test, we'd need to import (or accession) the migrated druids into stage Fedora.

**Comment by andrewjbtw** [comment]
I see this overlaps with what Justin already said. The stage preservation environment would also need the migrated data, as one of the versioning steps is to check on the existing versions in preservation.

**Comment by amyehodge** [comment]
It's always nice when @andrewjbtw and @jcoyne agree.

**Comment by jcoyne** [comment]
The best way to test this in stage is to create a Hydrus object in the staging environment, then we can migrate that to the h2 stage environment.  The problem exists when we migrate from the Hydrus production environment to the h2 stage enviornment, because the SDR (fedora/preservation) objects are not moved as that is not part of the migration.

**Comment by amyehodge** [comment]
Migrated objects in production are being successfully versioned, so closing this.
