### ISSUE TITLE
Prohibit deposit or saving as a draft while files are uploading

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1348]
At least one user during testing attempted to deposit an item without waiting for the file to upload. Is it possible and desirable to prevent the user from doing this? (Seems like it to me.) Files are also not saved and the user is not alerted if they Save as Draft before file upload is complete. This could be achieved by greying out the save and deposit buttons while this is going on, but I suspect there are other options.

@hannahfrost @astridu @jcoyne @mjgiarlo Thoughts?

**Comment by astridu** [comment]
Disabling the deposit button until the file is uploaded seems like a good idea.

**Comment by amyehodge** [comment]
@hannahfrost @astridu @jcoyne @mjgiarlo I've updated this to include saving as a draft as well, as the user receives no notification that files are not finished uploading and will not be saved. Let me know if this should be a separate ticket.

**Comment by jcoyne** [comment]
What sort of indication will we show the user that the submit button won't work while files are uploading?

**Comment by amyehodge** [comment]
@jcoyne Do we need something more than what we mentioned above -- having it greyed out?

**Comment by jcoyne** [comment]
If the button is grayed out, the user may wonder why it is grayed out.  Should there be a message that explains this unusual behavior to  a user?

**Comment by amyehodge** [comment]
Perhaps there can be a mouseover or a message under the button when it is in this state that says "Deposit is displayed during file uploading." @astridu ?

**Comment by jcoyne** [comment]
@amyehodge mouseover mesages are not accessible to people who use screenreaders and they don't work for people who use touchscreens.

**Comment by amyehodge** [comment]
@jcoyne Ah. Good to know.

**Comment by astridu** [comment]
Could we do something like this where there is a message above the button?
![image](https://user-images.githubusercontent.com/42216982/118174797-1fa8be80-b3e4-11eb-87ec-0e0771e3462d.png)

**Comment by jcoyne** [comment]
Yes, that works.

**Comment by amyehodge** [comment]
Thanks, @astridu !

**Comment by jcoyne** [comment]
So, there is an accessibility problem with the buttons being disable approach too.  Namely a keyboard user can submit a form by pressing enter, and not using the buttons at the bottom.  So how about an approach like this instead, where if they submit (by any means), an alert pops up telling them to wait a minute:

![Screen Shot 2021-05-28 at 11.10.55 AM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/b2811c47-7fbf-4a90-85e8-943ad2a37bf5)

**Comment by amyehodge** [comment]
This works for me, @jcoyne. Thanks for being diligent about the accessibility issues!

**Comment by amyehodge** [comment]
@jcoyne What's the status of this ticket? Can we get this finished before the release on Wednesday?
