### ISSUE TITLE
Allow H2-originated objects to be versioned.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1350]
Items created in H2 originally in an H2 collection (not a migrated collection) are not completing versioning.

See this object: https://sul-h2-stage.stanford.edu/works/13379

**Comment by jcoyne** [comment]
https://argo-stage.stanford.edu/view/pq586nq2665
It appears that the update message was received by dor-services-app, but SDR api didn't open/close a version

**Comment by jcoyne** [comment]
sdr-api retried this deposit a bunch of times `BackgroundJobResult.find('6698')`, but it wasn't going to succeed until some code was changed in dor-services-app.   

So we will have to set the `WorkVersion` back to version_draft and retry after the code has been changed:
```ruby
 work = Work.find(13379)
work_version = work.head
work_version.update(state: 'version_draft')
work_version.begin_deposit!
```
