### ISSUE TITLE
Make sure correct license is displayed in PURL

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1354]
As an example, see 
Item in H2: https://sul-h2-stage.stanford.edu/works/13295
Same item in Argo: https://argo-stage.stanford.edu/view/druid:yg374gn5670
Same item in PURL: https://sul-purl-stage.stanford.edu/yg374gn5670

User selected license CC-BY-NC-ND-4.0 but Argo and PURL both reflect CC-BY-NC-**SA**

And self-deposit items have in the past not had a copyright statement, but this item has one. @hannahfrost Is it appropriate to remove that to be consistent with how we've been doing this?

**Comment by andrewjbtw** [comment]
I think implicit in this ticket is that H2 deposits should not pick up APO defaults (which I think happened here and everywhere so far in H2 testing), and instead use values supplied from H2 for those same fields. I don't know if that should be ticketed explicitly.

**Comment by jcoyne** [comment]
No license will display on PURL until the access team updates the code to read the new access nodes.

**Comment by amyehodge** [comment]
@hannahfrost Did you see my question above about the copyright statement?

**Comment by jcoyne** [comment]
The license is sent to argo in #1397

**Comment by jcoyne** [comment]
Currently waiting on purl to bump mods_display to 0.9.1 (https://github.com/sul-dlss/purl/blob/master/Gemfile.lock#L222) and deploy to stage.  Then we can deploy https://github.com/sul-dlss/dor-services-app/pull/2830 and test that software licenses don't break purl.

**Comment by jcoyne** [comment]
@amyehodge I believe this is now ready for you to review.

**Comment by amyehodge** [comment]
This item with an MIT license appears to be displaying properly! Huzzah! https://sul-purl-stage.stanford.edu/bj743gf2729

![Screen Shot 2021-05-25 at 5 16 05 PM](https://user-images.githubusercontent.com/5558511/119569603-f7727580-bd7c-11eb-830c-530c52a41985.png)

Anything else, or shall I close this?

**Comment by jcoyne** [comment]
I think this is good to close now.
