### ISSUE TITLE
Prevent work type modal from showing up when you discard a draft

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1357]
When I start a draft and then decide to navigate away from the page (in this case, back to the collection view page) and discard my current work, the work type modal flashes up during the page transition.

![workTypeModal.gif](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/94a98fe5-e69b-4578-b2f8-20cf0f43c924)

**Comment by justinlittman** [comment]
I'm stumped.

**Comment by amyehodge** [comment]
@justinlittman Were you able to reproduce this? I haven't had a chance yet to look for this again.

**Comment by justinlittman** [comment]
Yes, I can reproduce (unfortunately).

**Comment by jcoyne** [comment]
Is this perhaps page caching done by Turbo?  Maybe this only happens when that modal was open when you were last on the page that has that URI?

**Comment by jcoyne** [comment]
@justinlittman try this:
```js
$(document).on("turbolinks:before-cache", function() {
  // Close modal window
}
```
