### ISSUE TITLE
Display file size and date uploaded for each file on the work edit form.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1359]
@astridu Could you do a mock-up for this? Thanks.

Also see #2348 for adding checksums.

**Comment by amyehodge** [comment]
@astridu could you do a mock up for this? Thanks.

**Comment by amyehodge** [comment]
![fileSizeDate.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/20f625ad-4cec-4260-8b54-4a5c7a343f68)

**Comment by jcoyne** [comment]
@astridu how should this look if they have long file names like `district means grade equivalent std (gs) (pooled year, grade and sub)_v1_1.csv` (from https://sdr.stanford.edu/works/1618)

**Comment by astridu** [comment]
Can we have it wrap? 
![image](https://user-images.githubusercontent.com/42216982/129844010-774b6770-aaee-4025-8c3c-bca94522f3fe.png)
