### ISSUE TITLE
When clicking on a year field in the work edit form, display the current year by default.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1363]
Currently, year '1000' is displayed. Using the arrows is then too hard and people have to click in the box again to highlight the '1000' to delete it and type in a new year. Displaying the current year will many time be correct and require no further editing, or the arrow keys could be useful to make changes.

**Comment by jcoyne** [comment]
Currently there is no default unless you click the arrow keys. Then it starts at the minimum. This is a browser behavior. Providing a default of current year probably won't work because it's probably not the right value and not required.
