### ISSUE TITLE
Make it clear to users that something has happened when they click deposit on the work edit form but it doesn't pass validation

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1365]
Several users during testing were confused about what was happening when they tried to deposit an item and it didn't pass validations, particularly if no error messages were displayed on the visible part of the page. In the video attached, the second time I click deposit, the green boxes around the validated fields I can see actually disappear, which is also confusing. Returning the user to the top of the page may be an adequate solution for this.

![validation.gif](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/a07d9bfc-e6bc-48fe-b4dd-614b72c7dbb3)

**Comment by amyehodge** [comment]
@astridu How do you feel about the suggestion of returning the user to the top of the page?

**Comment by astridu** [comment]
Yes, we should definitely return users to the top of the page. What might be even nicer is to display a list of the errors at the top of the page since it's such a long page, but this is a nice to have.

**Comment by amyehodge** [comment]
We've been removing the error messages at the top of the page because it seemed difficult at times to figure out where on the page those are occurring, but I guess we could add them back. There would need to be some improvement in the formatting of how these look, as they are pretty ugly in their default state.

**Comment by amyehodge** [comment]
See also similar ticket for collection edit form #1382

**Comment by jcoyne** [comment]
For now, just scroll up to the first error on the page.
