### ISSUE TITLE
Display information about checkbox selections for participants on the collection settings page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1366]
Currently users have to go into edit mode to see how these are set. 

@astridu I think we will need a mockup for this. Thanks.

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/115944796-e9bf8c80-a46c-11eb-8a21-d2452bb17900.png)

**Comment by amyehodge** [comment]
@astridu This works for me. If they have both checkboxes checked, would that appear on two separate lines?

**Comment by astridu** [comment]
Yes, it could look like this. 
![image](https://user-images.githubusercontent.com/42216982/116185422-6f924080-a6d6-11eb-95f7-6a471768b2be.png)

**Comment by amyehodge** [comment]
Perfect.

**Comment by jcoyne** [comment]
Not needed at this time (per Amy)

**Comment by amyehodge** [comment]
Redesign to split the collection into details and settings means that you no longer have to version the collection info to see this.
