### ISSUE TITLE
Implement alternate shading of table rows on collection details tables

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1368]
@astridu How do you feel about this? A user suggested it during testing and Hydrus has this currently. 

Since the dashboard tables are 4 rows max, I think they are small enough not to need it.

**Comment by astridu** [comment]
I like the idea. What do you think?
![image](https://user-images.githubusercontent.com/42216982/115944883-6ce0e280-a46d-11eb-942b-324f161ebb75.png)

**Comment by amyehodge** [comment]
I like this. We also need this on the Collection Deposits page, where there are many more things on the list. And for the Admin table of all the collections at the bottom of the dashboard.

**Comment by astridu** [comment]
I can update the mockups this week.

**Comment by astridu** [comment]
Collection deposits page
![Uploading image.png…]()

**Comment by astridu** [comment]
All collections table.
![image](https://user-images.githubusercontent.com/42216982/116501479-b4001680-a865-11eb-84c3-adc742331457.png)

**Comment by amyehodge** [comment]
Looks great. Thanks @astridu .

**Comment by jcoyne** [comment]
Look into using `.table-striped`
