### ISSUE TITLE
Migrated content that is pending approval needs to have the review workflow options displayed

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1369]
This is needed so the work can be approved and deposited, or returned. See video below from user testing. 

![PendingApproval.gif](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/6e829ab6-f818-45b5-82b6-6a8dd2476a1b)

**Comment by jcoyne** [comment]
@amyehodge Stella is not a reviewer in the collection, so she doesn't see those controls.

**Comment by amyehodge** [comment]
I feel like this keeps creeping up in places. Yes, managers should by default always have all the capabilities that reviewers have. However, note that managers should NOT have to be listed as reviewers in the review workflow section of the settings to have these permissions. Please update the policy to reflect this. Thanks.

**Comment by jcoyne** [comment]
Yes, I too thought this had been rectified in the previous workcycle.
