### ISSUE TITLE
Deposits list page for migrated collections should be viewable.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1370]
I was able to replicate an error seen by user when she attempted to click on the full list of deposits for a migrated collection. I had assumed this was going to be caused by a missing license on the collection, but the collection does have a license. https://sul-h2-stage.stanford.edu/collections/564

This produced a HB alert:
Error detected in: happy-heron (stage)

Full report at https://app.honeybadger.io/projects/77112/faults/76940953

TypeError: Parameter 'work_version': Expected type WorkVersion, got type NilClass Caller: /opt/app/h2/happy-heron/shared/bundle/ruby/2.7.0/gems/sorbet-runtime-0.5.6380/lib/types/private/methods/call_validation.rb:117 Definition: /opt/app/h2/happy-heron/releases/20210423110856/app/components/works/detail_component.rb:8

Summary

works#index

URL: https://sul-h2-stage.stanford.edu/collections/564/works

Hostname: sul-h2-stage.stanford.edu

Context

user_scope: user
user_id: 12
Trace

app/components/works/link_to_show_component.rb:16:in `new`
app/components/works/link_to_show_component.rb:16:in `title`
app/components/works/link_to_show_component.rb:12:in `link`

**Comment by jcoyne** [comment]
The problem here is bad data.  The question is how the data got in the bad state.  It's possible that the migrator didn't migrate the works in the collection correctly.  Track down the bad object, trace it back to hydrus and see why it got in this state.

**Comment by jcoyne** [comment]
There are 11 bad items in this collection:
```
Work.where(collection_id: 564, head: nil).count
D, [2021-05-11T09:48:08.743004 #10008] DEBUG -- :    (1.0ms)  SELECT COUNT(*) FROM "works" WHERE "works"."collection_id" = $1 AND "works"."head_id" IS NULL  [["collection_id", 564]]
 => 11
```
