### ISSUE TITLE
Determine what to do if a deposit fails part of the way through the register + deposit process

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#1373]
In testing, we've had items or collections fail during deposit. In some cases, we've simply left the object in some kind of failure state because it's just test data. But in other cases, we've fixed the object up so that it completes accessioning. In either case, the H2 interface may continue to show a spinning progress wheel forever - even if the deposit was completed later.

For example, this is a partial screenshot of my H2 page:
<img width="692" alt="Screen Shot 2021-04-26 at 4 40 21 PM" src="https://user-images.githubusercontent.com/8975583/116164587-dd2a7680-a6ae-11eb-98e5-6adc7a323587.png">

On this page, the three items listed as "in progress" do not appear to be anywhere in Argo stage, based on searching for their presumed source ids based on the H2 source id naming convention. But the two collections in that screenshot were deposited:

1. "another collection"
https://sul-h2-stage.stanford.edu/collections/724
https://argo-stage.stanford.edu/view/druid:cw494mx1066

2. "always be" [depositing]
https://sul-h2-stage.stanford.edu/collections/725
https://argo-stage.stanford.edu/view/druid:zh984hw4360

Ideally, we would not have deposits fail. However, given the possibility of network interruptions, Fedora disconnects, or other issues, we should have a standard way to mitigate a failure. Possible strategies could include:

1. Alert the user and given them a chance to initiate a retry
2. Alert an administrator and have an administrative-side retry process (ideally not an ad-hoc one)
3. Some kind of automated retry/cleanup, though as discussed in the context of Fedora disconnects, there is a chance that automation could intensify a problem by sending too many requests repeatedly

For the in progress icon and other status information in the H2 interface, I think we need a way to:

1. Update it with the relevant information if the object successfully completes deposit after intervention
2. Set it back to the pencil icon if the deposit is going to be started again from the H2 UI.

**Comment by amyehodge** [comment]
@astridu We'd like some feedback from you on this and some UI assistance on how this might look.

**Comment by astridu** [comment]
At what point would we be able to let the user know the deposit failed? Immediately? In which case, we could put an error on the page itself and ask the user to hit the Deposit button again. If not immediate, then we could show this error on the dashboard with the option to try again. 
![image](https://user-images.githubusercontent.com/42216982/116771203-5e12a680-a9fe-11eb-883a-026fc8d6e58d.png)

**Comment by jcoyne** [comment]
There are many different reasons that a resource could fail part way through the register + deposit process and unfortunately, the remedy for all of them will be different.  Retrying is not going to be sufficient, as we already have automatic retries baked into the system where possible. We must break these out into the various ways they may have failed and remedy each individually.  Here's some of the different ways I've seen so far:

1.  sdr-api ran out of upload space https://app.honeybadger.io/projects/67994/faults/69372762
2. H2 maps to invalid cocina https://app.honeybadger.io/projects/77112/faults/78684441
3. sdr-api is unreachable
4. dor-services-app is unreachable from sdr-api https://app.honeybadger.io/projects/67994/faults/64628740
5. Fedora is unreachable from dor-services-app.
6. Model version mismatch between h2 and sdr-api (https://app.honeybadger.io/projects/77112/faults/78457297)
7. File corrupted in sdr-api https://app.honeybadger.io/projects/77112/faults/78735927

**Comment by amyehodge** [comment]
@andrewjbtw @jcoyne Have any of these issues been resolved (other than "Fedora is unreachable," which I'm assuming is just no longer an issue)? I'm looking at what we should prioritizing of older tickets for the upcoming work cycle. Thanks.

**Comment by andrewjbtw** [comment]
I think most of those things could still go wrong but my intention with this ticket was to come up with a way of showing someone things failed or providing a way to retry. Basically, some way to avoid a perpetually spinning wheel if a deposit didn't work.

So far, what we've been doing is addressing the spinning wheels on a case by case basis. Maybe that's what we still want to do.

**Comment by amyehodge** [comment]
@andrewjbtw Do we eventually find out about all of these because of things going on on the back end? Or could there be some spinning that we don't know about without looking for them?

I'm wondering if there is an easy way to identify the spinning wheels and send a notification to someone (you, me, but maybe not the user) or allow us to include that state in reports we will be generating in the new admin functions? We could perhaps request an item report for all items that are "Depositing..."? Would that be possible?

**Comment by amyehodge** [comment]
From Andrew:  It's now much less possible to fail in the way outlined in the ticket. This ticket was mostly motivated by Fedora-related issues where registration could get partway (some datastreams but not all datastreams). Now it’s all or nothing.
