### ISSUE TITLE
Add "continue editing or deposit" button to item view page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1375]
Many users during testing did not understand how to return to a saved item in order to deposit it. This button is an attempt to make clearer what they need to do. This button will take the user to the work edit form, same as the pencil icon, which we will leave on the page for consistency.

This button should only appear when the work is in a draft state or when a work in the review workflow has been returned for editing. 

Mockup:
![image.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/57ffd9f1-3b53-457b-bf14-f0daa9d4c0e9)

**Comment by jcoyne** [comment]
@amyehodge should this go on all three tabs?  Since we have this button, should we remove the pencil icon, which I now believe would have the same function?

**Comment by amyehodge** [comment]
@jcoyne I want to leave the pencil icon for consistency's sake. Some users look for that.

Since the details page is the only that can ever be in an "in progress" kind of state like this, I think it makes sense to just have it on the one tab. @astridu does that make sense to you, or do you think it should be on all 3? I think that might be confusing.

**Comment by jcoyne** [comment]
@amyehodge I understand consistency can be good, but it's also a matter of now having several possible actions on the page and needing to make the decision about which action is the correct action to take. If you simplify it and only have one button, the user has little doubt about what button they push to enter the edit page. I leave this decision to you, but thought I'd raise this concern.

**Comment by amyehodge** [comment]
@jcoyne I definitely get your point, but Astrid and Hannah and I discussed this and felt that since we observed in the testing videos that some users consistently looked for the pencil icons, while others didn't understand that clicking the pencil in this particular instance was the way to continue working on a draft, we felt having both for this task would make it more likely any given user would find their way back to draft editing more quickly.

**Comment by astridu** [comment]
I agree w/Amy. It was very clear in the video that the user did not see the button and was looking for the pencil. I see Justin's point that it may be more clear to have one entry point, but having two would help the users in this case who have learned to look for the pencil.
