### ISSUE TITLE
Change keywords to single entry boxes similar to other elements in the UI

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1377]
After discussing with @astridu and @hannahfrost, we think changing this entry field so that the user enters one keyword at a time and then clicks on an "add another keyword" box to add another will be much clearer to the users and will be consistent with the rest of the UI where multiple entries can be made. It also eliminates an inconsistency in the UI where this field required use of the enter key, while hitting that key anywhere else on the page results in saving the page and returning to the view page.

@jcoyne and @mjgiarlo, how do you think this will work if we want to implement the FAST vocabulary lookup in the future? We prefer not to do something that will make that harder later. Also, let me know if you see any complications for the validations with this method. Thanks.

![keyword.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/a0d08b83-4cdc-43ef-9346-58f7b9610cc9)

**Comment by mjgiarlo** [comment]
@amyehodge I don't foresee this change giving us much heartache, so I say :shipit:
