### ISSUE TITLE
Add in a persistent checkmark for completion of file upload

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1378]
Several testers indicated they weren't sure that files were done uploading. To help make this clearer, we want to remove the black checkmark that appears in the file description box and then goes away, and replace it with one that displays persistently while the file upload is complete.

![FileUpload.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/1b217c22-432e-479e-a73c-a2a274e9e772)

**Comment by ndushay** [comment]
slack conv w Amy on May 23:

![image](https://user-images.githubusercontent.com/96775/120553633-931f6980-c3ad-11eb-8b2b-e69d40c01af3.png)

**Comment by ndushay** [comment]
error, in black, no message:

![image](https://user-images.githubusercontent.com/96775/120554576-c0204c00-c3ae-11eb-9914-6560c1981600.png)

**Comment by ndushay** [comment]
making the styling work for a variety of viewing widths meant the checkmark needed to be a different color from the progress bar, as at some (medium) widths, the checkmark is rendering on top of the progress bar.

**Comment by ndushay** [comment]
I'm concerned about users seeing the alert triangle.  Here are sizes:

size:  2x
![image](https://user-images.githubusercontent.com/96775/120562380-214e1c80-c3bb-11eb-8c8c-6b8858ae2db7.png)

size: lg
![image](https://user-images.githubusercontent.com/96775/120562419-375bdd00-c3bb-11eb-8054-c224aab12f55.png)

size: sm
(as above)

**Comment by amyehodge** [comment]
@ndushay If you're looking for my opinion, I think they would see this in the small because it's red, but the lg is also good. The 2x seems like overkill.

**Comment by ndushay** [comment]
Here I have finally gotten the error message to display

![image](https://user-images.githubusercontent.com/96775/120564711-63c62800-c3c0-11eb-866e-1c4529cb5d84.png)

**Comment by ndushay** [comment]
and finally:

![image](https://user-images.githubusercontent.com/96775/120565208-68d7a700-c3c1-11eb-9f32-0132826f2481.png)

**Comment by ndushay** [comment]
success:

![image](https://user-images.githubusercontent.com/96775/120565303-9ae90900-c3c1-11eb-8028-6d8c12ad495c.png)

**Comment by amyehodge** [comment]
This seems to be working well to me.
