### ISSUE TITLE
Create pop-up message when users have deposited work in a collection with the review workflow off

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1380]
For collections that have the review workflow off, when a user clicks the "Deposit" button, display a pop-up with the following message:

:greencheckmark: You have successfully deposited your work

Here's what to expect next:
- Your deposit is currently making its way through our systems.
- You will receive an email notification when your deposit is complete.
- You will be able to edit this work when the deposit is complete.
- You may continue to use this application and create or edit other works while this deposit is in progress.

![nonapprovalPopup.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/4868a93c-12bc-4302-93c8-6846926876d6)

**Comment by jcoyne** [comment]
@amyehodge What should be in the background of the page that has this modal?

**Comment by amyehodge** [comment]
@astridu what do you think? I think it should be the item view page.

**Comment by jcoyne** [comment]
I'm wondering if it is distracting to go to a new page, see the content on the page and start to read it and then suddenly a modal appears. I think an interstitial page that explains "deposit accepted, now what?" might be a less jarring experience. What do you think?

**Comment by amyehodge** [comment]
I'm deferring to @astrid here.

**Comment by astridu** [comment]
I like the idea of an interstitial page. Something like this? 
![image](https://user-images.githubusercontent.com/42216982/118174217-6518bc00-b3e3-11eb-8399-ec0504ad2a30.png)

**Comment by jcoyne** [comment]
@astridu Yes. that looks fantastic.
