### ISSUE TITLE
Create pop-up message when users have deposited work in a collection with the review workflow on; remove existing message on page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1381]
For collections that have the review workflow on, when a user clicks the "Deposit" button, display a pop-up with the following message:

:greencheckmark: You have successfully submitted your deposit

Here's what to expect next:

- The managers and reviewers on this collection have received a notice that your deposit was submitted.
- They will be prompted to review your deposit and either approve it or return it to you for changes.
- You will receive an email notification when your deposit is either approved or returned to you for changes.
- If you have questions about the review process for your deposit, please contact the managers or reviewers for this collection, which can be found on the Collection settings page.

![approvalPopup.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/a4b669a0-0d8b-4a41-a44c-df3df216e8f3)

**Comment by amyehodge** [comment]
In addition, since we will have this pop-up, please remove this existing message that displays on the page when the work is submitted for review:

![OldMessage.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/9efbe1fc-168e-4675-b298-918814ae2278)

**Comment by jcoyne** [comment]
@amyehodge What should be in the background of the page that has this modal?  Maybe this should be a new page and not a modal?

**Comment by amyehodge** [comment]
@astridu what do you think? I think it should be the item view page.

**Comment by jcoyne** [comment]
I feel that modals that appear on pages that aren't triggered by an interaction are a bit jarring.  Is there a reason this should be a modal an not a standalone page?

**Comment by amyehodge** [comment]
I'm deferring to @astrid here.

**Comment by astridu** [comment]
See #1380
