### ISSUE TITLE
Make it clear to users that something has happened when they click deposit on the Collection edit form but it doesn't pass validation

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1382]
Similar to #1365, if we can reload to the top of the page, I think this is more of the interaction that users expect. It's difficult to tell if anything happened if no error messages are displayed on the visible part of the screen.

![CollectionValidFail](https://user-images.githubusercontent.com/5558511/116428234-96956300-a7f9-11eb-9951-a02218a1462c.gif)

**Comment by jcoyne** [comment]
For now scroll up to the first error on the page.
