### ISSUE TITLE
Do all of the field validations in one pass

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1388]
Right now, these happen in stages. The user will attempt to deposit and get notices about some, fix those, and then when they try to deposit again they may get notices about different issues they weren't notified about before. In addition, some things, like dates, appear to be doing validations in real time. This inconsistency is confusing to users.

The ideal scenario is that when the user clicks "deposit" they see all errors in the form presented at one time so they can fix them all and be confidant that when they click "deposit" again it will go through (barring their having made new errors, of course).

**Comment by amyehodge** [comment]
@astridu We wanted to make sure that our solutions do not reduce usability for those who are using screen readers. We need to make sure that they still can understand which fields are required, so we wanted your feedback on this ticket. Thanks.

**Comment by astridu** [comment]
The screen reader will read the '*Required fields' and then will read all the asterisks on the page so users will know that field is required. I agree that they should see all the errors at one time so they can fix them all at once and not have to click twice to do this. (does this answer your question?)

**Comment by jcoyne** [comment]
Part of this is blocked by #1377

**Comment by jcoyne** [comment]
These have all been broken out as separate issues.
