### ISSUE TITLE
Add "continue editing or deposit" button to collection details view page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1390]
Parallels #1375 for items.

This button should only appear when the work is in a draft state. This button will take the user to the collection edit form, same as the pencil icon, which we will leave on the page for consistency.

![CollectionContinue.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/af5d9a2b-371e-4efc-953f-6ebd790c2156)

**Comment by jcoyne** [comment]
@amyehodge The description on this ticket says "work", but the title says "collection".  Can you make them consistent?

Should this button go on all three tabs?  Since we have this button, should we remove the pencil icon, which I now believe would have the same function?

**Comment by amyehodge** [comment]
@jcoyne I've changed this title to say "work." The works pages don't have tabs, so I don't think that question is relevant here.

**Comment by jcoyne** [comment]
Is there a reason that "editing" is lowercase and "Deposit" is capitalized? That seems inconsistent.

**Comment by amyehodge** [comment]
I'm guessing the thinking was that the first letter for each action is capitalized: "Continue editing" or "Deposit". I actually like it this way b/c I think it makes it easier to see the two choices. <shrug> 

@astridu may want to weigh in -- perhaps this was not intentional and it all supposed to be capitalized -- or "Deposit" should have been lower case. @astridu can you confirm? Thanks.

**Comment by jcoyne** [comment]
I would say "editing" is the action, "continue" is an adverb.   If we didn't have "Deposit" in there would you use "Continue editing" or "Continue Editing"?  I think a decision on that would inform whether we have "Continue Editing or Deposit" or "Continue editing or deposit".

I'd also explore whether "Continue" adds anything here.  "Edit or Deposit" would be more succinct.

**Comment by amyehodge** [comment]
I would use "Continue editing" if "Deposit" weren't there.

However, you make an excellent point on perhaps dropping the "Continue" entirely. I'd like to see what @hannahfrost thinks about that as well. Hannah, do you think we need "Continue editing or deposit" on this button, or would "Editing or deposit" actually be clearer/better?

**Comment by hannahfrost** [comment]
"Edit or Deposit" is concise and clear. 

I also don't mind "Continue editing or Deposit", but it is wordier and therefore not a better choice.

Thanks!

**Comment by astridu** [comment]
Edit or Deposit works well. 
![image](https://user-images.githubusercontent.com/42216982/118175079-7adab100-b3e4-11eb-8b9b-84b8f50ee23c.png)

**Comment by jcoyne** [comment]
@amyehodge should this ticket be for collections since #1375 is for items?

**Comment by amyehodge** [comment]
Sorry, @jcoyne . I'm not sure how I got these so confused. 

This one is for collections, and #1375 is for works.

**Comment by jcoyne** [comment]
![Screen Shot 2021-05-14 at 9.24.49 AM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/1746d657-a62a-48e0-b20e-e2121ed0cd58)

Is the "Edit or Deposit" button okay to put next to the existing "Deposit to this Collection" button?  What side?

**Comment by amyehodge** [comment]
Since the Deposit button is always there, let's leave it all the way to the right on every page and display the "Edit or Deposit" button to the left of that when it is present.
