### ISSUE TITLE
Add "Reserve a PURL" button to Collection details/settings/deposits pages

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1393]
We'll need a mockup for this, but let's get this working correctly before we add more buttons for it.

**Comment by amyehodge** [comment]
@astridu Can you mockup what it would look like to put the Reserve a PURL button on this page? Thanks.

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/124982752-eeb3c700-dfeb-11eb-9b97-6dfa2cced602.png)
![image](https://user-images.githubusercontent.com/42216982/124982783-f7a49880-dfeb-11eb-8b03-9852810c8ecd.png)
![image](https://user-images.githubusercontent.com/42216982/124982826-03905a80-dfec-11eb-9e12-d39ebaefcfe0.png)

**Comment by astridu** [comment]
If Edit or Deposit button doesn't appear, then it would look like this. 
![image](https://user-images.githubusercontent.com/42216982/124982885-1c990b80-dfec-11eb-9038-f1727c91024a.png)
