### ISSUE TITLE
Reserving a PURL does not reserve a PURL but instead opens the edit form

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1394]
Clicking "Submit" on the "Reserve a PURL" modal should reserve the PURL and leave user on the dashboard page where they were, so they can see the reserved PURL on the list for that collection. Instead, it opens an item edit form with the title entered as the title and an error for the embargo date at the top of the page. Video below.

![ReservePURL.gif](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/6ad4f57f-b40c-4b8b-805c-0188b99b4156)

**Comment by amyehodge** [comment]
It works for these collections:
https://sul-h2-stage.stanford.edu/collections/705

It does not work for these collections:
https://sul-h2-stage.stanford.edu/collections/703
https://sul-h2-stage.stanford.edu/collections/533

**Comment by jcoyne** [comment]
I believe this is occurring when the collection requires an embargo date:
![Screen Shot 2021-05-12 at 3.16.56 PM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/cbabe41f-f1f3-449f-9f85-75d781221415)

It's running validations on the draft form and getting:
```
> form.errors.full_messages
 => ["Embargo-date Must provide all parts"]
```
