### ISSUE TITLE
Evaluate viability of testing scheme for hydrus object versioning in H2

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1395]
Evaluate whether it is realistic/practical to use "option 3" as described below for testing object versioning:
1. migrate existing hydrus druids from production storage to hydrus stage without moving the info from all the other databases (events etc)
2. version items on hydrus stage
3. copy these versioned objects over to H2 stage and test versioning of them there

This work is dependent on our first fixing up the versioning of H2 objects that is currently not working on stage.

It would be good in combination with this to test some of our test druids in a production environment.

**Comment by amyehodge** [comment]
@jcoyne Is the hydrus stage environment at sdr-test.stanford.edu?

**Comment by jcoyne** [comment]
Yes. You are correct.

**Comment by amyehodge** [comment]
I've created some test items to use for this. 

Collection: 
jj825zc3077
Items: 

Collection: 
qg660vq3546
Items:
druid:xf890cw3385
druid:ht040km1956

**Comment by amyehodge** [comment]
Migrated objects in production are being successfully versioned, so closing this.
