### ISSUE TITLE
Deposit type modal

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#140]
https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/431445056

Begin a new deposit by selecting type and subtype from the deposit type modal.

<img width="707" alt="Screen Shot 2020-10-16 at 11 18 15 AM" src="https://user-images.githubusercontent.com/92044/96283136-5da24900-0fa1-11eb-8a41-f44cb38f68fa.png">

**Comment by mjgiarlo** [comment]
Dup of #190, closing
