### ISSUE TITLE
Citation links on dashboard should change color and functionality based on item state

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1405]
The citation icons on the dashboard should not be visible when the object is in "draft - not deposited" or "PURL reserved" state.

ALTERNATIVE: Another option -- if this is easier to do -- would be to have the citation icons there but have them greyed out and not be clickable.

When the item is in deposited or version draft state, the citation icon should be visible and clickable and bring up the citation modal as it does not.

One caveat here is that items that are "pending approval" or "returned" are of two types. Those that are still initial versions that haven't been deposited should not have the icon, but those that are in one of these states as part of the versioning process SHOULD have the citation icons visible and clickable.

**Comment by jcoyne** [comment]
Disable these buttons for "draft" or "purl reserved"

**Comment by jcoyne** [comment]
@astridu what color should this button text be? The wireframes show blue, but we currently aren't showing any other blue except for tool tips.

**Comment by astridu** [comment]
They should be red like the other links and buttons.
