### ISSUE TITLE
Email notifications: "Depositor: New version in progress, not submitted/published" -- not being sent as intended

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1420]
Leah should have received this notification about this work that has been in draft state since April 5, 2021, but she hasn't. Can someone check on why this isn't going out on schedule? Thanks.

See #592 for original ticket.

**Comment by jcoyne** [comment]
we don't run scheduled jobs on stage because that would send out messages for any of the migrated content from production. We don't want to bother people about things in stage.

**Comment by amyehodge** [comment]
I do want to be able to test this at some point, so perhaps we can talk about turn it on for a brief time or just for some users or something.

**Comment by amyehodge** [comment]
Closing this since the work is completed, but I will test this when we go into production and these are turned back on.

**Comment by amyehodge** [comment]
Closing this since the work is completed, but I will test this when we go into production and these are turned back on.
