### ISSUE TITLE
Unable to deposit items that have a trailing period in the title

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#1453]
Because dor-services-app tries to clean it up and then complains that round tripping failed.
```
Expected: {:title=>[{:value=>"Test name."}]}
but received: {:title=>[{:value=>"Test name"}] } 
```

**Comment by amyehodge** [comment]
I actually just looked at Argo for all existing hydrus objects with trailing periods and found zero. I did see this object:

"Exploring the Relationship between LGBTQ+ Inclusive Education and Queer Identity Formation among Asian and Pacific Islander (API) Youth in the U.S" that is druid:bk989gm7699 that looks like it had the trailing period stripped when it shouldn't have. Could be more of these.

**Comment by arcadiafalcone** [comment]
It's OK to change dor-services-app normalization to keep the period.
