### ISSUE TITLE
"Edit or deposit" button on collection pages should only appear when collection is in draft state.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1473]
See #1390:

"This button should only appear when the work is in a draft state. This button will take the user to the collection edit form, same as the pencil icon, which we will leave on the page for consistency."

**Comment by jcoyne** [comment]
Currently we're only showing this when it is in an updateable state.  Is that not what you are seeing?

**Comment by amyehodge** [comment]
That's what I'm seeing, but that's not what was requested.

**Comment by jcoyne** [comment]
Can you provide an example so I can see the difference in what you are seeing and what was requested?  I don't know where there's a difference.

**Comment by amyehodge** [comment]
We want this button to show up when someone has work in progress that they are unsure how to get back to in order to finish or deposit the work. This corresponds to collections that are in "Draft - not deposited" or "New version in draft" states. Items in the "Deposited" state are also showing this button but should not be, because there is no work in progress here.
