### ISSUE TITLE
"Edit or deposit" button on work show page should only appear when work is in draft state or has been returned for editing.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1474]
See #1375:

"This button should only appear when the work is in a draft state or when a work in the review workflow has been returned for editing."

**Comment by jcoyne** [comment]
Currently we are only showing it when the work is in an editable state.   Are you seeing something different?

**Comment by amyehodge** [comment]
That's what I'm seeing, but that's not what was requested.

**Comment by jcoyne** [comment]
I'm having trouble understanding the difference between the two.

**Comment by amyehodge** [comment]
We want it to show up when someone has work in progress that they are unsure how to get back to in order to finish or deposit the work. This corresponds to items that are in "Draft - not deposited" state, "New version in draft", and "Returned" states. Items in the "Deposited" state are also showing this button but should not be, because there is no work in progress here. For example, this item: https://sul-h2-stage.stanford.edu/works/13270
 
![Screen Shot 2021-05-18 at 12 23 39 PM](https://user-images.githubusercontent.com/5558511/118688269-e69d8f00-b7d3-11eb-8fc1-9813cff14d6c.png)

There should not be a button on this item.

**Comment by jcoyne** [comment]
Thank you. That helps me understand.

**Comment by jcoyne** [comment]
However, we still want the pencil button to show even though it's deposited, right?

**Comment by amyehodge** [comment]
@jcoyne Yes.
