### ISSUE TITLE
Correct display issue with "Edit or deposit" button so that it is always inline with the title and the other button on the top right.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1476]
On https://sul-h2-stage.stanford.edu/collections/560 you can see that this button is shifted below the other content.

![Screen Shot 2021-05-18 at 10.15.34 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/5f52fd54-3829-462a-a5cb-ad9a6cdecf57)

**Comment by jcoyne** [comment]
The problem here is that there is not enough space on the line for all of the content. Do you want to define a specific way for this to wrap?

**Comment by amyehodge** [comment]
@astridu Do you have any suggestions here? Thanks.

**Comment by astridu** [comment]
Here's a suggestion:
![image](https://user-images.githubusercontent.com/42216982/118862299-69851f00-b892-11eb-950c-c9af4a9749d6.png)

**Comment by jcoyne** [comment]
We would like the buttons to always be on the same line and have the title flow around them if it's too long.

**Comment by astridu** [comment]
Would this work?
![image](https://user-images.githubusercontent.com/42216982/118887668-83812a80-b8af-11eb-9d5f-f5220cdc157f.png)

**Comment by amyehodge** [comment]
@astridu I think what @jcoyne is thinking is that the buttons would also be on the top line, for consistency, and then the text would flow around it if it's too long. That make sense?

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/118888562-ab24c280-b8b0-11eb-9743-7483499c6eb8.png)

**Comment by astridu** [comment]
If the buttons need to stay at the top, I would prefer this:
![image](https://user-images.githubusercontent.com/42216982/118888645-c7c0fa80-b8b0-11eb-86b5-5f41d161f6a5.png)
