### ISSUE TITLE
Screen should scroll to error message on license when this is the only thing left off of a new collection

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1487]
I open a new collection and filled in all the fields except for choosing a default license, then tried to deposit. The should have scrolled up to show me that error message, but it didn't. 

![licenseError.gif](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/624b3999-d4c6-46c2-878a-93ef16833c92)

**Comment by jcoyne** [comment]
See #1382 where we added scrolling.

**Comment by amyehodge** [comment]
Yes, but for some reason this one bit isn't working properly. Just for the license section.
