### ISSUE TITLE
Include information about where changes were made by users in the history table for items

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1498]
Currently the history table logs on that the item was updated. 

![Screen Shot 2021-05-20 at 3.01.00 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/73a0630a-8d45-425c-a13f-f4facaf0fe77)

Hydrus includes information about which fields were changed:

![image.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/9b4642ed-e324-49a1-b4cb-462fc539c2da)

This information should be included in the Description of Changes column in the history table.

**Comment by jcoyne** [comment]
@amyehodge I'm not sure if you mean these entries should be imported from Hydrus or that h2 should be collecting this data as well.  If the latter, can you help me understand who uses these entries and how they are used?  I suspect this would take quite some time to implement and we would need to go into greater detail about when each of these entries should show up.

**Comment by amyehodge** [comment]
I think we can stick to the level of info that hydrus seems to have. So, in the case above, we would say "subtype modified" but not indicate exactly what the change was.

So, the list should be for collections:

- collection name modified
- description modified
- contact email modified
- related links modified

And for items the list should be:

- files modified
- file description modified
- title of deposit modified
- contact email modified
- authors modified
- contributors modified
- publication date modified
- creation date modified
- abstract modified
- keywords modified
- work subtypes modified
- citation modified
- related works modified
- related links modified
- embargo modified
- visibility modified
- license modified

And if multiple fields are modified, list them together as hydrus does, such as

- file description, embargo modified

These should be included for additions, deletions, or changes to the fields.

**Comment by jcoyne** [comment]
Does embargo modified cover both the release date and the visibility or should those be separate things?

**Comment by jcoyne** [comment]
Is "files modified" going to be confusing?  Would it be more helpful to say "file added" and/or "file removed" as separate things?  Do we need one for "File visibility changed?"

**Comment by jcoyne** [comment]
Should these entries ever occur on first drafts or only after the work has been deposited?

**Comment by amyehodge** [comment]
> Does embargo modified cover both the release date and the visibility or should those be separate things?

Visibility would be the choice of Stanford or world. Embargo would be having/not having an embargo and changes in the date.


> Is "files modified" going to be confusing (this sounds like the content of the file itself was changed)? Would it be more helpful to say "file added" and/or "file removed" as separate things? Do we need one for "File visibility changed?"

"File added" and/or "file removed" is certainly more specific. That sounds better. Ah! I forgot about file visibility. Yes, add that. I'll update the list above.

**Comment by amyehodge** [comment]
> Should these entries ever occur on first drafts or only after the work has been deposited?

Ideally, these entries would occur for every "save" event, including before the first submission or deposit, as shown in the hydrus screenshot above.

**Comment by jcoyne** [comment]
> Ideally, these entries would occur for every "save" event, including before the first submission or deposit, as shown in the hydrus screenshot above.

I'm having trouble seeing how these serve the use case you outlined to help a collection manager see what has changed, because every work would be required to fill out all of the sections before it can be submitted for review.   That's just going to lead to a lot of clutter in that table which won't help the reviewer at all.

**Comment by amyehodge** [comment]
I misspoke in that the details do not need to be noted for the initial save, which might involve changes to many fields. I do think some users may check to look for changes before doing the initial deposit ("Did I update that file like I meant to?" for example).

Noting changes is not in any way tied to requiring sections be filled out or to the validations. Maybe we need to talk this through on a call. I can't figure out where we are out of sync.

**Comment by jcoyne** [comment]
I don't think we are out of sync, we're just nailing down the details.  I'm a bit concerned, this seems like a big chunk of work to add into the work cycle, and I'm now a bit worried that this could jeopardize the goal of getting h2 launched on schedule.

**Comment by amyehodge** [comment]
So, if this is a big chunk of work, what could we do that is not as big a chunk of work but that could provide more information about what was modified?
