### ISSUE TITLE
Enable user to delete the first entry of multi-entry fields

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1499]
The multi-entry fields that I'm referring to in this ticket:
Collections: email, related links
Works: email, contributor, related works, related links.

In all of these cases, the first entry box can not be deleted. However, a user pointed out that if you enter multiple entries and then decide that you want to delete the first one, it doesn't have the trash can icon next to it. They have to delete the text -- and replace it with something else if it's a required field, even though they have other entries.

I recall making the decision that the first box should always be present so that users can see the entry fields on the forms, and for the required fields (email, author, keyword) because one is always required. But I don't think we considered this use case.

@jcoyne @astridu Any thoughts on how we can meet both of these criteria?

**Comment by jcoyne** [comment]
We could have the first delete button just clears out the existing text field rather than remove them from the page entirely.

**Comment by amyehodge** [comment]
@jcoyne will that leave an empty box? These tend to leave empty fields in the metadata I think -- at least on the view page you get entries like " , keyword 2, keyword 3". This was something else I wanted to file a ticket about -- alerting the user to empty fields so they could delete them or removing empty fields automatically. I hate to create more of them.

**Comment by jcoyne** [comment]
oh right. I was confused.

**Comment by astridu** [comment]
I would have suggested what justin suggested above, and for the other entries, deleting the content in the box would delete that entry (not leave a blank space like it is doing now). However, if that's not what is happening on the back end, then make that first field required so it throws an error if the user attempts to deposit without filling that one out.
