### ISSUE TITLE
Generate a list of all current Hydrus users 

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1501]
@hannahfrost and I need a list of all the current hydrus users so that we can contact them about the pending switch from hydrus to H2. This includes collection managers, reviewers, and depositors.

SUNet IDs seem like the best things to provide, as these should be the easiest to retrieve and are easily converted to email addresses.

**Comment by jcoyne** [comment]
What does "current" mean in this context?

**Comment by hannahfrost** [comment]
@jcoyne Every user that has a role in Hydrus at the time that the report is run.

**Comment by jcoyne** [comment]
Here is the incantation:
```
RAILS_ENV=production bin/rails runner "User.all.pluck(:email).each { |email| puts email }; nil" > report.txt
```

**Comment by amyehodge** [comment]
@jcoyne I talked with @hannahfrost earlier today about our communications plan, and we would like some additional information in this report. This additional information will help us target different communications to different groups of users.

We would like a .csv file that contains every user with the collection they are associated with and their role in that collection. There will be multiple users for nearly every collection, some users will have more than one role on a collection, and some users will be associated with multiple collections. Just give it all to us in the .csv as collection druid | sunet ID | role.

Let me know if you need clarifications. Thanks.

**Comment by justinlittman** [comment]
Here is the revised incantation:
```
RAILS_ENV=production bin/rails runner 'Hydrus::Collection.all_hydrus_collections.each {|druid| collection = Hydrus::Collection.find(druid); Hydrus::Responsible.role_labels(:collection_level).keys.each {|role| collection.apo.persons_with_role(role).each {|sunet| puts "#{druid},#{sunet},#{role}"}}}; nil' > report.csv
```

**Comment by jcoyne** [comment]
@amyehodge  do you want this report now or are we still waiting until you are ready?

**Comment by justinlittman** [comment]
Report generated and sent to @amyehodge. Amy -- you can decide whether to close this ticket or leave open.

**Comment by amyehodge** [comment]
@justinlittman Thanks. I've sent this to Hannah to see if it has what she needs. I'll let you know if we need to have it rerun. I'll leave this open for now.

**Comment by hannahfrost** [comment]
I believe this is perfect @amyehodge @justinlittman @jcoyne . Thanks a bunch!
