### ISSUE TITLE
Notify user and prevent saving when duplicate keyword has been entered

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1502]
Our keywords map to DOI subjects, which has a uniqueness requirement in the DataCite DOI API. See https://github.com/datacite/schema/blob/master/source/json/kernel-4.3/datacite_4.3_schema.json#L298.

If a user enters duplicate keywords, the DOI is not created, though a DOI displays in H2 as if it has been.

The request here is to identify duplicates via a string match against other entries on the current form so that users can delete one to prevent the DOI minting from running into trouble. Users should be able to save as draft, submit for approval, or deposit when there are duplicate keywords. Display error message and red box around field similar to other validation errors.

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/5558511/172940758-78fb6f01-496e-47b5-821e-79abf89c2348.png">

**Comment by amyehodge** [comment]
There is a uniqueness requirement in the DOI API for subjects. 

See https://github.com/datacite/schema/blob/master/source/json/kernel-4.3/datacite_4.3_schema.json#L298

Keywords in H2 map to these subjects. As I recall, the result of entering a duplicate keyword is that this causes a DOI not to be created, though a DOI displays in H2 as if it has been. 

It seems like we either need to:

1.    Identify duplicates so that users can delete one so that the DOI minting doesn’t run into trouble (can we do a string match against other entries on the current form?)
    OR
2.    Notify the user that the DOI minting was not successful and that they should check for and remove duplicate keywords and try again.

I prefer #1, but would take #2.

**Comment by amyehodge** [comment]
@astridu Here's an old ticket but one I'd like to see addressed in this work cycle. Can you mock up option #1 above? Thanks.

**Comment by jcoyne** [comment]
@peetucket I'm reopening this, because #2424 didn't yet do the client side validation that Amy asked for in this ticket.
