### ISSUE TITLE
List individual keywords on the item view page on separate lines

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1512]
These are currently separated by commas, but this becomes a little confusing when users enter terms that contain commas. Putting them on separate lines makes them much more readable.

**Comment by amyehodge** [comment]
Another option would be to display these as one word per line so that no separators are necessary. This would make them much easier for the user to scan.

**Comment by amyehodge** [comment]
@astridu Do you think a using a different separator or putting them on separate lines is better?

**Comment by astridu** [comment]
Here's how it looks with just a couple keywords and with several keywords. What do you think?
![image](https://user-images.githubusercontent.com/42216982/125550558-261cc9cb-ee57-4fbe-b76c-58b75d5a2e65.png)

**Comment by astridu** [comment]
Versus all in one line:
![image](https://user-images.githubusercontent.com/42216982/125551088-c2774871-ffae-4214-ba76-54dcdc3b8796.png)

**Comment by amyehodge** [comment]
@astridu The separate lines will make the page longer when there are more, but it's way more readable. And I'll note the PURL displays them on separate lines as well. I like that option, so I'm going to rename this ticket.
