### ISSUE TITLE
Collection details save button goes to view Collection settings

### ISSUE THREAD

**Issue by astridu** [sul-dlss/happy-heron#1516]
When I click on save on the Collection details page, I'm taken to the view Collection settings page. I should go to the view Collection details page.

**Comment by jcoyne** [comment]
Can you split this into two issues please?

**Comment by jcoyne** [comment]
I'm not sure I can reproduce #1.  When I'm on the collection details page and I click the edit (pencil) button. I go to the edit Collection details page:


<img width="1339" alt="Screen Shot 2021-05-21 at 4 28 33 PM" src="https://user-images.githubusercontent.com/92044/119199966-a1869080-ba51-11eb-8c6c-490e4c77fc25.png">

<img width="1250" alt="Screen Shot 2021-05-21 at 4 28 43 PM" src="https://user-images.githubusercontent.com/92044/119200077-d85ca680-ba51-11eb-9ae2-800327a0ccfc.png">

**Comment by astridu** [comment]
I can no longer reproduce # 1 either. I will remove it.
