### ISSUE TITLE
Clicking 'edit' or 'pencil icon' for collections in 'depositing' status takes me to homepage

### ISSUE THREAD

**Issue by astridu** [sul-dlss/happy-heron#1519]
If I click on 'edit' or 'pencil icon' for collections or objects in 'depositing' status, I'm taken to the homepage. In my account, the following collections are in 'depositing' mode:
- Collection for Astrid and Hannah
- Collection for Astrid and Hannah
- Astrid Testing Collection
If you click on any of these collections > then click on Collection details > then click any of the pencil icons on that page > I'm taken to the homepage.

**Comment by jcoyne** [comment]
@astridu can you submit a screenshot? I wouldn't expect that collections that are in depositing status would have an edit button.

**Comment by astridu** [comment]
Maybe these collections are buggy?
![image](https://user-images.githubusercontent.com/42216982/119199718-6def3a80-ba40-11eb-9bb3-c7ed9ad6b89b.png)

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/119199777-87908200-ba40-11eb-95f0-1890fe08c44d.png)

**Comment by jcoyne** [comment]
I believe this is a duplicate of #1482

**Comment by astridu** [comment]
ok, I'll close it.

**Comment by astridu** [comment]
duplicate of #1482
