### ISSUE TITLE
Error message should display inline for embargo date validation

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1527]
The boxes are highlighted but the text message is not displaying. 

![Screen Shot 2021-05-25 at 4.30.27 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/93022355-489c-4b87-9393-6a4fb4e2fca0)

**Comment by jcoyne** [comment]
What should the text be for this message?

**Comment by amyehodge** [comment]
This looks good to me.
