### ISSUE TITLE
Add link to Terms of Deposit FAQ to modal

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1534]
We now have a help page of FAQs about the Terms of Deposit. We need to include a link to that in the modal. This should be placed to the left of the Help link.

@astridu has provided a mockup below.
The icon to use is fa-question-circle. 
The link should go to https://library.stanford.edu/research/stanford-digital-repository/terms-deposit.

![image.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/a7830e95-a555-4e07-bae1-613f62e1e378)

**Comment by amyehodge** [comment]
This is the last piece of work that was lingering to complete the Terms of Deposit updates. I was waiting to file the ticket because I wasn't sure when/whether this was going to be ready in time, considering it involved Mimi and the General Counsel's Office. But it is now ready.

**Comment by jcoyne** [comment]
Should this link open in a new tab or the same tab?

**Comment by amyehodge** [comment]
Since this goes to the library website, I'd open this in a new tab.
