### ISSUE TITLE
Enable workTypeModal for Edit Link on Collections Deposits Page

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/happy-heron#1546]
On a collection's Deposits View Page, if a work version has a state of `purl_reserved`, clicking on the Edit icon should activate the `workTypeModal` to prompt the user to select a work-type before continuing. 

![Screen Shot 2021-05-28 at 9 29 06 AM](https://user-images.githubusercontent.com/71847/120008280-08e39980-bf98-11eb-8057-fed9e0a4c308.png)

Should be able to leverage the new `PurlCheckLinkComponent`.

**Comment by jcoyne** [comment]
Fixed by #1691
