### ISSUE TITLE
"What's changing" element for collections should be the same color as the one on the items page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1573]
The one for the collections page looks like this:
![Screen Shot 2021-06-02 at 5.00.27 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/92a94c9d-3c50-43c8-ba50-7c2927d2f5ba)

The one for the items page looks like this:
 ![Screen Shot 2021-06-02 at 5.00.13 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/f4a82702-52c9-4acb-b2f6-75ac92bf4c34)

**Comment by ndushay** [comment]
should it also say "version your collection *" ?   and should the item page one have the asterisk?

**Comment by jcoyne** [comment]
> should it also say "version your collection *" ? and should the item page one have the asterisk?

Yes, but that work is already done.
