### ISSUE TITLE
"What's changing" element on collections page should display error message when not filled in

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1574]
When it does not pass the validation it should display the same error message as is displayed on the items page.

Current collections validation error:
 ![Screen Shot 2021-06-02 at 5.00.39 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/b38f663b-0458-47b4-9574-f18bbbba9791)!

Items validation error:
![Screen Shot 2021-06-02 at 5.05.51 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/8fb5d10c-3c6f-43f7-b47b-2e2649e49436)

Text of error message: You must describe your changes.

**Comment by ndushay** [comment]
what about the asterisk?  Should it be present for both?  Absent for both?

**Comment by jcoyne** [comment]
Is "Version you **Work**" the correct text?  Should it be "Version your collection"?

**Comment by amyehodge** [comment]
@ndushay Please asterisk both. And good catch, @jcoyne . This should say "Version your collection". It takes a village.
