### ISSUE TITLE
Inital Migration

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#1630]
Initially we will migrate only 8 collections.

Then we will ensure the database has a snapshot of production (so we can fall back if we made an error).

Then we will migrate the rest of https://docs.google.com/spreadsheets/d/1hNxM5hobMzrptxLctWfzDGSrl0ueBg5xGtQ47wFKC2g/edit#gid=1972276175 *EXCLUDING* the initial 8, because we don't want any changes that were made via h2 to be overwritten with the old hydrus data.

**Comment by amyehodge** [comment]
**Please do not migrate until we have confirmed that we have talked to the content managers about the timing of a temporary outage. We also intend to change permissions on these collections in advance of the migration to make sure they can't change anything while this is going on.**

Druids of the 8 collections to be migrated in the first batch:
cb946pf0135
tg242xv5347
gk894yk3598
nc574ck0385
pn808wc6253
px507jb1735
qq279mc0438
wm752pd6356

This should be done with all the migration settings in place, i.e. items with catkeys should not be migrated, items in the spreadsheet for having work types updated should have the work types updated, etc.

**Comment by amyehodge** [comment]
Here’s the order of events from my perspective:

1. verify that the license work is complete
2. Amy and Justin will determine when to do the migration, as both need to be available (early in the morning would be good)
3. Amy will communicate that timing to the content owners
4. Amy will reset the collection permissions (save the participant lists elsewhere, remove everyone from collections and replace them with me)
5. Amy will let Justin know when step 5 is done.
6. Justin runs the migration at the predetermined time.
7. Once migration is complete, Justin lets Amy know and she will reset the permissions.
8. Amy will communicate with the content owners that they are free to work in H2 and provide instruction as needed.

**Comment by amyehodge** [comment]
@amyehodge Collection participant info for the first 8 collections -- for restoring after the migration is complete -- is in https://docs.google.com/spreadsheets/d/1DDFg3v3nRQ88bXYiEFzl-5IfKlKdpa2IKmxxuRq4UwU/edit#gid=482510041

**Comment by jcoyne** [comment]
@amyehodge regarding the individual items not to migrate, those 5 are already encoded in the export script in hydrus.  I've updated the type mappings in the h2 import script.
