### ISSUE TITLE
For a reserved PURL, the work subtypes modal should display an error message when the proper subtypes for Music, Mixed Materials, and Other are not selected

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1644]
If you try to edit a registered PURL, and you select either music, mixed materials, or other and do not select or fill in the required subtype information, it kicks you back to the dashboard. It should be displaying an error message to the user about what they need to fix.

For music without a subtype, the following HB error is also produced:

Error detected in: happy-heron (stage)

Full report at https://app.honeybadger.io/projects/77112/faults/79867416

ActiveRecord::RecordInvalid: Validation failed: Subtype is not a valid subtype for work type music

Summary

works#update_type

URL: https://sul-h2-stage.stanford.edu/works/18016/update_type

Hostname: sul-h2-stage.stanford.edu

Context

user_scope: user
user_id: 12
user_email: amyhodge@stanford.edu
Trace

app/models/work_version.rb:161:in `block in choose_type_for_purl_reservation`
app/models/work_version.rb:160:in `choose_type_for_purl_reservation`
app/controllers/works_controller.rb:53:in `update_type`

**Comment by jcoyne** [comment]
Is this the same as #1618 ?

**Comment by amyehodge** [comment]
Sorry, this has already been filed in #1618
