### ISSUE TITLE
History table should only indicate a field has been modified when it actually has been modified.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1678]
I versioned https://sul-h2-stage.stanford.edu/works/17866, an item migrated from hydrus and deposited originally by thalassa that had no history information. I added a version note and was required to update the license in order to redeposit. 

History now shows:
![Screen Shot 2021-06-18 at 4.07.59 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/719a6304-b0d1-4d40-a522-09f0378e2611)

I did update and deposit this item, but it says I modified everything when I only modified the license.

**Comment by jcoyne** [comment]
I think this happens when you do a new version, because the new version defaults to everything being blank.  So it sees that everything is changed.

**Comment by amyehodge** [comment]
This ticket is covered by #1694.
