### ISSUE TITLE
Editing a reserved PURL should bring up the work types modal

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1679]
Try any of the reserved purls at https://sul-h2-stage.stanford.edu/collections/1084/works.

When I click on the pencil I'm taken to the deposit form and skipping the work types modal altogether.

**Comment by amyehodge** [comment]
This appears to now be working for newly reserved PURLs in this same collection, but still not for the original set, named. "1" through "9".

**Comment by amyehodge** [comment]
@jcoyne Is there some reason that the original set I noted as not working correctly should not be working, even if others are? In other words, is there still a bug in here somewhere that needs to be addressed?

**Comment by jcoyne** [comment]
@amyehodge I don't know. I haven't been very involved in this work. I believe @jmartin-sul and @justinlittman know the most about this.
