### ISSUE TITLE
Error when I click on "Deposits" at the top of my collection page

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/happy-heron#1684]
I have deposited an item in my collection. 

https://sul-h2-stage.stanford.edu/collections/1134

When I try to navigate to the list of Deposits in this collection, I get the message, "We're sorry but something went wrong"

**Comment by amyehodge** [comment]
related to #1671?

**Comment by jcoyne** [comment]
yes, this is the same as #1671
