### ISSUE TITLE
Reserved PURLs should show up in the Deposits in Progress section at the top of the dashboard.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1703]

**Comment by ndushay** [comment]
@amyehodge Can you say more about what should be changed?

![image](https://user-images.githubusercontent.com/96775/125101112-b6b19000-e08e-11eb-9670-9c415045e18c.png)

**Comment by amyehodge** [comment]
After the user reserves a PURL, that item should show up in the Deposits in progress section. For example, I just reserved a PURL and called it "Friday's Reserved PURL test." I'd like to see it show up with the works in the screenshot above. It would look kinda like this:

`Creating another collection > Friday's Reserved PURL test [pencil icon]  [progress bar]   **_PURL reserved_**`

I'm not sure what order the deposits in progress are displaying in, but it should be inserted there in the proper place.
