### ISSUE TITLE
Final Migration 

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#1718]
See #1630 for initial migration. (Old set of directions: https://github.com/sul-dlss/happy-heron/issues/1226)

Migrate the rest of the collections from  https://docs.google.com/spreadsheets/d/1hNxM5hobMzrptxLctWfzDGSrl0ueBg5xGtQ47wFKC2g/edit#gid=1972276175 EXCLUDING the initial 8, because we don't want any changes that were made via h2 to be overwritten with the old hydrus data.

Druids of the 8 collections that were migrated in the first batch:
cb946pf0135
tg242xv5347
gk894yk3598
nc574ck0385
pn808wc6253
px507jb1735
qq279mc0438
wm752pd6356

Here’s the order of events from my perspective:

Tentatively scheduled for Aug 2.

- [x] Amy and Justin will determine when to do the migration, as both need to be available (early in the morning would be good)
- [x] Amy will communicate that timing to the content owners
- [x] turn off access to Hydrus
    - [x] Justin L will merge migration-third-run and maintenance-page into a branch and deploy to production
- [x] Move sdr.stanford.edu to h2 (#operations)
- [x] Justin L will export collections.json and items.json from Hydrus production.
    - [x] Get the list of collections from Amy (From “latest final list” in https://docs.google.com/spreadsheets/d/1hNxM5hobMzrptxLctWfzDGSrl0ueBg5xGtQ47wFKC2g/edit#gid=1972276175)
    - [x] Save this list as `collection_druids.txt` and upload it to Hydrus prod (in the `/opt/app/hydrus/hydrus/current` directory)
    - [x] on Hydrus prod, using `screen`, run: `RAILS_ENV=production bin/export-collections > collections.jsonl` (this takes about 5 minutes)
    - [x] Then run `RAILS_ENV=production bin/export-items > items.jsonl` (this takes about 1 hour) (5012 expected, but 4423 delivered because some were skipped due to having catkey)
    - [x] Move items.jsonl and collections.jsonl to h2 prod `scp "hydrus@sul-hydrus-prod:/opt/app/hydrus/hydrus/current/*.jsonl" .` then `scp *.jsonl h2@sul-h2-prod:`
    - [x] Rebase `migrations-third-run`, push to origin, and then deploy it to h2 prod
    - [x] ssh to h2 prod
    - [x] start `screen` and then run `RAILS_ENV=production bin/migrate-collections ~/collections.jsonl` (this take about 3 min)
    - [x] Get the migration_item_type_updates.csv in place on h2 prod. This comes from https://docs.google.com/spreadsheets/d/15yyaBUpY5JUmoCjN2oitVAWF2-uRxe2y1PHMNH_6mSU/edit#gid=1948024480 (the first tab called "Mapping") We download as csv and push it into the migration branch of the h2 repo.
    - [x] run `RAILS_ENV=production bin/migrate-items ~/items.jsonl 0 /data/hydrus-files migration_item_type_updates.csv ` (started at 12:30)
- [x] Developer runs the migration at the predetermined time.
- [x] Developer sets all pending hydrusAssemblyWF workflow steps to complete (see https://github.com/sul-dlss/happy-heron/issues/1744) in the workflow server console.
    - [x] On workflow-server-rails in the rails console run: `WorkflowStep.where(workflow: 'hydrusAssemblyWF', status: 'waiting').update_all(status: 'completed')`
- [ ] Amy will communicate with the content owners that they are free to work in H2 and provide instruction as needed.

**Comment by amyehodge** [comment]
@jcoyne, @hannahfrost and I discussed earlier today that we'd like to turn off access to Hydrus on the afternoon of Friday, July 30, and then plan for the migration first thing on Monday morning, August 2.

We'd like to see something similar to the maintenance page used last summer put up for people during the outage, though we would want to alter that text.

Also, we need to make sure that University Archives still has access to hydrus after this migration, so they can complete the evaluation of their content as we discussed at a recent meeting. What URL will they need to use to do that? Thanks.

**Comment by amyehodge** [comment]
@jcoyne Vivian asked that I confirm with you regarding some points on the migration.

1. During the "freeze" period no one should have access to hydrus.
2. After the migration, University Archives staff and me, @hannahfrost , and @andrewjbtw , should have permission to view but not edit content in Hydrus. I'd like to confirm the location of that -- I think sul-hydrus-prod, but please confirm here. 

Thanks.

**Comment by jcoyne** [comment]
> After the migration, University Archives staff and me, @hannahfrost , and @andrewjbtw , should have permission to view but not edit content in Hydrus. I'd like to confirm the location of that -- I think sul-hydrus-prod, but please confirm here.

Hydrus doesn't have such a feature.

**Comment by hannahfrost** [comment]
@jcoyne Is it possible to limit access to sul-hydrus-prod after the migration to a small set of users, even if it is not possible to prevent editing? 

@amyehodge I would expect that we can be trusted to not edit any Hydrus content in Hydrus, do you agree?

**Comment by jcoyne** [comment]
@hannahfrost I believe the operations team could put such a restriction in place.  However, there are other concerns as I had planned the migration in such that aspects of Hydrus may not be working correctly after the migration (namely the workflow).

**Comment by amyehodge** [comment]
@jcoyne @andrewjbtw Regarding the workflow post-migration, we only need this group of people to be able to look at the content that is there (correct, @hannahfrost?). They should not be making any changes to any objects or saving or depositing anything. That's all we need to be able to support.

**Comment by amyehodge** [comment]
@jcoyne and @justinlittman 

Hannah is making final updates to the migration list. 

See this step above:

- [ ]  Get the list of collections from Amy (From “Copy of latest final list for test migrations” in https://docs.google.com/spreadsheets/d/1hNxM5hobMzrptxLctWfzDGSrl0ueBg5xGtQ47wFKC2g/edit#gid=1972276175)

THIS SHOULD BE "latest final list" -- NOT "Copy of latest final list for test migrations"
Still the same spreadsheet link
