### ISSUE TITLE
What are valid sub-type values?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#172]
Is this something currently a part of Hydrus?

Is this a multiple select?  How do we store in MODS and the cocina data?

**Comment by mjgiarlo** [comment]
@jcoyne flag for discussion with @amyehodge and @peetucket ? (alongside the user groups issue)

**Comment by amyehodge** [comment]
This is not currently a part of hydrus, but @arcadiafalcone has been involved in the discussions around setting this up. We still need to discuss the mappings. Multiple subtypes can be selected and will, I think, be stored as genre terms in the MODS. @hannahfrost and I need to further discuss with @arcadiafalcone .

**Comment by mjgiarlo** [comment]
@amyehodge ok, thanks! moving to backlog for now.

**Comment by amyehodge** [comment]
@mjgiarlo @arcadiafalcone has asked for an estimate of when you need the mappings.

**Comment by mjgiarlo** [comment]
@amyehodge Depends on how high of a priority this issue is for us, I reckon. Would you like to see functional subtypes in sprint 0, sprint 1, or later? I'm :100: flexible.

**Comment by amyehodge** [comment]
@mjgiarlo As this is new, I'd like to see it sooner rather than later so we can get some feedback on it. @arcadiafalcone I don't know what looks reasonable to you, but this is fairly high priority for me. Thanks.

**Comment by arcadiafalcone** [comment]
@amyehodge @mjgiarlo @jcoyne I've recruited Greta in MDU to work on mapping these terms to controlled vocabularies (where possible) over the next week. Mapping document is here: https://docs.google.com/spreadsheets/d/1EiGgVqtb6PUJE2cI_jhqnAoiQkiwZtar4tF7NHwSMz8/edit?usp=sharing. Most if not all of the subtypes will map to MODS genre (a few may map to form), and the object types will map to typeOfResource.
