### ISSUE TITLE
Update layout for release and visibility section of item deposit form

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1724]
Goal is to make this section more readable and to make it clear that there are multiple settings the user may need to consider here. 

In general this will:
1.  split this into separate sections -- 2 now, and 3 once DOI is added
2. each section will have its own clear header
3. asterisks for whether a section is provided will be displayed next to the header ONLY when the user can actually make a choice, i.e. when the collection-level setting is "depositor selects"
4. sections will be set off from each other with gray boxes
5. in each section the display will either say what the setting is set for when it has been defined at the collection level, or the display will present the user an option when the collection has been set for "depositor selects"

See the design mockup for this at https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/453759485_DOI -- see mockup IIIa.

![Screen Shot 2021-06-29 at 3.34.06 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/d5b47e4e-6bee-4fd4-b56c-14ea247ae610)

This ticket is only for the release and visibility sections. The DOI section will be ticketed separately.

**Comment by amyehodge** [comment]
Currently waiting for final changes to the mockups to be completed.

**Comment by jcoyne** [comment]
@astridu should we drop the bold text on the radio label that is selected?

**Comment by jcoyne** [comment]
@amyehodge the implication for including DOI in this section is that it happens after publication, but we want the DOI to be minted right away, not after the embargo is released, right?  Is that confusing to the user?

**Comment by astridu** [comment]
@jcoyne 
should we drop the bold text on the radio label that is selected? Yes, it's inconsistent with how we treat other radio button selections (like on the collections page).
Are we going to stop doing the conditional title for this section? No. Updated the screenshot below.
![image](https://user-images.githubusercontent.com/42216982/125341648-b02e4d00-e308-11eb-9aa9-1086f734d19d.png)

**Comment by amyehodge** [comment]
@astridu and @jcoyne I've been thinking about @jcoyne's question to me above. The reason we had included "after publication" in this header was to make it clearer that these things only happen after you click the "deposit" button. Though this button in hydrus is called "publish" which was more of a direct connection. I wonder if that makes sense now that we changed the button to say "deposit." 

Maybe we should go for more clarity here -- "Manage settings for release date, download access, and DOI assignment". If we do that we may want to change the subheader for "Audience" as well to "Download access". 

Thoughts?

**Comment by astridu** [comment]
That sounds good. Will update mockup this afternoon.

**Comment by astridu** [comment]
Here is a link to the updated mockups: https://projects.invisionapp.com/share/EQXC9CLKCR2#/453759485_DOI

**Comment by amyehodge** [comment]
Thanks, @astridu. @jcoyne does this adequately address your concern?

**Comment by jcoyne** [comment]
Sure does. 👍

**Comment by amyehodge** [comment]
Cool. I'm putting this in the ready.
