### ISSUE TITLE
add user hahn1 as collection manager on selection of Hydrus collections

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/happy-heron#1725]
To review collections of university archives content deposited via Hydrus, and specifically to review item drafts in process or open versions, Hanna Ahn needs to be able to access collections for which she does not have user permissions.

The attached TXT is a list of druids for those collections.

Please add her SUNet ID, hahn1, as a collection manager on each of these collections so that she can access them in Hydrus.

[Hydrus.collections.-.add.hahn1.as.manager.txt](https://github.com/sul-dlss/happy-heron/files/6735601/Hydrus.collections.-.add.hahn1.as.manager.txt)

Note that we did this once before - adding user jschne. See https://github.com/sul-dlss/happy-heron/issues/824. 
The attached TXT has been updated and should not include the druids for objects that are not valid Hydrus objects.

**Comment by justinlittman** [comment]
PR for the rake task: https://github.com/sul-dlss/hydrus/pull/551

**Comment by justinlittman** [comment]
Here's the log
[add_to_collection_manager.log](https://github.com/sul-dlss/happy-heron/files/6777415/add_to_collection_manager.log)

@hannahfrost Can you verify that this is complete (and if so, close)?
