### ISSUE TITLE
DOI: Add DOI assignment options to collection deposit form and to the collection details form.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1726]
Add options in the Release and Visibility section for DOI assignment for the collection. This PR should be made against the DOI feature branch https://github.com/sul-dlss/happy-heron/pull/1776.

Design Doc: https://docs.google.com/document/d/16zGrIpRgGkq8d4VDUjEstoB2p8xFEuiAmKJopcT1CaQ/edit#heading=h.r3t7es1ylg4i

Mockups: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/453759485_DOI -- in particular mockup I.

**Comment by amyehodge** [comment]
@jcoyne would you like this to be two separate pages -- one for the complete version of the form the user sees when creating a new collection, and one for the just the details page they see when they are versioning?

**Comment by jcoyne** [comment]
@amyehodge what should existing collections be set to?

**Comment by amyehodge** [comment]
@jcoyne Does that include all the migrated collections and any H2-created collections made before this is implemented? 

This is a good question. Let me think on this.

**Comment by jcoyne** [comment]
@amyehodge yes any existing collections.

**Comment by amyehodge** [comment]
Let's go with the default setting be always assign a DOI.
