### ISSUE TITLE
DOI: Update collection settings view page to show DOI assignment setting

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1727]
This allows the user to see the DOI setting selected. This PR should be made against the DOI feature branch https://github.com/sul-dlss/happy-heron/pull/1776.

Design Doc: https://docs.google.com/document/d/16zGrIpRgGkq8d4VDUjEstoB2p8xFEuiAmKJopcT1CaQ/edit#heading=h.lr01ej7okb5u

Mockups: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/453759485_DOI -- in particular mockup II.

**Comment by justinlittman** [comment]
@amyehodge Does "not automatically assigned" make sense? It seems to suggest that the depositor can manually assign. Should it just be "not assigned"?

**Comment by amyehodge** [comment]
@justinlittman Agreed. "Depositor selects" is the notation for a depositor can choose, so this one should be "Not assigned." I've updated it in the Design Doc. @astridu can you update this is in the mockups? I've made a comment about it there.

**Comment by astridu** [comment]
Mockup is updated.

**Comment by ndushay** [comment]
correct "what is a DOI" link is noted in #1865
