### ISSUE TITLE
DOI: Update Item view page to list DOI when assigned and setting at all times

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1729]
This will allow the user to see the DOI when one has been assigned and to see what the setting is for the item under all conditions. This PR should be made against the DOI feature branch https://github.com/sul-dlss/happy-heron/pull/1776.

Design Doc: https://docs.google.com/document/d/16zGrIpRgGkq8d4VDUjEstoB2p8xFEuiAmKJopcT1CaQ/edit#heading=h.8gkxx9vaxlwq

Mockups: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/453759485_DOI -- see mockups IVa and IVb

**Comment by jcoyne** [comment]
I have a question about the format of this. Do we intend to use a DOI link or a DOI name.  The mockups are not clear.  The choice is about specifying a resolver or not (eg. the https://doi.org/ prefix.). doi.org is one resolver service for DOIs but it is not the only resolver service.

**Comment by amyehodge** [comment]
The display guidelines are at https://support.datacite.org/docs/datacite-doi-display-guidelines:

“Yes, a DataCite DOI must be displayed as a link, because it is both an identifier and a persistent link. It is easier for users when a DOI is displayed as a full link as it can be easily copied and reused.”

This should be displayed as `https://doi.org/ prefix/suffix`
