### ISSUE TITLE
DOI: send updated metadata to DataCite when an object with a DOI is versioned

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1732]

**Comment by jcoyne** [comment]
@amyehodge which metadata should be sent?

**Comment by amyehodge** [comment]
We at a minimum need to send whichever fields we have that are mapped to DataCite metadata and that have been changed by the user. Alternatively, we can just send all the metadata again after the update, whether it was changed or not. That might be easier. 

If the question is what are we sending even the first time around, I can get you the required set. @arcadiafalcone has the mappings, I believe. Though if we get ORCIDs implemented, we would want to send that as well, though it is not required, as well as anything else we have mapped that we can send.

**Comment by arcadiafalcone** [comment]
I think the preliminary mappings got dropped because DataCite wasn't in the first round of development - I can add those to dor-services-app with the other mappings (unless they should go elsewhere).

**Comment by arcadiafalcone** [comment]
@jcoyne @justinlittman What would be the best way to provide DataCite mapping specs? Should I add a `let(:datacite) do` stanza to the existing MODS specs or create separate files?

**Comment by jcoyne** [comment]
@arcadiafalcone can you create separate files? This is unlikely to be a part of the existing dor-services-app so it will be easier for us to move to the correct repo if it's separate.

**Comment by arcadiafalcone** [comment]
Mapping ticket: https://github.com/sul-dlss/dor-services-app/issues/2909
