### ISSUE TITLE
Rework keyword search to provide better matching and context for terms.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1736]
Improve this so that terms like "tea" return relevant matches. 

Provide some sort of context for users so they can better understand terms that might have many meanings, like "fabric." Possibly definitions or locations in the hierarchy, if one of those is available from FAST.

@jcoyne This ticket needs a lot more detail, I'm sure.

**Comment by jcoyne** [comment]
<img width="674" alt="Screen Shot 2021-07-06 at 1 46 07 PM" src="https://user-images.githubusercontent.com/92044/124651541-ac11b380-de60-11eb-8a10-e0d1e7299fa8.png">

<img width="473" alt="Screen Shot 2021-07-06 at 1 46 17 PM" src="https://user-images.githubusercontent.com/92044/124651548-addb7700-de60-11eb-9c73-ce04f008fd83.png">

**Comment by jcoyne** [comment]
@amyehodge do you think the work @justinlittman did on #1765 will complete this?

**Comment by amyehodge** [comment]
The remaining bit would be providing some context for the search terms as mentioned above -- definitions or locations within the hierarchy (assuming there is one). Is there anything like that available?

**Comment by justinlittman** [comment]
@amyehodge Can you take a look at http://fast.oclc.org/searchfast and see if there is additional context that you consider relevant?

**Comment by amyehodge** [comment]
@jcoyne I'm not finding a field that is consistently providing useful information to display in the app to users. We could link to the records, but it seems unlikely that people would click on those. When I look up generic terms like "fabric" or "fracture" I'm actually seeing specific options that I would hope people would choose or at least would make them more aware that there are multiple kinds of fractures (bones, rocks, etc.). 

All that to say, I'm not seeing anything very easy to deal with, so I don't think we can add any context for these. Seems like this is taken care of by your other work.
