### ISSUE TITLE
Add H2 tag to all items and collections migrated to H2

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1740]
Be sure to retain any Hydrus tags as well.

**Comment by jcoyne** [comment]
Amy will be able to add these tags via bulk tagging in Argo.

We can get a list of all druids from H2, since they were either migrated and need the tag or were created in H2 and will already have the tag.

**Comment by amyehodge** [comment]
I'm now ready for these two lists:
- druids for all the collections now in H2
- druids for all the items now in H2

**Comment by amyehodge** [comment]
Bulk tagging process used to update all items in these two lists that didn't already have the H2 tag with the H2 tag.
