### ISSUE TITLE
When versioning an item, only display release options when the item has an embargo date that has not yet passed.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1741]
See previous ticket #1352

I have tested this again and it is still not working. Behavior is slightly different this time. Changes are in bold below.

Yesterday I created https://sul-h2-stage.stanford.edu/works/18075
 and set it for embargo release today.

- Today I checked that embargo was lifted. H2 had a history entry saying it was released, but **the PURL still has the embargo message and will not allow me to download the file.**
- I then attempted to version the item. I opened it, added a version comment, added two files, and added in new keywords (removing the one old one).
- When I clicked deposit it behaved it first triggered an **error notification that the embargo date was invalid**. This should not happen for an item released from embargo. 
- Once I changed the embargo date and clicked "submit for review", it reloaded the page with the version comments gone and no error messages. My changes had also been wiped out.

This also triggered the HB alert pasted in below.

Error detected in: happy-heron (stage)

Full report at https://app.honeybadger.io/projects/77112/faults/80069649

NoMethodError: undefined method `[]=' for nil:NilClass

Summary

works#update

URL: https://sul-h2-stage.stanford.edu/works/18075

Hostname: sul-h2-stage.stanford.edu

Context

user_scope: user
user_id: 12
user_email: amyhodge@stanford.edu
Trace

app/services/new_version_parameter_filter.rb:19:in `block in filter_attached_files`
app/services/new_version_parameter_filter.rb:17:in `filter_attached_files`
app/services/new_version_parameter_filter.rb:7:in `call`

**Comment by jcoyne** [comment]
@amyehodge I'm not seeing "the PURL still has the embargo message and will not allow me to download the file."  looks good to me: https://sul-purl-stage.stanford.edu/ct114nf3383 In any case, the embargo release mechanism isn't part of h2, it's a function of dor-services-app and isn't something we've changed.

**Comment by amyehodge** [comment]
@jcoyne I see that I'm able now to download the file, but I'm sure I couldn't that morning. Perhaps it happens later in the day than I expect?

Regarding the second point about the date validation issue, the user should be able to version the item, and should not have to make further changes around the embargo options in the UI to do so. I think it could be confusing if the settings showed "immediately" when that is not what they had entered originally. It makes more sense to me for it to show the embargo date still in this area, but understand that it has already been released and for it not to trigger the validation error. I'm not sure how that could be done.

**Comment by jcoyne** [comment]
We have a validation that says "embargo dates must be in the future", so I'm not sure how we balance that requirement with the requirement that we don't validate in this case.   Also consider the case where they want to make a new embargo.  We'd want to ensure that new embargo isn't in the past.

**Comment by amyehodge** [comment]
I'm wondering if it makes sense to allow users to make changes to the release once it has happened? That is to say, if a user has chosen "immediately" or it is past the embargo date, the only thing they could do is to attempt to set a new embargo date in the future. However, if the content has already been released, then is there a point to that, and can the system actually do that? @astridu, what do you think about that from the user perspective? @hannahfrost are there any use cases you can think of where a self-deposit content that has already been released should get embargoed -- at least where the user should be able to do that themselves?

Sounds like if we stick with keeping these options available, we'll have to show the user "immediately" as the selected option in the UI once the embargo date has passed to keep it from triggering the "embargo date must be in the future" validation warning.

**Comment by amyehodge** [comment]
@jcoyne @astridu @hannahfrost 

I talked with Hannah about this briefly on Tuesday and here's what I'm thinking that might simplify this. HF and I discussed that being able to re-embargo something is not a use case that we need to support. Because of this, I would suggest that once an item has been released (either immediately or at the end of an embargo), we do not show the release options again, we just tell them when the item was released.

Scenarios
1. User chooses "immediate" for the release and deposits the work. If the user attempts to version the work later, we don't need to allow them to embargo it, so this item should forever after just display in this section the date it was released instead of showing options.
2. User chooses an embargo date. If the user attempts to version the item after the item has been released from its embargo, again, we don't need to allow them to re-embargo, so we should just be showing them the date the item was released from embargo without any options.
3. User chooses an embargo date. If the user attempts to version the item BEFORE it has been released from its embargo, this is the only time we should show the release options, since the user may want to change the embargo date or just set it for immediate release.

All of this should pass validations just fine, I think, and make more sense in general.

**Comment by astridu** [comment]
@amyehodge 
Screenshot for 1 & 2 (does this work?)
![image](https://user-images.githubusercontent.com/42216982/125872182-ddd1c78f-4bbf-4dde-950f-3e5d76b51fab.png)

Screenshot for 3
![image](https://user-images.githubusercontent.com/42216982/125872203-2d57b08f-28cb-450a-8408-87761fbed9dd.png)

**Comment by amyehodge** [comment]
@astridu These don't match with the new mockups you did for this section at https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/453759485_DOI section IIIa.

**Comment by astridu** [comment]
Sorry, I grabbed that screenshot off stage. Will update w/the latest mockup.

**Comment by astridu** [comment]
I deleted the wrong mockups and pasting the correct ones here. 
![image](https://user-images.githubusercontent.com/42216982/125984072-cf1f1945-aab7-4f0f-90dd-bed3a844e9f5.png)

**Comment by amyehodge** [comment]
Also, this will likely need the same yes/no toggle treatment that was just implemented over at #1815.

**Comment by amyehodge** [comment]
@jcoyne I think this one is ready for the Ready column. Could you have a look? Thanks.

**Comment by jcoyne** [comment]
It is to be considered "released" if the previous published version was "immediate" or it's embargo date has passed.

**Comment by amyehodge** [comment]
Here's the summary for this ticket:

Once an item has been "released" -- either the previously published version was "immediate" or its embargo date has passed -- the user should see only the release date displayed in the "Release date" section and not any selection options. 

If the item was deposited but has not yet reached its embargo release date, the user should still see the current options displayed and be able to change them. 

The text options for the first two scenarios are:
1. for items that were published as "immediate" -- "This item was released immediately upon deposit."
2. for items that were published with an embargo and that embargo date has passed -- "This item has been released from embargo."
