### ISSUE TITLE
Restore search box on collection deposits page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1742]
I'm pretty sure there used to be a search box on the right side above the table on the collection deposits page. Here's what I see at https://sul-h2-stage.stanford.edu/collections/1084/works:
![Screen Shot 2021-06-30 at 4.04.53 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/3659896f-cdec-494e-b1cc-bfb1f17ea8ba)

**Comment by jcoyne** [comment]
@amyehodge  I don't believe that was ever in the design, so we removed it.  I don't think it should be a problem to re-add it, but I also don't think it's a bug.

**Comment by amyehodge** [comment]
It wasn't in the design, but I thought super helpful. I'll take off the bug label.
