### ISSUE TITLE
User reports items showing multiple times in list temporarily

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1743]
Two instances reported by Kris Kasianovitz. 
First one:
Item: https://new-sdr.stanford.edu/works/114
Happened June 30 at around 4:40 or 4:45 pm.

She said, "When I submitted a document for approval, it showed up like this on my dashboard -- they all disappeared once I approved it. I can't recall anything out of the ordinary - I had saved the draft a few times before approving and publishing. But basically once I clicked the approve/publish then went back to my dashboard all those showed up. I did update the roles for that collection before depositing (this is a brand new deposit). I don't think that would have any bearing  but who knows."

![image.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/df78ffeb-76fb-4fdd-9dc1-cf325d88fb21)

Second instance:
Item: https://new-sdr.stanford.edu/works/105
"OH it just happened again! I just edited this deposit then sent it for approval."
![image2.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/e9c921d7-8c60-40f8-9a91-d87b615464d3)

**Comment by jcoyne** [comment]
@amyehodge can you ask Kris what browser and version as well as any plugins she is running?  Have you been able to duplicate this problem on a different computer?

**Comment by amyehodge** [comment]
@jcoyne From Kris: 

Using Google Chrome
Version 91.0.4472.114 (Official Build) (x86_64)
Using Standard Security Protection Standard protection against websites, downloads, and extensions that are known to be dangerous.

![image.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/a2275cae-da78-4727-af3a-c2263f23c930)

**Comment by amyehodge** [comment]
@jcoyne Also, I have been unable to replicate this, but watched it happen for her a couple of times back when she originally reported it.

**Comment by jcoyne** [comment]
I wonder if this is actually a back end problem for how we identify the list of items that need to be approved.

**Comment by jcoyne** [comment]
yeah that looks like the problem:
```
WorkVersion.where(work_id: 114)
.joins(:work)
.left_outer_joins(work: { collection: :reviewed_by })
.left_outer_joins(work: { collection: :ma
naged_by })
.where('reviewers.user_id = %s OR managers.user_id = %s', 5, 5)
.count
   (1.3ms)  SELECT COUNT(*) FROM "work_versions" INNER JOIN "works" ON "works"."id" = "work_versions"."work_id" LEFT OUTER JOIN "collections" ON "collections"."id" = "works"."collection_id" LEFT OUTER JOIN "reviewers" ON "reviewers"."collection_id" = "collections"."id" LEFT OUTER JOIN "users" ON "users"."id" = "reviewers"."user_id" LEFT OUTER JOIN "managers" ON "managers"."collection_id" = "collections"."id" LEFT OUTER JOIN "users" "managed_bies_collections" ON "managed_bies_collections"."id" = "managers"."user_id" WHERE "work_versions"."work_id" = $1 AND (reviewers.user_id = 5 OR managers.user_id = 5)  [["work_id", 114]]
 => 7
```
