### ISSUE TITLE
Add Public Domain Mark to H2 license options

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#1747]
There is at least one staff-deposited collection (government documents) that uses the Public Domain Mark. This option cannot be selected in H2 or Hydrus, but I've learned that it is assigned within Argo via special APO settings. 
(see the APO here: https://argo.stanford.edu/view/druid:yf511vz3216 )

Since H2 does not use special APOs for each collection, this has made the government documents workflow more complex as new H2-deposited objects are not associated with a special APO. 

If this license could be selected in H2, then it would not need to be assigned in Argo and would simplify things considerably. I believe PDM is the only license option available in Argo that is not available in H2. Adding this option would mean we could have parity in the license menus once we add the H2 options to Argo.

**Comment by jcoyne** [comment]
@amyehodge says we should put this next to "No License" and change the containing element to "Other"?

This only needs to be added in the list of valid and selectable licenses and it should work.
