### ISSUE TITLE
Accessibility: alt tags needed for interactive font awesome icons

### ISSUE THREAD

**Issue by astridu** [sul-dlss/happy-heron#1749]
Sample of recommended tag:
<a aria-label="Delete" class="btn btn-danger" href="path/to/settings">
  <i aria-hidden="true" class="fas fa-trash" title="Delete this item?"></i>
</a>

Titles:
Pencil: Edit item
Trash can: Delete item
Info icon: Help text

**Comment by jcoyne** [comment]
@astridu those icons have aria-label tags.  As they aren't images (they are span tags), it's not valid to give them alt tags.

**Comment by astridu** [comment]
Ok, I will close this ticket. Thanks!
