### ISSUE TITLE
Accessibility: Form elements need to be grouped and labeled

### ISSUE THREAD

**Issue by astridu** [sul-dlss/happy-heron#1751]
When a form contains elements that are logically connected to each other it is necessary to group them.

The form contains check boxes and/or radio buttons that are not grouped and named, using a 'fieldset' with a descriptive 'legend' or the WAI-ARIA attribute role="group" (for check boxes) or role="radiogroup" (for radio buttons) with a descriptive 'aria-labelledby' or 'aria-label'.

On the deposit page, these form elements need to be grouped:
- date fields
- work subtype checkbox items

**Comment by jcoyne** [comment]
@astridu if we use a legend, what should the text be (for each) and where/how do you want it to look on the page.  If we use a `aria-label`, what should the text for each be?

**Comment by astridu** [comment]
Seems like the legend would be easier? For the date fields, could we label it "Year month day" and for the work subtype checkboxes, could we label the group "Work subtypes". TY!

**Comment by jcoyne** [comment]
@astridu can you add it to the mockups?  Also what style should the fieldset have. By default browsers put a solid border around fieldsets. I believe Bootstrap makes the line hidden. So, what is the visual design for this change going to look like?

**Comment by astridu** [comment]
I thought this was something done in the code. I didn't want any changes to the visual design. Is this possible? TY!

**Comment by jcoyne** [comment]
It is in the code, but it's presentation code.  See https://www.sitepoint.com/fieldset-html-element/ for what this looks like.

**Comment by astridu** [comment]
If we can use the hidden line, that would be ideal. I want to keep the layout as is. Thank you!

**Comment by jcoyne** [comment]
what about the legend, do you want that to show?

**Comment by astridu** [comment]
no

**Comment by jcoyne** [comment]
Hmm, this might be a challenge, because we're adding a layout element, but trying to get it not to show up or to anyway influence the layout we've already done.

**Comment by amyehodge** [comment]
@jcoyne Can we put this in the ready?

**Comment by jcoyne** [comment]
I think we should split this out into individual tickets for the individual fields. I'm still not clear on what elements of the date fields we are talking about putting into field sets.

**Comment by astridu** [comment]
Will split this into 2 tickets.
