### ISSUE TITLE
Change keyword endpoint to use the OCLC "full term" index

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#1755]
e.g. the index that populates this page: https://fast.oclc.org/searchfast/?&limit=keywords&facet=all&query=Teacher&sort=usage+desc&start=0. not the typeahead endpoint we were using.

**Comment by justinlittman** [comment]
QA uses the SRW interface:
> OCLCFAST_DIRECT accesses http://experimental.worldcat.org/fast/search?query={subauth}+all+%22{query}%22&sortKeys=usage&maximumRecords={maxRecords}

We could do the same:
```
curl 'http://experimental.worldcat.org/fast/search?query=cql.any+%3D+%22tea%22&maximumRecords=10&sortKeys=usage&recordSchema=info%3Asrw%2Fschema%2F1%2Frdf-v2.0' -H 'Accept: application/xml'
```

However, this returns _a lot_ of XML.

As an alternative, QA using the OCLC FAST authority, e.g., https://lookup.ld4l.org/authorities/search/linked_data/oclc_fast?q=tea&maximumRecords=10

The sorting is problematic, however:
> QA sorts by alpha because the results are read into QA as a graph which loses ordering because graphs are unordered. 

We could, however, resort the returned results as: left anchored match then alpha, rest alpha. For example:
1. Boston Tea Party (Boston, Massachusetts : 1773)
2. Cooking (Tea)
3. East India Company
4. Japanese tea ceremony
5. Japanese tea ceremony--Utensils
6. Tea
7. Tea making paraphernalia
8. Tea trade
9. Tea--Therapeutic use
10. Tearooms

would be resorted as:
1. Tea
2. Tea making paraphernalia
3. Tea trade
4. Tea--Therapeutic use
5. Tearooms
6. Boston Tea Party (Boston, Massachusetts : 1773)
7. Cooking (Tea)
8. East India Company
9. Japanese tea ceremony
10. Japanese tea ceremony--Utensils

**Comment by jcoyne** [comment]
@amyehodge what do you think of the approaches that @justinlittman  has laid out?

**Comment by amyehodge** [comment]
@jcoyne @justinlittman That last sorted list looks really good to me.

**Comment by justinlittman** [comment]
I'll implement and then you can review more thoroughly @amyehodge.
