### ISSUE TITLE
Prevent submitting a draft with an incomplete range.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1763]
If I try to save an item with only a start date for the creation date field, it doesn't pass validation. The error message is displayed next to the form field, so we can remove the one that displays at the top of the page:

![Screen Shot 2021-07-08 at 10.44.52 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/2bc59634-014e-4a7c-9395-57c18c3c2d5d)

**Comment by amyehodge** [comment]
@jcoyne I don't understand your point above. It seemed that the validation of the creation date was working fine for me. Is it something else?

**Comment by jcoyne** [comment]
The point was more to the devs.  We don't want to remove this message so much as preventing you from getting into a situation where you would see it.  There should be a front end validation that should intercept before you get to this error.

**Comment by jcoyne** [comment]
On possible solution here is to persist an unbounded range in the draft and then validate that the range is bounded when we do final validation. The current EDTF library we use does not support unbounded range.

**Comment by jcoyne** [comment]
Another possibility is a custom bit of JS that prevents submitting a draft if range is selected and the range is not complete.
