### ISSUE TITLE
History should only list the sections that have changes made

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1764]
This is getting better (see #1695), but still isn't quite right.

I versioned https://sul-h2-stage.stanford.edu/works/17964 and only touched the "what's changing" field. After depositing again, the history shows that I changed several other fields as well:

![Screen Shot 2021-07-08 at 10.58.44 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/f539f628-d986-4c03-b622-04f197c329d2)

**Comment by amyehodge** [comment]
Here's another example: https://sul-h2-stage.stanford.edu/works/18064

Most of this is correct, but I did not change the file description

![Screen Shot 2021-07-08 at 11.04.55 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/54a7e212-cd0e-4ce7-813c-79f0acbbfa09)

**Comment by jcoyne** [comment]
@amyehodge can we change the title of this ticket to "File description shows as changed when it isn't changed"?

**Comment by amyehodge** [comment]
@jcoyne In the first example, none of the things listed were modified -- contact email, authors, keywords, or file description

**Comment by jcoyne** [comment]
@amyehodge this is a new version, so is this a duplicate of https://github.com/sul-dlss/happy-heron/issues/1694?

**Comment by amyehodge** [comment]
@jcoyne The second example does look like a duplicate of what was reported for #1694, but the first one was a version as well, and the behavior is different, since some untouched fields were logged, but not all of them.

**Comment by jcoyne** [comment]
#1695 was only for an update to an existing draft. #1694 was for the first update on a new version.  So, I don't think the test you set up met the scope of #1694.

**Comment by amyehodge** [comment]
Got it. I'll test that again. Thanks.

**Comment by amyehodge** [comment]
@jcoyne I retested and still see an issue. I think I'll close this messy ticket and create a new one.
