### ISSUE TITLE
Do not record changes in the history when there aren't any for an update of an initial version

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1768]
I updated an existing draft of https://sul-h2-stage.stanford.edu/works/17806 but made no actual changes and just clicked on "save" and changes were recorded in the history when none should have been.

![Screen Shot 2021-07-08 at 2.29.55 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/ba14a483-596a-4334-827f-b9d89b38a601)

**Comment by jcoyne** [comment]
@amyehodge Can you tell us how to reproduce this?

**Comment by amyehodge** [comment]
I'm now unable to reproduce this. I think other updates to the history info have likely fixed this. Closing.
