### ISSUE TITLE
Accessibility: Tabbing on deposit page

### ISSUE THREAD

**Issue by astridu** [sul-dlss/happy-heron#1798]
For radio buttons on the deposit page, I'm unable to select the radio button that is not selected by tabbing. When I tab from the radio button that is selected, it goes to the next question rather than going to the next radio button option. For users who only use keyboard, they won't be able to select the unselected radio button.

**Comment by jcoyne** [comment]
When you use radio buttons via keyboard, you tab to the first one and then use arrow keys to select which option.  Tab again moves to the next control.

**Comment by astridu** [comment]
Got it. That worked. thanks!
