### ISSUE TITLE
Accessibility: Name fields are not descriptive

### ISSUE THREAD

**Issue by astridu** [sul-dlss/happy-heron#1800]
I used the screen reader to make sure I could still navigate the site by screen reader only, and it worked pretty well. One thing I noticed was that for any field that had first name and last name, it said "Candidate for" instead of the label. Not sure if I have something specific on my Chrome browser that is doing that, but the label appears to be ok, and all the other fields work. Do you have any idea what the issue may be? Thanks!

**Comment by jcoyne** [comment]
I've never seen this. We don't have any code that says "Candidate for".  No idea what this is.
