### ISSUE TITLE
Update text and add yes/no to toggle for auto-generated work citation on work deposit page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1815]
On the work deposit page in this section:

![Screen Shot 2021-07-15 at 11.21.21 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/8c2988d3-abe2-4f2a-8fa7-c59d7c590d18)

1. Update the label next to the toggle from "Use default citation" to "Use auto-generated citation".
2. Add yes/no labels to the toggle bar to match the design we have for the DOI selection:

![image.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/b13a3748-0998-4e7c-887a-25ad4c48b2b9)

**Comment by justinlittman** [comment]
@amyehodge I can't find an existing component that looks like the Yes / No toggle. As I see it, the following are the options:
1. Use the existing Bootstrap switch, but choose less confusing colors. (Related: Not sure that the existing red/grey would be usable be someone red/green color blind.)
2. Switch to a checkbox.

I don't think writing our own Yes / No toggle is a viable option.

cc @jcoyne

**Comment by amyehodge** [comment]
@astridu @jcoyne @justinlittman Can we put yes/not text above or next to the toggle to make it clearer, instead of on top of it?

**Comment by justinlittman** [comment]
Using approach described here: https://stackoverflow.com/questions/39846282/how-to-add-the-text-on-and-off-to-toggle-button/39846603#39846603

**Comment by astridu** [comment]
Can we do this?

![image](https://user-images.githubusercontent.com/42216982/125994264-c4f0f467-4bde-42b7-a3d4-6fb7ab77e340.png)
![image](https://user-images.githubusercontent.com/42216982/125994416-59be786a-fe2d-4344-a395-0b48ced4972e.png)

**Comment by justinlittman** [comment]
Here's what I implemented:

![image](https://user-images.githubusercontent.com/588335/125995236-31844002-95b4-48ff-a4cd-fec690233c8a.png)

![image](https://user-images.githubusercontent.com/588335/125995323-2d7ed483-ecb2-4c23-bcd9-cb7026602ec4.png)

**Comment by amyehodge** [comment]
@justinlittman This is definitely clearer IMO

**Comment by astridu** [comment]
Beautiful! Can you make the 'Yes' 'No' text slightly bigger? It looks a little smaller than the body text.

**Comment by justinlittman** [comment]
Hah, I already did @astridu (after I took the screenshots).
