### ISSUE TITLE
For Deposits in Progress section of Dashboard, remove progress bar and replace current content with a table

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1826]
@astridu will be putting together a mockup for this.

**Comment by amyehodge** [comment]
@astridu Here's what needs to be in this table, listed in order from left to right, for the mockups:

Deposit [title of the deposit]
Pencil icons and trash cans when appropriate
Collection [title of the collection]
Deposit status [Draft- not deposited, New version in draft, or PURL Reserved]
Last modified

Thanks.

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/126020033-d4321055-60e6-469b-b185-81be6badb097.png)

**Comment by amyehodge** [comment]
This looks good. We need to also link the collection and item titles in both of these tables.

**Comment by jcoyne** [comment]
Do we want to keep the delete button on these rows too?

**Comment by amyehodge** [comment]
@jcoyne yes, please. whatever functionality is there we want to keep, we just want to put it in the table. Hopefully we didn't miss anything else.
