### ISSUE TITLE
Accessibility: date fields need to be grouped and labeled

### ISSUE THREAD

**Issue by astridu** [sul-dlss/happy-heron#1827]
When a form contains elements that are logically connected to each other it is necessary to group them.

The form contains check boxes and/or radio buttons that are not grouped and named, using a 'fieldset' with a descriptive 'legend' or the WAI-ARIA attribute role="group" (for check boxes) or role="radiogroup" (for radio buttons) with a descriptive 'aria-labelledby' or 'aria-label'.

On the deposit page, these radio button form elements need to be grouped:
Creation date
![image](https://user-images.githubusercontent.com/42216982/125996995-0c7f8491-ec6f-43e3-bc5b-761176bf85de.png)

Release date
![image](https://user-images.githubusercontent.com/42216982/125997034-ea408264-cae7-4309-83ab-6fd363ed5f12.png)

**Comment by jcoyne** [comment]
@astridu can you list the legend that we want for each of those?

**Comment by jcoyne** [comment]
> the WAI-ARIA attribute role="group" (for check boxes) or role="radiogroup" (for radio buttons) with a descriptive 'aria-labelledby' or 'aria-label'

this wouldn't apply here since these aren't checkboxes or radio buttons?

**Comment by astridu** [comment]
Sorry, I misunderstood what it was trying to tell me. So it's probably asking to group the radio buttons, not the date fields. Will update the mockup above.

**Comment by astridu** [comment]
@jcoyne By legend, do you mean a label to describe the group? The first one could be 'Creation date' and the second one could be 'Release date'.

**Comment by jcoyne** [comment]
Yeah, that makes a lot more sense now, with the updated groupings.
