### ISSUE TITLE
Accessibility: work types need to be grouped and labeled

### ISSUE THREAD

**Issue by astridu** [sul-dlss/happy-heron#1828]
When a form contains elements that are logically connected to each other it is necessary to group them.

The form contains check boxes and/or radio buttons that are not grouped and named, using a 'fieldset' with a descriptive 'legend' or the WAI-ARIA attribute role="group" (for check boxes) or role="radiogroup" (for radio buttons) with a descriptive 'aria-labelledby' or 'aria-label'.

On the deposit page, these work types form elements need to be grouped:
![image](https://user-images.githubusercontent.com/42216982/125997332-bb61c320-cec6-4b11-ae65-d21ad32da464.png)

**Comment by jcoyne** [comment]
@astridu why do we want these to be two separate fieldsets?  They are all subtype options, aren't they?

**Comment by astridu** [comment]
I see your point. Yes, they should probably be included in one group. Thx!
