### ISSUE TITLE
On item view page, list the pre-assigned collection-level keywords in a separate list

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1835]
The keywords assigned at the collection level should be displayed on the item view page in a separate row above the user-assigned keywords.

These should be displayed one per line (#1836 is the ticket for getting the user-assigned keywords on separate lines)

![keywordsOnePerLine.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/77f8d862-91a9-4b8a-b13d-d0745e9c4f40)

Originally part of #1738.

**Comment by ndushay** [comment]
from midsprint planning:   

Things that could affect an item's collection supplied keywords?
- when a collection's keywords change
- when an item is moved to a different collection
- when an item is saved after the collection's keywords change

**Comment by amyehodge** [comment]
@jcoyne Here's the summary from my discussion with @hannahfrost this morning on how we want this to work.

1. Regarding the discussion about the metadata and the point that there is no way to distinguish in the MODS between the depositer-entered keywords and those set by the collection manager, this is fine. If once it ends up in the MODS it is indistinguishable, that's not a problem.
2. When an item is deposited, it should be assigned the keywords listed for the collection at that time.
3. We will not update the collection keywords on items when we create new versions of items. They will stay what they were when the item was first deposited. (i.e. the third option on the third bullet point above).
4. Assigning or changing keywords at the collection level will not result in any changes to any items. 
5. As users can't at this time move items to different collections, we don't need to worry about support for that at this time.

Please let me know if there are still questions here, or if we can move this set of tickets to the Ready column. Thanks.

**Comment by jcoyne** [comment]
@amyehodge it sounds to me like we now have a good understanding of how to move forward. Push it to ready!

**Comment by amyehodge** [comment]
This is no longer a priority, so I'm closing this ticket.
