### ISSUE TITLE
Display user-assigned keywords on the item view page on separate rows

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1836]
Right now these are separated with commas, but they will be much easier to read for the user if they are on separate rows.

![keywordsOnePerLine.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/8ab46c01-205a-4028-a16e-640af9461008)

**Comment by jcoyne** [comment]
Is this a duplicate of #1512?

**Comment by amyehodge** [comment]
Oh, sorry. I forgot #1512 was modified to this. Closing.
