### ISSUE TITLE
On dashboard for Reserved PURLs, add trash can icon next to pencil icon. 

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1837]
This should do the same thing that the trash can icon does for the Reserved PURL, which is that it gets rid of the object entirely (I'm not sure what's happening to it on the back end).

@jcoyne Please let me know if you have any questions about this. I want to get this in the Ready if possible.

**Comment by ndushay** [comment]
@amyehodge can you include a screen shot showing where you want the trash can added?

**Comment by amyehodge** [comment]
@ndushay It should be just to the right of the pencil icon. Same place as shown for the regular item in progress in this screenshot.
![Screen Shot 2021-08-04 at 2 43 06 PM](https://user-images.githubusercontent.com/5558511/128237019-39b2c2d2-fdda-4541-a1bc-b74dca4e0e3b.png)
