### ISSUE TITLE
Add ORCID information to descriptive metadata

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1843]
ORCID IDs added to H2 should be stored in descMD.

@arcadiafalcone can you confirm the location where these should be stored? Thanks.

**Comment by arcadiafalcone** [comment]
https://github.com/sul-dlss/dor-services-app/blob/9ac97a4830684223e27c34d1dcfd84b26fcec27a/spec/services/cocina/mapping/descriptive/h2_datacite/contributor_h2_datacite_spec.rb#L1601 and https://github.com/sul-dlss/dor-services-app/blob/9ac97a4830684223e27c34d1dcfd84b26fcec27a/spec/services/cocina/mapping/descriptive/h2_datacite/contributor_h2_datacite_spec.rb#L1700 show the H2-cocina-DataCite mappings. I'll add ORCID to the H2-cocina-MODS mappings as well.

**Comment by arcadiafalcone** [comment]
PR for the MODS mapping: https://github.com/sul-dlss/dor-services-app/pull/2946

**Comment by ndushay** [comment]
this may be partially done?  Also needs another pass from @arcadiafalcone re: roundtripping concerns (?)

**Comment by jcoyne** [comment]
@ndushay no, this ticket primarily about exporting this data from h2.
