### ISSUE TITLE
Import Hydrus Collections

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#185]
So that users can deposit into collections that they have access to in Hydrus.

**Comment by jcoyne** [comment]
@amyehodge @andrewjbtw can we close this ticket?

**Comment by amyehodge** [comment]
Fine with me. We will, of course, still need to migrate the rest of the content, but we don't need to figure out how to do it.

**Comment by jcoyne** [comment]
Sorry, that message was supposed to be on another ticket.... something odd happened with zenhub.
