### ISSUE TITLE
Update "What is a DOI?" links

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1865]
All of these links should point to https://library.stanford.edu/research/stanford-digital-repository/documentation/purls-and-dois

There are several of these. Please search https://docs.google.com/document/d/16zGrIpRgGkq8d4VDUjEstoB2p8xFEuiAmKJopcT1CaQ/edit# for "What is a DOI?" to find them all. 

They are in three place:
1. Collection edit form, including both the initial creation form with everything and the separate settings form
2. Deposit edit form
3. PURL reservation modal

**Comment by ndushay** [comment]
main DOI branch doesn't seem to have these links implemented yet.   Maybe the updated link can be noted in a diff ticket for implementation???
