### ISSUE TITLE
Determine type of subject terms from FAST and include in cocina

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/happy-heron#1874]
(cc @amyehodge )

Each FAST subject term falls into one of these categories:
* Personal Names (cocina type: person)
* Corporate Names (cocina type: organization)
* Event (cocina type: event)
* Uniform Titles (cocina type: title)
* Chronological (cocina type: time)
* Topical (cocina type: topic)
* Geographic (cocina type: place)
* FormGenre (cocina type: genre)
* Meeting (cocina type: conference)

It is important to know the category a given term belongs to because terms of different categories are treated in different ways in systems such as SearchWorks (such as the facet a subject term goes into, and what heading it displays under in the record). Currently all subject terms are being typed as "topic", which means that terms such as places, names, and titles will not be handled correctly.

H2 should determine the type of the subject in FAST and include the corresponding cocina subject.type according to the mapping above.

MODS mappings are already in place for the different subject types. Data created prior to resolving this issue will need to be reviewed and remediated.

**Comment by jcoyne** [comment]
I'm wondering if this is a hard requirement for this to be in h2. Is it possible to put this resolver in the SearchWorks indexer or in the accessioning workflow? When doing this data enrichment, we may encounter problems connecting to remote service.  It's important we design this in a way to have the least likelihood of impacting the depositor.

**Comment by arcadiafalcone** [comment]
It's important that the subject type gets inserted into the metadata as soon as possible in the object lifecycle, ideally at the point of data creation, definitely before or at indexing (which may happen in multiple places, e.g., both SearchWorks and Spotlight). If it's more effective to do that in another codebase, that's fine, so long as this requirement is met.

**Comment by jcoyne** [comment]
@arcadiafalcone can you explain why that is important?
