### ISSUE TITLE
Add list of authors and contributors to the deposit form

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#188]
https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/428088403

![Screen Shot 2020-10-20 at 11.30.10 AM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/9cd0cf3d-9ab2-4600-9bcf-72c33be12980)

- [ ] Contributors are persisted to the contributors database table.
- [ ] DescriptionGenerator should be updated to send contributors in Cocina to SDR API. (See [cocina mappings](https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_name.txt#L168-L199).)

**Comment by mjgiarlo** [comment]
@jcoyne ready? backlog? milestone?

**Comment by jcoyne** [comment]
I don't know.  does it matter?

**Comment by mjgiarlo** [comment]
Does whether this is ready or backlog matter? I think so. Milestone, less so.
