### ISSUE TITLE
When there is space, file download icons should be on the same line as the file name

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1888]
See https://sdr.stanford.edu/works/1618

There appears to be plenty of space, but some of these have the file download on the next line. 

![Screen Shot 2021-08-04 at 1.47.58 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/839463a9-0c95-460b-8ed6-331ed9c02441)

**Comment by amyehodge** [comment]
Reported by @hannahfrost

**Comment by amyehodge** [comment]
@astridu, @jcoyne thinks this is the result of the 25% we set the first column for. Do you have any suggestions on how to adjust this so that this layout. In this case it looks odder because there are no file descriptions (and there aren't most of the time), but when there are, this may seem less strange. Not sure if there is a good solution to this.

**Comment by astridu** [comment]
@jcoyne @amyehodge If file descriptions are rare, could we increase the width of the first column and make the description column narrower?

**Comment by jcoyne** [comment]
Sure, but are there other tables we need to increase the width on too so we have alignment?  What should we increase it to?

**Comment by astridu** [comment]
We can't just change this table? or are you saying other tables may have this wrapping problem?

**Comment by jcoyne** [comment]
@astridu I'm asking about how this issue will relate to this issue https://github.com/sul-dlss/happy-heron/issues/1336

**Comment by astridu** [comment]
@jcoyne Ok, I see now. 
@amyehodge Would you be ok with making the width of this column larger for this table? It would result in this table's columns not aligning with the others below it, but it would help the problem you are seeing which is the wrapping.

**Comment by amyehodge** [comment]
@astridu @jcoyne Yes, I think that's fine.

**Comment by amyehodge** [comment]
@jcoyne Can we put this ticket in the ready? I think all questions have been answered.
