### ISSUE TITLE
Creation date for collection should match with the information in Argo

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1889]
For the Stanford Research Data collection, https://sdr.stanford.edu/collection_versions/168, it says the creation date is July 5, 2011, but the Argo record says Dec 13, 2021: https://argo.stanford.edu/view/druid:md919gh6774

I also want to make sure this isn't a global problem with more collections than just this one.

**Comment by amyehodge** [comment]
Reported by @hannahfrost

**Comment by andrewjbtw** [comment]
For posterity (since the issue is closed): I think this is more of an Argo issue with how the registration date has been determined over the years. It has been using workflow data rather than the Fedora data.
