### ISSUE TITLE
Content that has already been released should pass validation when versioning

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1891]
Example item: https://sdr.stanford.edu/works/746/edit

Attempt to version produced these errors:
![Screen Shot 2021-08-04 at 3.49.51 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/213d8c8f-95a6-409a-8927-a43c49ea7c41)

Release section looks like this:
![Screen Shot 2021-08-04 at 2.55.38 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/c5a83c6d-bed0-4584-957b-c12fe96bf8b1)

**Comment by jcoyne** [comment]
I've duplicated the problem in qa, it occurs when you try to edit an existing item that had been deposited with release set to immediate.
