### ISSUE TITLE
Select a work type

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#190]
When depositing, a modal should pop-up that selects the work type. (only do the top half of this form)

![Screen Shot 2020-10-20 at 11.48.35 AM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/c76983a7-090e-41bc-aff4-de619e7d7074)

See list of work types in `app/models/work_type.rb`

https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/431445056

- [ ] Work type is persisted in `work_type` column of `works` table.

**Comment by mjgiarlo** [comment]
@jcoyne ready? backlog? milestone?

**Comment by jcoyne** [comment]
I don't know, up for discussion.

**Comment by mjgiarlo** [comment]
@jcoyne ok, cool. how should we queue this up for discussion? add to running notes?
