### ISSUE TITLE
DOI links should all be https, not http

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1900]

**Comment by jcoyne** [comment]
@amyehodge can you provide success criteria for this issue?   Is there something that needs to change at present?

**Comment by amyehodge** [comment]
Actually, I believe the mock-ups specify this, so I'm just making sure this is implemented, in light of other recent conversations regarding https. I'll move this to the backlog.

**Comment by amyehodge** [comment]
These are all displaying as https, so I'm closing this ticket.
