### ISSUE TITLE
Generate list of collection managers for imported collections

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1912]
We need a list that has in the first column the titles of all the collections imported in H2 (we don't need collections created in H2) and in the second column the SUNet IDs of all the collection managers for each collection.

We need this so we can notify these people about the need to update the license settings for the collection before any items can be created or versioned.

@hannahfrost

**Comment by jcoyne** [comment]
I was able to create this report by running `jq -r '[.name, (.managers | join(", "))] | @csv' collections.jsonl > collections.csv`

And I put it in https://docs.google.com/spreadsheets/d/19Tm0yixkZWxj7WWcXxAn1z8p_whAZujpiuh_xkPXWa8/edit#gid=1487871984

**Comment by amyehodge** [comment]
Perfect. Thank you.
