### ISSUE TITLE
Include a way for user to get rid of SUNet search box

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1925]
I typed in "hfrost" to the SUNet ID lookup for managers and it found here, but I decided I didn't want to enter her and there was no way for me to get rid of the results display. Even when I deleted what I had typed, the results persisted.
![Screen Shot 2021-08-10 at 4.59.47 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/f944b453-486c-4f78-94a9-90afb691527f)

**Comment by jcoyne** [comment]
@amyehodge @astridu  What is the desired behavior in this case?

**Comment by amyehodge** [comment]
@jcoyne @astridu I'd say that it would be nice next to the "Add" button to have a button for "Don't Add" (but that text is not good) that makes that results box go away and clears the field. Or perhaps when the text in the box is completely cleared by the user that that search results box goes away?

**Comment by astridu** [comment]
I think we had a couple of use cases:

![image](https://user-images.githubusercontent.com/42216982/128963456-21d1e1b7-f59a-4063-af3a-497fcf24fe07.png)

**Comment by amyehodge** [comment]
@astridu Those mockups are for the ORCID lookup. This is a SUNet ID lookup for adding new collection participants.

**Comment by amyehodge** [comment]
@jcoyne, @astridu has updated the mockups above.
