### ISSUE TITLE
H2 deposits with Stanford-only rights are not getting the correct rights assigned

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#1933]
Items deposited with H2 where visibility is set to "Stanford community" should get object-level rights of "stanford". Currently, they are getting both

- object-level "stanford" rights
- file-level "world" rights

These file-level rights effectively override the object-level rights, resulting in objects that are actually world-viewable because the files are world-viewable.

Example on stage: https://argo-stage.stanford.edu/view/druid:vr108gr0567

**Comment by jcoyne** [comment]
The bug is here: https://github.com/sul-dlss/happy-heron/blob/main/app/services/cocina_generator/structural/file_generator.rb#L77-L83  It should use `work_version.access` if it is not a hidden file (rather than `world`)
