### ISSUE TITLE
User is unable to delete a reserved PURL

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1951]
Kristin Kutella is the manager of the Stanford Center for East Asian Studies Thesis Collection (https://sdr.stanford.edu/collections/23). A student reserved a PURL when they shouldn't have and she would like to delete it.

(Note: ticket 1837 adds trash can icons for these to the dashboard but is not in production yet.)

She has clicked the pencil icon and selected "Text" as the work type in order to get into the edit form. When she clicks on the "discard draft" button at the bottom of the page she sees the warning message about not being able to undo this action. She clicks "OK" (or whatever it says there) and then is dumped back onto the welcome page at sdr.stanford.edu with this error:
"You are not authorized to perform the requested action."
![Screen Shot 2021-08-13 at 12.29.43 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/b365c92f-7081-4bd8-8644-94ce0c89909a)

Note that I was able to delete this reserved PURL using the same procedure without any trouble.

**Comment by amyehodge** [comment]
@amyehodge Note to self to let Kristin know when we've fixed this.

**Comment by peetucket** [comment]
This is a collection manager trying to delete someone else's reserved PURL.

**Comment by peetucket** [comment]
I have a suspicion that the work already done in #1910 and in review in #1947 will fix this.

**Comment by peetucket** [comment]
I'm wondering if we need to add collection managers in addition to depositors and administrators to this check here:  https://github.com/sul-dlss/happy-heron/blob/main/app/policies/work_policy.rb#L14-L16

**Comment by amyehodge** [comment]
@peetucket Reviewers should also be able to do this. That may be another distinct set of user permissions?

**Comment by amyehodge** [comment]
Here are some samples of reserved PURLs that can't be deleted:

Item: https://sdr.stanford.edu/works/4658
Collection: https://sdr.stanford.edu/collections/67
User: akrogman

Item: need to check
Collection: https://sdr.stanford.edu/collections/23
User: kkutella

**Comment by jcoyne** [comment]
<img width="1158" alt="Screen Shot 2021-08-18 at 3 37 21 PM" src="https://user-images.githubusercontent.com/92044/129968920-2593a04f-5d38-478f-a58d-4449d5edb1a7.png">
It looks like you can delete it from the collection page.

**Comment by peetucket** [comment]
I looked at the first item ("Test PURL for Amy") and it passes all of the policy/permissions checks that should allow it to be deleted:

```
w=Work.find(4658);
w.head.deleteable?
 => true
w.persisted?
 => true
w.collection.managed_by.include?(User.find_by(email:"akrogman@stanford.edu"))
 => true
```

The collection page that lists the deposits shows the trash can for me.  I don't see it on my dashboard as a collection or deposit in progress because it's not mine, so I can't confirm that part.

![Screen Shot 2021-08-18 at 2.18.27 PM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/8532c905-b893-4a75-8353-e71185b0ac19)

**Comment by amyehodge** [comment]
@peetucket  Ali sees the trash can icons as well as the discard draft button, but when she tries the discard draft button, she it taken to the home page with the error message about not having permissions.

**Comment by peetucket** [comment]
ahh, ok.  Does it work for you? (as the depositor).  You are also an administrator (as am I probably), so maybe there is a distinction there that still needs some thought

**Comment by amyehodge** [comment]
It always works for me. I have been able to delete both my own items and ones in collections that I can only access because I'm an admin (i.e. I don't have depositor/reviewer/manager status).

**Comment by peetucket** [comment]
Ok, that's good to know.  I have more code change that may make a difference that I can work on.

**Comment by amyehodge** [comment]
Both the original reporter of this issue, Kristin, and my other tester Ali report that both the discard draft button and the trash can icons now successfully delete reserved PURLs. I am closing this ticket!
