### ISSUE TITLE
Collection managers and reviewers should be able to edit items submitted for review

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1960]
I feel pretty certain that we designed H2 so that collection managers could do this. See #656

From the collection manager, Kristin:
"In the old system, I was able to make small edits for the students prior to approving the submissions.  In the new system, it seems that I can only reject the submission and ask the students to make updates and then resubmit.  This may become problematic because the university has a firm dissertation/thesis deadline and many students submit very close to the deadline.  In these cases, I would review the theses as they arrived, but many I'd review after the technical deadline because I have a large queue.  In these cases, I would simply make a small edit to satisfy the requirements (changing advisor to primary advisor, or adding an ADA-compliant file name, for example) and then submit.  In this case, if I notice that there is a small issue, I'll need to return the item to the student, explain to them what they need to fix, and then wait for them to resubmit in order to review again.  In these cases, I'm concerned that the return and resubmit process would extend beyond the official deadline for the thesis.  We'd be entering into a gray area when it comes to university requirements and I'd like to avoid that if at all possible.  In addition, not being able to make small edits when I see the need simply adds more work to my plate and I'd also like to avoid that if possible."

**Comment by jcoyne** [comment]
Technical background: This was initially fixed in #962 I'm not sure why that isn't working now.

**Comment by jcoyne** [comment]
Hannah, who is an application administrator, also has the same problem.

**Comment by jcoyne** [comment]
@amyehodge does this mean the admin/manager/review just doesn't see the links to the edit page?

**Comment by justinlittman** [comment]
Some steps to replicate would be helpful.

**Comment by amyehodge** [comment]
Kristin reported:
"I think this is my mistake.  Previously, there was an edit button near the top of the page (if I remember correctly), so I didn't expect to see the pencil icons scattered throughout the page.  Now I see that it's possible to edit individual sections and I just tested it out on one of our student's submissions, so I think it works.  Please disregard my request."

Hannah's issue was that the collection did not have an updated license assigned. 

No work to be done on the dev side here. Closing ticket.
