### ISSUE TITLE
Problem depositing items under some conditions.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1970]
I'm having problems depositing some items. When this happens, the page reloads without any of my changes and there are no error messages on the page.

Steps to recreate this issue:
1. Clicked on “Deposit to this collection”
2. selected Text > technical report
3. Add a single 11b file via drag and drop. did not add a description
4. Typed in a short title
5. Typed in one email address
6. Selected ORCID option and pasted in my ORCID. My name then is displayed. I didn’t change it. Left this set at default of Author.
7. Chose “thesis advisor” from the menu for the first contributor and then typed in Hannah Frost.
8. typed in a short abstract
9. Typed “keyword” in the keyword field and selected “Keyword searching” from FAST
10. no further changes -- I’ve already agreed to the terms.
11. clicked Deposit.

If I do these steps exactly except that I type in my name instead of using the ORCID, it deposits fine without any issues.

**Comment by jcoyne** [comment]
It looks to me like this occurs when you enter an orcid that does not begin with `https://orcid.org`
