### ISSUE TITLE
Ignore PendingConnectionsError

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#1977]
https://github.com/rubycdp/ferrum

We can set `pending_connection_errors` to false

**Comment by justinlittman** [comment]
Can you say more about this? How does it manifest? How to reproduce?

**Comment by jcoyne** [comment]
It's an intermittent failure in feature specs, see https://app.circleci.com/pipelines/github/sul-dlss/happy-heron/3573/workflows/4b3cd7ee-01ea-48f0-bf36-dfba8bf57a9a/jobs/14355/tests#failed-test-0 for an example.
