### ISSUE TITLE
Refine spacing of ORCID UI

### ISSUE THREAD

**Issue by astridu** [sul-dlss/happy-heron#1988]
Current
![image](https://user-images.githubusercontent.com/42216982/130171031-1124f75e-0f0e-4e49-af6f-55c35acf1045.png)

Proposed design
![image](https://user-images.githubusercontent.com/42216982/130170988-155a028f-3744-49b1-92f5-e2392a171a0b.png)

**Comment by justinlittman** [comment]
Can you please provide a specification/description of the spacing? It is hard to determine the appropriate changes just by looking at the two mockups.

**Comment by astridu** [comment]
Does this work? 
![image](https://user-images.githubusercontent.com/42216982/130262426-e66e33ac-b3f9-4a15-a6d5-7d37d5d3eb44.png)

**Comment by justinlittman** [comment]
Yup, that helps.
