### ISSUE TITLE
Collection with the review workflow on is not sending items for approval.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2031]
See https://sdr.stanford.edu/collections/58

A depositor submitted https://sdr.stanford.edu/works/4691 and the manager got the notice it was deposited and went in to approve it and did not see the approvals options. Makes sense since this appears to have skipped the review workflow entirely and went straight to deposit. It should have shown up as pending approval and the manager should have seen the approvals options.

**Comment by amyehodge** [comment]
Just to clarify that while we don't want the depositor to be able to edit the work after they submit it for review (unless it's sent back to them for changes), we DO want the reviewers and collection managers to be able to edit it in this state.

**Comment by amyehodge** [comment]
We haven't seen this again, so closing this ticket.

**Comment by hannahfrost** [comment]
No, @amyehodge, I have not seen this again.
