### ISSUE TITLE
Change theme colors to align with Stanford brand identity changes

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/happy-heron#204]
The color changes are in the [design doc](https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit). 

See comments below for all the colors that have changed, and for the names of the new colors.

Ping @astridu if you have any questions.

**Comment by mjgiarlo** [comment]
@astridu I looked over the design doc and tried to whip up a list of changes. Did I get this right?

```
Link text: 00548F -> 006CB8
FontAwesome link: 0054F -> 006CB8
Dropdown text: 3A3A3A -> ??????
Error red: B1020F -> B1040E
Disabled button color: CBCBCB -> C0C0BF
Disabled button text: 575757 -> black
Toggle border: 979797 -> C0C0BF
Table header bgcolor: DFD4B4 -> C0C0BF
Table border color: DFD4B4 -> C0C0BF
Tab (unselected) heading 3: 4D4F53 -> black
Tab gray line: 4D4F53 -> C0C0BF
Pop up border: B3995D -> C0C0BF
Tooltip border: 01548F -> 006CB8
Progress bar (blue): 01548F -> 006CB8
Progress bar text on white bg: 979797 -> black
Progress bar border: C0C0BF
SDR header background: 4D4F53 -> 53565A
Modal background: F8F6EF -> EAEAEA
Modal border: 979797 -> C0C0BF
Versioning box background: F3E7E7 -> EAEAEA
Versioning tooltip icon: 01548F -> 006CB8
Embargo radio button icon: 01548F -> 006CB8
License background: DBD7CB -> C0C0BF
```

**Comment by astridu** [comment]
Yes, that's right. I just made all the text black instead of fussing with shades of gray. Thank you!!

**Comment by mejackreed** [comment]
Not sure if this is helpful or not but wanted to link some of the base work that we use to style our apps. I realize this may not fully align but hopefully could be a starting point.
https://github.com/sul-dlss/sul_styles/blob/style-components/app/assets/stylesheets/sul_variables.scss

And how we usually integrate (though w/ Bootstrap 4): https://github.com/sul-dlss/earthworks/blob/master/app/assets/stylesheets/bootstrap-variables.scss

**Comment by mjgiarlo** [comment]
# Names for new colors

* 006CB8: digital blue
* B1040E: digital red
* C0C0BF: 30% black
* 53565A: cool grey
* EAEAEA: 10% black
```

**Comment by mjgiarlo** [comment]
@astridu what black should we use for text? should we use the one specified in the primary color guide? that's #2E2D29

**Comment by astridu** [comment]
To keep things simple, let's just use good ole 000000. I can't tell the difference between those 2 blacks anyways.
