### ISSUE TITLE
12 GB object not finishing accessioning

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2056]
Alert from Honeybadger is below.
@jcoyne indicated the object experiencing issues is https://sdr.stanford.edu/works/3907. 

Error detected in: happy-heron (prod)

Full report at https://app.honeybadger.io/projects/77112/faults/81170002

RuntimeError: unexpected response: #<Faraday::Response:0x0000000008d8f0d8 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:put @request_body=#<File:/data/h2-files/kf/17/kf17t56yte1f6ep3oxp0ezy3xppw> @url=#<URI::HTTPS https://sdr-api-prod.stanford.edu/v1/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDam9JYTJWNVNTSWhZemQ2YjJGbk1HTjJOMlZrZW1kaWNESXphV3d4WlRKck1HMDJaQVk2QmtWVU9oRmpiMjUwWlc1MFgzUjVjR1ZKSWhSaGNIQnNhV05oZEdsdmJpOTZhWEFHT3daVU9oTmpiMjUwWlc1MFgyeGxibWQwYUdrRUV6VVhNam9OWTJobFkydHpkVzFKSWgwdmJXaEVSemRYT0daWE4zaGpNbXgxU21jMWMwNTNQVDBHT3daVU9oRnpaWEoyYVdObFgyNWhiV1U2Q214dlkyRnMiLCJleHAiOiIyMDIxLTA5LTE3VDEzOjU2OjUxLjM5OVoiLCJwdXIiOiJibG9iX3Rva2VuIn19--5df44070c303bec6c4165558a19c41b93101eb17> @request=#<Faraday::RequestOptions read_timeout=180> @request_headers={"Authorization"=>"Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2MzE5NzMxMTB9.ky1Lr2Iponp3xInwcdxO-7NC_cCtgoyRZOVwd901ho4", "User-Agent"=>"Faraday v1.7.1", "Content-Type"=>"application/zip", "Content-Length"=>"840381715"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x0000000008d8f0d8 ...> @response_headers={"date"=>"Fri, 17 Sep 2021 13:57:07 GMT", "server"=>"Apache/2.4.6 (CentOS)", "cache-control"=>"no-cache", "referrer-policy"=>"strict-origin-when-cross-origin", "x-permitted-cross-domain-policies"=>"none", "x-xss-protection"=>"1; mode=block", "x-request-id"=>"01924014-12f7-4bd4-ab18-54efb3abdea2", "x-download-options"=>"noopen", "x-runtime"=>"0.002336", "x-frame-options"=>"SAMEORIGIN", "x-content-type-options"=>"nosniff", "x-powered-by"=>"Phusion Passenger 6.0.4", "strict-transport-security"=>"max-age=31536000; includeSubDomains", "status"=>"404 Not Found", "transfer-encoding"=>"chunked", "content-type"=>"text/html"} @status=404 @reason_phrase="Not Found" @response_body="">>

Summary

DepositJob#perform

Hostname: sul-h2-prod.stanford.edu

Trace

app/jobs/deposit_job.rb:52:in `upload_responses`
app/jobs/deposit_job.rb:15:in `perform`

**Comment by jcoyne** [comment]
Seeing this in the prod log of SDR-API, but this doesn't give us much to go on:
```
I, [2021-09-17T10:56:30.204550 #20398]  INFO -- : [2126ef39-b204-430a-9283-0c8980b670dd] method=PUT path=/v1/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDam9JYTJWNVNTSWhlV1JuWVdFd2FYSm1kRzU0WVdaMmQzcG1OM0JwTjJzMmNtWjBjZ1k2QmtWVU9oRmpiMjUwWlc1MFgzUjVjR1ZKSWhSaGNIQnNhV05oZEdsdmJpOTZhWEFHT3daVU9oTmpiMjUwWlc1MFgyeGxibWQwYUdrRUV6VVhNam9OWTJobFkydHpkVzFKSWgwdmJXaEVSemRYT0daWE4zaGpNbXgxU21jMWMwNTNQVDBHT3daVU9oRnpaWEoyYVdObFgyNWhiV1U2Q214dlkyRnMiLCJleHAiOiIyMDIxLTA5LTE3VDE3OjU2OjAzLjIxN1oiLCJwdXIiOiJibG9iX3Rva2VuIn19--89890d1188cb6949db86224d901c6be9c568e408 format=*/* controller=ActiveStorage::DiskController action=update status=404 duration=0.49 view=0.00 db=0.00
```

**Comment by jcoyne** [comment]
This is a challenge to debug since it runs for a long time before failing:
<img width="1182" alt="Screen Shot 2021-09-17 at 2 17 51 PM" src="https://user-images.githubusercontent.com/92044/133842238-e744bb49-33c0-444e-bb68-974b55299d1c.png">

**Comment by jcoyne** [comment]
@amyehodge can this be closed?

**Comment by amyehodge** [comment]
Yes, this has completed accessioning.
