### ISSUE TITLE
Collection descriptions are not being sent to SDR from H2.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2058]
Both mz061vb5322 and mz061vb5322 have collection descriptions in H2, but that information is not in 1) the descMD, 2) Cocino, or 3) on PURL (which makes sense, because it's not in the MODS).

**Comment by mjgiarlo** [comment]
@amyehodge Hmmm, AFAICT based on [this code](https://github.com/sul-dlss/happy-heron/blob/main/app/services/cocina_generator/description/collection_description_generator.rb#L17-L20), H2 does not support sending collection descriptions along in the Cocina representation. I've only done a superficial check, though. Can you find any collections that do have descriptions in Argo? 

cc: @vivnwong @andrewjbtw @jcoyne

**Comment by andrewjbtw** [comment]
It's possible this has been a problem since the H2 launch that was never caught in testing. Hydrus-originated collections do have collection descriptions and descriptions should be sent from H2 too.

**Comment by andrewjbtw** [comment]
It also looks like the descriptions are getting removed from Fedora when updated from H2. This collection started in Hydrus: https://argo.stanford.edu/view/druid:md903dt5665

It had a short description until it was updated in December, as you can see in the datastream version history
Updated in June 2021 (pre-migration): 
https://sul-dor-prod.stanford.edu/fedora/objects/druid:md903dt5665/datastreams/descMetadata/content?asOfDateTime=2021-06-03T15:23:39.078Z

Update in September 2021 (post-migration):
https://sul-dor-prod.stanford.edu/fedora/objects/druid:md903dt5665/datastreams/descMetadata/content?asOfDateTime=2021-09-08T20:58:55.931Z
