### ISSUE TITLE
Updating items in H2 should not add month or year to dates that were only a year previously

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2066]
The user previously entered only a year for an item in Hydrus. After migration, the item was versioned in H2 and even though the date was not touched, January 1 was added to the creation date and is visible on the PURL and in the metadata. H2 continues to display just the year. The month and year should not be being added to these dates. 

This is definitely happening for creation dates of items that were originally created in Hydrus, but we should really check to be sure that it doesn't have broader implications, like for H2 originated items or for the publication date.

__________________________
Reported initially by @hannahfrost :
Comment:
This was deposited via H2 and the creation date was entered in the H2 form as "2021". On PURL however, it is displaying as "2021-01-01". It would appear somewhere in the H2/Cocina/PURL flow, the date value format is affected in a way that is altering the intended value.

__________________________

Further investigated by @andrewjbtw:
In Fedora, this item had a date created of 2021 up until the most recent update, when it became 2021-01-01.
 
As of 2021-06-07:
 
<dateCreated keyDate="yes" encoding="w3cdtf">2021</dateCreated>
 
As of 2021-08-10:
 
<dateCreated encoding="edtf">2021-01-01</dateCreated>
 
The change came in when the item was updated via H2. The migration from Hydrus didn’t touch the Fedora data already in SDR. It was just a migration of data into H2 so that H2 could manage the items in the future.
 
I just updated the date on a test item in stage where I entered only “2020” on the form for date created and it is being represented as 2020-01-01. So I think H2 is filling in the month and day. Test item: https://sul-purl-stage.stanford.edu/ms771vw9339
 
Andrew

**Comment by amyehodge** [comment]
Once this is fixed, we should identify all items updated in H2 for dates with Jan. 1 and remediate those that did not have the month/day in the date previously.

**Comment by jermnelson** [comment]
I think I figured out the problem. When a four digit year is parsed as an EDTF date, it assumes January 1st:

```ruby
date_string = EDTF.parse('2021')
Fri, 01 Jan 2021
```

**Comment by peetucket** [comment]
As Jeremy noted, we are parsing the date entered by the user when generating cocina.  The date entered by user is stored as a string in the database: https://github.com/sul-dlss/happy-heron/blob/main/db/structure.sql#L582 and can be viewed that way via the console before it is parsed:

```
w=Work.find_by(druid:'druid:ms771vw9339')
w.work_versions.last[:created_edtf] # direct value from the database before parsing
 => "2020"   
w.work_versions.last.created_edtf # value after parsing by the model
=> Wed, 01 Jan 2020 
```

The parsing in the model is here: https://github.com/sul-dlss/happy-heron/blob/main/app/models/work_version.rb#L156-L162 and the values get put into cocina here: https://github.com/sul-dlss/happy-heron/blob/main/app/services/cocina_generator/description/generator.rb#L90-L96

So the question is: (1) should the parsing be conditional in some way (i.e. if it's just a year, don't parse?).  There is also the ability for the user to mark a date as approximate and (2) where is the EDTF parsing library located?

**Comment by peetucket** [comment]
EDTF gem in the Gemfile: https://github.com/sul-dlss/happy-heron/blob/main/Gemfile#L56

**Comment by peetucket** [comment]
Ok, change in idea after my experiments described above didn't pan out.  I basically altered the parsing only when generating cocina, which I believe is all we need to do to affect display on PURL without affecting other H2 functionality.  See #2085
