### ISSUE TITLE
Embargoed items that will be released to the world have file-level rights that override the embargo

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#2072]
**Description of the problem**

When a self-deposit item is embargoed with settings that will release it to the world, the rights to the object should be citation-only and the files should not be available during the embargo period. Currently, the object rights are being set correctly to citation-only but the files are being given world rights, which means that they could be accessed prior to the end of the embargo.

Example druid: https://argo-stage.stanford.edu/view/druid:px464rn8992

The one file in this object has been given file-level world rights:
```xml
  <access type="read">
    <file>placeholder.txt</file>
    <machine>
      <world/>
    </machine>
  </access>
```

This means that the file could be downloaded directly from its Stacks URL
https://stacks-stage.stanford.edu/file/druid:px464rn8992/placeholder.txt

Fortunately, the Purl display does not expose the Stacks URL in this situation because it is set up to display the embargo information, so it makes it a little less likely that people have been able to access files that have been exposed.
<img width="583" alt="Screen Shot 2021-10-08 at 1 07 25 PM" src="https://user-images.githubusercontent.com/8975583/136619208-86443b28-cc43-48e5-b256-120cc2021043.png">

**Expected behavior**

Embargoed objects should be citation only with files made inaccessible for the duration of the embargo.

**Comment by peetucket** [comment]
This looks like the spot in the H2 code that is generating the cocina file level rights: https://github.com/sul-dlss/happy-heron/blob/main/app/services/cocina_generator/access_generator.rb#L34 and https://github.com/sul-dlss/happy-heron/blob/main/app/services/cocina_generator/access_generator.rb#L31-L37

I think we need to check to see at the object level if there is an embargo (like we do here: https://github.com/sul-dlss/happy-heron/blob/main/app/services/cocina_generator/access_generator.rb#L15 and https://github.com/sul-dlss/happy-heron/blob/main/app/services/cocina_generator/access_generator.rb#L31-L37) and then set the file level rights to none if so.  

What is not immediately clear to me is how the embargo release process works ... is it smart enough to correctly set the file level rights once the embargo period is over?

**Comment by peetucket** [comment]
See #2069 - similar problem
