### ISSUE TITLE
File uploads of 5-10 GB hit 502 errors

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#2119]
We received reports of upload problems from a couple of users during the winter closure. Two of the files with problems, from separate deposits had sizes of around 5 GB and 8 GB. In Hydrus, we were able to support uploads of single files up to around 10 GB so we should try to support the same size range in H2.

**Description of the problem**

I've been trying to upload a file today that Hannah tried to upload last week, and that the depositor has also tried to upload. What I've seen is the following sequence:

- I start the upload
- The progress bar starts showing green
- Eventually, the bar either turns entirely green or gets very close to that point - this took long enough that I wasn't watching at the moment when it failed
- The progress bar turns red and I get this message: `Unable to upload file due to: Error storing "DNAPolymerase.zip". Status: 502. Delete the file and try again.`
<img width="842" alt="Screen Shot 2022-01-03 at 12 16 35 PM" src="https://user-images.githubusercontent.com/8975583/147984385-f7d1b23b-1cd4-445d-8bd8-2cbb5b24747d.png">
- The whole process took about an hour, which is roughly the time it would take to upload 5 GB at my current upload bandwidth

**Additional information**

I believe we determined that timeout settings are part of the problem with large file uploads. I'm currently on a connection with 100 Mbps download/10 Mbps upload. I don't think that's unusually slow for home internet these days, though it's nowhere near fiber speeds for upload, and likely slower than Stanford campus wifi as well. At that speed, it would take a little over 1 hour to upload 5 GB and at least 2 hours to upload 10 GB.

I wonder if we could set our timeout based on a calculation of what bandwidth we could expect to support for a 10 GB file? I'm not sure what we're basing the setting on at the moment. The tradeoff would be that a longer timeout might mask other issues, but we do seem to have motivated users willing to wait 1-2 hours or more for an upload to complete.

**Comment by jcoyne** [comment]
The tradeoff of a long timeout is that users can use up all the connections (if they are malicious by doing very slow uploads) so that there are no connections available for other users of the system.  Our current timeout is set to 10 minutes: https://github.com/sul-dlss/puppet/blob/production/hieradata/node/sul-h2-prod.stanford.edu.eyaml#L251

**Comment by amyehodge** [comment]
We don't actually know how often we might encounter such a problem if we have a long timeout. But we *do* know that we regularly have timeout problems now.

Let's say we set it for an hour and someone is using up all the connection. Then another user wants to upload something. What kind of interaction will the second user have? Will they get a similar upload error to what people see now with the timeout? Or will it error immediately (as opposed to at the end of trying to upload)? Can we identify this error and create a custom message that recommends people come back later when it's less busy to do a file upload?

**Comment by jcoyne** [comment]
If all the connections are used, they won't even be able to load the website. It will just sit and spin.

**Comment by andrewjbtw** [comment]
Could we limit the number of simultaneous uploads for a given item? So a user could work on multiple submissions but within each submission they could only upload one or two files at the same time? I'm not sure what limits we have on connections overall.

**Comment by mjgiarlo** [comment]
@andrewjbtw @amyehodge @jcoyne @aaron-collier Is this fixed yet or is it still hanging around?

**Comment by amyehodge** [comment]
It looks fixed to me. Deposit completed in H2 and everything is accessible as it should be from the PURL.
