### ISSUE TITLE
Release option for item should allow options dictated by collection release setting.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2121]
Release option on the item is not displaying the option selected on the collection. 
The collection is js114xn4901/83.
The item is yp355vz4656/4349.

This deposit is set to release on Jan. 14, 2022. The author requested an extension. The collection was originally set for 6 months max embargo, with the depositor choosing release timing. I updated the collection setting earlier today to allow for one year, and then planned to update the item. 

However, when I went to look at the item in H2, it said the item was released immediately. Argo and PURL indicate the embargo is still active as it should be. Initially after talking to Andrew, we thought the embargo date was not migrated properly from Hydrus. However, I'm now wondering if this is a problem with the application not reflecting the proper release setting for the item since when I open the item to edit it, I still says it will be released immediately and will not give me the option to choose.

**Comment by andrewjbtw** [comment]
A few additional details:

In Hydrus, the item ~shows~ showed the embargo release setting for January 14, 2022 - which is what can be seen in Argo https://argo.stanford.edu/view/yp355vz4656. 

In H2, the item says it was released immediately upon deposit, even though the item still has not been released.
<img width="395" alt="Screen Shot 2022-01-11 at 2 38 27 PM" src="https://user-images.githubusercontent.com/8975583/149032640-2956f651-34d2-437d-829f-080341729d78.png">

The item was registered in Hydrus in May 2021 and then published in mid-July 2021, not long before the launch of H2 and possibly after the soft launch of H2. I still do wonder if the embargo metadata was never migrated to H2. If not, I wonder if that could still be done and if that would then allow us to extend the embargo within H2 itself.

**Comment by amyehodge** [comment]
Embargo has been updated to July 14, 2022 via Argo, but the above issues still need to be investigated.

**Comment by jcoyne** [comment]
I concur with Andrew. In the data export the item "yp355vz4656" did not have a `embargo_release_date` property, but other items did.

**Comment by jcoyne** [comment]
We determined this was a bad migration due to Fedora having stored the embargo date in two places.  Some of the records (with cc 4.0 licenses) were corrected to only have one location, but the export from Hydrus used the old location. We remediated with:
```ruby
data =[
%w[druid:ct913hh2270 2023-11-28T00:00:00+00:00],
%w[druid:gf072tq5537 2022-05-05T00:00:00+00:00],
%w[druid:gz610dt4642 2022-02-01T00:00:00+00:00],
%w[druid:jg418vz8621 2024-01-01T00:00:00+00:00],
%w[druid:kd878gf5841 2022-06-02T00:00:00+00:00],
%w[druid:kq632vn7933 2024-11-05T00:00:00+00:00],
%w[druid:kv313yy7422 2024-05-13T00:00:00+00:00],
%w[druid:mx814rh9820 2022-03-22T00:00:00+00:00],
%w[druid:rk392dj6710 2022-06-03T00:00:00+00:00],
%w[druid:sr420hn6830 2024-03-02T00:00:00+00:00],
%w[druid:tq095bx1940 2023-01-01T00:00:00+00:00],
%w[druid:xq853fr8935 2022-03-16T00:00:00+00:00],
%w[druid:xw875vf5293 2022-06-29T00:00:00+00:00],
%w[druid:xy954tt5426 2022-06-03T00:00:00+00:00],
%w[druid:yp355vz4656 2022-07-14T00:00:00+00:00]
]

data.map do |row|
  work = Work.find_by(druid: row.first)
  work.head.update(embargo_date: DateTime.parse(row.last))
end
```

**Comment by jcoyne** [comment]
@amyehodge Is this closeable now?

**Comment by amyehodge** [comment]
@jcoyne @andrewjbtw I just checked all of these. All the embargo dates are reflected accurately in H2. However, for two of them, the release information is wrong. They indicate release only to Stanford but should say world. gf072tq5537 is one of these, but it’s a test object of mine, so I’m not concerned about it. However, jg418vz8621 is a real object. The release info on this one should be updated to world.
