### ISSUE TITLE
Item with 8.1GB file upload should complete deposit faster than 3 days

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2128]
Item druid:mc421yx0335 / work 4931 has been "depositing" a new version in the H2 app since Jan. 7. This item has an 8.1GB file that was uploaded after our recent changes to allow for larger uploads. This is one of the users that reported this issue to us that we've been trying to help.

This item was created in December, after which the item was modified in Argo to allow for streaming of the originally-deposited video file.

The user has now uploaded the 8.1GB file (in addition to the 1.5GB file from the initial deposit) and the app indicates it is still "depositing." Argo does not yet seem to have any knowledge of the new version that I can tell.

Is this large file really still "depositing" or did it get hung up in the system somewhere?

**Comment by jcoyne** [comment]
work 4931 has a workVersion 5277, which corresponds to https://app.honeybadger.io/projects/77112/faults/81085562

**Comment by jcoyne** [comment]
@amyehodge can this be closed?
