### ISSUE TITLE
do not insert month/day data when the creation date is approximate and contains only year or year + month

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#2139]
**Description of the bug**

When a user enters a creation date for a deposit and marks the date as "Approximate", H2 is adding an "01" if the month or the month+day was not entered on the form.

Example:
https://sdr.stanford.edu/works/4939 (H2 entry)
https://argo.stanford.edu/view/nw987sj3048 (as deposited)

The date range for this item has been entered as an approximate year to another approximate year. But when writing to Cocina, an "01-01" for month and day was added to each date in the range.

**Expected behavior**

Users are given the option to enter a creation date for their deposits in the following forms:

- year
- year, month
- year, month, day

They can also:

- enter a date range, where the start and end dates each follow the same format as for a single date
- check a box labeled "Approximate" for any or all dates entered
<img width="976" alt="Screen Shot 2022-01-18 at 3 05 54 PM" src="https://user-images.githubusercontent.com/8975583/150033317-065f8bbe-2c18-4b15-9bf9-4822b8b9c501.png">

If the date entered does not include a month or day, no month or day should be added. If the creation date is "2020" it should not be transformed into "2020-01-01". Similarly, "ca. 2020" should not be transformed into "ca. 2020-01-01"

**Additional information**

An earlier PR fixed this issue for non-approximate dates but may not have fixed the approximate date case: https://github.com/sul-dlss/happy-heron/pull/2085

I've tested all of these creation date possibilities and how they get represented in Cocina after deposit:

For one creation date (i.e. not a range):

- year only: correct Cocina
- year-month: correct Cocina
- approx year: 01-01 is added
- approx year-month: 01 is added

For date ranges:

- year-to-year range: correct Cocina
- year-month to year-month range: correct Cocina
- approx year-to-year range: 01-01 is added to the approx date
- approx year-month-to-year-month range: 01 is added to the approx date

So I think it's really only the approx dates that have this issue now.

**Comment by peetucket** [comment]
Thanks for the detailed sleuthing and link to the previous work Andrew (I thought this sounded familiar).  I think the fix is pretty simple (see #2140), but would be good to validate in stage once approved.

**Comment by peetucket** [comment]
@andrewjbtw my fix was merged and I deployed it to -stage and -qa if you want to validate

**Comment by andrewjbtw** [comment]
@peetucket I checked on stage and it all looks good to me. Thanks!
