### ISSUE TITLE
SDR logo at the top of all pages at sdr.stanford.edu should be updated.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2151]
Tom pointed out that somehow we did not get the approved logo on the H2 site. 

The correct logo file is here: https://drive.google.com/file/d/1KrqNa5MkocaDqipeBTj4XwBWMAlWX6gr/view

See the Design Doc for the header that is on every page (now updated with this link):
https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.o1072wkbq96t

and for the home page:

https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#

**Comment by ndushay** [comment]
fixed by #2152

![image](https://user-images.githubusercontent.com/96775/152569323-6f8f581e-acb5-42ca-ac2a-61c69ee41fb0.png)

**Comment by ndushay** [comment]
PR was merged;  Amy said deploy could wait until Monday dep updates are deployed.

**Comment by ndushay** [comment]
Now with capital R in Repository on home page!
