### ISSUE TITLE
clean up H2 deposit for work 5192

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/happy-heron#2163]
see https://sdr.stanford.edu/works/5192 and https://argo.stanford.edu/view/wm893ry9991

this got stuck depositing from H2's perspective (though it completed accessioning of v1 according to argo).

@andrewjbtw observes a couple of related HB alerts:
> Both a DOI update error: https://app.honeybadger.io/projects/50568/faults/83331860
> and a Cocina roundtrip error: https://app.honeybadger.io/projects/50568/faults/84122636

the depositor noticed an error and re-deposited the content as work 5193, which succeeded.

it sounds like @andrewjbtw will decommission the SDR object by moving it to the graveyard, and will then delete work 5192 from H2.

**Comment by andrewjbtw** [comment]
This is now complete.
