### ISSUE TITLE
deposits with Stanford rights are instead getting rights set to "world and stanford (file)"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#2167]
I deposited jg195dj5668 via h2-stage and set the rights to "Stanford" in H2. The item was accessioned with object-level rights of "world" and a file-level right of "stanford". It should have been accessioned with object-level rights of "stanford".

H2: https://sul-h2-stage.stanford.edu/works/18656
Argo: https://argo-stage.stanford.edu/view/druid:jg195dj5668

The rightsMetadata XML has been written with a file-level right:

```xml
<access type="discover">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <file>preview.jpg</file>
    <machine>
      <group>stanford</group>
    </machine>
  </access>
```

It should just have object-level rights of "stanford" in the rightsMetadata. Since the file-level right is set correctly, the object is still accessible with the intended settings. However, it's indexed in Argo as if it's a "world" object when it should show up in the facets as a "stanford" object.

**Comment by andrewjbtw** [comment]
Prod example from last week with the same issue: https://argo.stanford.edu/view/druid:yf968qy2211

**Comment by andrewjbtw** [comment]
Based on a broader discussion of possibly related rights issues, I think what may be happening is this:

- H2 creates the appropriate Cocina, including both object and file rights
- the H2 Cocina hands off to the API
- the Hydrus Ur-APO's defaults for the object-level rights are being applied, overriding the H2 object rights, but the file-level rights remain untouched
- this is resulting in combinations like "world and stanford (file)" or "world and dark (file)"

If that's true, a back-end change being made to handle APO default rights (to address a different issue) is likely to also correct this issue.

**Comment by andrewjbtw** [comment]
Having now tested a dor-services-app change in stage that is related rights and APOs, I think that (https://github.com/sul-dlss/dor-services-app/pull/3582) will fix this issue. H2 itself seems to be making the correct Cocina.

**Comment by ndushay** [comment]
@justinlittman - do you think https://github.com/sul-dlss/dor-services-app/pull/3582 fixed this?

**Comment by ndushay** [comment]
@andrewjbtw so this can be closed?

**Comment by andrewjbtw** [comment]
I think so.
