### ISSUE TITLE
possible timezone/UTC conflict with embargo dates

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#2168]
On February 22, at about 5:30 PM PST, I tried to set an embargo release for February 23 but got a message saying the embargo date must be in the future. I suspect the system is using UTC rather than local time on the Pacific coast. It seems like the day for embargo purposes should be localized to Pacific time so that someone working in Stanford's time zone in the late afternoon or evening can set an embargo to be released the next day.

<img width="1300" alt="Screen Shot 2022-02-22 at 5 39 46 PM" src="https://user-images.githubusercontent.com/8975583/155248879-f64ca0de-e89c-455c-8708-1fbf56b4579f.png">

**Comment by amyehodge** [comment]
I concur that this should work the way @andrewjbtw has indicated. Is this making it to FR or is it just in the backlog for now?

**Comment by jcoyne** [comment]
So that we can prioritize this issue with regard to other issues, do you think that this affects anyone besides someone testing the system?  As a work around is it possible to use Argo to modify the embargo date?

**Comment by amyehodge** [comment]
@jcoyne Users do sometimes set very short embargoes, so this could impact a real user. However, the majority of users do not embargo content and the majority of the time those embargoes are set for farther out than the last day. So, I wouldn't consider this high priority.

**Comment by andrewjbtw** [comment]
I agree with Amy about priority. I filed it since I came across it while looking at how H2 is setting rights when there's an embargo, but the possible issues with rights that I'm investigating will be higher priority. 

Argo is setting embargoes according to Stanford's timezone, so we can go in and embargo that way.

**Comment by andrewjbtw** [comment]
Just after we thought this wouldn't be a big problem, a user ran into it last week. It turns out the problem is larger than setting an embargo for the next day. 

The problem is that once an embargo is set, you can't save and update the item after midnight UTC - even if you're not editing the embargo. It looks like the record will not save once the embargo has been set because the validation of the embargo date runs each time the item is saved.

I think it's much more likely that someone will edit a record the night before an embargo is to be released than it is that they'll set an embargo for the first time that night. So I'm adding this to the FR board.

What the user ended up doing was to modify the embargo to be longer so they could save the record, then they came back the next day and attempted to remove the embargo altogether so the item would release. That didn't work and we ended up intervening via Argo to help them.

**Comment by amyehodge** [comment]
@andrewjbtw Thanks so much for sorting through this. I agree that this should be elevated to first responder.
