### ISSUE TITLE
Can't view deposits in "Stanford University Libraries staff publications and research" collection

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#2174]
When viewing the page for the "Stanford University Libraries staff publications and research" collection, it's not possible to view the list of deposits in that collection. Specifically:

- this URL is reachable: https://sdr.stanford.edu/collections/76
- this URL is hits a 500 error: https://sdr.stanford.edu/collections/76/works

It's possible that this problem was the result of a depositor running into an error and then trying to delete the affected item. Based on this [Slack thread](https://stanfordlib.slack.com/archives/C09M7P91R/p1646090153985769), it sounds like the depositor cannot see their own list of deposits, possibly for the same reason I'm unable to load the list of deposits in the collection above.

Three errors were triggered around the same time - #2171 , #2172 , #2173 - and seem to all have been part of the same sequence of trying to edit, delete, or view.

**Comment by jcoyne** [comment]
The problem here is there were two Works that has no WorkVersion:
```
Work.where(head: nil)
[
#<Work:0x0000000003e8b6f8
  id: 4151,
  druid: "druid:wn714rn8040",
  head_id: nil,
  collection_id: 76,
  depositor_id: 23,
  created_at: Fri, 16 Oct 2020 19:36:07.294000000 UTC +00:00,
  updated_at: Mon, 28 Feb 2022 22:45:11.567474000 UTC +00:00,
  assign_doi: false,
  doi: nil>,
#<Work:0x0000000006eac440
 id: 5206,
 druid: nil,
 head_id: nil,
 collection_id: 76,
 depositor_id: 60,
 created_at: Tue, 01 Mar 2022 01:53:16.839514000 UTC +00:00,
 updated_at: Tue, 01 Mar 2022 01:53:16.839514000 UTC +00:00,
 assign_doi: true,
 doi: nil>
]
 ```
 
 Any work with a druid must also have a `head` which is the pointer to the current work version.

There is one work version for the first work:
```
WorkVersion.where(work_id: 4151)
 =>
[#<WorkVersion:0x000000000566cf88
  id: 4155,
  version: 2,
  title: "MSS_MEDIA002_40_1_2: Farewell party for the DeCamps, given by the people of Irish Town at Bermuda Mount",
  work_type: "music",
  created_edtf: "1958-08-27",
  abstract: "Excerpt of Reel 40 Track 1",
  ...
```
  
  So I'm going to set that as the `head`
  
  ```ruby
  Work.find(4151).update(head_id: 4155)
  ```

There was no work_version for the second:
```
WorkVersion.where(work_id: 5206)
=>
[]
```
So I deleted it:
```
Work.find(5206).destroy
```

Now https://sdr.stanford.edu/collections/76 is reachable
