### ISSUE TITLE
Create header and footer styles and apply them to the front page.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#22]

**Comment by mjgiarlo** [comment]
@jcoyne it appears we already have a styled header and footer. what needs to be done for this?

**Comment by jcoyne** [comment]
Maybe @astridu could review and comment.

**Comment by astridu** [comment]
Can I get more context? The header and footer are specified in the design doc.

**Comment by mjgiarlo** [comment]
@astridu No problem! Here's the current site in its nascent form:

![Screenshot from 2020-10-13 09-07-09](https://user-images.githubusercontent.com/131982/95886623-af459c00-0d33-11eb-8fa2-3f45c6ba8eb7.png)

Should we be using the design doc, the UI mockups on Invision, or both as our reference? (If both, when should we reach for one or the other?) Thanks for helping me sort this out; I am sure the developers will ask design-related questions during the upcoming work cycle and this will help @jcoyne and I steer them in the right direction.

**Comment by astridu** [comment]
You can use the UI mockups on Invision to understand what it's supposed to look like, and then you can use the design doc to for detailed functionality, images, content, and what different use cases look like. Thank you!

**Comment by mjgiarlo** [comment]
@astridu thanks!

**Comment by mjgiarlo** [comment]
For now, the look and feel of the header and footer are close enough. Let's create specific new issues in sprint pre-planning meetings as needed, depending on P.O. priorities. Thanks, all.
