### ISSUE TITLE
Include the work number, depositor sunet, and (if available) the druid, in H2 error messages

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#2217]
Error messages like https://app.honeybadger.io/projects/77112/faults/84949137 include a WorkVersion but it's not clear to me if there's a way to get from the work version number to the work number without going through the H2 database. The URLs in H2 seems to be based on work number, though could be missing something there.

If the HB messages include the work number, then anyone with access to error message could go straight to the work URL in H2 and see the current status of the item.

**Comment by andrewjbtw** [comment]
I checked with Amy and in addition to the work number she'd like the depositor sunet in the error messages so that she can more easily tell whether to contact them, if need be.

**Comment by peetucket** [comment]
> I checked with Amy and in addition to the work number she'd like the depositor sunet in the error messages so that she can more easily tell whether to contact them, if need be.

Added the sunet, along with work id and druid (which I believe could be nil for a first version that hasn't yet been deposited).
