### ISSUE TITLE
Work 5200 (druid:zd394zj9776) failed to submit to SDR on v2

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/happy-heron#2229]
This item was versioned in H2 in order to add a PDF file to be published, but looking at the object in Argo, the PDF never made it. 

The object's content type had been changed in Argo (to "book") before the versioning attempt in H2, so perhaps this introduced the issue which prevented the versioning from being successful? 

There is also an error on PURL referring to iiif manifest (residual of the "book" content type changed made in Argo's v3).

The goal is to replace the jpg deposited in v1 with the pdf uploaded in H2's v2, then have the object set to "document" content type and then never touch it again.

**Comment by aaron-collier** [comment]
@hannahfrost I see that the item has a PDF and content_type is "document" in Argo: https://argo.stanford.edu/view/druid:zd394zj9776

However, I do still see the iiif error. Does it look like argo is now correct? Wondering if I just need to try re-publishing or something first. Thanks for any pointers :-)

**Comment by andrewjbtw** [comment]
The issue here is that there is no PDF in SDR for this item. The file in Argo is a JPG and there's no sign that the PDF was ever deposited.

**Comment by aaron-collier** [comment]
@andrewjbtw I see a PDF listed now: https://sdr.stanford.edu/works/520 but not in argo.

**Comment by hannahfrost** [comment]
And I resubmitted from H2, but the deposit is spinning there, and the object has not been opened, looking at Argo.

**Comment by andrewjbtw** [comment]
I see the issue: https://app.honeybadger.io/projects/67994/faults/83912195

We haven't resolved the problem of H2 version numbers differing from actual SDR version numbers. I'm surprised this isn't happening more often, to be honest. I thought H2 would simply increment the SDR version by one.

**Comment by jcoyne** [comment]
I think this is working as designed. We don't want h2 to overwrite changes made in Argo without finding out about them first.

**Comment by andrewjbtw** [comment]
I thought we did want that because that's parity with how Hydrus did things even though it's less than ideal. If this was by design, we should have designed user-facing feedback giving some indication of what happened.

**Comment by hannahfrost** [comment]
So, we will have to fix the object in SDR proper? In this case, I could also just make a new object via H2 and we could kill this bad one.

**Comment by aaron-collier** [comment]
I was able to get the version and PDF aligned in argo: https://argo.stanford.edu/view/druid:yr405yf9710

**Comment by andrewjbtw** [comment]
I just noticed there was a typo in the issue title. This is work 5200 not 520. https://sdr.stanford.edu/works/5200

**Comment by hannahfrost** [comment]
oh, my bad!

**Comment by andrewjbtw** [comment]
Aaron updated work 5200 and I went to Argo to change the content type. With the PDF, the page looks correct now in the document/PDF viewer.

**Comment by hannahfrost** [comment]
Looks good to me. Thanks, @aaron-collier and @andrewjbtw

**Comment by amyehodge** [comment]
> https://sdr.stanford.edu/works/520

I have made a note in my backlog of the need for some alert when this happens.

**Comment by amyehodge** [comment]
> I thought we did want that because that's parity with how Hydrus did things even though it's less than ideal. If this was by design, we should have designed user-facing feedback giving some indication of what happened.

I have made a note in my backlog that we need an alert when this situation arises -- both for users and for admins.
