### ISSUE TITLE
Remediate version comments in SDR from "updated via sdr-api" to comments added in H2 app

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2262]
Related to #2090, which is for sending new comments when they are made to SDR.

This ticket is for remediating all the comments that were made previously and not sent and instead just have the text "updated via sdr-api" in Argo.

![138905090-4403ec90-04be-4fe2-a15c-7002b7ca4642](https://user-images.githubusercontent.com/5558511/171269289-3f42cd53-10a7-4045-be49-85253998d0c4.png)

**Comment by ndushay** [comment]
@jcoyne I'm not 100% clear where Argo gets the version comment from.  Is it correct that 

this ticket is to update  DSA ObjectVersion.description with version descriptions from H2 database when DSA ObjectVersion.description matches "Update via sdr-api"

?

**Comment by jcoyne** [comment]
@ndushay yes, that's correct.

**Comment by ndushay** [comment]
@amyehodge This has been done in stage and in prod.

In prod, 
- there were some h2 version descriptions with quotes in them, such as bb973hw5160, version 3 `"correcting \"affect\" to \"effect\" per user request"`
- 596 version descriptions were updated.

In stage, 203 version descriptions were updated.

Below is the script I used, and I attached the csv files I got from h2-stage and h2-prod


```
# if this needs to happen again, loop on the csv file as it is much smaller the number of object versions in prod (duh)
csv_file = CSV.parse(File.read("tmp/h2-stage-version-desc-sorted.csv"), headers: true)
object_versions_to_update = ObjectVersion.where(description: 'Update via sdr-api').pluck(:id, :description, :druid, :version)
object_versions_to_update.each do |obj_ver_row|
  obj_ver_id = obj_ver_row.first
  druid = obj_ver_row[2]
  version = obj_ver_row.last

  csv_row = csv_file.find { |row| row.fields.first == druid && row.fields[1].to_i == version }

  if csv_row
    object_version = ObjectVersion.find(obj_ver_id)
    object_version.description = csv_row.fields.last
    object_version.save
  end
end
```

**Comment by ndushay** [comment]
[h2-prod-version-desc-sorted.csv](https://github.com/sul-dlss/happy-heron/files/9427866/h2-prod-version-desc-sorted.csv)
[h2-stage-version-desc-sorted.csv](https://github.com/sul-dlss/happy-heron/files/9427867/h2-stage-version-desc-sorted.csv)

**Comment by ndushay** [comment]
https://argo.stanford.edu/view/hd938dh1291

![image](https://user-images.githubusercontent.com/96775/186758080-f0068158-723c-4d58-8bc1-7a22baa3fc78.png)

**Comment by ndushay** [comment]
@amyehodge I'll leave it for you to close this;  I think it's done.

descriptions with backslash (which may or may not have been updated just now):
1. druid:bb973hw5160,3,"correcting \"affect\" to \"effect\" per user request"
2. druid:ng812mz4543,5,"Added new data for follow-up work: \"Neural Collapse Under MSE Loss\""
3. druid:ny927zd1474,2,"Changed \"Lully Archive\" to \"Lully Project\" "
4. druid:ty017zm2813,1,"Removed publication and creation date. Received advisor signature. Added advisors as \"Primary thesis advisor\" author and \"Thesis advisor\" contributor. "
5. druid:xq853fr8935,2,"Used \"Preliminary Report\" throughout the form"
6. druid:xs088yt3392,1,"Added Benjamin L. Byerly as data contributor, Donald R. Lowe as Primary Thesis Advisor, and Gary R. Byerly as Thesis Advisor. Removed \"creation date\""
7. druid:yb936vv8634,3,"author should be \"Guy, Donna J.\"   not sure why system noted it otherwise"
8. druid:yy463gr8945,2,"I've added the original DOI to the \"citation for this deposit\" section"

**Comment by amyehodge** [comment]
@ndushay This looks great. I did a quick spot check of a couple items and I definitely am seeing the version comments now. Love it!

I have questions about two of the items on the list above. The rest on the list above look fine, but these:
#1 -- just says "Version 3" instead of the comment
![Screen Shot 2022-08-25 at 5 50 30 PM](https://user-images.githubusercontent.com/5558511/186775326-281841d6-4d0a-4906-ac4a-c719f8c6f699.png)

#7 somehow didn't get the first bit of text
![Screen Shot 2022-08-25 at 5 55 57 PM](https://user-images.githubusercontent.com/5558511/186776063-f4d39a7e-02cf-466d-9da3-fbbb84566942.png)

**Comment by ndushay** [comment]
I need a druid for the "Version 3" one.  I will fix the Donna J one now.  yb936vv8634

**Comment by ndushay** [comment]
![image](https://user-images.githubusercontent.com/96775/186969772-74749416-9c50-4b16-bab0-9ebe81017896.png)

**Comment by ndushay** [comment]
for "Version 3", I tried to find it and there are a LOT of them:  43,331 in fact.

![image](https://user-images.githubusercontent.com/96775/186970218-f11cb73a-8d7b-4322-9449-9cbdb218e51a.png)

**Comment by ndushay** [comment]
found it, I think:  bb973hw5160.

![image](https://user-images.githubusercontent.com/96775/186972730-6ad6fad8-b4ca-43cb-9444-2037db9c96dd.png)

I dunno why those were messed up.  🤷🏻‍♀️

**Comment by amyehodge** [comment]
Sorry, yes, that's it. It was the first one on your list. Thanks! I'll continue to keep an eye out for stragglers, but it's impossible to check this thoroughly. I think this one is good!
