### ISSUE TITLE
In work type modal, update options for "Mixed Materials"

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2275]
When a user selects "Mixed Materials" in the work type modal, update the text that displays in red

from: Select at least two terms below:
to: Select at least two terms from any of the options below:

Also, the "See more options" section should be expanded by default for the "Mixed Materials" work type (but not for any other work type).

Remove the javascript that collapses the options. There should no longer be the "see more/fewer options"

<img width="487" alt="Screen Shot 2022-06-08 at 12 59 46 PM" src="https://user-images.githubusercontent.com/5558511/172674465-af53d1b6-e180-4148-b367-a6fd1eea1f34.png">

**Comment by amyehodge** [comment]
@peetucket It looks like there is a commit here but this never got pushed out. Can you check on this? Thanks.

**Comment by peetucket** [comment]
Yes, it looks done but not merged.  This comment on the PR suggests we were waiting for reviewing similar term changes from @arcadiafalcone before merging: https://github.com/sul-dlss/happy-heron/pull/2501#pullrequestreview-1087434928

**Comment by arcadiafalcone** [comment]
Answered in comment on #2501
