### ISSUE TITLE
Citation is now an optional element.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#228]
Note that this will require a new database migration.

**Comment by mjgiarlo** [comment]
@jcoyne I'm 90% sure you already took care of this in your subtype PR yesterday: https://github.com/sul-dlss/happy-heron/commit/dafad87a8ef97a1f4b27e310459e97b47686d0d9#diff-d00b45976b488f35d33740ac743f912fd835857cd139620e4e4e40c2b0444d22R6

Close?
