### ISSUE TITLE
Update layout for Creation dates on item edit form

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2280]
**New description**
On the item edit form in the Date section, update the creation dates so that there is a check box for choosing if you want to enter a date range. If the user enters a single date and then chooses the date range, keep the entries in the single range boxes and show the fields for the end of the range.
 
![image.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/2156ed14-0fe0-492d-bf4c-f371dc9eadd2)

**Comment by amyehodge** [comment]
@astridu We have had users confused about how to get rid of a date they entered because they can't deselect both radio buttons in the current implementation. Even changing to this dropdown, the user needs to select one of the option. To get rid of an entry in either case, the user needs to delete the entries in the individual boxes and that is not clear to everyone.

I'm wondering if we should add something like text to the right of the entries that says "clear" or "remove" or something like that that would be clearer to users about how to remove a date entry. What do you think?

**Comment by astridu** [comment]
We decided to stick with the garbage can which the user can click to 'clear' the date.
<img width="975" alt="image" src="https://user-images.githubusercontent.com/42216982/173725155-7d91edbd-a372-4151-95e0-7863a9ff05f3.png">

**Comment by justinlittman** [comment]
Supporting clearing of dates was moved to #2597.

**Comment by justinlittman** [comment]
@astridu @amyehodge In the past, driving behavior from the "onChange" of an HTML select posed an accessibility problem. Is that still the case?

**Comment by astridu** [comment]
@justinlittman Are you referring to the date range pull down? I don't think that's an issue.

**Comment by justinlittman** [comment]
Yes, the date range pull down.

**Comment by justinlittman** [comment]
Let me add that as a user, I wouldn't know what to expect to find in that pull down, so it might obscure the availability of other date options. (Where those options are apparent with the existing radio buttons.)

**Comment by astridu** [comment]
If they tab to the dropdown, it should id it as a drop down and read the options in it.

**Comment by justinlittman** [comment]
I'm talking about using a plain-old browser, not the screen reader. With a plain-old browser the other option is hidden from view. Single dates vs. date ranges are something that users are unlikely to be familiar enough with to guess what other options are in the pull down. And there is no label on the pull down to provide a hint.

**Comment by astridu** [comment]
Oh, I see what you're saying. Yes, the dropdown is not ideal for that reason, but they can click on it to see the other options. If we default it to one of the options, they can just click it to see the other option.

**Comment by justinlittman** [comment]
The point is that without clicking and with no label, (I would suggest) a user is unlikely to have any idea what the other option is. Users are unlikely to have a mental model of bibliographic date entry to know "I see single date entry; there's likely to be an option for date range entry."

Maybe this at least warrants a hallway test with a non-librarian to see if they can guess what the other option is?

**Comment by justinlittman** [comment]
Ugggh.
