### ISSUE TITLE
Update work subtype lists in work type modal

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2281]
Entering a work subtype that is the same as the work type causes duplications in the metadata displays. This is confusing to users and not helpful or needed in the metadata, so we should prevent this from happening.

See https://purl.stanford.edu/kn066mv7984.

<img width="142" alt="Screen Shot 2022-06-08 at 2 18 23 PM" src="https://user-images.githubusercontent.com/5558511/172688549-937742f8-12be-4013-8ee6-1b6d7fd0cabd.png">

For each work type, do not display the subtype option that is the same as the work type, both in the work type modal and in the item edit form.

For example, for work type "data," the term "data" should not be in the subtype list in the modal or the form:

![Screen Shot 2022-06-08 at 2 19 42 PM](https://user-images.githubusercontent.com/5558511/172689168-a06a0651-126f-405f-b306-de05b690bb84.png)

![Screen Shot 2022-06-08 at 2 20 07 PM](https://user-images.githubusercontent.com/5558511/172689187-b6d7472e-da12-457e-82dd-2e1b10d7e4db.png)

**Comment by ndushay** [comment]
doesn't "see fewer options" cover it?

**Comment by amyehodge** [comment]
@ndushay no, it doesn't, because the user can expand that and select that option. They can choose "Data" as the work type and then "Data" as a subtype too. I don't want "Data" to be an option in the subtypes list when "Data" is the work type so that this can't happen. Ditto for the other work types.

**Comment by ndushay** [comment]
I forgot the smiley face - I was joking.

**Comment by amyehodge** [comment]
@ndushay 

Remove subtypes for the following work types:
For work type Data, remove subtype Data
For work type Image, remove subtype Image
For work type Text, remove subtype Text

That's it. Thanks.
