### ISSUE TITLE
Make clear on item view form which entries are "Authors" and which are "Contributors"

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2283]
These are all currently displayed in the order they were entered, but the user can't tell when it switches from "Authors to be included in the citation" to "Additional contributors."

In the case below, the first two were authors and the second two contributors:
<img width="509" alt="Screen Shot 2022-06-08 at 2 25 44 PM" src="https://user-images.githubusercontent.com/5558511/172689825-4d49869a-bed8-456d-b271-d069f7b066d7.png">

The original mockup showed that this should look like this:
<img width="943" alt="Screen Shot 2022-06-08 at 2 26 05 PM" src="https://user-images.githubusercontent.com/5558511/172689893-9ae81e29-f7cc-4737-85f5-5765cc0e3d88.png">
_However, this wouldn't be accessible, so instead split this into two tables, one for authors and one for contributors. (edit by jcoyne)_

**Comment by jcoyne** [comment]
I'm a bit concerned about the accessibility of this.  I don't believe we have the markup to say "Authors" is for the first few rows and then "Contributors" are the next rows.   Can this be split into separate tables each with different captions?

**Comment by amyehodge** [comment]
@jcoyne That solution also works for me.
