### ISSUE TITLE
For initial collection form, cancel button should go to Details view page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2290]
When in the full collection editing form for an initial version of a collection (one that has never been deposited), if the user clicks the "Cancel" button at the bottom of the page, they should be taken to the Collection Details view page. Currently they are taken back to the dashboard.

**Comment by lwrubel** [comment]
This will be different than what happens if the user clicks Cancel while editing a deposited collection. That takes the user to the Collection Settings tab. Just wanted to confirm I'm understanding correctly that the different destinations are what is intended.

**Comment by amyehodge** [comment]
@lwrubel Actually, what happens now for deposited collections is that if the user clicks on the pencil icon from the settings tab and then cancels, they are taken back to the settings tab. If they click on the pencil from the details tab and then cancels, they are taken back to the details tab. 

In this case for the initial version, they are currently being taken to the dashboard, which is not where we want them to go. Since when they are editing in this situation they are seeing everything from the details tab and the settings tab, I'm not sure if it's possible to know how they got to the form. If it's possible to know that, then it would be great if they cancelled to be able to direct them back to the tab they came from. If it's not possible to know that, then we should take them to the collection details tab (and not the dashboard). I'm happy to walk you through this if it's confusing.

**Comment by lwrubel** [comment]
@amyehodge thanks for stepping through that, I think I've got it now. I hadn't picked up on the different edit forms for the details and settings tabs on deposited collections, which is sending the user back to different pages when canceling an update.
