### ISSUE TITLE
Set the title value (in the html head)

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#23]
Set it to `SDR | Stanford Digital Repository`. That's it. That's the issue. (You can disregard the comments below.)

**Comment by mjgiarlo** [comment]
We should talk with @amyehodge about this. This value governs what you see in the browser tab when you have H2 loaded. FWIW, Hydrus uses `Stanford Digital Repository`. Should H2 use the same value?

**Comment by amyehodge** [comment]
@mjgiarlo I'll think about this and get back to you.

Also, this changes depending on where you are in the application. If you are looking at a collection it says "[collection.title] - Stanford Digital Repository". If you are on an item, it says "[item.title] - Stanford Digital Repository". If you are editing a collection or item it says "Editing [collection.title/item.title] - Stanford Digital Repository".

**Comment by mjgiarlo** [comment]
@amyehodge For now, how about we set the title to `Stanford Digital Repository` on all pages, and if there are specific deviations from this you'd like to prioritize in future sprint pre-planning meetings, we can write up issues and get them on the board. Cool?

**Comment by amyehodge** [comment]
Sounds good. I think including the collection and item titles makes them too long to be useful anyhow. I tend to only be able to see the first half-dozen characters at best, so I'm wondering if something like "SDR | Stanford Digital Repository" might be better? But let's go with your plan for now. Thanks, @mjgiarlo

**Comment by mjgiarlo** [comment]
@amyehodge :speech_balloon: 
> Sounds good. I think including the collection and item titles makes them too long to be useful anyhow. I tend to only be able to see the first half-dozen characters at best, so I'm wondering if something like "SDR | Stanford Digital Repository" might be better? But let's go with your plan for now. Thanks, @mjgiarlo

`SDR | Stanford Digital Repository` it is. Thanks!
