### ISSUE TITLE
Add "OR" between name and ORCID options for authors and contributors in the item edit form

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2300]
In the "Authors to include in citation" and "Additional contributors" sections of the item edit form, when a user chooses an individual role term, include "OR" between the two radio buttons for the options to 1) add in a name manually or 2) to use the ORCID entry option.

**Comment by astridu** [comment]
Thanks @amyehodge !
<img width="64" alt="image" src="https://user-images.githubusercontent.com/42216982/173490838-6f181529-98d1-4fe5-835e-b2112a59a786.png">

**Comment by astridu** [comment]
I put a few guidelines in this one to show alignment. 

<img width="881" alt="image" src="https://user-images.githubusercontent.com/42216982/173491109-87518224-84ce-4200-a83e-f894185d0c5e.png">

**Comment by jcoyne** [comment]
I think addressing the question on #1990 might affect how we implement this.
