### ISSUE TITLE
Add in missing metadata for 2 items with DOIs migrated to H2

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2301]
See also #2302 for list of Hydrus items with DOIs to be migrated.

Two items with DOIs were not found during the preparations for migration and were migrated to H2 when they shouldn't have been. They need to have their metadata updated as indicated below. All metadata compatible with H2 should be added to H2.

dp477my6166 -- This item's H2 record does not reflect DOI and ORCID information that I can see in Argo.
mx682ny6097 -- This item has been versioned since the migration which has resulted in the loss of some information. We will need to retrieve this info from the DataCite metadata record. I'll paste it in below.

**Comment by amyehodge** [comment]
JSON from DataCite for mx682ny6097:

{
  "id": "https://doi.org/10.25740/mx682ny6097",
  "doi": "10.25740/MX682NY6097",
  "url": "https://purl.stanford.edu/mx682ny6097",
  "types": {
    "ris": "RPRT",
    "bibtex": "article",
    "citeproc": "article-journal",
    "schemaOrg": "ScholarlyArticle",
    "resourceType": "Instructional book",
    "resourceTypeGeneral": "Text"
  },
  "creators": [
    {
      "name": "Guevara, Marcelo",
      "nameType": "Personal",
      "givenName": "Marcelo",
      "familyName": "Guevara",
      "affiliation": [
        {
          "name": "Stanford University",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/00f54p054",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "nameIdentifiers": []
    },
    {
      "name": "Torres, Marta",
      "nameType": "Personal",
      "givenName": "Marta",
      "familyName": "Torres",
      "affiliation": [],
      "nameIdentifiers": []
    },
    {
      "name": "Vogl, Adrian",
      "nameType": "Personal",
      "givenName": "Adrian",
      "familyName": "Vogl",
      "affiliation": [
        {
          "name": "Stanford University",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/00f54p054",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "nameIdentifiers": [
        {
          "schemeUri": "https://orcid.org",
          "nameIdentifier": "https://orcid.org/0000-0001-9369-1071",
          "nameIdentifierScheme": "ORCID"
        }
      ]
    },
    {
      "name": "Moss, Sydney",
      "nameType": "Personal",
      "givenName": "Sydney",
      "familyName": "Moss",
      "affiliation": [
        {
          "name": "Stanford University",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/00f54p054",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "nameIdentifiers": [
        {
          "schemeUri": "https://orcid.org",
          "nameIdentifier": "https://orcid.org/0000-0002-2116-6638",
          "nameIdentifierScheme": "ORCID"
        }
      ]
    },
    {
      "name": "Da Roit, Gianinna",
      "nameType": "Personal",
      "givenName": "Gianinna",
      "familyName": "Da Roit",
      "affiliation": [],
      "nameIdentifiers": []
    },
    {
      "name": "Weil, Charlotte",
      "nameType": "Personal",
      "givenName": "Charlotte",
      "familyName": "Weil",
      "affiliation": [
        {
          "name": "Stanford University",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/00f54p054",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "nameIdentifiers": []
    },
    {
      "name": "Caballero Espejo, Jorge",
      "nameType": "Personal",
      "givenName": "Jorge",
      "familyName": "Caballero Espejo",
      "affiliation": [],
      "nameIdentifiers": []
    },
    {
      "name": "Pillaca Ortiz, Jorge Martin",
      "nameType": "Personal",
      "givenName": "Jorge Martin",
      "familyName": "Pillaca Ortiz",
      "affiliation": [],
      "nameIdentifiers": []
    },
    {
      "name": "Schmitt, Rafael",
      "nameType": "Personal",
      "givenName": "Rafael",
      "familyName": "Schmitt",
      "affiliation": [
        {
          "name": "Stanford University",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/00f54p054",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "nameIdentifiers": []
    },
    {
      "name": "Rioja Ballivian, Guillermo",
      "nameType": "Personal",
      "givenName": "Guillermo",
      "familyName": "Rioja Ballivian",
      "affiliation": [],
      "nameIdentifiers": []
    },
    {
      "name": "De Oliveira, Iván",
      "nameType": "Personal",
      "givenName": "Iván",
      "familyName": "De Oliveira",
      "affiliation": [],
      "nameIdentifiers": []
    },
    {
      "name": "Fredriksson Häägg, Anna Ingrid Kristina",
      "nameType": "Personal",
      "givenName": "Anna Ingrid Kristina",
      "familyName": "Fredriksson Häägg",
      "affiliation": [
        {
          "name": "Stanford University",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/00f54p054",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "nameIdentifiers": []
    },
    {
      "name": "Mandle, Lisa",
      "nameType": "Personal",
      "givenName": "Lisa",
      "familyName": "Mandle",
      "affiliation": [
        {
          "name": "Stanford University",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/00f54p054",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "nameIdentifiers": []
    },
    {
      "name": "Wolny, Stacie",
      "nameType": "Personal",
      "givenName": "Stacie",
      "familyName": "Wolny",
      "affiliation": [
        {
          "name": "Stanford University",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/00f54p054",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "nameIdentifiers": []
    },
    {
      "name": "Fernández, Luis",
      "nameType": "Personal",
      "givenName": "Luis",
      "familyName": "Fernández",
      "affiliation": [],
      "nameIdentifiers": []
    },
    {
      "name": "Ascorra Guanira, César",
      "nameType": "Personal",
      "givenName": "César",
      "familyName": "Ascorra Guanira",
      "affiliation": [],
      "nameIdentifiers": []
    },
    {
      "name": "Ruckelshaus, Mary",
      "nameType": "Personal",
      "givenName": "Mary",
      "familyName": "Ruckelshaus",
      "affiliation": [
        {
          "name": "Stanford University",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/00f54p054",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "nameIdentifiers": []
    },
    {
      "name": "Reyes, Juan Fernando",
      "nameType": "Personal",
      "givenName": "Juan Fernando",
      "familyName": "Reyes",
      "affiliation": [],
      "nameIdentifiers": []
    },
    {
      "name": "Daily, Gretchen",
      "nameType": "Personal",
      "givenName": "Gretchen",
      "familyName": "Daily",
      "affiliation": [
        {
          "name": "Stanford University",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/00f54p054",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "nameIdentifiers": [
        {
          "schemeUri": "https://orcid.org",
          "nameIdentifier": "https://orcid.org/0000-0003-1443-1111",
          "nameIdentifierScheme": "ORCID"
        }
      ]
    },
    {
      "name": "Fidhel Sánchez, Jesus A.",
      "nameType": "Personal",
      "givenName": "Jesus A.",
      "familyName": "Fidhel Sánchez",
      "affiliation": [],
      "nameIdentifiers": []
    },
    {
      "name": "Gallegos Chacón, Luis",
      "nameType": "Personal",
      "givenName": "Luis",
      "familyName": "Gallegos Chacón",
      "affiliation": [],
      "nameIdentifiers": []
    },
    {
      "name": "Anderson, Christopher",
      "nameType": "Personal",
      "givenName": "Christopher",
      "familyName": "Anderson",
      "affiliation": [
        {
          "name": "Stanford University",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/00f54p054",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "nameIdentifiers": []
    },
    {
      "name": "Kain, Morgan",
      "nameType": "Personal",
      "givenName": "Morgan",
      "familyName": "Kain",
      "affiliation": [
        {
          "name": "Stanford University",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/00f54p054",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "nameIdentifiers": []
    },
    {
      "name": "Cafasso, Sarah",
      "nameType": "Personal",
      "givenName": "Sarah",
      "familyName": "Cafasso",
      "affiliation": [
        {
          "name": "Stanford University",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/00f54p054",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "nameIdentifiers": []
    },
    {
      "name": "Panduro Rosas, Mario",
      "nameType": "Personal",
      "givenName": "Mario",
      "familyName": "Panduro Rosas",
      "affiliation": [],
      "nameIdentifiers": []
    }
  ],
  "titles": [
    {
      "lang": "es",
      "title": "Proyecto de Resiliencia y Ordenamiento Territorial del agua y Servicios Ecosistémicos en la Amazonía de Perú, Bolivia y Brasil",
      "titleType": null
    }
  ],
  "publisher": "Stanford Digital Repository",
  "subjects": [
    {
      "subject": "cuenca"
    },
    {
      "subject": "hídrologia"
    },
    {
      "subject": "inundación"
    },
    {
      "subject": "Ordenamiento Territorial"
    },
    {
      "subject": "Servicios Ecosistémicos"
    },
    {
      "subject": "Resiliencia"
    },
    {
      "subject": "Amazonía"
    }
  ],
  "contributors": [
    {
      "name": "The Natural Capital Project",
      "nameType": "Organizational",
      "givenName": null,
      "familyName": null,
      "affiliation": [
        {
          "name": "Stanford University",
          "schemeUri": "https://ror.org",
          "affiliationIdentifier": "https://ror.org/00f54p054",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
      "contributorType": "ResearchGroup",
      "nameIdentifiers": [
        {
          "schemeUri": null,
          "nameIdentifier": null,
          "nameIdentifierScheme": null
        }
      ]
    }
  ],
  "dates": [
    {
      "date": "2018",
      "dateType": "Created",
      "dateInformation": "Start of creation date range"
    },
    {
      "date": "2020",
      "dateType": "Created",
      "dateInformation": "End of creation date range"
    }
  ],
  "publicationYear": 2021,
  "identifiers": [],
  "sizes": [],
  "formats": [],
  "rightsList": [
    {
      "rights": "Creative Commons Attribution 3.0 Unported",
      "rightsUri": "https://creativecommons.org/licenses/by/3.0/legalcode",
      "schemeUri": "https://spdx.org/licenses/",
      "rightsIdentifier": "cc-by-3.0",
      "rightsIdentifierScheme": "SPDX"
    }
  ],
  "descriptions": [
    {
      "lang": "es",
      "description": "El libro tiene una mirada integral y busca apoyar los procesos de construcción de puentes entre ciencia y política, plantea y desarrolla una iniciativa en base al Proyecto de Resiliencia y Ordenamiento Territorial del agua y Servicios Ecosistémicos en la Amazonía de Perú, Bolivia y Brasil (PRO-Agua) de The Natural Capital Project (NatCap) de la Universidad de Stanford.\nEstablece el paisaje amazónico trinacional de Madre de Dios (Perú), Acre (Brasil) y Pando (Bolivia) como ámbito de estudio, así como identificar los servicios ecosistémicos hidrológicos como el eje del mismo, ofrece la oportunidad de llevar adelante un análisis con enfoque multidisciplinario y territorial de gestión integrada de cuenca. Este paisaje amazónico conocido como MAP por las iniciales de los ámbitos subnacionales que lo componen, permite visibilizar un mismo ecosistema bajo tres miradas de gestión y gobierno, dependiendo de las estructuras institucionales y legales de cada país; ofreciendo además la oportunidad de armonizar la toma de decisiones con una visión de cuenca transfronteriza, basada en ciencia.\nEl libro presenta el aporte del trabajo realizado en el marco del proyecto PRO Agua permite avanzar en la agenda del conocimiento, proveyendo de data e información analizada de manera multidisciplinaria respecto de los servicios ecosistémicos y su importancia. Se exploran los ciclos hidrológicos del ámbito de estudio (las cuencas de los ríos Madre de Dios, Acre y Purús), asi como la gestión del territorio y las presiones antrópicas que los alteran poniendo en peligro no solo su continuidad, sino la vida y bienes de las poblaciones que enfrentan, entre otros riesgos, inundaciones atípicas por el cambio de uso de suelo (con un enfoque específico pero no excluyente, en los sectores de Puerto Maldonado – Mazuko y Tahuamanu – Cobija).\nEl rediseño de los paisajes amazónicos, se enfrenta a un crecimiento poblacional reflejado en nuevos asentamientos urbanos y el crecimiento de ciudades que deberían hacerlo en armonía con el entorno; así como a presiones antrópicas producto de una ocupación no planificada del suelo o producto de actividades ilegales e informales que priorizan el retorno económico del cambio de uso de suelo, sobre la sostenibilidad de la actividad planteada o del entorno.\nOtro aspecto clave del presente trabajo reflejado en el libro, está dado por la mirada prospectiva del mismo, al plantear una gama de escenarios a futuro que reflejan la vulnerabilidad de los ecosistemas estudiados, trabajar en el desarrollo de un Índice integral de Servicios Hidrológicos (ISH), ofrecer acceso a la información obtenida y organizada a través de un portal web que permite visualizarla y de ser el caso monitorear su evolución, además de identificar oportunidades de mejora a través de modelamientos que permitirían la recuperación y regeneración de ámbitos altamente intervenidos, poniendo como ejemplo uno de los más deteriorados e internacionalmente conocidos como es el caso de La Pampa en Madre de Dios (Perú).\nUna mirada integral de la información y escenarios presentados, asi como el análisis de los mismos, permite diseñar estrategias de corto, mediano y largo plazo a ser plasmadas en políticas públicas de diverso nivel de decisión, desde lo local a lo nacional e incluso como insumo para coordinaciones binacionales o trinacionales en el caso del ámbito del MAP.\nUn aspecto final y fundamental del proyecto, reflejado en el libro, es que se haya realizado entre investigadores del la Universidad de Stanford e investigadores locales permitiendo asi, compartir capacidades y conocimientos mutuos, que se materializarán en beneficio de la consolidación y fortalecimiento de la toma de decisiones local. Incidir en la generación de conocimiento, su difusión y apropiación a nivel local, asi como su canalización como sustento en la toma de decisiones para el diseño de políticas públicas, es un aspecto clave en el que debería visibilizarse el esfuerzo de cada trabajo de investigación.\n\n",
      "descriptionType": "Abstract"
    }
  ],
  "geoLocations": [
    {
      "geoLocationPlace": "Peru"
    },
    {
      "geoLocationPlace": "Bolivia"
    },
    {
      "geoLocationPlace": "Brasil"
    }
  ],
  "fundingReferences": [
    {
      "awardUri": null,
      "awardTitle": null,
      "funderName": "Gordon and Betty Moore Foundation",
      "awardNumber": null,
      "funderIdentifier": "https://doi.org/10.13039/100000936",
      "funderIdentifierType": "Crossref Funder ID"
    }
  ],
  "relatedIdentifiers": [],
  "schemaVersion": "http://datacite.org/schema/kernel-4",
  "providerId": "sul",
  "clientId": "sul.sdr",
  "agency": "datacite",
  "state": "findable"
}

**Comment by amyehodge** [comment]
Same as above in xml

<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">
  <identifier identifierType="DOI">10.25740/MX682NY6097</identifier>
  <creators>
    <creator>
      <creatorName nameType="Personal">Guevara, Marcelo</creatorName>
      <givenName>Marcelo</givenName>
      <familyName>Guevara</familyName>
      <affiliation affiliationIdentifier="https://ror.org/00f54p054" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Stanford University</affiliation>
    </creator>
    <creator>
      <creatorName nameType="Personal">Torres, Marta</creatorName>
      <givenName>Marta</givenName>
      <familyName>Torres</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Vogl, Adrian</creatorName>
      <givenName>Adrian</givenName>
      <familyName>Vogl</familyName>
      <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="https://orcid.org">https://orcid.org/0000-0001-9369-1071</nameIdentifier>
      <affiliation affiliationIdentifier="https://ror.org/00f54p054" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Stanford University</affiliation>
    </creator>
    <creator>
      <creatorName nameType="Personal">Moss, Sydney</creatorName>
      <givenName>Sydney</givenName>
      <familyName>Moss</familyName>
      <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="https://orcid.org">https://orcid.org/0000-0002-2116-6638</nameIdentifier>
      <affiliation affiliationIdentifier="https://ror.org/00f54p054" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Stanford University</affiliation>
    </creator>
    <creator>
      <creatorName nameType="Personal">Da Roit, Gianinna</creatorName>
      <givenName>Gianinna</givenName>
      <familyName>Da Roit</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Weil, Charlotte</creatorName>
      <givenName>Charlotte</givenName>
      <familyName>Weil</familyName>
      <affiliation affiliationIdentifier="https://ror.org/00f54p054" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Stanford University</affiliation>
    </creator>
    <creator>
      <creatorName nameType="Personal">Caballero Espejo, Jorge</creatorName>
      <givenName>Jorge</givenName>
      <familyName>Caballero Espejo</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Pillaca Ortiz, Jorge Martin</creatorName>
      <givenName>Jorge Martin</givenName>
      <familyName>Pillaca Ortiz</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Schmitt, Rafael</creatorName>
      <givenName>Rafael</givenName>
      <familyName>Schmitt</familyName>
      <affiliation affiliationIdentifier="https://ror.org/00f54p054" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Stanford University</affiliation>
    </creator>
    <creator>
      <creatorName nameType="Personal">Rioja Ballivian, Guillermo</creatorName>
      <givenName>Guillermo</givenName>
      <familyName>Rioja Ballivian</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">De Oliveira, Iván</creatorName>
      <givenName>Iván</givenName>
      <familyName>De Oliveira</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Fredriksson Häägg, Anna Ingrid Kristina</creatorName>
      <givenName>Anna Ingrid Kristina</givenName>
      <familyName>Fredriksson Häägg</familyName>
      <affiliation affiliationIdentifier="https://ror.org/00f54p054" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Stanford University</affiliation>
    </creator>
    <creator>
      <creatorName nameType="Personal">Mandle, Lisa</creatorName>
      <givenName>Lisa</givenName>
      <familyName>Mandle</familyName>
      <affiliation affiliationIdentifier="https://ror.org/00f54p054" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Stanford University</affiliation>
    </creator>
    <creator>
      <creatorName nameType="Personal">Wolny, Stacie</creatorName>
      <givenName>Stacie</givenName>
      <familyName>Wolny</familyName>
      <affiliation affiliationIdentifier="https://ror.org/00f54p054" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Stanford University</affiliation>
    </creator>
    <creator>
      <creatorName nameType="Personal">Fernández, Luis</creatorName>
      <givenName>Luis</givenName>
      <familyName>Fernández</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Ascorra Guanira, César</creatorName>
      <givenName>César</givenName>
      <familyName>Ascorra Guanira</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Ruckelshaus, Mary</creatorName>
      <givenName>Mary</givenName>
      <familyName>Ruckelshaus</familyName>
      <affiliation affiliationIdentifier="https://ror.org/00f54p054" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Stanford University</affiliation>
    </creator>
    <creator>
      <creatorName nameType="Personal">Reyes, Juan Fernando</creatorName>
      <givenName>Juan Fernando</givenName>
      <familyName>Reyes</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Daily, Gretchen</creatorName>
      <givenName>Gretchen</givenName>
      <familyName>Daily</familyName>
      <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="https://orcid.org">https://orcid.org/0000-0003-1443-1111</nameIdentifier>
      <affiliation affiliationIdentifier="https://ror.org/00f54p054" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Stanford University</affiliation>
    </creator>
    <creator>
      <creatorName nameType="Personal">Fidhel Sánchez, Jesus A.</creatorName>
      <givenName>Jesus A.</givenName>
      <familyName>Fidhel Sánchez</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Gallegos Chacón, Luis</creatorName>
      <givenName>Luis</givenName>
      <familyName>Gallegos Chacón</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Anderson, Christopher</creatorName>
      <givenName>Christopher</givenName>
      <familyName>Anderson</familyName>
      <affiliation affiliationIdentifier="https://ror.org/00f54p054" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Stanford University</affiliation>
    </creator>
    <creator>
      <creatorName nameType="Personal">Kain, Morgan</creatorName>
      <givenName>Morgan</givenName>
      <familyName>Kain</familyName>
      <affiliation affiliationIdentifier="https://ror.org/00f54p054" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Stanford University</affiliation>
    </creator>
    <creator>
      <creatorName nameType="Personal">Cafasso, Sarah</creatorName>
      <givenName>Sarah</givenName>
      <familyName>Cafasso</familyName>
      <affiliation affiliationIdentifier="https://ror.org/00f54p054" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Stanford University</affiliation>
    </creator>
    <creator>
      <creatorName nameType="Personal">Panduro Rosas, Mario</creatorName>
      <givenName>Mario</givenName>
      <familyName>Panduro Rosas</familyName>
    </creator>
  </creators>
  <titles>
    <title xml:lang="es">Proyecto de Resiliencia y Ordenamiento Territorial del agua y Servicios Ecosistémicos en la Amazonía de Perú, Bolivia y Brasil</title>
  </titles>
  <publisher>Stanford Digital Repository</publisher>
  <publicationYear>2021</publicationYear>
  <resourceType resourceTypeGeneral="Text">Instructional book</resourceType>
  <subjects>
    <subject>cuenca</subject>
    <subject>hídrologia</subject>
    <subject>inundación</subject>
    <subject>Ordenamiento Territorial</subject>
    <subject>Servicios Ecosistémicos</subject>
    <subject>Resiliencia</subject>
    <subject>Amazonía</subject>
  </subjects>
  <contributors>
    <contributor contributorType="ResearchGroup">
      <contributorName nameType="Organizational">The Natural Capital Project</contributorName>
      <nameIdentifier nameIdentifierScheme="" schemeURI=""/>
      <affiliation affiliationIdentifier="https://ror.org/00f54p054" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Stanford University</affiliation>
    </contributor>
  </contributors>
  <dates>
    <date dateType="Created" dateInformation="Start of creation date range">2018</date>
    <date dateType="Created" dateInformation="End of creation date range">2020</date>
  </dates>
  <sizes/>
  <formats/>
  <version/>
  <rightsList>
    <rights rightsURI="https://creativecommons.org/licenses/by/3.0/legalcode">Creative Commons Attribution 3.0 Unported</rights>
  </rightsList>
  <descriptions>
    <description xml:lang="es" descriptionType="Abstract">El libro tiene una mirada integral y busca apoyar los procesos de construcción de puentes entre ciencia y política, plantea y desarrolla una iniciativa en base al Proyecto de Resiliencia y Ordenamiento Territorial del agua y Servicios Ecosistémicos en la Amazonía de Perú, Bolivia y Brasil (PRO-Agua) de The Natural Capital Project (NatCap) de la Universidad de Stanford.
Establece el paisaje amazónico trinacional de Madre de Dios (Perú), Acre (Brasil) y Pando (Bolivia) como ámbito de estudio, así como identificar los servicios ecosistémicos hidrológicos como el eje del mismo, ofrece la oportunidad de llevar adelante un análisis con enfoque multidisciplinario y territorial de gestión integrada de cuenca. Este paisaje amazónico conocido como MAP por las iniciales de los ámbitos subnacionales que lo componen, permite visibilizar un mismo ecosistema bajo tres miradas de gestión y gobierno, dependiendo de las estructuras institucionales y legales de cada país; ofreciendo además la oportunidad de armonizar la toma de decisiones con una visión de cuenca transfronteriza, basada en ciencia.
El libro presenta el aporte del trabajo realizado en el marco del proyecto PRO Agua permite avanzar en la agenda del conocimiento, proveyendo de data e información analizada de manera multidisciplinaria respecto de los servicios ecosistémicos y su importancia. Se exploran los ciclos hidrológicos del ámbito de estudio (las cuencas de los ríos Madre de Dios, Acre y Purús), asi como la gestión del territorio y las presiones antrópicas que los alteran poniendo en peligro no solo su continuidad, sino la vida y bienes de las poblaciones que enfrentan, entre otros riesgos, inundaciones atípicas por el cambio de uso de suelo (con un enfoque específico pero no excluyente, en los sectores de Puerto Maldonado – Mazuko y Tahuamanu – Cobija).
El rediseño de los paisajes amazónicos, se enfrenta a un crecimiento poblacional reflejado en nuevos asentamientos urbanos y el crecimiento de ciudades que deberían hacerlo en armonía con el entorno; así como a presiones antrópicas producto de una ocupación no planificada del suelo o producto de actividades ilegales e informales que priorizan el retorno económico del cambio de uso de suelo, sobre la sostenibilidad de la actividad planteada o del entorno.
Otro aspecto clave del presente trabajo reflejado en el libro, está dado por la mirada prospectiva del mismo, al plantear una gama de escenarios a futuro que reflejan la vulnerabilidad de los ecosistemas estudiados, trabajar en el desarrollo de un Índice integral de Servicios Hidrológicos (ISH), ofrecer acceso a la información obtenida y organizada a través de un portal web que permite visualizarla y de ser el caso monitorear su evolución, además de identificar oportunidades de mejora a través de modelamientos que permitirían la recuperación y regeneración de ámbitos altamente intervenidos, poniendo como ejemplo uno de los más deteriorados e internacionalmente conocidos como es el caso de La Pampa en Madre de Dios (Perú).
Una mirada integral de la información y escenarios presentados, asi como el análisis de los mismos, permite diseñar estrategias de corto, mediano y largo plazo a ser plasmadas en políticas públicas de diverso nivel de decisión, desde lo local a lo nacional e incluso como insumo para coordinaciones binacionales o trinacionales en el caso del ámbito del MAP.
Un aspecto final y fundamental del proyecto, reflejado en el libro, es que se haya realizado entre investigadores del la Universidad de Stanford e investigadores locales permitiendo asi, compartir capacidades y conocimientos mutuos, que se materializarán en beneficio de la consolidación y fortalecimiento de la toma de decisiones local. Incidir en la generación de conocimiento, su difusión y apropiación a nivel local, asi como su canalización como sustento en la toma de decisiones para el diseño de políticas públicas, es un aspecto clave en el que debería visibilizarse el esfuerzo de cada trabajo de investigación.

</description>
  </descriptions>
  <geoLocations>
    <geoLocation>
      <geoLocationPlace>Peru</geoLocationPlace>
    </geoLocation>
    <geoLocation>
      <geoLocationPlace>Bolivia</geoLocationPlace>
    </geoLocation>
    <geoLocation>
      <geoLocationPlace>Brasil</geoLocationPlace>
    </geoLocation>
  </geoLocations>
  <fundingReferences>
    <fundingReference>
      <funderName>Gordon and Betty Moore Foundation</funderName>
      <funderIdentifier funderIdentifierType="Crossref Funder ID">https://doi.org/10.13039/100000936</funderIdentifier>
    </fundingReference>
  </fundingReferences>
</resource>

**Comment by jcoyne** [comment]
It looks like dp477my6166 was updated in argo, so when we try to save it it gives a version mismatch error
![Screen Shot 2022-08-17 at 5.53.35 PM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/af158d44-22ae-4dec-af7a-906c6fb86271)

https://app.honeybadger.io/projects/67994/faults/83912195
