### ISSUE TITLE
Migrate Hydrus items with DOIs to H2

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2302]
See also #2301 for 2 items with missing DOI-related metadata that were migrated to H2.

These items were not migrated to H2 because at the time we did the migration, we could not support DOIs in H2. Now that we can support DOIs, we would prefer to be able to manage these items from within H2.

We are aware that some of these have DOI metadata that is not supported in H2, but we prefer to lose that extra metadata so that we can manage these within H2. All metadata compatible with H2 should be migrated.

NOTE: 5 of the druids below **do not have druid-based DOIs** and one uses a **different prefix**, so we may need to figure out how to make saving/versioning work properly for these in H2. If we can't figure out how to make them work properly in H2, we should not migrate them.

List of 28 druids and their DOIs to be migrated can be found at https://docs.google.com/spreadsheets/d/12X5kjW-U45Y-_HMoR7eR65n9-EpqDzU6roQeM5G7y_k/edit#gid=0

**Comment by jcoyne** [comment]
These items can be put into collections that you find via argo.  e.g. go to https://argo.stanford.edu/view/hr045dx8661 and note the collection is "Biogeochemistry data" (https://argo.stanford.edu/view/druid:wg919by6182), then search for that collection in H2 by druid to find: https://sdr.stanford.edu/collections/130

**Comment by amyehodge** [comment]
@jcoyne The spreadsheet has been updated with license, work type, and owner/depositor for each item.

**Comment by amyehodge** [comment]
@jcoyne All items are now in H2 and all users have been notified. Can you reset these from me to the proper owner? I think that's the last piece of the puzzle.

Assigning back to you for this last step before closing.

**Comment by jcoyne** [comment]
<img width="1053" alt="Screen Shot 2022-09-09 at 11 19 07 AM" src="https://user-images.githubusercontent.com/92044/189395920-6350b8cd-bbb4-4dc9-9451-2e0c73adb70f.png">
@amyehodge is there a reason we can't use the new functionality to do the ownership change?

**Comment by amyehodge** [comment]
@jcoyne I don't see why not. Good thinking! I'll try to get that done right now.

**Comment by amyehodge** [comment]
Details about this work are documented in the Google Drive folder at https://drive.google.com/drive/folders/1pxq5h55UMGwbhOJWzcjEjd0KXQvd1npz. 

Regarding the content, checksum report was run on all the files for this list of druids before downloading them all from Argo. I then reran the checksums on my local machine before uploading the files to the items to make sure they were all the same. After I finished depositing all the items, I reran the check sum report from Argo to make sure everything still matched up. These reports are in the folder above and all matched up.

All managers and depositors whose SUNets still appeared to be valid were emailed regarding this content migration.

**Comment by amyehodge** [comment]
For completeness, I also wanted to note here that I noticed these did not get assigned H2 tags in Argo, so I went in and added "Project : H2" tags to all 29 of these items.
