### ISSUE TITLE
Add additional descriptions to item history table for some events and update one event

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2304]
Some user actions are not generating descriptions in the right-most column of the history table on the item view page when an item is saved as a draft or deposited.

Actions not generating a description and what the description should be:
- removing file description: "file description changed"
- removing a contact: "contact email modified"
- removing an author: "authors modified"
- removing a contributor: "contributors modified"
- removing a keyword: "keywords modified"
- removing a related work: "related works modified"
- removing a related link: "related links modified"
- removing a work subtype: "work subtypes modified" (note: I can't verify this one currently because there is a bug preventing me from removing a work type)

Also, there is currently a bug with the 

See https://github.com/sul-dlss/happy-heron/blob/48b1cbe2d1d8faaaae0c8159399a2b5c92c2a0c5/app/services/work_version_event_description_builder.rb#L24-L111

**Comment by peetucket** [comment]
Note: there may have been some wonkiness because of this: #2634, which is now corrected.  So it's likely at least some of these will start working again with no further change, but we should do some more testing.

**Comment by jcoyne** [comment]
@amyehodge Now that #2634 is fixed, can you reassess this ticket?

**Comment by amyehodge** [comment]
@jcoyne Sure. I'll put this on my list to review, hopefully today.

**Comment by amyehodge** [comment]
@jcoyne I have reviewed this and most of it is working. There is now just a short list of content removal that is not being logged. I've updated the description above.
