### ISSUE TITLE
Create new Admin dashboard page with drop-down menu to access some functions

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2306]
Create this new page and the drop-down chooser for the functions that will be listed there, which will include:

- Search for druid
- Search SUNet ID
- Generate item report
- Generate collection report
- Change item owner
- Lock/unlock item
- Decommission item

For this ticket to be complete, the list can be empty. Further tickets will populate the list.

This page will be accessible by admins only from a link on the home page (#2305) and will include a set of features accessible only to individuals with administrator permissions.

To include (see other tickets linked below):

- Druid search (#2382)
-- moved here from the existing main page and incorporated into drop-down list
-- maintain existing functionality
- SUNet ID search (#2308)
- Item report (#2309)
- Collection report (#2310)
- Change item ownership (#2312 and other tickets that start with "Change owner")
- Prevent editing of specific item (#2317 and other tickets that start with "Lock editing")
- Decommission item (#2375) 
- Table of collection recent activity (#2325)
- Table of item recent activity (#2325)
- Table of locked items (#2318)
- "All Collections" table (#2307)
-- moved here from the existing main page
-- maintain existing format and information
-- collapsed by default

In addition, there should always be an "Admin" button at the top right of this page that takes the user back to this page. This will allow the user to get back here after selecting another function from the drop-down menu.

Mockup: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/467473848

![Screen Shot 2022-06-28 at 3 05 04 PM](https://user-images.githubusercontent.com/5558511/176262699-99d8246b-8fa4-43dc-8133-821dc5973a01.png)

**Comment by jcoyne** [comment]
Developer will probably want to take #2305 at the same time.
