### ISSUE TITLE
Create ability to search H2 database by SUNet ID

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2308]
Add the ability for an admin (only) to perform and search by SUNet ID for an exact match. 

Once found, the user should be shown the name and affiliation associated with that SUNet ID, and the following three tables of information specific to that user should be displayed: 

- H2 collections this user can access, including
-- collection title (linked to view page)
-- work id
-- druid when available
-- Role for that collection (manager, reviewer, depositor).
- H2 collections (in all states) created by this user, including
-- collection title (linked to view page)
-- state of each item (draft, awaiting approval, deposited, version draft, etc.)
-- work id
-- druid when available
-- role for that collection (manager, reviewer, depositor, current owner)
- H2 items (in all states) created or owned by this user, including
-- item title (linked to view page)
-- collection title (linked to view page)
-- state of each item (draft, awaiting approval, deposited, version draft, etc.)
-- work id
-- druid when available
-- Role for that item (depositor or current owner)

Mockup: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/467473852

![Screen Shot 2022-06-28 at 3 09 36 PM](https://user-images.githubusercontent.com/5558511/176264438-fa3f068d-d271-41b4-a936-8410a7173502.png)

**Comment by amyehodge** [comment]
This needs a mockup of the error state.

**Comment by amyehodge** [comment]
Here's the error state if no SUNet ID is found:
![Screen Shot 2022-06-20 at 2 12 33 PM](https://user-images.githubusercontent.com/5558511/174658349-4459348a-e384-46ce-b0d1-e5c3b8a4f57b.png)

**Comment by jcoyne** [comment]
@astridu @amyehodge why are we putting "work id" on these tables?  Internal identifiers like that should be completely opaque to the user.

**Comment by amyehodge** [comment]
@jcoyne yes, for two reasons:
1. not all items will have druids, but all items have work ids
2. this feature is just for admins, who are very familiar with the work ids

**Comment by jcoyne** [comment]
What do the admins do with the work ids?  What if the ID scheme changes?  We've never discussed making this a permanent scheme to be used outside of the internal workings of H2.

**Comment by amyehodge** [comment]
@andrewjbtw could you provide some feedback on how you use H2 work IDs? 

In Hydrus, the druid was part of the URL, and I and others frequently used the druid to go straight to an item page without having to navigate through the UI. This was particularly handy when we did not have readily at hand information the information we needed to navigate there -- i.e. open app, select the right collection [must know collection name], identify the right work by title [must know the title]. By inserting the druid at the end of a known URL we could go straight there.

In H2, we can't do this because the druid is not part of the URL, but the work ID is. So, if we have a report and it includes the work ID, we can easily get to the item page in the UI without doing all the clicking to get there.

This is one example of how we use this information. I don't see any reason to generate a report with all the other information and leave this piece out, when it is something that we do sometimes want/need, particularly when the item does not have a druid.
