### ISSUE TITLE
Create ability to generate item report

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2309]
This is one of the options in the drop-down menu on the admin page that is available only to administrators.

Report should include the following information in csv format for all items in all states in H2. 

- item title
- work id 
- druid when available
- state of each item (draft, awaiting approval, deposited, version draft, etc.) 
- version number
- SUNet ID of user who created the item 
- SUNet ID of current owner 
- indication of whether item is "locked" for editing
- date created
- date last modified
- date last deposited
- release setting 
- visibility setting 
- license 
- DOI yes/no
- collection title
- collection work ID
- collection druid when available

Default sorting should be by SUNet ID of item creator.

We also request options to restrict the results based on the following:
- a single collection
- range of dates created
- range of dates last modified
- range of dates last deposited
- H2 state, selected via checkboxes, multiple boxes can be checked
-- PURL reserved
-- initial draft
-- submitted for approval
-- returned for review
-- deposited
-- version draft
-- decommissioned

Mockup: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/467473853

See screenshot of mockup in comment below.

For the three date range options:
- require year, month, and day for start and end dates
- second date must be after the first date

Mockup: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/467473849

![Screen Shot 2022-06-20 at 2 24 36 PM](https://user-images.githubusercontent.com/5558511/174659649-5fde09ed-aac5-4c12-ad8e-0adcc37aab7d.png)

**Comment by amyehodge** [comment]
Is there a way we can know in this report for 
- release setting
- visibility setting
- license
- DOI yes/no
whether the depositor got to make a selection or if these were set at the collection level?

**Comment by amyehodge** [comment]
@astridu has suggested an error message if no results are found because of the filters chosen. Is this possible to do? This is not a high priority, but this is what she was thinking. Same on the item report (#2310).

See: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/467473849

<img width="666" alt="report_no_results" src="https://user-images.githubusercontent.com/5558511/174659979-ca1d8826-e818-476b-86d0-82e105e26523.png">

**Comment by amyehodge** [comment]
@astridu Can you please add the "decommissioned" state to the list of options for "H2 state"? Thanks.

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/184016063-31214e7f-58e6-461f-a8b7-a1dc489553ed.png)
<img width="672" alt="image" src="https://user-images.githubusercontent.com/42216982/184016109-5387f870-936e-4aae-9476-190812404da4.png">

**Comment by jcoyne** [comment]
These mockups make it look like you have to enter all of the date ranges.   Should it be possible that you don't want any ranges or would you want open ended ranges?  What does the button that looks like a lego block do?

**Comment by amyehodge** [comment]
@jcoyne The intent is that the admin can choose none, any, or all of the date options to filter the report results. The "lego block" button is the calendar icon for choosing dates, similar I think to ones in Argo. @astridu can you please clarify that? I suspect the built-in widget would be fine.

I hadn't considered an open-ended date range. For anything since a certain date, it would be easy enough to complete the range, as the end date would just be today, so I don't think we need to support a start date without an end date. 

As for having an end date but no start date, I can imagine wanting anything up to a certain date, like before 12-31-2020, and not knowing what the earliest possible date would need to be to be able to enter that. I don't think this is a common use case to need to support.

**Comment by amyehodge** [comment]
@jcoyne @astridu I think it might improve clarity regarding whether you have to enter date options/all the date options if we move the collection ID box to the below the "H2 state" filter. Right now the text that says "Limit your search with one or more of the options below" is above that box and it kind of makes it look like it's just for that box as opposed to being for everything below it on the page. @astridu What do you think about this?

**Comment by amyehodge** [comment]
@jcoyne Also, to be clear, we do not need to support open-ended date ranges. Both a start date and an end date should be required for each of those filters. Thanks.

**Comment by astridu** [comment]
@amyehodge How about something like this?
<img width="479" alt="image" src="https://user-images.githubusercontent.com/42216982/184789657-aeca136d-5626-47b8-ab5c-b5e5d11b4de4.png">

**Comment by amyehodge** [comment]
@astridu With this configuration, the limit using the collection work ID is now below the text about limiting the search. What about moving the collection work ID limit below the H2 state?

**Comment by jcoyne** [comment]
I'm a bit concerned that if we include "version number" in this report it will be confused with the version number in argo.  These are not the same.  Is there a business case that requires this field?

**Comment by amyehodge** [comment]
@jcoyne I propose we label this field "H2 version" to help improve the clarity here. This can help when diagnosing issues caused by version mismatching, though I hope we have less of that these days. And it's helpful for us to understand how often users are actually versioning works and how many times, so it's something we have looked at in the past.

**Comment by justinlittman** [comment]
Recommend using pattern from https://github.com/sul-dlss/happy-heron/pull/2436
