### ISSUE TITLE
Create ability to generate collection report

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2310]
This is one of the options in the drop-down menu on the Admin page that is available only to administrators.

Report should include the following information in csv format for all collections in all states in H2.

- collection title
- collection id 
- collection druid when available
- state of each collection (draft, deposited, version draft, etc.) 
- version number
- SUNet ID of user who created the collection
- SUNet IDs of all current collection managers
- date created
- date last modified
- date last deposited
- release setting
- visibility setting
- license
- DOI yes/no
- review workflow

Default sort by collection title.

We also request options to restrict the results based on the following:

- range of dates created
- range of dates last modified
- range of dates last deposited
- H2 state, selected via checkboxes, multiple boxes can be checked
-- Initial draft
-- Deposited
-- Version draft
-- Decommissioned

Mockup: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/467473849

![Screen Shot 2022-06-28 at 3 18 03 PM](https://user-images.githubusercontent.com/5558511/176267820-c8ac55f6-7230-4c41-b4fd-fd3630db022c.png)

For the three date range options:
- require year, month, and day for start and end dates
- second date must be after the first date
![Screen Shot 2022-06-20 at 2 24 36 PM](https://user-images.githubusercontent.com/5558511/174659649-5fde09ed-aac5-4c12-ad8e-0adcc37aab7d.png)

**Comment by amyehodge** [comment]
@astridu has suggested an error message if no results are found because of the filters chosen. Is this possible to do? This is not a high priority, but this is what she was thinking. Same on the item report (#2309).

See: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/467473849

<img width="666" alt="report_no_results" src="https://user-images.githubusercontent.com/5558511/174659979-ca1d8826-e818-476b-86d0-82e105e26523.png">

**Comment by amyehodge** [comment]
@astridu Can you please add the "decommissioned" state to the list of options for "H2 state for collection"? Thanks.

**Comment by astridu** [comment]
<img width="672" alt="image" src="https://user-images.githubusercontent.com/42216982/184016109-5387f870-936e-4aae-9476-190812404da4.png">

**Comment by jcoyne** [comment]
@amyehodge what is a "collection work id"?

**Comment by amyehodge** [comment]
@jcoyne that is intended to be the work id assigned to a collection or does it have a different name than that? Basically, the ID for the collection that is used in the URL in a similar way that work ids for items are used.

For example, I believe the ID for the Stanford Research Data collection is 168, since it is located at https://sdr.stanford.edu/collections/168.

**Comment by jcoyne** [comment]
I've update the description to just "collection id", I think that is less confusing.

**Comment by justinlittman** [comment]
@amyehodge I'm assuming that "date last deposited" is equivalent to the `published_at` field for work versions. If so, this isn't supported for collections. Do you want this omitted? Otherwise, can you ticket this adding `published_at` for collection versions, as it is beyond the scope of this ticket?

**Comment by amyehodge** [comment]
@justinlittman  I was thinking of the piece of information that I can see on this collection page in "Last Saved."
![Screen Shot 2022-08-17 at 1 06 42 PM](https://user-images.githubusercontent.com/5558511/185200463-01623d41-26c9-41d0-91fb-6f2e139ab9e4.png)

This is on https://sdr.stanford.edu/collection_versions/302
