### ISSUE TITLE
Change owner: Add to Item view pages a function that enables a  change in item ownership

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2312]
**Background**
We need to be able support use cases where the depositor of an item no longer needs access to the item and wants another user to be able to manage it. 

This should be a "current owner" field (i.e. a new field in the database) so that we can retain the information about who the original depositor was. The "current owner" should have all the same permissions that the original depositor had with respect to that item.

The original depositor (or other previous owners) should no longer see the item on their dashboard or be able to perform any actions with the item, and they should no longer receive any email notifications about the item.

We should be able to accommodate more than one change of ownership, i.e. item is deposited by Person A, then Person B becomes the current owner, and sometime later Person C becomes the current owner.

**Comment by amyehodge** [comment]
We also want to display an error message to the user if the work ID is not found:

Work ID not found. Please try searching for another work ID number.

![Screen Shot 2022-06-15 at 12 22 54 PM](https://user-images.githubusercontent.com/5558511/173877477-193e6000-d4f3-4d0d-adea-c1d03857db62.png)

**Comment by amyehodge** [comment]
This feature will go on the item view page along with two other features. This is the what that page looks like before this feature is selected:
![image (3).png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/82b4fd90-fe2d-483a-8fd6-e59cc7ee4033)

And this is what the change owner function looks like. The admin will perform the same kind of SUNet ID search that we are using on the collection form to make sure they are entering a valid SUNet and that it is for the correct person. When they identify the correct person, they will click the Add button. And then the "change owner" button.
![image (2).png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/635cef2c-db55-43a2-aead-70d1b3184806)

**Comment by justinlittman** [comment]
All additional work related to this ticket has been split into additional tickets.
