### ISSUE TITLE
Change owner: Include "current owner" in dashboard tables

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2313]
When an item has had its ownership changed to another user, display the "current owner" of the item in tables on the dashboard page instead of the original depositor. All users should see this.

**Comment by amyehodge** [comment]
Do we need to display both the original depositor and the current owner here? If not, will listing "current owners" under "depositor" cause any confusion?

**Comment by jcoyne** [comment]
@amyehodge can you confirm that this work is already complete? See https://sdr.stanford.edu/works/5891 as an example:
![Screen Shot 2022-08-24 at 9.40.51 AM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/cff2c38c-c078-48b6-8c5c-0b509578e46f)

**Comment by amyehodge** [comment]
@jcoyne Ideally we would have a new column added between the "Depositor" and the "Last modified" column. In reality, I think real estate is likely getting very tight in this table. In that case, I think the person who now owns the item is the more important one to show, so can we have this display one column that shows the current owner if the ownership has changed or the original depositor if it hasn't (which is most of the time)? The label could perhaps be updated to "Depositor/Current owner." @astridu what do you think about this?

**Comment by jcoyne** [comment]
@amyehodge we always have an owner set. It defaults to the depositor. So we can just show the owner, without having to say "if it's different"

**Comment by amyehodge** [comment]
Great @jcoyne That's even easier. I have a question out to @andrewjbtw and @hannahfrost to see if they see any issue with this, but I think changing this column to current owner makes sense. And the label perhaps only needs to be "Owner," unless that strikes anyone as more confusing.

**Comment by jcoyne** [comment]
And just to clarify "in dashboard tables" means just the one table that shows per collection?

**Comment by amyehodge** [comment]
Yes, those tables. Changes for tables elsewhere are in other tickets.

**Comment by astridu** [comment]
Some spacing will have to be taken from each of the columns to make room for this one.
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/42216982/186565180-5986f92c-b9a4-450e-9e94-8d05478a2090.png">

**Comment by jcoyne** [comment]
@astridu Amy said "I think changing this column to current owner makes sense. And the label perhaps only needs to be "Owner," unless that strikes anyone as more confusing."

Do we want to add two columns?

**Comment by astridu** [comment]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/42216982/186573605-38730795-f4d4-47ec-9c4c-d5141b85be30.png">
