### ISSUE TITLE
Change owner: On item view page add a row for "current owner"

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2314]
On the item view page, if the ownership of the item has changed hands, include a line under the "Depositor" line with 

label: Current owner
content: SUNet ID (name) -- same as how the Depositor info is displayed.

Mockup: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/467473850

![Screen Shot 2022-06-28 at 3 12 41 PM](https://user-images.githubusercontent.com/5558511/176265737-5188c0d7-9966-4ccd-abd3-a594971c4485.png)

All users should see this.

**Comment by amyehodge** [comment]
@astridu Can you mock this up? Thanks.

**Comment by justinlittman** [comment]
@amyehodge I'm taking this to mean that "Current owner" should only be displayed when different than "Depositor". Is this correct?

**Comment by amyehodge** [comment]
@justinlittman Yes, that's right. If it's a lot easier to display it all the time though, I have no problem with that.
