### ISSUE TITLE
Change owner: On the item view page, add a row in the history log to indicate when item ownership is changed

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2315]
When the item ownership is changed, the history table should reflect this. All users should see this.

The column entries should be 
History: "Owner changed"
Modified by: [SUNet of admin making the change]
Last modified: [date/time stamp same as other entries] 
Description of changes: "owner changed from [depositor SUNet ID] to [current owner SUNet ID]"

**Comment by astridu** [comment]
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/42216982/173725670-0ddc1793-6e80-4ff1-8a43-c117e1a0ed3e.png">

**Comment by jcoyne** [comment]
@amyehodge I believe this is already complete. Do you want to check that out?

**Comment by amyehodge** [comment]
@jcoyne this is good and can be closed.
