### ISSUE TITLE
Lock editing: On dashboard, replace pencil icon with lock 

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2319]
On the dashboard, if a locked item displays in a table, the pencil icon for editing should not be displayed and should be replaced with a lock icon. This should be true for all users.

When the user clicks on the lock, they should see a tooltip that says "This deposit can no longer be edited in this application. If you need to make changes to this deposit, please use the Help link at the top of this page to contact us."

**Comment by astridu** [comment]
Lock icon: fa-solid fa-lock
