### ISSUE TITLE
What's in a name?

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/happy-heron#232]
When editing an item, a depositor may elect to add one or more authors and contributors to the work:

https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/420954309

The form currently has three fields for each person: a role field, a first name field, and a last name field. I have two questions about the name fields:

1. Should either or both be required fields? Or is it valid to have a first name w/o a last name, or a last name w/o a first name?
2. Related to the prior question, how should we be dealing with names that do not easily decompose into a first name and a last name? (See also: [falsehoods programmers believe about names](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/). This turns out to be very tricky for some cases, and I suspect we need to make a call about *how right* we want to get this, grounded in the functional requirements these fields are driving.)

Flagging for @amyehodge. We'll discuss in mid-sprint planning, so no replies needed on this issue for now.

**Comment by amyehodge** [comment]
@mjgiarlo and @astridu After talking with Arcadia and Hannah, we are going to revise this.

1. List of roles will be updated. I'll do that in the design doc.
2. We will return to one single box for all entries, not separate boxes for "first name" and "last name". This will accommodate the organizations/events, as well as the personal names. An entry in this field should be required.
3. We need the first name and last name for SW indexing, so Arcadia requests that ask for a "last name, first name" format in the box and require that a comma be present to validate they have done it this way. One issue is that "John Smith, Jr." would also validate if the presence of a comma is the only requirement, so if there any additional validations that would minimize the number of those that pass, that would be nice. I've never seen anyone enter honorifics or degrees, so perhaps just excluding versions of Jr/Junior/Sr/Senior would be adequate? If that's not too much trouble. 
4. We should have the field box show an example of a name entered in the correct format. 
4. I will update the Tooltip in the documentation to include instructions to this point. 

I'll make sure that between @astridu and I we get the wireframes and the design doc updated. Please let me know if you have any questions.

**Comment by amyehodge** [comment]
@mjgiarlo Astrid and I have completed all the updates to the wireframes and the design doc for this issue. Please let me know if you have any questions.

**Comment by mjgiarlo** [comment]
@amyehodge thanks! @jcoyne and i will revisit this the next time we scan the board for `question` issues and do board grooming.
