### ISSUE TITLE
Lock editing: On the item view page, add a row in the history log to indicate when item is locked

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2323]
When an item is locked or unlocked, the history table should reflect this. This should be viewable by all users.

The column entries should be
History | Modified by | Last modified | Description of changes
[Item locked/Item unlocked] | [SUNet of admin making the change] | [date/time stamp same as other entries] | [blank]

See: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/467473850_admin_Item_View_Lock
![Screen Shot 2022-06-20 at 2 19 47 PM](https://user-images.githubusercontent.com/5558511/174659157-344199c1-ddd0-4129-8b72-37d265422269.png)

**Comment by amyehodge** [comment]
Do we want to be able to see some kind of note about this action in the history table? If so, we need to build that into the locking/unlocking feature.

**Comment by peetucket** [comment]
Yes, my PR that implemented the lock/unlock admin feature added to the events table (which builds that history view).
