### ISSUE TITLE
Delete from H2: Create function that allows for deleting an item from H2

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2324]
This will allow admins to remove H2 database entries for items that have been decommissioned from SDR.

On the admin page, include a "Delete item from H2" option in the dropdown menu that when selected presents the user with a search box for work ID. This should look ONLY for items and not collections. User should get the error message indicated below if there is no match to an item.

Search result should return a table with the following:
- item title for item found in search, linked to item view page
- collection title, linked to collection view page
- work status (i.e. work state)
- work ID
- Item owner (SUNet of depositor or other current owner) with pencil icon

Below this table should be a check box that says "I confirm this item has been decommissioned from Argo and understand _this action can not be undone_" -- with the italic text in red.

Below this should be a Delete button and a cancel link. The delete button should be greyed out and unclickable until the check box has been checked. 

Mockup: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/467473854

![Screen Shot 2022-06-16 at 4 01 55 PM](https://user-images.githubusercontent.com/5558511/174154399-d4a89c46-7307-4119-be7f-f2289c2dc23b.png)

Also, If the work ID search does not find a match, display an error message:

Work ID not found. Please try searching for another work ID number.

https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/467797269_admin_Decommission_Error
![Screen Shot 2022-06-20 at 2 16 19 PM](https://user-images.githubusercontent.com/5558511/174658712-c63927c1-772d-4628-91a3-4907d985ab23.png)

**Comment by amyehodge** [comment]
Is there a log somewhere that tracks when things are deleted? If so, it would be good to be able to see that list here with work title, work id, druid, date deleted and by whom.

**Comment by amyehodge** [comment]
Do we need this functionality for collections as well? If so, do we need further safeguards in place for that? 

If not, what happens in the above scenario when a work id matches a collection work id?

**Comment by amyehodge** [comment]
We had a request in June to remove an item for Kris K. I deferred doing it then so we could use it as a test case when this is implemented. See https://jirasul.stanford.edu/jira/browse/SDRSUPPORT-218.

**Comment by amyehodge** [comment]
Requests to remove collections happen infrequently, and requires a few more safeguards. After talking with Hannah we have decided we will implement this only for items.

**Comment by andrewjbtw** [comment]
If we're not going to delete collections, we should transfer ownership at least when someone makes a delete/decommission request.

**Comment by amyehodge** [comment]
> 

@andrewjbtw  That sounds like a completely reasonable workflow. I'm thinking it should be transferred to someone like you, me, or Hannah? Or do you think that deleting collections would be relatively straightforward and should be included? We need to figure out how to handle it when there are items in the collection. Perhaps we could allow the deletion of empty collections only?

**Comment by andrewjbtw** [comment]
Only allowing deletion on an empty collection is definitely a good validation to have. I'm imagining a few scenarios - some of which have already happened in the past:

1. Someone makes a collection and decided not to use it - no items in the collection

2. Someone makes a collection and deposits items, but then has legitimate reasons to remove all of it

In this case, I think we should remove the items first, leaving a collection with no items.

3. Someone makes a collection and deposits items, then decided all items should move to a different collection

In this case, once the items are moved to a different collection, it would leave an empty collection.

So in each of the cases, I think we'd end up with an empty collection before deleting the collection.

**Comment by amyehodge** [comment]
Replaced by #2375
