### ISSUE TITLE
Display recent activity for items on Admin page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2325]
THIS IS ONLY FOR ITEMS ACTIVITY; FOR COLLECTIONS ACTIVITY SEE #2446

This table should display all the time on the admin page that is accessible only to administrators, under the dropdown menu for the other functionality.

Mockup: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/467473848

![Screen Shot 2022-06-16 at 3 53 45 PM](https://user-images.githubusercontent.com/5558511/174153237-3b929442-c8a0-46ef-8fe9-4f585727650c.png)

After the table header it should indicate the three available options of recent activity for last "7 days | 14 days | 30 days."

Types of activity to be included in the items table:
- updated by user
- submitted for review
- submitted for deposit
- deposit completed
- item locked
- item unlocked
- item decommissioned
- ownership changed

This table should be collapsible, and it should be collapsed by default.

Item table should include the following columns:
- item title, linked to item view page
- collection title, linked to collection view page
- type of activity
- date/time of activity

**Comment by justinlittman** [comment]
Where is this recent activity supposed to come from? My assumption was events, but these are the only events that I see:
```
h2=> select distinct event_type from events;
    event_type
-------------------
 type_selected
 submit_for_review
 begin_deposit
 embargo_lifted
 settings_updated
 pid_assigned
 deposit_complete
 update_metadata
 reserve_purl
 reject
```

Should we only display these events? Add new events? Different source of data?

**Comment by amyehodge** [comment]
@justinlittman These events are ones we are already tracking in the history table, so I was assuming they would be easy to identify for this purpose as well. This is the text displayed in the history to the user; I don't know for sure which events in your list these correspond to:

For collections:
- updated by user
- submitted for deposit
- deposit completed

For items:
- updated by user
- submitted for review
- submitted for deposit
- deposit completed


On the other hand, the following are things being added this work cycle that I'm guessing will require new event_types:

For collections:
- item decommissioned

Types of activity to be included in the items table:
- item locked
- item unlocked
- item decommissioned
- ownership changed
