### ISSUE TITLE
Email notification: Admin notification of new collection

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2326]
Send an email to h2-administrators@lists.stanford.edu when a user starts a new collection. See https://docs.google.com/document/d/1TZVILUrORI25kRZyUZ70vMQYo90Ngp_tqCI7BdU_VyQ/edit#heading=h.ktttnwfwffk7

Subject: A new collection has been created
Body: 

Dear Administrator,

The following new collection has been created in H2:

[collection.name] [linked to the collection details page]
Created by [depositor’s preferred name] 

The Stanford Digital Repository Team

**Comment by amyehodge** [comment]
How exactly does the admin role differ from other users? Should we send this message to all other admins or perhaps that includes too many people? Amy and Hannah want to get this.

**Comment by amyehodge** [comment]
I have requested a new email list and will update the ticket when it is confirmed.

**Comment by ndushay** [comment]
@amyehodge would this be when the new user starts a first draft, when they move from draft to depositing, or when the deposit is complete?

**Comment by amyehodge** [comment]
@ndushay This should be when the user starts the first draft.
