### ISSUE TITLE
Admin page breadcrumbs

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2327]
The breadcrumb for the main admin page should say "Dashboard > Admin dashboard". 

If the user chooses a function from the drop-down menu, the breadcrumbs should say "Dashboard > Admin dashboard > [function selected]"

That list of functions is
- Search druid
- Search SUNet ID
- Generate item report
- Generate collection report
- Change item owner
- Lock item
- Decommission item

![Screen Shot 2022-06-16 at 4 38 10 PM](https://user-images.githubusercontent.com/5558511/174159535-099b02a5-2897-404f-a53d-dcb6cf6b6011.png)

**Comment by amyehodge** [comment]
@jcoyne I'm not sure if we need a separate ticket for this, but the sake of completeness, I've made one. It will at least remind me to check that these exist and work properly.

**Comment by peetucket** [comment]
We don't have many admin functions yet, but I'll get the plumbing setup for the breadcrumbs to be added easily as we put functions in.
