### ISSUE TITLE
Change owner: Once function to change item ownership is implemented, update email notifications to go to current owner and not original depositor

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2328]
Once we have items that have both an original depositor and a current owner, all email notifications that are set to go to the depositors should go to the current owner.

**Comment by amyehodge** [comment]
@jcoyne Do we need this ticket to make sure that these emails get directed to the right person? I'm happy to leave it here as a reminder for us to check this is happening properly once this feature is in place, even if nothing actually needs to be done.

**Comment by jcoyne** [comment]
@amyehodge I think this is already complete. Can you review and ensure it is so?

**Comment by amyehodge** [comment]
I realized I can't check email notifications in stage, so I'll double-check this when it goes to production. This is fine to close.

**Comment by amyehodge** [comment]
@jocyne I'm closing this and will check the email once it gets to production, since emails are off in stage.
