### ISSUE TITLE
Globus: Allow user to designate that files have been uploaded to Globus 

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2349]
**Please release this to production with #2351**

1. Add an option to the file upload section where instead of uploading files, depositor can select an option that says "I have uploaded my files to a Globus endpoint provided to me by SDR staff." Subtext here should read: "Do not check this box unless you have already discussed this with SDR staff."
2. Depositor will then be prevented from uploading files.
3. A placeholder file will be attached to the deposit (does not need to be displayed to user, and probably shouldn't be to avoid confusion)
4. Depositor clicks "Deposit" button to complete the deposit.
5. Notification is sent to Admins that a Globus-related deposit has been completed. (Notification to be ticketed separately.)

**Background**
We have some users depositing large files who misunderstand what they need to do regarding the files in H2. The current workflow is that they provide the metadata, do not upload files, and leave the item in a draft state. Andrew then attaches a placeholder file, deposits the item via H2, and completes accessioning the files outside of H2.
 
Some users don’t understand they should not upload any of the files and still try to upload the smaller ones, some users get confused that they can’t click deposit (even though we told them not to), and we would prefer if they could do the deposit themselves, as this is more appropriate than having Andrew do it.
 
**The new option**
I’d like to add an option in the file upload section of the item deposit form that says something like “I have uploaded my files to a Globus endpoint provided to me by SDR staff.” If this option is selected the user should NOT be allowed to upload any files to the item. Instead, a placeholder file will be attached to the item. I actually think the user doesn’t need to know about this file because I think it will confuse them, but we could discuss that point. The user would then be able to deposit the item. After which, Andrew can complete the accessioning using the files on Globus and lock the item for future editing (assuming we get that feature built in this work cycle).
 
Benefits of this are that 1) the user can’t upload files when they shouldn’t but 2) they can still deposit the item, eliminating both of those points of confusion. And 3) Andrew does not need to deposit the item or manually attach a placeholder file.

**Comment by amyehodge** [comment]
See also #2351 for the email notification related to this feature.

**Comment by astridu** [comment]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/42216982/176979310-d23e010d-5987-4090-a6f7-0f68705438b8.png">
