### ISSUE TITLE
Prevent user from choosing "approximate" option for creation date when a day is entered

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2358]
If the depositor enters a value in the "day" field for either a single creation date or a creation date range, do not allow them to also select the "approximate" check box. 

For example, if they enter "2020 November" they can select to add "approximate" to this date, but if they enter "2020 November 12" they can't select "approximate." 

Note that the two ends of the date range should function independently, so that if one end has a day then that end of the range can't be approximate, but if the other end is just a year or a year/month then that end of the range can be approximate.

**Comment by amyehodge** [comment]
@astridu Could you mock this up please?

Do you think this needs a message next to/under the "Approximate" text that tells the user this option is not valid when a day is entered? I'm not sure that's needed or will fit comfortably. I leave it to you.

**Comment by jcoyne** [comment]
@amyehodge can you explain the need for this?  The EDTF metadata format certainly allows for full dates to be approximate or uncertain:

> Qualification of a date (complete)
>
> The characters '?', '~' and '%' are used to mean "uncertain", "approximate", and "uncertain" as well as "approximate", respectively. These characters may occur only at the end of the date string and apply to the entire date.
>
 >   Example 1             '1984?'             year uncertain (possibly the year 1984, but not definitely)
 >  Example 2              '2004-06~''       year-month approximate
 >  Example 3        '2004-06-11%'          entire date (year-month-day) uncertain and approximate



https://www.loc.gov/standards/datetime/

**Comment by jcoyne** [comment]
@amyehodge @arcadiafalcone should this sort of validation, be present across the whole repository or only for H2 users?  The phrase "finding and using the content" makes me wonder if this is broader than just H2.

**Comment by arcadiafalcone** [comment]
I would say only for H2 users - there might be legitimate reasons for a cataloger to do this, but for a non-cataloger it's almost certainly an error.

**Comment by astridu** [comment]
So sorry, I forgot to put the mockup in here. If user enters the day, then the checkbox is disabled.
<img width="673" alt="image" src="https://user-images.githubusercontent.com/42216982/179897037-bf97b342-1300-4486-9a11-34dccd45dd48.png">
