### ISSUE TITLE
Reset work 5328 to first deposited version

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2361]
The depositor tried to modify this item after cataloging was done and a catkey assigned, so this got hung up in the "depositing..." state.  Please reset this item back to the first deposited version if possible and stop the spinning. 

The depositor needed to correct a misspelling, which I have directed him to request a fix for by his cataloger elsewhere so that the SDR record is properly updated.

**Comment by jcoyne** [comment]
This is druid: [yn200hw8896](https://purl.stanford.edu/yn200hw8896)

**Comment by amyehodge** [comment]
Looks good. Thanks.
