### ISSUE TITLE
Rename webauth login path

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/happy-heron#2364]
see https://github.com/sul-dlss/SearchWorks/issues/1649

- [ ] make changes in puppet to add new path at `/sso/login`
- [ ] change route in the app to `/sso/login` and deploy it
- [ ] remove old `/webauth/login` path in puppet

affected boxes:
- sul-h2-qa
- sul-h2-stage
- sul-h2-prod

**Comment by jcoyne** [comment]
@thatbudakguy can you explain why this is necessary? The original ticket isn't relevant because unlike searchworks this project was never using the legacy webauth authentication.

**Comment by thatbudakguy** [comment]
then it's not necessary! my bad.

i saw that there's [a path named /webauth/](https://github.com/sul-dlss/puppet/blob/58ff6ee1081ce2f3eaf39395ac5665fb61492404/hieradata/node/sul-h2-prod.stanford.edu.eyaml#L211-L217) in the puppet configs for this project, and so assumed it might have once used webauth.
