### ISSUE TITLE
Prevent error when user attempts to set embargo date for the future on the day that the embargo has already been lifted.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2366]
HB error: https://app.honeybadger.io/projects/77112/faults/80837103
There is a previous discussion on this error in the #dlss-infrastructure slack channel if you search for that link.

I have successfully recreated this error. In a nutshell, it seems to me like there is confusion when modifications are made on **the day the embargo is released** because the form still displays the embargo date instead of showing that it has been released. Today's date won't validate, because it's not in the future, but you can't change this to a future date because the item has already been released. Attempting to do so will trigger the error message.

Here are the steps I took. 

- I created new item https://sdr.stanford.edu/works/5764 (druid:wn318vm7113) on 7-25-2022 and assigned it an embargo date of 7-26-2022. 
- On 7-26-2022, I checked to see that the embargo had been lifted. The history indicated that it had been. 
![Screen Shot 2022-07-26 at 10 10 01 AM](https://user-images.githubusercontent.com/5558511/181026781-2e122742-bb8c-4e69-8c03-de17bdcdcf51.png)
- I then clicked the pencil icon to edit the item. I entered a note in the "What's changing?" box at the top, then modified the abstract. Note that the section for the embargo showed that the embargo date was today, though the history said the embargo had been lifted:
![Screen Shot 2022-07-26 at 10 03 01 AM](https://user-images.githubusercontent.com/5558511/181027029-2847c5cb-2e76-4b7f-b368-677af75e6ac7.png)
- When I clicked "Deposit", I got the same message as the user below -- the validations ran and it told me that the embargo date must be in the future. 
- I then changed the embargo date to **tomorrow**, and then clicked "Deposit" again. 
- I then got the blank page with the "That wasn't supposed to happen" error message. 
- I think I then clicked back on the browser (maybe I refreshed? I don't think this is critical) and the view page for the item reloaded.
- I clicked the pencil icon again, made a note at the top about the changes, then changed the embargo option to "immediate" release.
- I clicked "deposit" and it completed just fine.
- When I re-open the form the release information displays like this and the user can't make changes:
![Screen Shot 2022-07-26 at 10 15 53 AM](https://user-images.githubusercontent.com/5558511/181028137-3a81ad4d-9991-46a3-86f7-55b7f58f0961.png)

**Comment by amyehodge** [comment]
Another user encountered this error on 7-20-2022. She was able to complete her deposit. Below are the details she reported about what happened. I generally followed the first part of this to recreate my error above.

“Sure, I removed the DOI sentence from the abstract, added what I changed, and submitted it. It told me that the embargo date must be in the future. I changed the embargo date and resubmitted, then the oops error appeared. I refreshed the browser and started over. This time I changed the abstract and embargo date. I forgot to describe what I had changed. It told me that I had to add that information. I did, and then successfully resubmitted with confirmation on the webpage and a subsequent email message. It seems that the glitch occurs when someone tries to make changes while the embargo date is not in the future. I hope this helps. By the way, this is a great service and so important for research! Cheers Cindy”

**Comment by lwrubel** [comment]
@amyehodge would the desired behavior here be that when the embargo is today, and therefore the item has been released, that the embargo date is no longer editable and it reflects instead that it's been released?
![Screen Shot 2022-08-03 at 9 00 48 AM](https://user-images.githubusercontent.com/1619369/182614423-c2e9d788-6d23-4a2a-a53c-dfa38f3c3d9a.png)

(And then the user can carry on with editing metadata.)

**Comment by amyehodge** [comment]
Yes, @lwrubel that's exactly right.
