### ISSUE TITLE
Adjust links in header to add spaces

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2372]
There should be some spacing between the words and the dots in this section of the header. There used to be spaces, but somehow they've all gotten smashed together.

![Screen Shot 2022-08-01 at 6 01 41 PM](https://user-images.githubusercontent.com/5558511/182253426-c62202c9-bd02-4b57-b45a-8799330098ba.png)

**Comment by jcoyne** [comment]
<img width="545" alt="Screen Shot 2022-08-01 at 5 06 54 PM" src="https://user-images.githubusercontent.com/92044/182254015-7a31e00e-ed4b-4bb5-9bc5-9ffdf01871a0.png">
It looks like bootstrap is not setting `--bs-nav-link-padding-x`
