### ISSUE TITLE
Images should display in notification email headers

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2374]
Proper display for email notifications from H2 should look like this:
<img width="576" alt="Screen Shot 2022-08-02 at 12 37 34 PM" src="https://user-images.githubusercontent.com/5558511/182447394-fbd3ce6b-5b93-42a8-aa74-34d27f4a53b1.png">

I'm using Outlook desktop client for Mac and I see this:
<img width="629" alt="Screen Shot 2022-08-02 at 12 37 15 PM" src="https://user-images.githubusercontent.com/5558511/182447325-683989b7-20b4-4d97-b26e-c58bd857d3bd.png">

When I use the Outlook web app in Chrome I see this wrong display:
![Screen Shot 2022-08-02 at 2 26 48 PM](https://user-images.githubusercontent.com/5558511/182447429-27aa0248-072f-40db-9889-25c91f9dbc91.png)

We had some issues with this early on but this has been working smoothly for months and worked as recently as July 30, 2022.

**Comment by jcoyne** [comment]
It looks to me like it's sending a local file path:
<img width="986" alt="Screen Shot 2022-08-02 at 5 03 09 PM" src="https://user-images.githubusercontent.com/92044/182481443-a9e74a15-99d5-4438-bb5f-6b63ce0dc9d9.png">
