### ISSUE TITLE
Decommission: Create method to decommission H2 items

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#2375]
Currently, decommissioning items that were deposited via H2 requires:

1. The "normal" decommission process, carried out via Argo
2. Extra steps to delete from H2, which requires updating the H2 database directly

For the upcoming workcycle, we'd like to make the H2 steps a function available in the web UI to H2 administrators. It is not a requirement to connect the H2 steps with the Argo steps (which are standard for any SDR content regardless of source).

**Proposal**

Implement decomissioning as a "soft delete":

- Lock item to prevent future edits
- Change ownership to an H2 admin so original depositor no longer has it on their dashboard
- Remove from collection (open question: does this mean item needs to move to a decommission/"graveyard" collection)?
- Do a regular delete of the files

Advantages of the soft delete approach:

- Retains a record of decommissioned items
- Potential to run reports on decommissioned items as an H2 admin

**Comment by andrewjbtw** [comment]
Adding the collection use case:

Collections should also be decommissionable following the same process with one important distinction: a collection must be empty before it can be decommissioned. If the collection has any objects, those objects must be moved to a new collection or decommissioned themselves before the collection can be decommissioned.

**Comment by amyehodge** [comment]
We do not need to create a "graveyard" collection for these, as we can find them via the item and collection reports.

**Comment by andrewjbtw** [comment]
The question for me is how to approach decommissioning a collection. If the collection has to be empty, the items have to go to some other collection, unless we allow decommissioned items to exist without a collection. 

But we could allow decommissioning a collection that has items in it, provided the items have been decommissioned first.

**Comment by amyehodge** [comment]
@andrewjbtw I suggest we let the decommissioned items exist in H2 without a collection, and then as you suggested allow the decommissioning of a collection as long as all the items have been decommissioned first.

**Comment by justinlittman** [comment]
Where/how is this supposed to go in the UI?

**Comment by amyehodge** [comment]
@justinlittman, this is the bit of design work that is in progress right now. We are planning to put it on the item view pages along with lock/unlock and change owner functions.

**Comment by amyehodge** [comment]
This feature will go on the item view page along with two other features. This is the what that page looks like before this feature is selected:
![image (3).png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/82b4fd90-fe2d-483a-8fd6-e59cc7ee4033)

And this is what the decommission function looks like. The checkbox must be checked before the button can be clicked:
![image (1).png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/49e4f5bf-3776-4521-adb0-692b4da270db)

**Comment by jcoyne** [comment]
Note to developers: Decommissioned should be a state in the state machine and you can "decommission" (event) from any state.
