### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#2384]
The spec/features/mediated_deposit_versioning_spec.rb often fails on CI. Figure out why and fix the problem

**Comment by justinlittman** [comment]
Here's an example: https://app.circleci.com/pipelines/github/sul-dlss/happy-heron/4190/workflows/03ea1005-5a66-4b7b-b1f4-8282d60982da/jobs/15847

**Comment by justinlittman** [comment]
When it fails:
![screenshot_2022-08-15-05-15-22 830](https://user-images.githubusercontent.com/588335/184636295-7ea4cc32-b617-4f30-b3fb-7c871c9825eb.png)

**Comment by justinlittman** [comment]
When it doesn't fail:
![screenshot](https://user-images.githubusercontent.com/588335/184636330-2965f49a-08d5-45dc-8856-96ce0d0c610d.png)

**Comment by justinlittman** [comment]
The failure occurs in the code right after switching from depositor to reviewer. When it fails, it appears that the user is NOT signed in as the reviewer.

I will try adding an explicit sign out to see if it helps.

**Comment by justinlittman** [comment]
![image.png](https://images.zenhubusercontent.com/5d8270f64def500001d12f23/d2580ae4-0073-4963-9755-4f53cca57eed)
