### ISSUE TITLE
Map contributors into cocina model

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/happy-heron#240]
When done, you should see any authors and contributors added for a work mapped into descMD in Argo, with the proper role term specified.

See [mapping](https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_name.txt#L168-L199)

May require upstream mapping work, not sure. Test in QA.

**Comment by ndushay** [comment]
See also https://docs.google.com/spreadsheets/d/1CvEd_NODprNhM2D9VfvJBFs1jfAMEUr0kDxXHe2HkL4/edit#gid=435507816 for more information on role mappings.

**Comment by ndushay** [comment]
- [ ] tests
- [ ] generates model but it doesn't go through to argo (!)

**Comment by ndushay** [comment]
PR #496 covers everything **except** for order, which @jcoyne and @arcadiafalcone.   I propose to close this issue after PR #496 is merged, and that we have a new one opened for any order mappings needed for contributors for H2. 

Note that the contributor_generator_spec  does have some comments about order per Arcadia's mapping at this time.

**Comment by ndushay** [comment]
This is from the h2 infrastructure-integration test run yesterday, so we're looking good:

![image](https://user-images.githubusercontent.com/96775/99572507-a034b800-2989-11eb-96b2-09b2c94d38de.png)

**Comment by ndushay** [comment]
looking better!  marcrelator role only:

![image](https://user-images.githubusercontent.com/96775/99845670-e163ce00-2b29-11eb-8b8e-61b1b47e3c3a.png)

**Comment by ndushay** [comment]
### From this in H2:

![image](https://user-images.githubusercontent.com/96775/99846442-289e8e80-2b2b-11eb-89b9-a03a57707e1e.png)

### To this MODS in Argo

**Comment by ndushay** [comment]
I'm calling contributor mappings from H2 to cocina done.  @amyehodge @arcadiafalcone Just notifying you of this fact.
