### ISSUE TITLE
Add "work on app in progress" banner to home page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2400]
Add a banner to sdr.stanford.edu alerting people that we are currently working on the application. 

This banner will need to be removed when the work cycle is finished.

**Comment by astridu** [comment]
@amyehodge The forklift icon is not free, but the wrench is. What do you think?
wrench: <i class="fa-solid fa-screwdriver-wrench"></i>
![image](https://user-images.githubusercontent.com/42216982/184790118-77342538-c6c1-4c65-91d5-df20f5d421c9.png)

**Comment by amyehodge** [comment]
@astridu I like this one better, actually. Thanks!

**Comment by amyehodge** [comment]
@astridu Do you have the details on where to get the icon?

**Comment by jcoyne** [comment]
I'd urge you to reconsider this request.  Here are a couple of concerns I have:
1. This is going to make people nervous and there's little they can do about it.  It may drive people away from using the site.
2.  It's pretty normal that software is changed and improved and vague announcements that things are going to change are not necessary or helpful. Most software now has automatic updates turned on by default.  This reminds me of the eternally displayed "Under construction" banners that were fashionable 20 years ago (http://textfiles.com/underconstruction/).
3. This is going to be a fair amount of work to ensure this banner is in the right spot and doesn't break the existing layout.  

Questions I have:

What color yellow?  Which pages should this banner display on?

**Comment by astridu** [comment]
Yellow: FFE781
Wrench is a fontawesome icon: i class="fa-solid fa-screwdriver-wrench"

I thought this was just going on the homepage? I put it in the same spot as the banner that you see when you log out.

**Comment by jcoyne** [comment]
devs: FFE781 = "Illuminating-light" https://identity.stanford.edu/design-elements/color/accent-colors/

**Comment by amyehodge** [comment]
I've decided to pass on doing this.
