### ISSUE TITLE
Record the name of the user depositing collection in the history table

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2402]
I edited the metadata on this collection and it shows my name for the "updated by user" and "submitted for deposit" lines but then inserted the name of the collection creator for "deposit completed." This should have had my SUNet ID as I was the person who was making the changes.

This was on https://sdr.stanford.edu/collections/199

![Screen Shot 2022-08-10 at 12 46 50 PM](https://user-images.githubusercontent.com/5558511/184027693-5006bc98-85c2-470d-9cac-63d13d39624c.png)

**Comment by justinlittman** [comment]
Based on my reading of the code, I believe that the "modified by" comes from the collection's creator; the collection version does not have a creator attribute.

To handle this situation, a creator will have to be added to the collection version.

**Comment by jcoyne** [comment]
@justinlittman sounds good.

**Comment by jcoyne** [comment]
@justinlittman is it not possible to get the user from the event context on the collection?

**Comment by justinlittman** [comment]
I think that is where it is currently coming from. However, in @amyehodge's scenario the collection version creator is different than the collection creator.

**Comment by amyehodge** [comment]
@justinlittman that's right -- the person creating the new version is not necessarily the person who created the collection originally.

**Comment by jcoyne** [comment]
@amyehodge Would it be possible that we leave off the "Modifed by"  or set it to "SDR" in this case? The actor is the SDR system, not the person who submitted for deposit.

**Comment by amyehodge** [comment]
@jcoyne Since the "updated by user" and "submitted for deposit" rows have the correct user on them, I think it's okay if we don't get the SUNet ID on the "Deposit completed" row. Let's use "SDR," because I'm afraid leaving it blank would look like something is wrong/missing. Thanks.
