### ISSUE TITLE
Map work types & subtypes to cocina model 

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/happy-heron#241]
**NOTE**: check with Arcadia to ensure the mappings are finished before starting work on this issue.

When done, you should see the work type and subtype mapped into descMD in Argo.

See [mapping](https://docs.google.com/spreadsheets/d/1EiGgVqtb6PUJE2cI_jhqnAoiQkiwZtar4tF7NHwSMz8/edit#gid=0). Note that for types and subtypes, there are mappings into `genre` and `typeOfResource`.

See https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/d70470ae9d126dd72d30bb227dbd117ede7feacb/h2_cocina_mappings/h2_to_cocina_form.txt

May require upstream mapping work, not sure. Test in QA.

**Comment by arcadiafalcone** [comment]
Updated mapping now at https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/h2_cocina_mappings/h2_to_cocina_form.txt.

**Comment by mjgiarlo** [comment]
@arcadiafalcone H2 will also allow a user to select an `Other` type with one or more arbitrary, free-text subtypes. How should we map those? I'll start on the known mappings for now. That'll keep me busy until tomorrow!
