### ISSUE TITLE
Record terms of deposit acceptance time in database at user level

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/happy-heron#243]
once recorded, ToD checkbox on work edit form renders as already checked if its been less than 1 year since they last checked it manually

**Comment by amyehodge** [comment]
@jcoyne Can we put this one in the ready column? Is there something blocking our ability to implement this? Thanks.

**Comment by jcoyne** [comment]
There is nothing stopping this from being worked on.

**Comment by peetucket** [comment]
I think this is actually done.  I verified on localhost.  The existing column name on the `work_versions` table is called `agree_to_terms`

**Comment by amyehodge** [comment]
@peetucket Did you see @mjgiarlo 's note above -- I'm not seeing this rendered as already checked.

**Comment by peetucket** [comment]
huh, it showed as checked for me in a draft work after i checked it and saved the draft, and then came back to edit the draft (on localhost anyway on the main branch)

**Comment by mjgiarlo** [comment]
As I understood it, this issue is about changing ToD acceptance from a work- (or work version-) specific implementation to a user-specific implementation.

**Comment by amyehodge** [comment]
@mjgiarlo That's right. Though to clarify, you should see the box there, but it would be checked.

Once a year is the time we have currently in Hydrus I think and that works fine, so I'd say go with that.

Thanks, @mjgiarlo. Didn't mean to pull you away from other things!

**Comment by mjgiarlo** [comment]
> @mjgiarlo That's right. Though to clarify, you should see the box there, but it would be checked.

Ah yes, thank you!
 
> Once a year is the time we have currently in Hydrus I think and that works fine, so I'd say go with that.

That sounds reasonable to me, too.
 
> Thanks, @mjgiarlo. Didn't mean to pull you away from other things!

np!

**Comment by peetucket** [comment]
Ah, I see.  

Does this require a new user level setting somewhere (like the home page) to indicate this overall acceptance?  Or do we use the first work acceptance for a user as a way to set this?  In other words, when I create my work first and check the existing box, this gets stored at the user level for the next year so that each new work now defaults to checked.  Then after a year, it gets toggled back to off by default, forcing me to re-accept the next time I create a new work?

**Comment by amyehodge** [comment]
Yes, that's how it works currently. There isn't a user level setting anywhere else.
