### ISSUE TITLE
Change owner: When owner changes original depositor should no longer be able to see or modify the item

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2461]
The original depositor (or other previous owners) should no longer see the item on their dashboard or be able to perform any actions with the item, and they should no longer receive any email notifications about the item.

@justinlittman asked me to separate this piece out from #2312

I have also made a ticket to add the user to the depositor list for the collection (#2329). And to have the collection manager notified about the ownership change and the addition of the new person to the collection (#2331).

**Comment by jcoyne** [comment]
@amyehodge I believe this may be done already. Do you want to test that this is the case?

**Comment by amyehodge** [comment]
@jcoyne This is good and can be closed.
