### ISSUE TITLE
Create a user profile page where managers and reviewers can manage email notifications they receive

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2510]
We have heard from some managers and reviewers that not all people in these roles are always involved in all the day-to-day of the collection management and do not want to receive all the emails.

We want to add a user profile icon (or image if possible, see #2577) to the main dashboard **for managers and reviewers only** that takes them to a profile page.

![Screen Shot 2022-09-07 at 3.12.27 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/c6885ba5-dd42-4a3a-b8a6-1c083e4328d1)

This page will display a "Communication preferences" table of the collections for which they are a manager and/or reviewer. This is the only thing on this page for now.  See image below.

Next to each collection title will be a pencil icon that will let them turn on or off individual email notifications for that collection.

![Screen Shot 2022-09-07 at 3.13.39 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/9e94a588-11f1-4065-9b9b-59086f29fcf5)

Users listed as a manager OR as a manager and a reviewer on the collection will see this when they click the pencil:

![image.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/b9313363-da3e-4090-93e7-56eb0fbf30d8)

Users listed as only a reviewer on the collection will see this when they click the pencil:

![image (1).png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/8727079c-6df9-4a05-9719-b407dffdfa7f)

- All boxes should be checked by default
- The first option at the top should by default be "Deselect all". Checking this box will deselect all the other boxes.
- If all boxes are unchecked, the option the top should be "Select all". Checking this box will select all the other boxes
- Users can uncheck individual boxes to prevent sending of the emails or check the boxes to allow sending.
- Clicking "Cancel" should return the user to the previous list of collections for managing notifications without making any changes.
- Clicking "Save" should return the user to the previous list of collections for managing notifications and should save the changes.
- Any email notifications not on these lists should always be sent, i.e. user can't turn them off

**Comment by amyehodge** [comment]
@astridu Can you please provide 1) the icon image for when there is no photo (or if we don't get photos at all) and 2) the text that would be read in place of an icon for text only users? Thanks.

**Comment by astridu** [comment]
If no photo available, use:
fontawesome icon: fa-solid fa-circle-user

alt text: User profile icon

**Comment by astridu** [comment]
Amy took a screenshot of the page Justin created. Looks fine, just 2 comments:
1. Can we put a 'select all' checkbox at the top of the list?
2. The font size for the page title, collection, and 'Receive an email when...' all look a little big. Could we use the same size we are using on the other pages?TY!

**Comment by jcoyne** [comment]
Select all is #2707. Can you specify if which sizes you want? I'm just using h1 & h2 which is pretty good from an accessibility perspective as it shows they are headings at different levels of nesting.

**Comment by astridu** [comment]
Is Comm Prefs = H1 and collection name = H2? What is 'Receive an email when...'? Is that H3? 

<img width="549" alt="image" src="https://user-images.githubusercontent.com/42216982/190703144-af73594b-cabe-4322-9cb6-604d9fa84508.png">
