### ISSUE TITLE
Update error text for duplicate keyword entry

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2518]
The error text here should read: 
Each keyword must be unique. Enter a different keyword.

It currently says something else.

**Comment by ndushay** [comment]
this?

![image](https://user-images.githubusercontent.com/96775/187542843-2ffb0144-4abe-49e5-b221-7426488f8f81.png)

(which, btw, you can hit enter and it gets saved in draft)

![image](https://user-images.githubusercontent.com/96775/187542965-7f9b8cad-8a7e-42d9-9ce0-59372759c2fb.png)

Or this:

![image](https://user-images.githubusercontent.com/96775/187543124-2ff9ea29-4195-4a62-97a7-050ec205ae8a.png)

**Comment by amyehodge** [comment]
@ndushay I actually thought we'd turned off all of those big ugly error blocks at the top of the page and only had the inline ones on the page. I was talking about this one:
![Screen Shot 2022-08-30 at 5 07 14 PM](https://user-images.githubusercontent.com/5558511/187543356-68544ef9-02ce-4beb-ae47-da3745b0eca4.png)

**Comment by ndushay** [comment]
@amyehodge JCoyne rightly asks if we are still giving an error message when the field is empty.  How is this:

"Keyword must be filled in and each keyword must be unique. Enter a different keyword."

**Comment by ndushay** [comment]
![image](https://user-images.githubusercontent.com/96775/187546336-429eb12f-85fd-4d2d-a61b-8c4a79addbcc.png)
