### ISSUE TITLE
Collection version stuck trying to deposit

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2533]
Collection manager tried to update https://sdr.stanford.edu/collections/155 with a related link. This item is now stuck. 

I did notice that in H2 it says v5, but we are only on v3 in Argo. AND Argo still says "updated via sdr-api" for its most recent version, so my guess is we have a version sync problem going on.

Can someone take a look at this? Thanks.

**Comment by andrewjbtw** [comment]
Looking at the history in H2, I'm not sure how it got to v5. There is a "submitted for deposit" that succeeded yesterday, which must be v3 and then another "submitted for deposit" that I would guess should have been v4 and not yet v5.

**Comment by andrewjbtw** [comment]
This is the error for trying to update with a version 5: https://app.honeybadger.io/projects/67994/faults/87722839

**Comment by amyehodge** [comment]
@andrewjbtw @jcoyne So, I was just looking at bz714qy3272, which is an item I updated recently. It was our test item for the DOI migration. After I versioned it, it appears to have been versioned again, 10 minutes later. 

H2 now shows this item on v3:
https://sdr.stanford.edu/works/5860

![Screen Shot 2022-08-29 at 4.25.57 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/52884007-4e19-476e-92f7-1ad9ba902a1d)

While argo shows this item on v4. 

![Screen Shot 2022-08-29 at 4.26.03 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/730a52d8-557c-4950-9528-b8d8762b2b13)

So maybe this version mismatch is caused by something else that affected more than this item?

**Comment by jcoyne** [comment]
@amyehodge bz714qy3272 looks like maybe we had two sets of workers working on depositing this, possibly using different versions of code because one shows the message you typed in and the other shows "Update via sdr-api"...  Unless we see this again, I don't know how to diagnose this.   

I'm not sure that one has anything to do with the problem exhibited by https://argo.stanford.edu/view/jd276dz9994 (the collection this ticket is about)

**Comment by amyehodge** [comment]
@jcoyne I'll keep an eye out for the issue with bz714qy3272 to repeat itself somewhere. In the meantime, is there a path forward for fixing collection jd276dz9994 for this user?

**Comment by jcoyne** [comment]
```
col = Collection.find(155)
col.collection_versions.pluck(:version, :created_at)
 =>
[[3, Fri, 26 Jul 2013 16:03:51.523000000 UTC +00:00],
 [5, Sun, 28 Aug 2022 23:09:51.745250000 UTC +00:00],
 [4, Sun, 28 Aug 2022 19:05:19.740042000 UTC +00:00]]
```

So, this looks like the version number maybe was off by one:
![Screen Shot 2022-08-30 at 10.41.19 AM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/e372d625-7107-4066-828c-87b501586f34)

I'm going to decrement all the h2 versions for this object by 1.
