### ISSUE TITLE
Clarify history table entry when item state is updated due to review workflow changes

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2534]
See #2455

When this happens:

> When turning off review workflow alter the state to "version_draft" for any work_version in the collection that is currently "pending_approval" or "rejected".

The history table does not have an intelligible to the user entry

![Screen Shot 2022-08-29 at 4.01.49 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/2be294f1-a2ad-4968-a6dd-aeb3cb752b20)

**Comment by justinlittman** [comment]
What should the history entry be? Does `no_review_workflow` just need a label?

**Comment by amyehodge** [comment]
@justinlittman Yes, no_review_workflow needs a label.

I would suggest "review no longer required".
