### ISSUE TITLE
Simplify recent activity tables for items and collections

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2567]
After seeing what these look like with the actual production data, @hannahfrost, @andrewjbtw and I have agreed that they are a bit too busy to be as useful as they could be. We are proposing the following simplification:

1. For both tables, remove the columns with the event information and the date/time information. 
-- For the collection table, this will leave just a list of collection titles (linked)
-- For the item table, this will leave a list of item titles (linked) and the titles of the collections they belong to (linked)
2. Display a *deduplicated* list of items or collections, depending on the table, for which an event has been logged in the time period selected.

This will allow us to easily scan a short list of items or collections that have been touched in some way without missing something that has only a single entry amongst the ones that 2 or 3 or 7 entries. All the detailed information about the events and dates are easily accessible with one click from the item or collection view pages.

**Comment by peetucket** [comment]
This is in the admin interface, correct?

**Comment by amyehodge** [comment]
@peetucket Yes it is.
