### ISSUE TITLE
Adjust overlapping elements at top of item page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2602]
I'm not sure how the "Edit or Deposit" button should be behaving on this page for non-admins, but it's now overlapping with the admin box.

![Screen Shot 2022-09-06 at 2.48.55 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/5268575d-53c7-4ee2-9771-76f1fd843d03
)

@astridu can you propose a solution for this?

**Comment by jcoyne** [comment]
@astridu what if the title is even longer (more than one line)?  What if it's very short? Can you mock those scenarios up also?

**Comment by astridu** [comment]
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/42216982/189001974-1f46b859-6d9f-48e8-aabf-af960f7c4556.png">

Can we truncate it at ~140 characters so that it doesn't wrap to a 3rd line?
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/42216982/189002020-8f072559-0248-45cf-8570-b65ed4afc34f.png">

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/42216982/189002205-2f274dcd-ed34-4aa8-9195-36bcb2946f7f.png">

**Comment by amyehodge** [comment]
@astridu @jcoyne When sometimes get multiple items with fairly long titles where the only distinguishing bit is a year at the end. Truncating the title in the breadcrumbs and at the top of the page is fine with me, but we are going to need to display the full-length title somewhere on the page so people can verify they are on the right item. 

If the long titles are complicating the display at the top, perhaps we could add the title as the first entry in the Details box on this page?

**Comment by astridu** [comment]
Is there a character limit to the titles? It would be ok to display the full title as long as it didn't wrap to more than 5 lines (~1000 characters).

**Comment by jcoyne** [comment]
We do not impose any limits on the titles.

**Comment by astridu** [comment]
@amyehodge You may have already seen an example like this, but this is what it looks like with a 1000 character title.
<img width="558" alt="image" src="https://user-images.githubusercontent.com/42216982/190026616-74321085-176b-4573-baf6-ea752a1c8822.png">

**Comment by astridu** [comment]
Example where the title's last line takes up the full line. The pencil and 'New version in draft' appears on the next line.
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/42216982/190451152-614c2c77-8623-45f4-95d0-f3f023f0b90e.png">
