### ISSUE TITLE
Do not grey options that are active but just not selected

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2605]
We do not want to grey out any options that are available for the user to select, only the suboptions.

Here the "immediately" option appears to be greyed out and not an option, but it is actually available to select. 

![image.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/c51b8843-dd8a-4243-9afd-440597eda53f)

And when "immediately" is selected, the embargo should not be greyed out like it is below:

![Screen Shot 2022-09-06 at 3.55.45 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/9beffeec-8362-4d5b-90aa-3b1875c40333)

**Comment by jcoyne** [comment]
To translate for implementers: the "label" of the radio button shouldn't be gray when it's not selected.
