### ISSUE TITLE
Add DOI to autogenerated citation

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#2628]
We should already know what the DOI is as soon as we have a druid.

Like this: https://github.com/sul-dlss/dor-services-app/blob/2f3817c9a07d918f923b8a1a74e04b2c54759763/app/services/create_object_service.rb#L115-L116

**Comment by amyehodge** [comment]
When either 1) the collection requires the item to get a DOI upon deposit or 2) the depositor has selected to get a DOI upon deposit, the DOI should be added to the autogenerated citation, similarly to how the PURL is added now. There should be placeholder text that reads ":DOI will be inserted here automatically when available:" This should be separated by a period from the PURL and should be followed by a period.

So, the depositor will see at the end of the autogenerated citation, prior to the first deposit: 
`Available at :link will be inserted here automatically when available:. :DOI will be inserted here automatically when available:`.

And once deposited the autogenerated citation should read:
`Available at https://purl.stanford.edu/xx000xx0000. https://doi.org/10.25740/xx000xx0000.`

**Comment by amyehodge** [comment]
@jcoyne Please let me know if you need any further info for this one.
