### ISSUE TITLE
Add autocomplete for keywords 

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#264]
These should come from OCLC FAST authority hosted by Cornell's QA.

See conversation in #82

**Comment by ndushay** [comment]
preferred component for typeahead?   "something that doesn't include jQuery"

we might need to proxy the back end ... can the front end query OCLC FAST directly?  (Do we want to have a rails controller query the QA server and return results to the front end?)

Using Cornell's QA has a search; not sure if OCLC FAST does;  Cornell's QA is implemented with blacklight so can query Solr ...

Cornell's QA is associated with LD4P, so Sinopia may have some code we can use ...

**Comment by ndushay** [comment]
Possible typeahead components:
- https://github.com/gch1p/bootstrap-5-autocomplete/
- https://www.algolia.com/doc/ui-libraries/autocomplete/introduction/what-is-autocomplete/ "This is a good one too, but more heavyweight" (JCoyne)
    - Source at https://github.com/algolia/autocomplete
-  https://github.com/alphagov/accessible-autocomplete "May also want to look at ... as it’s geared toward accessability.
" (JCoyne)

**Comment by jcoyne** [comment]
@ndushay at some point the requirements for the front end, might become so divergent from what OCLC offers that it makes sense for us to build our own backend for the search.

**Comment by ndushay** [comment]
@jcoyne understood.  Let's call this "phase 1" and see what happens when I make the requested changes.

**Comment by ndushay** [comment]
if we did do our own backend we might want to use it for ETDs and possibly some other apps as well.
