### ISSUE TITLE
Make buttons for author and contributor sections easier to click

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2642]
After having done 29 deposits recently, I've found that the radio buttons in the author/contributor section are hard to click on the first try. It feels like they should be bigger or the clickable area should be bigger. 

![Screen Shot 2022-09-09 at 1.50.26 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/4e2dbd8b-daf6-4681-b985-5b3448f405b7)

@astridu What's the best way to improve this?

**Comment by astridu** [comment]
Could we try the next size up? I realize that will affect all radio button sizes, but maybe it would be a good thing for all of them to be slightly larger.

**Comment by amyehodge** [comment]
@jcoyne Does @astridu 's suggestion work here?

**Comment by jcoyne** [comment]
@astridu I think the problem here is a bigger accessibility issue.  Typically radio buttons have visible labels and you can click anywhere on the radio and it's adjacent label to select it. Our designs have no visible labels to click on.  Here are some examples: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

**Comment by astridu** [comment]
Does something like this work? Could we use the slightly bigger red radio buttons instead of the smaller blue radio buttons?
<img width="881" alt="image" src="https://user-images.githubusercontent.com/42216982/189461843-4f7e246d-fbbd-42f3-a54c-db6323cd15cd.png">

**Comment by amyehodge** [comment]
@astridu I like the bigger buttons. And will the new text be clickable here too, not just the button? That would be helpful. I think this should still have the "OR" between the two, yes?

I'm wondering a bit about the bold treatment on that text, because I think that will be very different from the rest of the form, where we are only using the bold for the section headers. Will that look odd? Maybe not. Having bigger buttons and clickable text will certainly be helpful here.

**Comment by astridu** [comment]
I don't think it will look odd, and the bold will make it clear there are 2 options with form fields below them. And yes, the text should be clickable too.

**Comment by jcoyne** [comment]
@astridu what about the "Details" which is the accessible label for the radio group?

**Comment by astridu** [comment]
Sorry, forgot about that. 
<img width="881" alt="image" src="https://user-images.githubusercontent.com/42216982/189952035-c028bf0e-0eb3-4b03-b041-7e9a107ae12a.png">

**Comment by jcoyne** [comment]
@astridu "Details" doesn't currently have an asterisk.  Do you want that to be added?

**Comment by jcoyne** [comment]
@astridu should the bold be consistent across all radio buttons? (e.g. "Single date"/"Date range") or is that only for "Enter Author Name", "Enter ORCID", " Upload files" and "I have uploaded my files to a Globus endpoint..."?

**Comment by astridu** [comment]
across all radio buttons. Thank you!
