### ISSUE TITLE
Make sure email notifications go to the new item owner

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2654]
I have tested in production and when an item is changed to a new owner, the email notifications are still going to the original depositor. These need to go to the new owner. 

Basically, this is a repeat of ticket #2328.

**Comment by peetucket** [comment]
It looks like when an owner is changed, there are three separate emails that will go out:

1. A single email only to the new owner (subject line: "You now have access to an item in the SDR")
2. An email to everyone who is listed as a manager or reviewed on the collection that the work is part of (subject line: "Participant changes for the XXXX collection in the SDR")
3. An email to everyone who is listed as a manager on the collection that the work is part of (subject line: "The ownership of an item in your collection has changed")

The code for sending all of the emails looks ok to, and I did some debugging on my laptop and to me it appears email 1 *should* only be going to the new owner, and not the depositor it was changed from.  

Note that if the original work depositor is also a manager of the collection (plausible for test data), they will still get emails 2 AND 3 (but should *not* get email 1). 

Can you confirm if email 1 is the one actually going to the original depositor and not the new owner?  If so, we'll need to dig some more, but that's not what I am currently seeing in the code.

**Comment by amyehodge** [comment]
@peetucket Ah, sorry. Those are not the emails I meant. The change of ownership emails are going out as expected. 

The emails that aren't going out as expected are subsequent emails when the item is modified. So, when I tested with Kim Durante earlier today, I assigned one of my items to her. I then had her:
1. create a new version and submit it for approval
2. I then approved the item
3. I then turned the review workflow off and had her directly submit the item. 

In all these cases I continued to receive the emails and she didn't receive any of them. What should be happening is that she should be getting these messages and I should not.

**Comment by peetucket** [comment]
I see, thanks for the clarification -- my suspicion is that all of those emails are hardcoded to the depositor from before there was a notion of ownership, and need to be changed to look to see if an owner exists for a given work that is different from the depositor, and to use that instead.  I presume it is safe in all cases to "override" the depositor with the latest owner for these emails?

**Comment by amyehodge** [comment]
@peetucket Yes, it should be safe to override that in this situation.

Though it is possible to change the owner back or again to third person, so you might want to look at what happens in those cases as well.

**Comment by peetucket** [comment]
Ok, I suspect we should just globally use the owner for all of those work emails.  The database design to me looks like there is *always* a single owner and a single depositor for a work.  They start out as the same person, and while the depositor can never be changed, the owner can be changed by an admin as often as you like (even back to the original depositor if you want).  So it seems pretty safe to say that at any time an email about a particular work goes out, it should just go to whoever the current owner is at that point in time (usually the same as the depositor of course, but could be different).

**Comment by amyehodge** [comment]
Yep, that sounds exactly right to me.
