### ISSUE TITLE
Unable to remove a file uploaded while item was in draft state so I can select the Globus option

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2662]
Once an item has been saved as a draft with a file, it is not possible to choose the Globus option and make a deposit. This means the user is not able to change their mind about which option to use in this scenario.

If you attempt to open the saved draft and change to Globus and deposit, you are prompted that you must remove the file:

![Screen Shot 2022-09-12 at 5.01.29 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/af0aff47-1c4e-4736-8477-240ccf1e1ecb)

The user then has to select the file upload option again in order to remove the file, and then select the Globus option again. This is an awkward series of steps. At which point it looks like this:

![Screen Shot 2022-09-12 at 5.01.56 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/53efbda6-605f-4c57-8666-7e04b7e38824)

Note this error says I need both attach a file and remove all files.

And when the user tries to deposit from this state, they see this error message again and are caught in an endless loop:

![Screen Shot 2022-09-12 at 5.02.46 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/e77b7a63-a649-4a0a-85b5-621b97202091)

**Comment by jcoyne** [comment]
@amyehodge can we make is such that if they select the globus option, then the files automatically removed?

**Comment by amyehodge** [comment]
@jcoyne If we do that there is some chance that someone will switch it back to the upload option and have to spend a long time reuploading fairly large files. But overall I think that makes the most sense and will hopefully be an edge case.

**Comment by jcoyne** [comment]
Remove the files when they click "save draft" or "deposit" if globus is selected.
