### ISSUE TITLE
Update the H2 work with the range that is still present in the Cocina

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#2673]
These items have not been updated via H2 since the migration away from Hydrus. So they only need to be updated in H2 because the record in Cocina/SDR has not changed since the migration.

There are 259 items in this category. CSV listing these druids with links to their Argo pages: [update-h2-date-range.csv](https://github.com/sul-dlss/happy-heron/files/9538404/update-h2-date-range.csv)

Get the data from sdr-api and update the missing range end in the database.

(This used to be part of #2224)

**Comment by jcoyne** [comment]
```
druids.each do |druid|
 cocina = Repository.find("druid:#{druid}")
 date = cocina.description.event.first.date.first.structuredValue
 work_version = Work.find_by(druid: "druid:#{druid}").head
  puts "#{druid},#{work_version.created_edtf}"
  work_version.created_edtf = EDTF.parse("#{date.first.value}-#{date.last.value}")
  work_version.save
end
``

**Comment by jcoyne** [comment]
@amyehodge @andrewjbtw we don't have a record of "dp690mm3959" in h2:

**Comment by andrewjbtw** [comment]
Huh. Those three all have the H2 tag in Argo but they correspond to a project where we had been decommissioning a lot of items in the same collection. These aren't tagged for decommissioning but it's possible I started the process on these by deleting them from H2 and then got sidetracked.

In any case, I don't think there's a cause for concern because as I understand the state of that project, these shouldn't be in H2 regardless.

**Comment by andrewjbtw** [comment]
I see what must have happened. Those three items were in a registered state, and were created in Hydrus just before the migration to H2. So the sequence was probably:

- user requests decommission of deposited items
- user deletes "draft" items from H2 since they can do that in the UI
- but because the H2 drafts previously existed in Fedora as registered objects, they stuck around in Argo

I'm going to decommission them in Argo to leave a record in case any question comes up later.

**Comment by jcoyne** [comment]
@andrewjbtw thank you.  

@amyehodge I assigned this ticket to you to make sure I made these changes correctly.

**Comment by amyehodge** [comment]
@jcoyne I checked half a dozen and the dates in H2 now match the dates in the cocina.

However, for yy758rc6782, does this bit of cocina mean that there should be an approximate flag on one or both of these dates? If so, that didn't make it into H2.

"event": ⊖[
           ⊖{
                "date": ⊖[
                   ⊖{
                        "structuredValue": ⊖[
                           ⊖{
                                "value": "2008",
                                "type": "start",
                                "status": "primary"
                            },
                           ⊖{
                                "value": "2014",
                                "type": "end"
                            }
                        ],
                        "type": "creation",
                        "encoding": ⊕{1 item},
                        "qualifier": "approximate"
                    }
                ]
            }
        ],


I see a similar thing on wp894vt1248.

**Comment by jcoyne** [comment]
@amyehodge I've updated those two.

**Comment by amyehodge** [comment]
@jcoyne Is there a way to find out if there are more like that without my looking at each one of them? I only checked 6 and found those 2, so I suspect there are more.

**Comment by amyehodge** [comment]
@jcoyne Great. I've verified that all those need the approximate option on both ends of the date range as well. Can you make those updates? 

And did your script catch those that might only need an approximate on one end? All of these needed both, which makes me a little suspicious. Thanks.

**Comment by jcoyne** [comment]
@amyehodge in the cases I identified, I was only looking for "the whole thing is approximate"

**Comment by amyehodge** [comment]
@jcoyne If you could look for those and then make those updates as well, I think that's the last thing we need to be able to close this ticket. Thanks!

**Comment by jcoyne** [comment]
Here's the start qualifiers:
```
start_qualifiers = test_druids.select do |druid|
  cocina = Repository.find("druid:#{druid}")
  date = cocina.description.event.first.date.first.structuredValue
  date.first.qualifier
end

["gr207rd0652",
 "br087nj9017",
 "ms902yj3161",
 "vb795px8802",
 "kb858vc3553",
 "hj415jd0699",
 "jk169yp4624",
 "vp198gc8085",
 "rp520mb1905",
 "sq973xh1416",
 "fv312pt6985",
 "rr512xk8301",
 "vb828sg2673",
 "mc747zz6607",
 "wt914rs9753",
 "dk954yp6586"]
```
and the end qualifiers
```
end_qualifiers = test_druids.select do |druid|
  cocina = Repository.find("druid:#{druid}")
  date = cocina.description.event.first.date.first.structuredValue
  date.second.qualifier
end

["gb907hx6404", "fr894kt7780", "wm965jd5484"]
```

**Comment by amyehodge** [comment]
Yep, all those look good to be updated like that if you haven't done it already.
