### ISSUE TITLE
Add option to move an item to a new collection

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2685]
Admins should be able to move an item to a different collection in H2. This feature should appear in the admin function drop-down menu on the item page.

* Items can only be moved to collections that have been deposited (so, not anything in a "first draft" state, but later draft states are fine)
* Items can't be moved if certain conflicts exist:
-- the item is embargoed but the collection is set for immediate release only
-- the depositor of the item chose not to get a DOI but the collection requires DOI assignment
-- the item has a license that is not allowed by the collection setting
-- the item is set for Stanford visibility but the collection requires world visibility
* this move needs to trigger a versioning of the item so that the new collection information is sent to SDR

Item view page with "move to another collection" selected.
![Screen Shot 2022-09-15 at 4.08.53 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/356b1805-100f-4200-a2e8-616aef7d2ea7)

The drop-down menu would exclude collections that are in first draft state. Collection titles should be prefaced with their druid in this list.

![Screen Shot 2022-09-15 at 4.08.58 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/07a9b206-4be7-428f-a9a8-28ea4eb1348f)

Once a collection has been selected, the user will click the "Move" button.

At this point, the check for conflicts would run and if there are none, the move would happen and the item would be redeposited and a success message similar to the others for the admin actions on items would be displayed.

If conflicts are found, the user would see a message that would include whichever errors are appropriate for this item:

![Screen Shot 2022-09-15 at 4.09.03 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/85060783-4fa8-456f-92f2-a988797cb14a)

**Comment by amyehodge** [comment]
Type-ahead would be nice for this drop-down since here are many collections, but another option is to have the selector move to the "S" part of the list when the user types an "S", etc. Though with these prefaced by the druid, that might not work -- any way to have the type ahead ignore the druid?

**Comment by peetucket** [comment]
Just a note that there are currently 237 collections (which will continue to grow), which will make the drop down menu more and more unwieldy.  Perhaps searching by collection name (similar to what is done when changing owner) is a better approach ?

**Comment by amyehodge** [comment]
Just a drop-down is likely to be a bit problematic and get more so over time. The above design includes prefacing the collection names with the druid. I'm wondering if we should just do this via druid search? If we are going to be moving items, we are going to know which collection we want and the druid is easy enough to find. We may even already have that collection open in another window. Perhaps a druid search (of just the collection druids) is a good way to go. Then display the collection name. If that sounds reasonable I'll see if @astridu is back in yet and can mock that up.
