### ISSUE TITLE
When new item is saved without any changes, history entry should not indicate any changes

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2686]
If I create a new deposit and save it as a draft without making any changes, the history says "license modified" when it should not say anything.
![Screen Shot 2022-09-14 at 11 10 22 AM](https://user-images.githubusercontent.com/5558511/190193356-a20d3448-40f1-4c93-9c4c-635202eb4092.png)

If there is a new item in a collection that lets a depositor choose the license and they choose a license other than the default, show the "license modified", if they use the default license then show no message.

**Comment by jcoyne** [comment]
@amyehodge is this in a collection that prescribes a particular license, or lets the depositor choose, or in both cases?

**Comment by amyehodge** [comment]
Good question @jcoyne. Turns out this only happens when the depositor can choose.

**Comment by jcoyne** [comment]
If there is a new item in a collection that lets a depositor choose the license and they choose a license other than the default, show the "license modified", if they use the default license then show no message.

**Comment by peetucket** [comment]
Note: this work would be modified by PR #2649 (still waiting for review), which makes all new works/collections just say "Created" in the description of changes.  If we want that change, we'd need to modify it so that the license actually does some comparison with the collection default to decide if we need to show this message or note.

**Comment by peetucket** [comment]
From https://github.com/sul-dlss/happy-heron/pull/2726#issuecomment-1251508139:

Here's my thinking on what should be happening:

- IF an item is created and saved without anything being done in the form: “Created”
- IF an item is created and the license is changed (and nothing else): “License updated”
- IF an item is created and the license is changed and other things are changed: “License changed, title modified, keywords modified, etc.”
