### ISSUE TITLE
When deleting an in progress item from the dashboard, user should stay on dashboard

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2695]
When the user clicks on a trash can icon on a draft item on the dashboard to delete an item, they should be taken back to the dashboard page again. Instead, they are taken to the deposits list for this collection.

This applies to the trash can icons in two locations on the dashboard:
* in the "Items in progress" table on the dashboard
* in the table under "Your collections"

Delete options in other places in the UI for items -- on the "Deposits" tab for the collection and in the item edit form -- currently go to the "Deposits" tab and should not be changed. 

Clicking on the trash can icon here:

![Screen Shot 2022-09-14 at 2.01.07 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/87a53114-06e4-4a8c-976e-ec8b407a7df4)

Or here:

![Screen Shot 2022-09-15 at 10 50 13 AM](https://user-images.githubusercontent.com/5558511/190435946-01ba8fd6-4765-4cdb-8ee7-4397501de34a.png)

Takes me to:

![Screen Shot 2022-09-14 at 2.03.30 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/4f043dfa-8af5-4e8d-b5f7-91ed4d54a34c)

What the user should see after confirming the deletion is the dashboard like this:

![Screen Shot 2022-09-14 at 2.04.10 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/9da8e2da-cb35-4e58-b690-26feb56c3cfb)

**Comment by jcoyne** [comment]
@amyehodge Are there other places in the application were a user can do a delete of a work?  Are those paths intended to change or to stay the same?

**Comment by amyehodge** [comment]
@jcoyne I have updated the description above. There are two places on the dashboard that should behave this way. The other places where an item can be deleted should not change.
