### ISSUE TITLE
Update the APO for objects migrated to H2 to use the Hydrus Ur-APO

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#2747]
**Proposal**: Normalize all Hydrus/H2 items to use the Hydrus Ur-APO

**Background**

When we migrated objects from Hydrus to H2, we did not change their governing APOs. In Hydrus, every collection had its own unique APO. The function of the Hydrus-specific APO was to control collection settings: default license, default visibility, whether the review workflow is active, authorization of depositors, etc. The Hydrus collection-specific APOs were all connected to the Hydrus Ur-APO, essentially creating a hierarchy of:

Hydrus Ur-APO --> Hydrus collection-specific APO --> Collection --> Item

In H2, all of the collection settings are controlled by the H2 app itself. Since that means there is no need for collection-specific APOs, all H2 deposits just use the Hydrus Ur-APO. As I recall, at the time of the H2 migration, we weren't quite sure what to do with the Hydrus collection-specific APOs, so we left them in place for existing objects. Now that a year has passed and we have not run into anything indicating a continued need for the Hydrus collection-specific APOs, it seems like a good time to retire them.

To do this, we need to update all H2 and Hydrus items and collections that still have a Hydrus collection-specific APO to use the Hydrus Ur-APO. This would standardize all self-deposit items to use the same APO. Currently, what we've found is that certain collections are split between items that use the old Hydrus collection-specific APO and the Hydrus Ur-APO.

For example, the VISTA Lab collection has items that use different APOs even though they're all in one collection:
https://argo.stanford.edu/catalog?f%5Bis_member_of_collection_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Aqd500xn1572

In that collection, the 15 items deposited before the H2 migration use the "[APO for VISTA Lab](https://argo.stanford.edu/view/druid:gj641wz5091)". The one item deposited in 2022 uses the Hydrus Ur-APO. It would be preferable to have them all use a single APO.

**Normalization options**

There is one complication with making this change: updates to the governing APO are usually handled as "versioning" events. The standard way to update APOs would be:

1. Open new version in Argo
2. Update the APO
3. Close the version

The problem with doing this for objects migrated to H2 is that it would throw off the version numbering. Every item that needs to be moved to the Hydrus Ur-APO would have its version incremented by 1. Changes made via Argo carry the risk of causing problems for subsequent edits in H2.

That leaves us with a couple of viable options:

1. Re-deposit every item in H2 in order to update the APO. H2 will always use the Hydrus Ur-APO, so the next version sent from H2 will switch the APO.
2. Make an update in the Cocina only, without versioning. We could update the APO in the Cocina and not send a new version to preservation.

@amyehodge and I met today to discuss the options. Our inclination is to make the update in Cocina only and not go through the versioning process. Our reasoning is:

- APOs are completely invisible to H2 users. We would be creating a new version that only changed information no one sees.
- APO information is not published to the Purl, so there's no need to update the Purls
- Even though the change in APO wouldn't be preserved if we updated only the Cocina, nothing in the SDR system relies on the APO relationship being expressed in the preservation system
- In any disaster recovery scenario, the Cocina database is as important as the contents of the preservation system, so making sure the change in APO was saved to preservation in a new version may not provide much benefit.

**Example**

I think the only change required would be to change the APO druid here:

```
"administrative": {
    "hasAdminPolicy": "druid:gj641wz5091",
```

to 

```
"administrative": {
    "hasAdminPolicy": "druid:zw306xn5593",
```

**Comment by andrewjbtw** [comment]
cc: @hannahfrost This is the proposal we discussed today to remove the old Hydrus APOs from active use. If we follow this route, then I would decommission them afterwards.

There are 955 Hydrus APOs, making up around 75% of all APOs: https://argo.stanford.edu/catalog?f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=Hydrus+Ur-APO&f%5BobjectType_ssim%5D%5B%5D=adminPolicy&search_field=text

**Comment by hannahfrost** [comment]
Thanks for the clear explanation of the situation, @andrewjbtw . I will be very happy to see this APO clutter removed from Argo. The Cocina route is clearly the right way to go.

**Comment by peetucket** [comment]
(Documenting for my own benefit here) 

Process to update a single object on the Argo VM, to be scripted:

```
ur_hydrus_apo = 'druid:zw306xn5593'

# iterate over all relevant druids
object_client = Dor::Services::Client.object(druid)
cocina = object_client.find
change_set = ItemChangeSet.new(cocina)
change_set.validate(admin_policy_id: ur_hydrus_apo)
change_set.save
Argo::Indexer.reindex_druid_remotely(druid)
```

**Comment by peetucket** [comment]
[hydrus_apos_updated.csv](https://github.com/sul-dlss/happy-heron/files/9669219/hydrus_apos_updated.csv)

**Comment by peetucket** [comment]
12309 druids updated.  CSV of druids updated attached as a comment.
