### ISSUE TITLE
fix FAST searching for keywords

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2774]
The FAST keyword searching does not appear to be working in production this morning. This is functioning like just a free text field. I’m not seeing any search results being presented.

**Comment by jcoyne** [comment]
The FAST service seems to be down:
```
curl "http://fast.oclc.org/fastIndex/select?q=keywords:dog*"
curl: (56) Recv failure: Connection reset by peer
```

Can you report to OCLC?

**Comment by amyehodge** [comment]
I have sent a message to the support@oclc.org
