### ISSUE TITLE
Use fontawesome wastebasket rather than emoji

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#280]

**Comment by ndushay** [comment]
for future tickets, it would be super helpful to have a bit more information, such as:

- where does this need to be done in our code (e.g. I had to figure out how to find where a trash icon was being used)
- Then I had to discover that fontawesome has a whole bunch of trash icons, and I had to realize that i needed to look at the design document to determine WHICH fontawesome icon.   (Just maybe mention to get the correct trash icon from the design doc)
- are there other spots in the app that should have a trash icon that I didn't find?  How would I know?

Speaking for myself, I do not always have the whole H2 app and its current state loaded in my mind so I am starting about N paces back from where you are when I'm looking at a ticket.
