### ISSUE TITLE
"first time user" form submissions are not sending emails

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/happy-heron#2821]
This week two users have reported that they used what we call the "first time user" form to request access to and use of H2, but the form submission never resulted in a JIRA ticket or an email to sdr-contact@lists. The first occurrence was sometime the week of Oct 10 (I can ask for a more precise date if it would be helpful) and the second occurrence was this morning before 11:09 AM PT.

I am not able to test this feature due to my admin permissions.  Happy to help test if we can find a way to do that.

**Comment by peetucket** [comment]
Is the from the one shown below (that shows up when you click "Help")?  If so, the H2 side is pretty simple -- it just sends an email to sdr-support@jirasul.stanford.edu with the "from" address set as the email address entered into the form.  

Perhaps the jira side is not working as expected, OR a user is not entering an email address in the form and this is confusing Jira?  It looks like email address is required (and defaults to your email if you are logged in), but the validation appears to be javascript only to me, which means it could be bypassed if you had JS turned off (this is unlikely though).

![Screen Shot 2022-10-21 at 12 43 49 PM](https://user-images.githubusercontent.com/47137/197276829-6a08b0d3-e731-4efd-a1f1-daef006485dd.png)

**Comment by hannahfrost** [comment]
No, it is not the “help" form. It is the “first time user” form. I believe this form appears when someone who has no permissions for anything in H2 clicks “enter here” on the home page.

One of the impacted users provided a screenshot of the form they used - see attached.

[cid:BA34AF46-16CF-4403-AA5D-146ACFD7553F]



—
Hannah Frost | Associate Director for Digital Services
Stanford Libraries<https://library.stanford.edu/> | Digital Library Systems and Services
Lathrop Library 384
E: ***@***.******@***.***> | C: (650) 799-1352
Pronouns: she/her

On Oct 21, 2022, at 12:47 PM, Peter Mangiafico ***@***.******@***.***>> wrote:



Is the from the one shown below (that shows up when you click "Help")? If so, the H2 side is pretty simple -- it just sends an email to ***@***.******@***.***> with the "from" address set as the email address entered into the form.

Perhaps the jira side is not working as expected, OR a user is not entering an email address in the form and this is confusing Jira? It looks like email address is required (and defaults to your email if you are logged in), but the validation appears to be javascript only to me, which means it could be bypassed if you had JS turned off (this is unlikely though).

[Screen Shot 2022-10-21 at 12 43 49 PM]<https://user-images.githubusercontent.com/47137/197276829-6a08b0d3-e731-4efd-a1f1-daef006485dd.png>

**Comment by hannahfrost** [comment]
![image006](https://user-images.githubusercontent.com/1801076/197280661-47c11138-8059-4375-9741-d91231ca2cac.png)

**Comment by peetucket** [comment]
ok, thanks

**Comment by peetucket** [comment]
I simulated this on my laptop and our code suggests the email is being sent ... I wonder if there is someone we can use as a tester who won't have access by default and we can watch what happens in the logs when they fill in the form and send it ... it's possible the emails are being sent from our code and there is something mis-configured on the Jira side

**Comment by peetucket** [comment]
Note: this slack thread has some info about investigations so far: https://stanfordlib.slack.com/archives/C09M7P91R/p1666380457093009

**Comment by peetucket** [comment]
Changes in #2823 show that the (stage) server can send emails, as a test form submission made it to sdr-contact@lists.stanford.edu  after that PR was deployed

Jira integration seems the likely suspect.

**Comment by peetucket** [comment]
Deployed to QA, stage and production, tested in all environments and emails are being sent to sdr-contact@lists.stanford.edu

**Comment by hannahfrost** [comment]
I have ticketed the issue with JIRA emails not generating tickets reliably here for Rob Smith to investigate: https://github.com/sul-dlss/operations-tasks/issues/3206

**Comment by hannahfrost** [comment]
Rob Smith found that a configuration in the SDRSUPPORT project in Jira has been changed resulting in the tickets not getting generated. The change has been reverted and tickets are now getting made as expected.

**Comment by peetucket** [comment]
Great!  Would you like to leave the backup email going to sdr-contact ?  If so, you will get the email to sdr-contact immediately and then likely the notification from Jira about a new ticket once it's created.

**Comment by hannahfrost** [comment]
I think we’ll leave the backup email for the timbering. If it gets annoying to have the extra messages, we can take it out later. For now, I like the assurance that we are getting messages independently from JIRA.

Thanks for your help, Peter!


On Oct 26, 2022, at 4:55 PM, Peter Mangiafico ***@***.******@***.***>> wrote:



Great! Would you like to leave the backup email going to sdr-contact ? If so, you will get the email to sdr-contact immediately and then likely the notification from Jira about a new ticket once it's created.
