### ISSUE TITLE
Add new option for single ZIP file upload

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#2843]
As part of hierarchical file upload, we are removing the ability to upload a folder and instead will ask users to upload a single ZIP, which will be expanded.

This new option is in addition to the current options of uploading files, or using globus, here:

https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471005606

The new radio button option language is shown in the UI above.

1. If this option selected, users will are able to select and upload a single ZIP file.  We need to validate that only a single ZIP is provided with this option.

2. Once uploaded, the content of the ZIP will be shown to the depositor in the H2 work edit/show page, something like this (but note we will only allow a single ZIP to be uploaded)

https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471005875
 
3. Once deposited, the single ZIP file will be expanded and accessioned as files with hierarchy (the same way the current folder upload works)

- only the zip will be downloadable in H2; individual files will not be downloadable from anywhere in H2
- users will not be able to rename, move, or delete individual files 
- the "hide file" option and the file description entry field will not be available for this upload option

**Comment by astridu** [comment]
3 radio button choices on the deposit page:
<img width="884" alt="image" src="https://user-images.githubusercontent.com/42216982/202080042-200082af-05a2-4680-8e89-9865dee3bd36.png">

**Comment by astridu** [comment]
@amyehodge This is what it might look like if user selects to upload a zip file and sees the expanded folders.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/42216982/202082607-e83b1239-b530-49b3-9bde-887932c58ec2.png">

**Comment by amyehodge** [comment]
> Questions for PO:
>
> Do we want users to be able to drag and drop the single ZIP or click the browse button and select a single file?

Yes, we want users to be able to either drag and drop the single ZIP or click the browse button and select a single file. Drag and drop is a must have. Browse button is slightly less important.

**Comment by amyehodge** [comment]
> Questions for PO:
>
> Updated verbiage for options and any instructions

For the first option, I'm concerned that saying "individual files" will make some users think they can only upload one file.
For the last option, I'm not sure if the rest of the language that @astridu suggested for this one is accurate until I see how that workflow is going to work out. It may need to also indicate that they may need to install software.


My suggested text for the radio buttons:

- **Upload one or more files (< 10GB) to be displayed as a flat list.**
- **Upload a single zip file (<10 GB) to be expanded on the PURL page.** Viewers will see the file hierarchy and be able to download individual files.
- **Upload one or more files (> 10 GB) via Globus web-based file transfer software.** Use single sign-on to activate your Globus account first if you don't already have one, and then return to here to complete this form.

**Comment by amyehodge** [comment]
> @amyehodge This is what it might look like if user selects to upload a zip file and sees the expanded folders.
> 
> <img alt="image" width="669" src="https://user-images.githubusercontent.com/42216982/202082607-e83b1239-b530-49b3-9bde-887932c58ec2.png">

Looking great!

As indicated in Peter's notes above, for this option the user should not see the file description or the hide file option. 

For the text, I've recommended above starting with this:

- Upload a single zip file (<10 GB) to be expanded on the PURL page. Viewers will see the file hierarchy and be able to download individual files.

Then when expanded, here's what I'm thinking:

- Files types accepted: (list these -- I'm not sure what will work? @peetucket can you assist with this list?)
- To rename, move, or delete individual files in your zip file, you must delete the existing file and reupload a modified version of the file. 

I don't think we need the info about the permissions as that is the same as it always was, with the exception of the ability to hide the file, which we will be removing from this option anyhow.

**Comment by amyehodge** [comment]
@astridu @peetucket Is one of these options selected by default? I think the way we've always had this working is that one of the options is always selected -- you can't deselect all options.

**Comment by astridu** [comment]
That's a good point. If we select the first option, the other 2 get pushed down and may not be visible above the fold.

**Comment by peetucket** [comment]
Currently the "upload files" option is selected by default.  If you select the "globus" option, it gets hidden and if you reselect the "upload" option, it re-appears.  So I would think this new option would work in a similar way (still defaulting to "upload files" as now, but selecting one of the other options would hide the upload panel as needed).

**Comment by amyehodge** [comment]
With three options, I prefer that they not see all the detailed info right away. So, I like this to be what they see initially, which I think means allowing this to have everything deselected to start at least:

> <img alt="image" width="884" src="https://user-images.githubusercontent.com/42216982/202080256-1aae2692-9b17-4a4f-8a1a-160d4fb82948.png">

**Comment by amyehodge** [comment]
> Currently the "upload files" option is selected by default. If you select the "globus" option, it gets hidden and if you reselect the "upload" option, it re-appears. So I would think this new option would work in a similar way (still defaulting to "upload files" as now, but selecting one of the other options would hide the upload panel as needed).

The suboptimal part of this is that once the first option is expanded it takes up so much screen space that users may not even notice the other options.

**Comment by peetucket** [comment]
OK, i see.

**Comment by peetucket** [comment]
Created #2859 to remove default upload option selected for a new work

**Comment by amyehodge** [comment]
Text for zip file upload option:

**Upload a single .zip file (<10GB) to be displayed as a hierarchy.**
We recommend the .zip file not contain over 1000 files.
