### ISSUE TITLE
Change text of globus option

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#2844]
The option for users to use globus will become automated instead of requiring manual intervention by SDR support staff.  As such, the actions that happen when users select this option will change, and we will also need to change the text of the option.

UI flow: https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/470591811_Globus_Workflow

![Screen Shot 2022-11-10 at 9 35 14 AM](https://user-images.githubusercontent.com/47137/201172529-b5e98bfb-8cb6-433f-a8ca-4e16a20d4610.png)

New text (to be validated by PO):

"Use Globus, web-based file transfer software, to upload files (> 10 GB)"

Also, add some text indicating the user needs to have a globus account first to select this option and link to the instructions in #2855

**Comment by astridu** [comment]
Latest thinking on text here: https://invis.io/YQ132HXFX2GR#/470591811_Globus_Workflow

**Comment by amyehodge** [comment]
@astridu @peetucket I have documented modified email text at https://docs.google.com/document/d/1TZVILUrORI25kRZyUZ70vMQYo90Ngp_tqCI7BdU_VyQ/edit#heading=h.phchieea3q7x.

The bit guiding them to help text is nice, but that would also need to be created elsewhere.
