### ISSUE TITLE
Disable Deposit button when globus option is selected

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#2846]
When a user selects the globus file upload option (via the radio button), they should not be able to deposit immediately, as they still have to move the files into the globus endpoint first.

We also need to show the following text near the Deposit/Save As Draft buttons:

"You can save this deposit as a draft.  Next, you will receive an email with instructions on how to upload the file in Globus.  You you have uploaded your files, you can return to this page and click the "Deposit" button to complete your deposit."

Once the user clicks "Save As Draft", this triggers some follow on actions, as described in a separate ticket here: #2847

Once we've done those follow on actions (which should happen almost immediately after Saving), the "Deposit" button will become active the next time a user visits the edit page.  So... I expect we will need some new states in the work version to keep track of where we are in the flow.  That is described here: #2865

See UI: https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/470591811_Globus_Workflow

----
This is the overview of what happens.

**Comment by justinlittman** [comment]
I can't follow the UI flows in invision. @peetucket Can you extract the relevant parts and add to this ticket?

**Comment by peetucket** [comment]
I updated the description of this ticket, trying to break down the various pieces of the user globus workflow into separate tickets (of which this is just one).  The others are linked to from the description and are under the globus epic
