### ISSUE TITLE
Review tool tips in deposit form

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2858]
When updates to the deposit form for HFS and Globus are complete, review tooltips to make sure they reflect those changes.

**Comment by mjgiarlo** [comment]
@amyehodge Is this a ticket for you or for a dev? Is it ready or in progress or should it stay in the backlog?

**Comment by amyehodge** [comment]
@mjgiarlo This is for me; I've assigned it to me. This is not ready -- I want to wait until the functionality is finalized before I see if there need to be any updates. I don't expect there to be many that need changes.

**Comment by mjgiarlo** [comment]
@amyehodge OK, no problem. I'd like to link this issue to the blocking issues. Do you have a sense of which ones you'd like done before doing this review?

**Comment by amyehodge** [comment]
@mjgiarlo You know what, we can close this ticket. I just went to check which tooltips might need updating to see which tickets would impact this and it turns out that nothing we are doing will impact the tool tips. So, basically, I just completed this are there is nothing further that needs to be done.

**Comment by mjgiarlo** [comment]
@amyehodge OK, awesome! Thanks 😄
