### ISSUE TITLE
As a user when I click deposit for a globus upload, store the list of files in H2

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#2861]
When the user clicks deposit for a globus upload, we need to go get files from the globus endpoint for their deposit and add them as AttachedFiles to that work.  We also need to know that these files came from globus and were not uploaded (possible changes to the AttachedFile model).

Currently do not have any knowledge of those files in H2.  However, #2852 describes a user being able to create V2 of a globus object and add to/replace/remove existing files (that were originally deposited via globus).

For this to work, we would need knowledge of these files, either at the time v2 is created (by pulling the cocina from SDR), or at the time V1 is deposited (by using the globus API), and then we would need to store this list of files in the H2 database.

We need to come up with an implementation plan for this so we can do #2852

**Comment by mjgiarlo** [comment]
Blocked by https://github.com/sul-dlss/globus_client/issues/9 ?

**Comment by peetucket** [comment]
Yes, but i can't seem to make the dependency across repos (insufficient permissions)

**Comment by mjgiarlo** [comment]
@peetucket I apparently just did it in the zenhub UI so I think we're good?
