### ISSUE TITLE
[HOLD] Notify user when there is a version conflict and prevent them from opening a new version

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2864]
HOLD for UI decision from Amy (?)

Any time a user clicks on the pencil icon to edit any previously deposited work, we should compare version numbers between Argo and H2. This includes doing this check on items in a draft state that they have come back to edit again (I think we'll have to include this, yes, in case it's been sitting in draft for 6 months?).

- If both Argo and H2 have the same number of versions, then the user will be allowed to edit the item. 
- If there is a mismatch in the number of versions between Argo and H2, the user will not be allowed to open the form and edit the item.
-- The user should be shown a message instructing them that they will need to talk with us about editing. **(this needs design)**
-- An email notification should be sent to SDR Admins. Email text at https://docs.google.com/document/d/1TZVILUrORI25kRZyUZ70vMQYo90Ngp_tqCI7BdU_VyQ/edit#heading=h.iewd5vxbas3i and below:

> Subject: An H2 version mismatch error has occurred 
> Body: 
> 
> Dear Administrator,
> 
> [user sunet ID] has attempted to edit [item.name] (item.workid) in the [collection.name] collection and has encountered a version mismatch error.
> 
> The Stanford Digital Repository Team

Note that we do not need to do this check for initial drafts because Argo does not yet know about these items and therefore it should be impossible to have a version mismatch.

It also seems like we need to do 

Questions:
- Can we exclude mismatches solely due to embargo releases, as these should be fine to be edited?
- Do we need to address the use case where the item is open in Argo and presumably being edited?
-- Ideally we should detect this as well and prevent the user in H2 from editing

**Comment by amyehodge** [comment]
Suggested text for the message to users. Note that I'm intentionally thinking that less is more in this case.

> Your item can not currently be modified. Please contact SDR staff at sdr-contact@lists.stanford.edu or via the help link above for assistance.

**Comment by mjgiarlo** [comment]
Is this attached to one of our epics or should this be outside the scope of the current work cycle?

**Comment by amyehodge** [comment]
> Is this attached to one of our epics or should this be outside the scope of the current work cycle?

@vivnwong indicated this was in scope for this work cycle and @peetucket opted to leave it without an epic since none really apply, but he's put it in the ready. I'm fine if it gets attached to an epic if that keeps it from falling between the cracks.

**Comment by mjgiarlo** [comment]
We decided not to move forward with this due to concerns around performance.
