### ISSUE TITLE
Add feature flag for new globus upload support

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/happy-heron#2874]
Globus upload support requires changes that we do not want to release to prod until the full workflow is completed. 

Add a feature flag setting for globus upload features and also allow a query string param (e.g. `globus=true`) to enable globus features. If at least one is true, enable the globus features.

Having a query string param will make it simpler for cypress to run tests on the front end javascript new features.

**Comment by peetucket** [comment]
Completed by #2875
