### ISSUE TITLE
Lock items for editing in H2

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2880]
We have identified a set of items that have been modified outside of H2 and should therefore be locked in H2 to prevent their further editing there. I'm hoping that someone can write a script to do this so they don't have to be done one at a time by hand as there are over 300 of them.

All items in the following 8 collections should be locked. Skip any item that is already locked (I know of 3 items that are already locked):

km092my4610
ft306nd3768
nj669yc9949
jm681xz5805
dn308bq6123
yd955cs5721
yw836rh9143
hr920pc0585

In addition, these 69 individual items should be locked:

ty997vz5847
rw694qh3935
mq184tk7726
yn442xf7245
gq661wq7355
kp253qp6280
kb219xm5239
ph230vc2183
bw629xf8940
bh646gn6043
vp123jj3577
bp210jw8496
rp024kr0540
bk301jh4981
jj231js1483
jx762pf4910
sk296vs9698
hg178tf3161
qw554jt1143
cd292zy7226
cm493kp4086
cp665mt7231
dz730vt9384
gc052sn0539
gv696hp6712
gx690yr5264
gy093vv6464
jg592xf2051
jh781jc7000
jq702nw8632
jw764bx3994
mf441fh4427
mh353rg5893
nb982xp2484
nz506bg1335
pk855yv7627
qj782qq2957
rt010jc1825
sp311bw2936
wd541bt5032
ww303ns5342
xv665wg1672
yk849pt7273
yz846hq2486
kj266bp6696
kv216rg1561
qv118vn8574
zm215bs8409
vr813gk6824
bb390wn9224
vh549zx7252
kx439qq9249
rd381cq2558
wz837dg8589
dr256qn8279
bs374hx3899
mc421yx0335
zc963nt7495
bn930qv0208
jh093tq0931
td784vq8122
kz354wt1387
vv654pm1204
bg823wn2892
yg514nn4311
ng380gm7028
dp872vw9896
rv840qz8865
tf546jp6572

**Comment by peetucket** [comment]
Script complete and run, all works listed above and all works in listed collections should now be locked.
