### ISSUE TITLE
Deposit button enabled for globus objects when ready

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#2884]
#2875 disables the deposit button via JS when the user selects the globus upload option (and the feature flag is set).  However, we need to be able to re-enable the deposit button once the work in #2847 and #2848 is complete

Basically, for a user who is setup in globus already, once they have clicked "save as draft", and we've been able to setup their globus endpoint, we can are now read to enable the Deposit button.  This can happen once they check a new checkbox called "I've finished uploading my files to Globus".

The Deposit button is disabled is (1) the new work is not yet persisted (i.e. not yet saved as draft), but they've selected the globus upload radio button (which is handled by the work in #2875), (2) the new work is persisted and is in the new states defined in #2882 (`globus_setup_first_draft` or `globus_setup_version_draft`), and (3) they've selected the globus upload radio button, the work has been saved as draft and an endpoint was created (so work is in the "first_draft" or "version_draft" state), but they haven't yet checked the "I've finished uploading my files to Globus" checkbox and saved as draft to pull the files from globus.

**Comment by peetucket** [comment]
@justinlittman wanted to check in with you before i pick up this ticket having to do with fixing how the deposit button gets enabled/disabled for globus deposits (since it may be part of what you are currently doing)

**Comment by mjgiarlo** [comment]
I believe https://github.com/sul-dlss/happy-heron/pull/2913 has unblocked this issue. Confirm/deny, @justinlittman?

**Comment by justinlittman** [comment]
I suspect this ticket is done. Confirm/deny @amyehodge ?

**Comment by amyehodge** [comment]
I'm pretty sure this worked properly when I tested it before the break. I can't verify that it works now because of the other issues I reported, but I think we can close this.

**Comment by mjgiarlo** [comment]
OK, closing. thanks!
