### ISSUE TITLE
Incorrect fileset external identifiers on update

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/happy-heron#2886]
H2 is creating incorrect external identifiers when performing an update.

See, for example, https://argo.stanford.edu/view/hp267yt1382:
![image](https://user-images.githubusercontent.com/588335/205360631-17769f5d-1640-4bf1-8fb5-94a2b15b533a.png)

This is occurring here: https://github.com/sul-dlss/happy-heron/blob/main/app/services/cocina_generator/structural/generator.rb#L54-L56

Instead, H2 should be re-using the existing fileset identifier (if there is one), otherwise it should be generating one using the approach from https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/id_generator.rb. (Perhaps this should be moved to Cocina gem?)

**Comment by mjgiarlo** [comment]
@justinlittman Is this for the current work cycle, or the first responder, or neither? Thanks! (Doing board grooming.)

**Comment by justinlittman** [comment]
@mjgiarlo Either, but not one.
