### ISSUE TITLE
Error on attempted deposit of files with the same name

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/happy-heron#2891]
HB errors on [stage](https://app.honeybadger.io/projects/77112/faults/91320175) and [qa](https://app.honeybadger.io/projects/77112/faults/90963970) when doing the following steps:

1) Start a new version of a work.
2) Upload a file with the same name as one that already is on the work. Click Deposit.
3) You should correctly get an error that you need to have unique filenames.
4) Delete the original version of the file so there are no longer two with the same filename.
5) Click Deposit. Error triggered, and H2 shows the "something went wrong" page.

If you delete the original file first, it does not raise an error.

**Comment by peetucket** [comment]
This was merged ~3 weeks ago, which added validation to prevent saving a record with duplicate filenames, and could possibly be related: https://github.com/sul-dlss/happy-heron/pull/2800

**Comment by amyehodge** [comment]
@lwrubel @peetucket I have successfully recreated this error in production and generated [this HB error](https://app.honeybadger.io/projects/77112/faults/91338356).
