### ISSUE TITLE
Users can edit lists of files that have been uploaded

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#2893]
Regardless of version 1 or later, or how files were uploaded to an object (globus, browser, zip expansion), users should be able to edit the list of files in an object in their existing hierarchy.  The current H2 UI allows users to delete a file, add a description or hide a file, or add a new file.  This new interface would replace the existing interface and allow for the same behaviors, in addition to replacing an existing file and adding files within existing folders.

Simplification: use checkboxes for hide/show changes, as this mimics current functionality and is easier to implement.

See https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471005613 for the UI

For this ticket, implement:
- display of hierarchy
- show/hide
- edit description
- delete

Follow on ticket to implement add files/replace

The icons to implement as shown are are:
- ![Screen Shot 2022-12-07 at 1.04.31 PM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/f30aa732-1102-4559-aa6c-950b47f3fe40): deletes the file

Ignore the hide icon and the replace icon.  We will checkboxes to show/hide as in the current design.  See https://stanfordlib.slack.com/archives/C69UZCJ8M/p1673986693423669 for discussion.

For some background/history, see #2852 which was simplified down to this ticket.

**Comment by peetucket** [comment]
@astridu : when you have a chance, can you see if my description of the file editing interface (https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471005613) in this ticket makes sense?

**Comment by astridu** [comment]
Yes, makes sense. 
Re: adding a file to the top level folder, we could do something like this. Place an 'Add another file' button at the top of whatever list exists. When user clicks the 'Add another file' button, their file will get placed in alpha order at the top level. 
This is what it looks like when user first comes to the page and sees the one file they have already deposited.
<img width="667" alt="image" src="https://user-images.githubusercontent.com/42216982/206306680-8dcf754c-5df4-4005-a335-7362f260cc4e.png">

They then click 'Add another file' and see the drag and drop UI. They then upload their file and see it in the list in alpha order at the top level.

**Comment by astridu** [comment]
What it would look like if user had deposited files with folder hierarchy
<img width="667" alt="image" src="https://user-images.githubusercontent.com/42216982/206309040-1add5d8c-f5a9-4abb-940d-a90a215116e0.png">

**Comment by peetucket** [comment]
Will be helpful to complete #2943 first since there will likely be similar code use.
