### ISSUE TITLE
For v2 of an object, only the new files display on purl

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2897]
Testing on qa with work https://sul-h2-qa.stanford.edu/works/310

This work has 5 files added via the zip file upload on v1.
For v2, I selected a single additional file as described below, and the PURL update showed only the new file.

1. Clicked pencil icon to edit
2. entered version comment
3. dragged over a single file; list now shows 6 files
4. inadvertently saved as draft; clicked pencil icon to edit again
5. deposited item without further changes
6. view page displays all 6 files and shows all of them are Hide=no
7. PURL page shows only the new file https://sul-purl-stage.stanford.edu/ng865pf9314

**Comment by justinlittman** [comment]
Let's try to replicate after https://github.com/sul-dlss/happy-heron/pull/2889 is merged and zip PR is rebased.

**Comment by justinlittman** [comment]
This is a zip-specific bug.
