### ISSUE TITLE
Scroll long lists of files on item view page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2910]
See mockups 1 and 2 on https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471212700_long_List_Item_View

User sees 15 lines (folder and file names) in the file section, and the rest can be seen when scrolling through that section.

If this takes a long time to load, load the rest of the page first and present a spinner/wait image over the file section so user knows it's still in progress but they can see the rest of the page while they wait.

File list view:
![Screen Shot 2022-12-13 at 2.47.04 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/48b241bd-ac67-4a92-b1c3-0fd9c7918d99)

Wait state:
![Screen Shot 2022-12-13 at 2.47.13 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/52e03d5a-e645-40fb-b8a8-be812972c6bc)

Analogous to the #2920 (which is the same thing on the item edit page)

**Comment by justinlittman** [comment]
Implementation note: This should probably be handled with a turbo frame.
