### ISSUE TITLE
Display number and total size of all files in globus folder on item edit page

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#2912]
For a globus deposit in the draft state (either first_draft or version_draft), when the user is on the item edit form, we should display the total number of files and the total size of all of the files in their globus endpoint.  This allows the user to have a visual clue that they have correctly placed files in their globus folder and they when they click deposit, the expected number of files will be deposited.

see https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471005611 
see sul-dlss/globus_client#34

Note: we expect this may cause performance issues as is dependent on the globus API.  It may also need to be async.

**Comment by peetucket** [comment]
thanks for the heads up ... created in the wrong repo by zenhub...moved  to h2

**Comment by peetucket** [comment]
Note: benchmarks indicate that for a given path, we can expect it to take roughly number_of_subdirectories * 1.25 seconds to complete, so content that has many directories will take a long time to complete.

So:

1. In we expect most globus deposits to *not* have a large number of files/directories (e.g. > 100 or so), we could implement this and will work reasonably well for most cases, but for objects with very large number of files/directories, it will either time out or take a long time.  This will not prevent the user from proceeding with the deposit though.

2. If we do expect many globus objects to have many files/folders, we could look into implementing an "empty/not-empty" display instead of counting files and file sizes.  In other words, we can at least indicate to the user if there is *any* content in the globus folder (yes/no) vs the amount of content found.  We believe we can implement this is in a way that will be performant in call cases.
 
3. In any case, if implemented, we should do this async and render the result in a turbo frame (so we don't have to wait for the operation to complete to render the rest of the page).

**Comment by justinlittman** [comment]
I've implemented this using a turbo-frame. It takes over a minute to render:
![image](https://user-images.githubusercontent.com/588335/211037248-2be0cf11-5f21-4507-ba59-472317f07f96.png)

during which the user sees:
![image](https://user-images.githubusercontent.com/588335/211037420-d4c2e3a2-f431-4524-b5ba-ca7649257d35.png)

I'd suggest that this is not a good user experience, since it likely to be unclear to the user what actions can or cannot be performed while waiting.

**Comment by mjgiarlo** [comment]
We decided not to move forward with this.
