### ISSUE TITLE
Scroll long lists of files in deposit form

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2920]
See mockups at https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471258804_long_List_Deposit_View_Drop_Zone

User sees a max of 15 lines (folder and file names) in the file section, and the rest can be seen when scrolling through that section.

Mockups show where this fits with dropzone for the different scenarios.

Analogous to #2910 (which is the same thing on the item view page)

**Comment by mjgiarlo** [comment]
You may want to coordinate with @justinlittman since he's working on stuff in this area as well.
