### ISSUE TITLE
Message and button to indicate Globus setup is complete should show up on view page the first time item is saved as draft. (on stage)

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2928]
Once I save a draft, a message should appear on the view page that tells me to go do stuff and then come back. For some reason, I am having to save as a draft twice in order to get that message to appear. So:

1. open new item
2. select Globus option
3. fill in form fields
4. save as draft
5. returned to view page. no message displays. refresh a bunch. wait. hard refresh. nothing.
6. edit item — do nothing but scroll to bottom and save as draft again.
7. returned to view page and this time the message displays immediately.

I was able to replicate this.

**Comment by justinlittman** [comment]
@amyehodge Can you provide a screenshot of the expected message?

**Comment by amyehodge** [comment]
@justinlittman it's the content in the pink/red box:
<img width="817" alt="Screen Shot 2023-01-05 at 2 31 20 PM" src="https://user-images.githubusercontent.com/5558511/210864617-14bd0461-c6a9-47e7-832b-0e6ed3c9f063.png">

**Comment by amyehodge** [comment]
With the system now recognizing my Globus account, I can no longer tell if this is still a problem. I'm going to consider this as no longer blocking for user testing, but will keep an eye out during the testing by users without a Globus account to see if it happens to them. If so, I'll file a new ticket.
