### ISSUE TITLE
H2 does not recognize that I have Globus account set up (on stage)

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2929]
When I click on the button on the view page to indicate that I'm done setting up Globus, it tells me that I haven't set up an account yet, even though I was actively logged into Globus at the time and definitely have an account.

I’m now stuck and unable to finish the deposit. We need this to work for user testing.

**Comment by lwrubel** [comment]
This is likely the issue: the access token from Globus includes `"expires_in":172800,` which is a 48-hour expiration. The token is created in the [globus_client initializer](https://github.com/sul-dlss/happy-heron/blob/6ebb79bfd23b10d341216e5dfdebaa11b332a709/config/initializers/globus_client.rb#L3).

**Comment by lwrubel** [comment]
See #2937 for work to request a new access token.

**Comment by lwrubel** [comment]
See #2937 for work to request a new access token.

**Comment by lwrubel** [comment]
Closing since the work moved to #2937.
