### ISSUE TITLE
Globus upload should not include .DS_Store files

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2935]
Globus file upload option on QA picked up a .DS_Store file that we don't want it to pick up. 
Particularly odd is that even when I display hidden files on my machine, I don't see this file, so I'm not sure where it's coming from.

![Screen Shot 2023-01-05 at 3.37.01 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/91fc00c9-e173-423c-b55e-79fc77394377)

**Comment by justinlittman** [comment]
See the filtering that occurs when unzipping: https://github.com/sul-dlss/happy-heron/blob/main/app/jobs/unzip_job.rb#L32-L34
