### ISSUE TITLE
Request new access token more frequently

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/happy-heron#2937]
Globus API access tokens currently expire in 48 hours. An access token is requested via the `globus_client.rb` initializer when the app is deployed and/or passenger restarted. We will need to get a new access token more frequently, at some step in the interactions with Globus. Note, if a request for a new access token were done with every call to Globus, this could make rendering Globus directory contents (e.g. `GlobusClient.list_files`, `GlobusClient.get_filenames`) take even more time. 

We could instead request a new access token if the initial call returns a 401. 

Example response for an expired token: 
```
{'errors': [{'detail': 'Call must be authenticated',
   'code': 'UNAUTHORIZED',
   'title': 'Unauthorized',
   'status': '401',
   'id': '26d048ac-3a56-4d34-b121-ffc42b5d7682'}],
 'error': 'unauthorized',
 'error_description': 'Unauthorized'}
```

**Comment by mjgiarlo** [comment]
@lwrubel Thanks for writing this up and running with it!

**Comment by lwrubel** [comment]
What do we want to have happen in H2 when refreshing the token does not work, in addition to notifying via Honeybadger? This could happen when there is some other problem authenticating to the Globus API. For example, would we want to show some kind of notice to the user about there being a problem and admins having been notified?

**Comment by lwrubel** [comment]
@amyehodge and I discussed how to handle this and decided to wait and see. Since it doesn't seem like this will be a very likely or frequent situation, we'll just make sure Honeybadger notifies about an error and ideally, includes a user and work when known. If we find this situation happens enough in production, we can flash a message and will know better at that point what the message should actually say.

**Comment by lwrubel** [comment]
Re-opening because we need to update the Gemfile in H2 and confirm that Honeybadger notifications are configured correctly.
