### ISSUE TITLE
Files not retrieved from Globus/likely related HB error

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2948]
We triggered this HB error during user testing on STAGE, so fetching of files from Globus did not complete. https://app.honeybadger.io/projects/77112/faults/92396628 

During testing on STAGE, the user 1) created a new item and checked the Globus option 2) saved the item as a draft 3) used the back button on the browser to return to the form 4) checked the Globus option and saved as draft again. Could this have caused this problem? I see there is some uniqueness constraint that is being violated. And could this be why the file fetching from Globus is stuck? Thanks!

**Comment by lwrubel** [comment]
@amyehodge I'm trying to replicate this locally, but I'm having trouble getting the steps right, I think. When they did step 4 after hitting Back, do you remember if that was a new, empty form? I'm assuming the Globus option they clicked this second time was the "Upload one or more files (>10GB) via Globus web-based transfer software" not the checkbox to indicate that the deposit was complete?

**Comment by amyehodge** [comment]
I just watched the recording and did exactly what she had done and was unable to replicate the error. For the record, here are the exact steps she took:

1. created new item (chose Data type and Tabular Data subtype), selected Globus option, saved as draft
2. clicked on 20223 User Testing Collection bread crumb
3. clicked on Collection details tab
4. clicked the browser back button twice
5. clicked Globus option, saved as draft again
6. clicked on the collection title in the details box
7. clicked on dashboard in breadcrumbs
8. clicked on the pencil icon next to title of item
9. agreed to the terms of deposit
10. clicked on the box that all files have been deposited
11. clicked on saved as draft -- here's where it seemed to get stuck

**Comment by lwrubel** [comment]
Closing at @amyehodge's suggestion since we can't get this to happen anymore.
