### ISSUE TITLE
Update file upload options and Globus instructions on deposit form for 

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2957]
**1. Update file upload options**
Update text of all options under **Add your files** to provide more clarity to users. They should read as follows:

- **Upload one or more files (less than 10GB) to be displayed as a flat list of files.**
- **Upload a single zip file (less than 10GB) which will be unzipped and displayed in its original order, including any file hierarchy**
   Viewers will see the file hierarchy and be able to download individual files.
- **Upload one or more files (more than 10GB) which will be displayed as uploaded, including any file hierarchy.**
   Viewers will see the file hierarchy and be able to download individual files.

**2. Update Globus instructions**
In addition, when the third option for Globus is selected, this section should expand so that users see the instruction steps below. Other than the links in the text to parts of the instructions, this section has no interactivity.

![Screen Shot 2023-01-17 at 3.35.48 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/ade418fc-d29a-4b60-ae66-81be35355c17)

See Step 1 at https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471628807_Globus_Integ_Enh

In case you want to copy and paste, here's all the text for the above:
STEP 1
Scroll to the bottom of this page and click "Save as draft." 
You can finish filling out the form now or later.

STEP 2
Set up a Stanford Globus account, following these [instructions|https://docs.google.com/document/d/10b7y3yZCOfyVJ_uP4l7QHbkILQKnfdJi9hj-MpmmdIk/edit?pli=1#heading=h.ptdws4k1wnlz]. 
Have a Stanford Globus account? Skip to Step 3.

STEP 3
Complete  Globus setup (may require software installation) following these [instructions|https://docs.google.com/document/d/10b7y3yZCOfyVJ_uP4l7QHbkILQKnfdJi9hj-MpmmdIk/edit?pli=1#heading=h.3h6eldy9ndya].

STEP 4
Return to your item at sdr.stanford.edu and click the button that says "Globus setup complete."
Don't see this button? Proceed to Step 5.

STEP 5
Check your email from "Globus Notifications."
Click the link in the email and follow these [instructions|https://docs.google.com/document/d/10b7y3yZCOfyVJ_uP4l7QHbkILQKnfdJi9hj-MpmmdIk/edit?pli=1#heading=h.f2rvtrjiw01] to complete your upload.

STEP 6
Return to this page and make sure the form is complete. Then click "Deposit."
This will move your files from Globus to the SDR.

**Comment by lwrubel** [comment]
I think the instructions in italics on Step 2 should say "Skip to Step 5 if you already have a Stanford Globus account." If someone completes Step 1 and they already have a Stanford Globus account, they shouldn't have to do Step 3 or Step 4. 

I'm assuming these instructions stay visible until the deposit is complete? I'm thinking about the step when someone returns to the page after uploading their files and need to click the "All files uploaded to Globus" checkbox. The checkbox would be below the steps?

**Comment by lwrubel** [comment]
Sorry, I missed seeing the mockup with the checkbox in the full list of screenshots at https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471628807_Globus_Integ_Enh. So that last question above is answered. :)

**Comment by amyehodge** [comment]
@lwrubel It's tricky, because even if they have a Stanford Globus account, they may not have installed the software or set up the Google Drive connector or investigated the Oak/Sherlock connection (depends on where their content is). So, I definitely DO want them to look through the instructions on Step 3. We are checking that they have logged into an account, but there is no way for us to know that they've done the work in Step 3. It's a little awkward, but I think these instructions are fairly clear without requiring the drawing of arrows, etc.

**Comment by amyehodge** [comment]
Also, note that the instruction links are sending people to specific headers in that document to help them find what they need. I'm hoping it makes it easier for folks who had difficulty in our testing with the length of that document. It does mean I have to be *very* careful about not deleting and creating new headers or it will break the links. One other solution would be dividing parts of the documentation into separate Google Docs, which also didn't seem great.

**Comment by lwrubel** [comment]
Thanks, I understand now why they should do Step 3 regardless of their Globus account status and why the "Don't see this button?" note is on Step 4.
