### ISSUE TITLE
Update message when fetching files from Globus

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2959]
This could take some time, and users weren't clear what they could do here in the meantime. They also had a hard time seeing this, so we'd like to make it larger and a different color.

When fetching files from Globus, message on item view page should read:

Transferring your files from Globus. This could take some time depending on file size. You may leave this page or close this window and return later.

![Screen Shot 2023-01-17 at 3.41.08 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/57994b84-eac2-4dbd-9b41-c62a30e5b2a9)

**Comment by astridu** [comment]
orange: D1660F

**Comment by lwrubel** [comment]
I want to make sure I understand at what point in the workflow this message should appear. There is a "Fetching from Globus" spinner that appears after the user clicks the "All files have been uploaded to Globus" checkbox and then clicks the "Save as draft" button. Should this new message replace that? 

Or should this appear at another point in the workflow?

**Comment by amyehodge** [comment]
@lwrubel Yes, this message should replace that.

**Comment by amyehodge** [comment]
@lwrubel That makes sense. The new message is much too long to display there. Thanks.

**Comment by amyehodge** [comment]
@lwrubel I think providing the information is worth the wrapping at this point. Thanks for checking.
