### ISSUE TITLE
Ensure name roles as shown in design doc are up to date in the app

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#296]
See #232

**Comment by jcoyne** [comment]
Design doc has:

> List of roles for dropdown menu:
Individual
Author
Composer
Contributing author
Copyright holder
Creator
Data collector
Data contributor
Editor
Event organizer
Interviewee
Interviewer
Performer
Photographer
Primary thesis advisor
Principal investigator
Researcher
Software developer
Speaker
Thesis advisor
Organization
Author
Conference
Contributing author
Copyright holder
Data collector
Data contributor
Degree granting institution
Event
Event organizer
Funder
Host institution
Issuing body
Publisher
Research group
Sponsor
