### ISSUE TITLE
Files with the same name in the same directory raise RecordNotUnique error

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/happy-heron#2980]
With regular upload, the user gets an error in the UI if two files have the same name. @amyehodge can verify, but it looks like this situation occurred through a zip upload? 

[happy-heron/qa] ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_active_storage_blobs_on_key" DETAIL: Key (key)=(druid:zm106cy8043/1/my-icons-collection/license/license.pdf) already exists. #2980 

## Backtrace

    line 108 of [PROJECT_ROOT]/app/models/work_version.rb: block in switch_to_preserved_items!
    line 103 of [PROJECT_ROOT]/app/models/work_version.rb: each
    line 103 of [PROJECT_ROOT]/app/models/work_version.rb: switch_to_preserved_items!

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/77112/faults/92772341)

![Screen Shot 2023-01-24 at 7 43 57 AM](https://user-images.githubusercontent.com/1619369/214294788-d6fede4c-6e1e-46ae-b12f-b8720c90e886.png)

**Comment by amyehodge** [comment]
I believe @justinlittman has addressed this issue. Does that sound right @justinlittman ?

**Comment by justinlittman** [comment]
Yes, unless I didn't (in which case can be re-opened).
