### ISSUE TITLE
Globus deposits encounter 500 error and do not complete

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2992]
See HB error https://app.honeybadger.io/projects/77112/faults/93007857

Another user and I both encountered this issue. My object is https://sdr.stanford.edu/works/6256. His is work_version_id: 7951, druid: druid:kq456hs1417. He did get it successfully deposited the first time. 

For work_version_id: 7951, druid: druid:kq456hs1417, it looks he deposited it the first time the old Globus method (i.e. without any files) and then today saw the new feature, selected that, and tried to deposit that way. He did not run into any problems until he clicked the "Deposit" button and now it's spinning.  

For work 6256, which is my test, I selected the Globus option and deposited about 100 kb (so tiny!) in 8 files, one of which I uploaded via H2 after the Globus file transfer. I also deleted some files. I too had no issue until I clicked deposit and it's just spinning. My object also triggered this HB error.

I just successfully deposited https://sdr.stanford.edu/works/6257, so it's not a global issue.

**Comment by lwrubel** [comment]
sdr-api-prod is not able to access the globus files. It doesn't look like it is mounted to sdr-api-prod, so I've put in operations-tasks ticket:  https://github.com/sul-dlss/operations-tasks/issues/3278

I've added `globus_location` to shared_configs for sdr-api-prod, since that was also missing.

**Comment by lwrubel** [comment]
Timeout still occurred with the read_timeout setting being increased, so reopening.

**Comment by lwrubel** [comment]
Re-closing since the globus mount was completed and a globus deposit has gone through. I created a separate issue about the timeout still happening with one of these works. https://github.com/sul-dlss/happy-heron/issues/2995
