### ISSUE TITLE
Preferred citation on PURL page should include the actual PURL link

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2997]
See https://sdr.stanford.edu/works/6284 and the purl at https://purl.stanford.edu/rx114mz1833. 

In H2, it's showing the purl link in the auto-generated citation:
<img width="954" alt="H2" src="https://user-images.githubusercontent.com/5558511/216386588-a2f97332-136b-4533-a068-6d72efa333bf.png">

But this is not displaying on the PURL:
<img width="736" alt="purl" src="https://user-images.githubusercontent.com/5558511/216386634-44130c0d-ebbd-4e28-9d60-fc70b110ad49.png">

The above was a test Globus deposit, but the following was just a single small file done entirely via H2, and it has the same problem:
https://sdr.stanford.edu/works/6285
https://purl.stanford.edu/mq075mr3577

**Comment by andrewjbtw** [comment]
The value is also not in the underlying XML, so it must not be getting picked up when the publish happens.
```
 <note type="preferred citation">Hodge, A. (2023). This is a sample deposit using the Globus system. Stanford Digital Repository. Available at :link:. </note>
```

**Comment by andrewjbtw** [comment]
Looking at mq075mr3577, the internally stored Cocina in SDR does not have the Purl, just the `:link:` value.

```json
 "note": [
      {
        "value": "Hodge, A. (2023). This is a test of the auto-generated citation. Stanford Digital Repository. Available at :link:. ",
        "type": "preferred citation"
      }
    ],

**Comment by lwrubel** [comment]
@amyehodge wondering if there is some delay in the Purl page getting updated? I now see this on the Purl page: 

![Screenshot 2023-02-02 at 2 22 34 PM](https://user-images.githubusercontent.com/1619369/216429517-fd0e1dd8-d7c2-463b-b4aa-51e67642605c.png)

The [other test work](https://purl.stanford.edu/mq075mr3577) is still showing :link: at the moment, so I'm watching that.

**Comment by andrewjbtw** [comment]
Oh, sorry. I clicked republish on rx114mz1833 manually, which must be why that one got updated. I saw the Cocina showed the correct value.

**Comment by lwrubel** [comment]
OK, good to know how that got pushed out. And also that you saw the purl in the Cocina.

**Comment by amyehodge** [comment]
@lwrubel @andrewjbtw Here's the full list of items I found with this problem by looking through the recent activity table on the admin page in H2 for the last 7 days:

tr806nn5051
zj466pw3463
pm007md6862
tb076ph9251
vp674vf0950 -- test object of mine
mq075mr3577 -- test object of mine

Short list at this point, thankfully.

**Comment by peetucket** [comment]
The PR #2999 above fixes the bug for new objects, but we still need to remediate the data in the objects above

**Comment by peetucket** [comment]
Peter will fix the other druids listed manually in the database cocina and then re-publish to ensure the DOI and PURL links make it on the PURL page.

**Comment by peetucket** [comment]
All PURL and DOI links for objects listed above fixed in cocina and re-published to fix PURL pages.  We believe this problem first ocurred with the main branch of H2 was deployed on monday with all of the new code and should be fixed as of this afternoon.
