### ISSUE TITLE
When Globus items are versioned, file hierarchy should be retained

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2998]
Desired behavior: content uploaded with file hierarchy should retain that hierarchy when versioned. That is currently not the case, at least for this Globus deposit (notes on testing the zip file upload option are in a comment below).

See https://sdr.stanford.edu/works/6284.
This was a deposit done via Globus. Went fine the first time (other than setting off this HB error https://app.honeybadger.io/projects/77112/faults/93159350).

I then edited this item and removed a single file. This again all appeared to go as it should, but when the page reloaded after the deposit was done, the file hierarchy was gone:

view page
<img width="979" alt="Screen Shot 2023-02-02 at 12 00 31 PM" src="https://user-images.githubusercontent.com/5558511/216392031-6da277fc-f990-4801-8f81-76bba96d1e21.png">

deposit form
<img width="1104" alt="Screen Shot 2023-02-02 at 12 00 22 PM" src="https://user-images.githubusercontent.com/5558511/216392006-6fbbc514-104f-47e7-9e14-7fc3f30cedfc.png">

In addition, Argo now shows only a single file
<img width="999" alt="Screen Shot 2023-02-02 at 12 01 17 PM" src="https://user-images.githubusercontent.com/5558511/216392056-c31c0e4f-9da4-44df-b385-83397a4bc917.png">

while the PURL page is showing all the original 19 files still. I even republished the PURL, but maybe there is some delay on updating here? Though if it did update I assume it would show the single file that Argo shows.
<img width="1204" alt="Screen Shot 2023-02-02 at 12 02 51 PM" src="https://user-images.githubusercontent.com/5558511/216392315-d3df2e08-732f-4733-b583-0c2266749531.png">

**Comment by amyehodge** [comment]
Yes, this is happening for content depositing via a single zip file for unzipping as well. See https://sdr.stanford.edu/works/6286 -- druid:pd772pv7120.

**Comment by peetucket** [comment]
verified in localhost  with a zip file that started out as hierarchy.

everything was fine until I started a new version of a deposited item, immediately upon saving the draft, it looks like the paths of the attached files on the new work version had the `/` replaced with a `-`, which messes up the hierarchy.

for example:
```
 #<AttachedFile:0x000000010e8b1f00
  id: 107,
  label: "asdsad",
  hide: false,
  work_version_id: 93,
  created_at: Fri, 03 Feb 2023 00:14:46.764778000 UTC +00:00,
  updated_at: Fri, 03 Feb 2023 00:15:23.814472000 UTC +00:00,
  path: "test images/at_level_1_a/SpongeBob1a.jpg">,
```

becomes

```
 #<AttachedFile:0x000000010f4c32f8
  id: 116,
  label: "asdsad",
  hide: false,
  work_version_id: 94,
  created_at: Fri, 03 Feb 2023 00:17:31.916462000 UTC +00:00,
  updated_at: Fri, 03 Feb 2023 00:17:31.922840000 UTC +00:00,
  path: "test images-at_level_1_a-SpongeBob1a.jpg">,
```

**Comment by peetucket** [comment]
Looking at the rails console on localhost, I can see where these new attached files are created and attached to our new work_version when you save as draft on V2 of the item: https://github.com/sul-dlss/happy-heron/blob/main/app/forms/draft_work_form.rb#L196-L201, but I'm not sure why or where that is actually happening.
