### ISSUE TITLE
Technical Metadata workflow step failing on large deposit

### ISSUE THREAD

**Issue by edsu** [sul-dlss/happy-heron#3007]
The solution for this is likely to involve changes elsewhere in SDR but I'm ticketing here because a large H2 deposit is what seemed to surface the problem. 

It appears that there are cases where technical-metadata workflow step is running prior to all the files landing on the filesystem. @andrewjbtw noticed this with [cg185zq8485](https://argo.stanford.edu/view/cg185zq8485), as he was ssh'd into `dor-techmd-prod-a` and could see files changing in `/dor/workspace/cg/185/zq/8485/cg185zq8485/content/` after the workflow error was encountered.

The error surfaces in Argo, but not in Honeybadger. In the case of an H2 deposit the user has no access to Argo, so these would sit and wait for someone with access to Argo to notice and move it along once enough time has passed for the files to completely land.

It seems like the technical-metadata workflow step should not be initiated until all the files land completely?

The reported error in this case was:

```
Problem with technical-metadata-service on dor-techmd-worker-prod-a.stanford.edu: ["/dor/workspace/cg/185/zq/8485/cg185zq8485/content/1ee63015eba36f0e4aa00549233089f3_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/23c9784949701f46f79b9322d1ce8679_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/3458cd25ca904c5cf7ebcfff13966ef2_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/3914ad79c56e23eb789b7aa82557fcce_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/3dfb622d34f562bfc6f0539d1e26337b_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/488d37c8deec81060439835c0bb230c6_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/57aeed2988fc423b4d264d96da82a7ab_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/5b006e28570c3607cd9bb4f389dc1b01_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/75510e005fe4904c89a0b992b95d667a_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/7607ba33b9d0bd84ddae53d369874033_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/78353835b30f6b1d903c2b259d6b4a52_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/79446135b089ce8d2904d7b2afcbdaf2_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/7a28789689c872c5d40b9dc9acf47f24_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/896ce1ec8819c68bf357a419bcca8e5a_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/92188e2fb4f5ea088e233d1f28c1f719_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/92c64a5100900546b71b372180b14f6f_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/9542c2af6d7e12094630398af4a1a2b6_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/96bfd042bd4af53db6eb26492cb4359a_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/9bc2b070882d8f1dfb874cc656c47756_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/9e5146af8eebf02db80c3331ed122a41_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/a3da3ccb018b11abf2e2d7d2d8ddd23f_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/abc64fffb1a54e6c6610fdc8307c7d2e_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/bceb2e378e0e9735d63c8c96ebc051bb_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/bdccea99eed96c8a7bb00b1669a89e5b_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/bfbde65e6887d0bab9aec207f97a32ce_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/c0bb580dbc0fab5f609145d352da11e5_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/c6bfb2bb7fc3b900d65e8fd2e6bac912_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/c6d5919bff143ab5a4cfcd942e9f57cb_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/c7521802f265555c61be8d28687f4b56_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/c7ece3e58049e981a8ab2033c721ea4f_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/f4a7a9f86a2bd0cfc2eac542026ca1fd_raw_cohort.zip not found", "/dor/workspace/cg/185/zq/8485/cg185zq8485/content/f5257c27275c111be0a30fce62839d79_raw_cohort.zip not found"]
```

<img width="1445" alt="Screenshot 2023-02-09 at 10 36 41 AM" src="https://user-images.githubusercontent.com/33829/217864531-a8cfd2cc-9f5b-4e37-8990-c05ef0a7166c.png">

<img width="1445" alt="Screenshot 2023-02-09 at 10 36 58 AM" src="https://user-images.githubusercontent.com/33829/217864562-a493e68f-e1f6-47d7-8686-f3c6637a51c1.png">

**Comment by andrewjbtw** [comment]
It's the whole accessionWF that's starting too early, but after numerous changes to that workflow, the `technical-metadata` step is generally the first one that tries to do any actual work.
<img width="1097" alt="Screen Shot 2023-02-09 at 8 45 33 AM" src="https://user-images.githubusercontent.com/8975583/217881324-d1ff75a2-9b89-4ab3-88ef-3d7da2950d67.png">

I think the sequence is supposed to be:

- Send files
- Send Cocina
- Finish sending files
- Start accessionWF

But what's happening is:

- Send Cocina
- Send files
- Start accessionWF 
- Files are still being sent
- technical-metadata can't find all the files listed in the Cocina

**Comment by edsu** [comment]
@justinlittman observed that both Globus and Blob staging should be complete before creating the workflow [here](https://github.com/sul-dlss/sdr-api/blob/main/app/jobs/ingest_job.rb#L51-L57).

**Comment by edsu** [comment]
This was fixed by https://github.com/sul-dlss/sdr-api/pull/558 which was deployed to production as part of SDR-API as part of [rel-2023-02-22](https://github.com/sul-dlss/sdr-api/releases/tag/rel-2023-02-22).
