### ISSUE TITLE
Report of users in H2 database

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3041]
We need a list of all the SUNet IDs with anyone with a role (depositor, reviewer, manager) in the H2 database. We don't need anything other than the SUNets. No names or roles or anything else is required.

Hannah and I are preparing some new communications. Thanks.

**Comment by jmartin-sul** [comment]
list attached to slack thread -- https://stanfordlib.slack.com/archives/C09M7P91R/p1680549499628719?thread_ts=1680548983.071979&cid=C09M7P91R
