### ISSUE TITLE
Update email to Globus users

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3049]
ON HOLD until we do the other Globus updates in #3021 and #3022.

Update app/views/works_mailer/globus_endpoint_created.html.erb so that it reads as shown below. The Globus instruction link to use is https://docs.google.com/document/d/10b7y3yZCOfyVJ_uP4l7QHbkILQKnfdJi9hj-MpmmdIk/edit#heading=h.3h6eldy9ndya.

Let me know if there is a better way to describe the needed updates for you.

```
<p>Dear <%= @user.first_name %>,</p>

<p>You have initiated a deposit to the SDR using Globus. Here's what you need to do to complete it:</p>

<ol>
  <li> Follow these [instructions](link to ) to set up Globus (may require software installation). Be sure you have logged into Globus with your Stanford credentials!</li>
<li> Go to this [shared folder at Globus](link) that we have created just for you and transfer your files there.</li>
  <li><%=link_to 'Return to your item', work_url(@work)%> at sdr.stanford.edu and click the pencil icon to edit your draft.</li>
  <li>Check the box in the "Add your files" section to indicate that you have uploaded your files to Globus.</li>
  <li>Scroll to the bottom and click "Save as draft" to finish your deposit later, or click "Deposit" to complete your deposit now.</li>
</ol>

<p>If you have any questions, contact the SDR team at: <%= link_to contact_form_url, contact_form_url %></p>

<p>The Stanford Digital Repository Team</p>
```

**Comment by ndushay** [comment]
what is the "shared folder at Globus" and the link?

**Comment by amyehodge** [comment]
@lwrubel Can you help @ndushay with the details on the link to be provided? Thanks.

**Comment by lwrubel** [comment]
Constructed in UI as follows: https://github.com/sul-dlss/happy-heron/blob/1d070aecacb3b5efd36ac8390f96b358bf7ffbd7/app/components/works/globus_setup_component.rb#L32

**Comment by lwrubel** [comment]
Origin id would be different in the case where the user selects Sherlock/Oak/Google Drive. See #3022 for link info.

**Comment by ndushay** [comment]
@amyehodge @lwrubel this email is specific to globus.  Should we have other ones for Sherlock/Oak/Google Drive ?

**Comment by lwrubel** [comment]
@ndushay Since those are also Globus origin endpoints, then links will get set up accordingly via `GlobusSetupComponent#endpoint` like you're doing with your PR.
