### ISSUE TITLE
Investigate solutions for objects with large number of files

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3088]
Deposits in many files are now possible with ZIP or Globus.  Once we have in thousands of files, rendering file lists becomes a problem, sometimes so much so that the user cannot even click the "Deposit" button in H2 because the page never renders.  #3195 tests an object with 25k ZIP files in a zip, which works, but takes ~5 minutes to render the page

One possibility: if the number of files is > 10k (or some other number), do not render the file list, but instead just render a panel on both the work edit and work view page that says:

"There are XXX files in this object, which is more than can be displayed."

This will prevent the user from working with any files individually however, i.e. they will NOT be able to remove files, edit files, add labels, etc.  If we need to provide a separate mechanism for users to "reset" the object (i.e. delete all of the files together), that would be a separate ticket.

This does not deal with the separate but related issues of Argo and PURL pages taking a long time to render (or not rendering).  This purely deals with a user being able to continue their deposit.

Another possibility - paging of file results, or infinite scroll and ajax loading on the fly.

Here is an example with 19k files in Argo: https://argo.stanford.edu/view/druid:hj302gv2126

Note: on pause for now because even if we correct display issues in H2, we still have to deal with the fact that very large cocina objects are problematic throughout the rests of SDR (both for display and for loading into jobs).  So best to consider as part of a more comprehensive effort to handle objects with large number of files.

**Comment by amyehodge** [comment]
@peetucket I believe that if you are trying to version something that has already been deposited and you want to change the files, you could again choose the Globus upload and it would wipe out the existing files and replace it with the new Globus upload. Basically the same if you choose the zip file upload. But if you want to make a small change to just one or a few files, then those are terrible options and you would want to be able to see the whole file list and interact with it.

If you want to change one or a few files on the item before you complete the version you are working on, is it possible to do that at Globus and get H2 to refetch the file list? That's a possible option. It's significantly less better for later versions when we are storing the files in a different location on Globus and we don't want the user to have to reupload everything every time.

But I think we have to maintain a way for the files to be modified in H2 or we are creating another place where modifications can only be made in Argo. And we are trying to eliminate those scenarios.

Can we only fetch the files when the user says they want to modify them? Can we only fetch the files they say they want to modify? Though in that case we have to have some way for them to tell us which files, which may require us to fetch the file list. 🤔

**Comment by peetucket** [comment]
This sounds like it would benefit from a team discussion when we get to working on it.  My understanding of the issue with objects with a large number of file is that there is so much data, it cannot render the web page in a reasonable amount of time.  We may need to thinking about paging or some infinite ajax scrolling view to mitigate, but these are complicated by the fact we also have to display hierarchy.  And again, the issue would be present in H2, Argo and PURL -- this ticket is just for H2.

**Comment by amyehodge** [comment]
Closing as we have a workaround in place for H2.
