### ISSUE TITLE
Admins should be able to edit a work type after an object is created

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3092]
The work type is stored in the `WorkVersion` model and is set when a user first creates a work in H2 via a modal.  After that point, it is not editable by anyone.

As an admin, I want to be able to change the work type for an item so that it meets best practice guidelines, displays in SW in a way that is appropriate for the kind of work that it is, and has a work type that is consistent with other similar works.

- The desired functionality is to add a new admin function that does not open the full work edit form, but showing the full work form is acceptable. 
- Add this feature as one of the list items in the Admin functions on each item view page (see below).
 
![Screen Shot 2023-06-13 at 4.10.24 PM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/852661a2-301a-47bb-8cf5-8b32f4d2d870) 

- If the item is in a disallowed editing state, the option should be greyed out/unavailable.
- If the item is in the deposited state, the admin can select this option. They will then see the work type modal with the current work type selected so that they can make a new selection. 
- The "what's changed" field should automatically be set with "work type changed".
- Once the work type and subtypes on a deposited work are modified, the item will need to be re-accessioned, which means it likely needs to be versioned (in H2 and thus in SDR as well).   This will ensure the PURL is republished and SW record is updated.

Disallowed editing states: Reserving PURL, PURL reserved, Initial draft, Pending approval, Returned, Deposit in Progress, New version in draft, Decommissioned

See https://docs.google.com/document/d/1AeWIp1NulYb3AwXB2ZxwgbFxD33ZAOrqseq7Ixa7_yc/edit and https://projects.invisionapp.com/share/NP138M0QX7T3#/screens/473244398_admin

**Comment by peetucket** [comment]
@amyehodge

1. is there a reason a depositor cannot change the work type/subtype themselves?  or is this really a specific admin feature?
2. if so, should we reconsider the modal approach to selecting work types/subtypes instead of integrating directly into the existing form?  this would reduce a lot of complexity in the code

**Comment by amyehodge** [comment]
@peetucket The reason the user can't do this is because we have a long-range vision of being able to collect metadata specific to the work type, e.g. special fields for images that we wouldn't have for software, etc. This means work type changes would need to be made carefully to make sure mandatory fields got filled in etc. We are adding this in now because it is one of the things that we now have to change via Argo when it needs to be changed, and then we have to lock the item for further editing in H2.

I'm not following question 2, so perhaps we should chat about that.

**Comment by peetucket** [comment]
Ok, great -- just wanted to be sure we weren't making an admin only feature that could be more easily implemented as a user feature.  Question 2 had to do with the current complexity of the way a user must first select a type/subtype before the actual form renders.  Given the user will continue to **not** have the ability to edit types once selected, making it simpler and part of the main form is less relevant.

**Comment by justinlittman** [comment]
I just want to register that this is adding yet another layer of complexity on to work types. This code is verging on being unmaintainable (if we can even manage to implement this feature).

At some point, we're going to need to back out of this modal approach. I understand that in the future we may want to vary the form based on the content type, but this modal implementation is a very expensive and probably incorrect way of preparing for that.

**Comment by amyehodge** [comment]
Is it possible to retain the previous subtype selections when a new work type is selected? Except for "Other," of course, where these are replaced by the text entry box.

See the video below where the item was originally work type "Date" with subtype "Tabular data," and when I changed it to work type "Software/Code" the "Tabular data" selection disappears.

![workTypeEdit](https://github.com/sul-dlss/happy-heron/assets/5558511/2521bf6a-2696-4f9d-9466-58ae6998e568)
