### ISSUE TITLE
EPIC: Custom Publisher Statement

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3093]
Requirements: https://docs.google.com/document/d/1eWkkCIbdxO4UGT-YQoMCx-O3m_Bo3UaEaDj8OVkcTc0/edit#

Design: https://projects.invisionapp.com/share/NP138M0QX7T3#/screens/473602644_custom_Statement_Y

OA Requirements driving this issue: https://docs.google.com/document/d/18RGicHs5zvFU7KLDt29DKFvFvvjZnfAQagi8q57vExk/edit#heading=h.4irp318p0ni3

**Comment by amyehodge** [comment]
Closing as all associated tickets are closed.
