### ISSUE TITLE
Allow depositors to enter a custom rights statement

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3094]
IMPORTANT NOTE: This work should be based on the branch in #3271 and end as a PR into #3271

Background:
- Currently all H2 objects receive the same Terms of Use statement, which is hard-coded in the `settings.yml file` in the key `access:use_and_reproduction_statement`.  
- This statement is then added to cocina so that it can be shown on PURL pages.  
- Some publishers require authors to add specific text to their deposit in order to comply with licensing requirements. Read more here: https://docs.google.com/document/d/18RGicHs5zvFU7KLDt29DKFvFvvjZnfAQagi8q57vExk/edit#heading=h.4irp318p0ni3)
- This requirement thus allows depositors to add a custom statement which is prepended (does NOT replace) to the current hard-coded statement.  
- This is optional (i.e. many depositors will continue to just have the hard-coded statement).
- This ability is only available on works in collections for which the collection manager has enabled it: see #3097

Requirements:
- Free text entry field to support several sentences/a paragraph. 
- Field label: "Additional Terms of Use"
- Default instructions: "For open access articles, use this section for required publisher's statement. For other deposits, use this section to describe other terms of use not covered by the license you select below. This section does not constitute a formal Data Use Agreement."
- Include this new field in the "Select a license" section of the form, below the license selection.
- Re-title this section of the form "Terms of use."
- Field should be editable on later versions like most of the other fields on the form.
- Existing Use and Reproduction statement (see above) will continue to be included on all items and does not need to be alterable when a custom statement is entered.  Any statement entered by a user here is pre-pended when adding to cocina.
- Entry of content in this field will in no way alter requirements for end users to access the files, i.e. this will not change file or object rights and will not require end users to agree to anything. This is not a formal data use agreement.
- Items with these entries will not trigger a requirement for review.

Design: https://projects.invisionapp.com/share/NP138M0QX7T3#/screens/473365681_custom_Rights_Statement
Requirements: https://docs.google.com/document/d/1eWkkCIbdxO4UGT-YQoMCx-O3m_Bo3UaEaDj8OVkcTc0/edit#

**Comment by jmartin-sul** [comment]
part of https://github.com/sul-dlss/happy-heron/issues/3093
