### ISSUE TITLE
Update existing collection manager email to include custom rights statement if one exists

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3096]
See #3094

Update the email at app/views/collections_mailer/item_deposited.html.erb so that when the deposit includes a custom rights statement, the email notes that there is a custom rights statement and includes the text of that custom statement.

Include the custom statement whether it is one that the collection manager has entered for all items in the collection or the depositor has entered it for a specific item.

Email details are in a note below.

Design: https://projects.invisionapp.com/share/NP138M0QX7T3#/screens/473602644_custom_Statement_Y
Requirements: https://docs.google.com/document/d/1eWkkCIbdxO4UGT-YQoMCx-O3m_Bo3UaEaDj8OVkcTc0/edit#

**Comment by amyehodge** [comment]
This is a modification to the existing email sent to managers when a new item is created. 

File: app/views/collections_mailer/item_deposited.html.erb
Subject: Your deposit, #{@work_version.title}, is published in the SDR

**The current email is this:**

```
Body:
<p>Dear <%= @user.first_name %>,</p>

<p>The Depositor <%= @owner.name %> has submitted a <%=link_to 'deposit', work_url(@work)%> in the <%= @collection_version.name %> collection.</p>

<p>If you have any questions, contact the SDR team at: <%= link_to contact_form_url, contact_form_url %></p>

<p>The Stanford Digital Repository Team</p>
```



The revised email should have a new paragraph inserted between the two sentences of the body of the email ONLY if the depositor has entered their own custom rights statement. If there is a custom rights statement that is defined by the manager and goes on every item in the collection, it should not be included in the email.

**The revised email, if there is a custom rights statement, should be:**

```
Body:
<p>Dear <%= @user.first_name %>,</p>

<p>The Depositor <%= @owner.name %> has submitted a <%=link_to 'deposit', work_url(@work)%> in the <%= @collection_version.name %> collection.</p>

<p>This item has a custom rights statement:</p>
<p>[include statement text here]</p>

<p>If you have any questions, contact the SDR team at: <%= link_to contact_form_url, contact_form_url %></p>

<p>The Stanford Digital Repository Team</p>
```
