### ISSUE TITLE
Add department field next to affiliation field

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3101]
See https://projects.invisionapp.com/share/NP138M0QX7T3#/screens/473166568 for design and https://docs.google.com/presentation/d/1FI9yn7vUSeX7Yd5IemrLxnYH2__JlTxNwgP8guATb18 for requirements

- Departments should be entered in a separate field.
- This would also allow us to enter identifiers that are for specific departments, which LC and Wikidata both support.
- Department should be optional.
- Handle institutions as authors and contributors in the same way.

**Comment by justinlittman** [comment]
@peetucket Isn't this done?

**Comment by peetucket** [comment]
Oh maybe it is.  Just saw it on QA (i guess you did it as part of the other work)?

**Comment by justinlittman** [comment]
Yes, as part of the initial implementation of affiliations. Just wanted to make sure that I understood correctly.
