### ISSUE TITLE
EPIC: Push H2 content to ORCID

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3102]
Requirements: https://docs.google.com/document/d/1vAMI3OqJDxdQiLyseBi0IMtrL3HiL7y6cj0fT_P8t80/edit

**Comment by justinlittman** [comment]
To include Orcid pushes as part of SDR, here is a proposed approach.
1. Add a "update-orcid" step after the "update-doi" step in the accessioning WF.
2. If a cocina item, the update orcid robot will invoke the update_orcid endpoint in DSA.
3. The update_orcid endpoint will invoke an update orcid job for the cocina item.

The update orcid job will:
1. Check if any orcids are found in the cocina descriptive. Return if no orcids are found.
2. For each orcid, use of Mais Orcid client to check (1) if a Stanford user with write permissions and (2) get the access token. Return if no Stanford users with write permission.
3. Map the Cocina item to Orcid work metadata.
4. Check the orcid put code table if there is an existing put code for the cocina item and the orcid id.
5. If there is an existing put code, perform an update of orcid work using the put code. If there is not an existing put code, perform a create of orcid work and record the resulting put code.

**Comment by edsu** [comment]
Should there be any check to try to ensure that the work isn't already present in the users' ORCID profile to prevent duplication?

Also, should H2 allow users to enter an existing DOI that can be used when pushing data to ORCID to prevent duplication?

**Comment by peetucket** [comment]
Sandbox ORCIDs useful for testing (all have write access enabled):

```
jlittman - https://sandbox.orcid.org/0000-0003-3437-349X
amyhodge - https://sandbox.orcid.org/0000-0002-4933-2837
jtim - https://sandbox.orcid.org/0000-0002-7262-6251
vivnwong - https://sandbox.orcid.org/0000-0002-5466-7797
ndushay - https://sandbox.orcid.org/0000-0003-0962-2466
kcasciot - https://sandbox.orcid.org/0000-0002-7372-3555
petucket - https://sandbox.orcid.org/0000-0002-2230-4756
```
