### ISSUE TITLE
Map H2 works to ORCID works for sending deposit metadata to ORCID

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3103]
For background, see #3160

_ORCID requirements:_
Indicates we should only any H2 works (even without a DOI).  The PURL can act as an identifier.
"Works added by trusted organizations using the ORCID API must include an identifier. Works can have multiple identifiers, and an identifier must be included for duplicate versions of the work to group on the ORCID record. If you start entering an identifier by choosing the identifier type, then the identifier value and relationship are required."
- https://support.orcid.org/hc/en-us/articles/360006971353-Metadata-in-the-Works-section
- https://pub.orcid.org/v3.0/identifiers
- https://community.orcid.org/t/identifiers-when-pushing-orcid-works/2051

_ORCID Data model information:_
- Work XSD: https://github.com/ORCID/orcid-model/blob/master/src/main/resources/record_3.0/work-3.0.xsd
- Sample XML files: https://github.com/ORCID/orcid-model/blob/master/src/main/resources/record_3.0/README.md , works: https://github.com/ORCID/orcid-model/blob/master/src/main/resources/record_3.0/samples/write_samples/work-simple-3.0.xml and https://github.com/ORCID/orcid-model/blob/master/src/main/resources/record_3.0/samples/write_samples/work-full-3.0.xml

_H2 cocina generators:_
To see how we get from the database to cocina
- https://github.com/sul-dlss/happy-heron/blob/main/app/services/cocina_generator/dro_generator.rb
- https://github.com/sul-dlss/happy-heron/tree/main/app/services/cocina_generator/description (has many files that build the description)

_H2 database schema:_ 
To see what we store (in particular, focus on the "works", "work_versions", "abstract_contributors"
- https://github.com/sul-dlss/happy-heron/blob/main/db/structure.sql

_ORCID API information:_
- https://info.orcid.org/ufaqs/how-do-i-add-an-item-using-the-orcid-api/
- https://info.orcid.org/documentation/api-tutorials/api-tutorial-add-and-update-data-on-an-orcid-record/

**Comment by justinlittman** [comment]
* Is pushing with every deposit permissible? It requires less complicated machinery and tracking.
* Can the mapping from H2 work metadata to an ORCID work metadata be specified? What should be used as the required identifiers?
* Are we really sure that users want H2 content to be added to their Orcid profiles without request/approval? (For example, if the H2 item are files supporting a different publication or H2 item is just another copy of a different publication. Concrete example: If I deposited a copy of my recent C4L Journal article in the Staff collection, I wouldn't want it added to my Orcid profile, since the original publication is added to my Orcid profile).

**Comment by amyehodge** [comment]
@justinlittman Pushing with every deposit is permissible if that's what you decide. For me, weekly would be often enough, but sooner works too.

**Comment by amyehodge** [comment]
@justinlittman Regarding request/approval, we can only push to ORCID records for individuals who have already given us approval to do so. ORCID users can choose whether to make any individual work publicly visible or not on their ORCID record, and can set up notifications so that they get an email from ORCID every time something is added to their record. 

<img width="432" alt="Screenshot 2023-06-22 at 11 01 34 AM" src="https://github.com/sul-dlss/happy-heron/assets/5558511/7a3833d0-2325-469b-97a4-a459ce2b9147">

Given that the point of the trusted user authorization is so that organizations like Stanford can push things to their record, we consider doing so to be a bonus for users. And if they are concerned, they can set up the necessary notifications to intercept and hide additions as soon as they are made.

**Comment by justinlittman** [comment]
Have we asked any users if this is a desired feature and/or if they would expect or be surprised by H2 items being added to Orcid record? (I understand that they have consented to it; did they understand what they consented to?)

**Comment by peetucket** [comment]
>     * Can the mapping from H2 work metadata to an ORCID work metadata be specified? What should be used as the required identifiers?
> 

Can I recommend that the developer that picks up this ticket takes a first pass at going through the available metadata from H2 and use the ORCID data model to map the obvious fields.  For fields that we have in H2 with no obvious counterpart is in ORCID, we then ask for assistance from either ORCID and/or our metadata department?  I think this was the approach we took in sul-pub.

>     * Are we really sure that users want H2 content to be added to their Orcid profiles without request/approval? (For example, if the H2 item are files supporting a different publication or H2 item is just another copy of a different publication. Concrete example: If I deposited a copy of my recent C4L Journal article in the Staff collection, I wouldn't want it added to my Orcid profile, since the original publication is added to my Orcid profile).

For the duplicate question, I believe ORCID allows us to only push works with a specific list of known identifiers (e.g. DOIs) so that they can be de-duped on the ORCID side (as is done with sul-pub).

**Comment by amyehodge** [comment]
@justinlittman I think there is still a plan to do some user interviews. We can look at adding a question to this effect to those interviews. Though I think for this question it would be best to find some H2 users who have already authorized Stanford to push to ORCID. 

How hard is it to get the intersection of SUNet IDs that 1) exist in the H2 database as any kind of user and 2) have authorized Stanford to write to ORCID? These are the people we want to ask. Others won't know what we're talking about.

**Comment by peetucket** [comment]
> @justinlittman I think there is still a plan to do some user interviews. We can look at adding a question to this effect to those interviews. Though I think for this question it would be best to find some H2 users who have already authorized Stanford to push to ORCID.
> 
> How hard is it to get the intersection of SUNet IDs that 1) exist in the H2 database as any kind of user and 2) have authorized Stanford to write to ORCID? These are the people we want to ask. Others won't know what we're talking about.

We should be able to get that list easily, let me ticket it.  Part of the challenge here honestly is that I suspect not many researchers are really asking for this feature nor even care that much about it.  But if/when it exists, it will provide additional value in the future (by further promoting their research)...assuming ORCID continues to take off and be relevant, as we all hope.  To me it feels a bit like the apocryphal Henry Ford "quote" about if you asked people what they wanted, they would have said a faster horse.  In some sense, we are building a speculative car here, and hoping we are correct.

**Comment by peetucket** [comment]
See #3117 for results of my analysis of ORCIDs currently in H2.

**Comment by amyehodge** [comment]
For the record, results of mini-survey of users on pushing works to ORCID is at https://docs.google.com/spreadsheets/d/1csEtMDALUTW86avBisbQln-ypQeP12zi2vst4vVTW1Q/edit. They are overwhelmingly in favor of this and they don't want to be asked or notified.

**Comment by ndushay** [comment]
do we need Arcadia to sign off on this mapping?

**Comment by peetucket** [comment]
> do we need Arcadia to sign off on this mapping?

Yes, for sure.  We are awaiting her assistance for this (indicated with the "metadata" tab).

**Comment by arcadiafalcone** [comment]
H2 to ORCID metadata mapping - vocabulary mappings still in progress

```
<?xml version="1.0" encoding="UTF-8"?>
<work:work xmlns:common="http://www.orcid.org/ns/common" xmlns:work="http://www.orcid.org/ns/work"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.orcid.org/ns/work/work-3.0.xsd ">
    <work:title>
        <common:title>H2 title</common:title>
    </work:title>
    <work:short-description>H2 abstract</work:short-description>
    <work:citation>
        <work:citation-type>formatted-unspecified</work:citation-type>
        <work:citation-value>H2 preferred citation</work:citation-value>
    </work:citation>
    <work:type>See H2 work type mapping</work:type>
    <!-- use deposit date if publication date not present -->
    <common:publication-date>
        <common:year>H2 publication (or deposit) year</common:year>
        <common:month>H2 publication (or deposit) month</common:month>
        <common:day>H2 publication (or deposit) day</common:day>
    </common:publication-date>
    <common:external-ids>
        <common:external-id>
            <common:external-id-type>doi</common:external-id-type>
            <common:external-id-value>DOI value</common:external-id-value>
            <common:external-id-url>DOI URL</common:external-id-url>
            <common:external-id-relationship>self</common:external-id-relationship>
        </common:external-id>
        <common:external-id>
            <common:external-id-type>uri</common:external-id-type>
            <common:external-id-value>Stanford purl value</common:external-id-value>
            <common:external-id-url>Stanford purl URL</common:external-id-url>
            <common:external-id-relationship>self</common:external-id-relationship>
        </common:external-id>
    </common:external-ids>
    <common:url>Stanford purl</common:url>
    <work:contributors>
        <work:contributor>
            <common:contributor-orcid>
                <common:uri>ORCID or ROR URL</common:uri>
                <common:path>ORCID or ROR identifier</common:path>
                <common:host>orcid.org or ror.org</common:host>
            </common:contributor-orcid>
            <work:credit-name>H2 first name + space + H2 last name</work:credit-name>
            <work:contributor-attributes>
                <work:contributor-role>See H2 role mapping</work:contributor-role>
            </work:contributor-attributes>
        </work:contributor>
    </work:contributors>
    <common:language-code>en</common:language-code>
    <common:country>US</common:country>
</work:work>
```

**Comment by arcadiafalcone** [comment]
For H2 work type and role mappings, see https://docs.google.com/spreadsheets/d/1zrRCFgwWkPW0Vg9mIsUe-rMZkiCvudB2t3VLw0dn-rY/edit?usp=sharing.

For `<work:credit-name>`, include only names in the H2 cited author section. Omit names not in the citation.

For `<work:contributor-role>`, enter a value only if there is a mapping, otherwise omit this stanza.

**Comment by arcadiafalcone** [comment]
The following values are literals, i.e. not mapped based on H2 content.
```
<work:citation-type>formatted-unspecified</work:citation-type>

<common:external-id-type>doi</common:external-id-type>

<common:external-id-type>uri</common:external-id-type>

<common:external-id-relationship>self</common:external-id-relationship>

<common:language-code>en</common:language-code>

<common:country>US</common:country>
```
