### ISSUE TITLE
Investigate limit of what can be deposited in H2

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3114]
Note: test in stage, which is where disk limits were increased to accommodate testing

We need to understand based on limits provided to us by PO, and for this we need to have the requested maximum number of files, maximum single file size, and maximum total file size that should be possible to accession so that we can test if this is possible in QA or stage.  If it is, we could presume it would also be possible in production (which has more resources).

We can then determine if we can accession without problems (e.g. timeouts, pages not rendering, stalls in workflows, filling up stacks, etc.):

1. The maximum number of files in an object required
2. The maximum single file size in an object required
3. The maximum combined size of all files in an object required

We can then take further steps:

1. Investigate how to increase the limits if not sufficient.
2. Add validation/messages to the user if the limits are sufficient, but we need to prevent users from exceeding them

From Amy June 27:

Requested limits (specifically to H2 and assuming usage of globus):
- 4 TB total object size
- 25k total number of files
- 4 TB total single file limit

We are not sure if we currently enforce any limits in the UI (i.e. browser uploads), other than ZIP upload being a single file. See #3183

Question:
- can we reject objects that exceed these limits if deposited into H2?  YES - early in process is better

**Comment by amyehodge** [comment]
@peetucket I saw this and have reached out to Andrew and Hannah to discuss. I understand that problem with trying to test to make sure "anything" will work, so I'll work to get you some concrete numbers as soon as possible.

**Comment by peetucket** [comment]
Thanks!  I was wondering too if we could try and find the current limits, but the challenge of this approach is that the limits are likely to be different in qa/stage vs prod due to differences in the resources/disk space/compute power in each environment.  

For example, if we spent time finding the limits of QA, it's likely prod will be higher (but unclear as to how much higher).  And relatedly that if we determine that a reasonable limit is possible in QA, its very likely this limit is possible in prod.

If we really wanted to test the current limits, we'd have to do in production to be accurate, and this may not be desirable (it.e. breaking prod on purpose) it we can avoid it.

**Comment by amyehodge** [comment]
@peetucket Agreed that testing limits in prod that could interrupt depositing for everyone does not seem optimal. And your other logic makes sense as well.

Though, conversely, if we could find the limits on qa/stage, could we reasonably surmise that the limits in prod are at least that much? That might be helpful if it's maybe half the limit of prod, but if it's 1/10th, that seems less useful.

**Comment by peetucket** [comment]
> Though, conversely, if we could find the limits on qa/stage, could we reasonably surmise that the limits in prod are at least that much? That might be helpful if it's maybe half the limit of prod, but if it's 1/10th, that seems less useful.

Yes, that is true.  Worth asking the team about when we discuss this ticket with them.  My guess is that it's hard to know what faction of prod it currently is, but maybe we can come up with some strategies to get an estimate.

**Comment by justinlittman** [comment]
While stage does not have the capacity of prod, it is also under less load. Without actually running tests, any attempt to predict the relationship between stage and prod would be a guess.

The exception is the UI -- one would expect it to break roughly the same in all environments.

**Comment by justinlittman** [comment]
> Requested limits:
    4 TB total object size
    25k total number of files
    4 TB total single file limit

this is presumably the limit for Globus deposit?

What are the requested limits for file upload and zip upload?

**Comment by amyehodge** [comment]
I was under the impression that we already had a limit of 10GB (for both individual file and total) for file upload and zip upload. Is there any reason not to set the number of objects to the same as for Globus as long as the totals are under the 10GB?

**Comment by peetucket** [comment]
Closing this and creating separate tickets for remaining work
