### ISSUE TITLE
Provide a valid label for form fields on welcome screen

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3118]
This was identified as a critical issue by SODA during their recently completed accessibility review of H2. The following information was provided in that report.

[Issue]
There are form fields that do not provide a programmatically associated label that describes the purpose of each field.  Each of the form fields is duplicated in the Help modal dialog and the relationships between the for and id values are negated because they are duplicated.

[User Impact]
Users may not be able to fill out form fields correctly, if there is no programmatically associated and visible label for each field.

[Recommendation]
Input form fields should provide visible, programmatically associated labels that can be announced properly to screen reader users. Typically labels and form fields need to be explicitly programmatically associated which is commonly done by providing a "for" attribute on the <label> element with its value set to the input's id value or by providing another mechanism that specifies an accessible name.  However, each id must be unique.

Astrid will validate if fixed.

**Comment by justinlittman** [comment]
I don't see "Each of the form fields is duplicated in the Help modal dialog". I only see them once.

How can this be replicated?

**Comment by justinlittman** [comment]
I don't see "Each of the form fields is duplicated in the Help modal dialog". I only see them once.

How can this be replicated?

**Comment by ndushay** [comment]
Looking at the welcome screen, there is only this form:

![image](https://github.com/sul-dlss/happy-heron/assets/96775/6670c117-6968-413a-b48d-40903de16ada)

Which has html like this:

```html
<label for="mce-EMAIL">Sign up for our newsletter</label>
<div class="row">
      <div class="col-sm-9">
            <input type="email" value="" name="EMAIL" class="form-control form-control-sm" id="mce-EMAIL" autocomplete="on" placeholder="Enter your email address" required="" data-dashlane-rid="51227cd6bcab77ce" data-kwimpalastatus="alive" data-kwimpalaid="1687808156255-0" data-form-type="email">

 snip ...          

                <div class="col-sm-3">
                  <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary btn-sm" data-dashlane-rid="512718620ff70af3" data-form-type="action,subscribe">
                </div>
             </div>             
```

And the help modal:

![image](https://github.com/sul-dlss/happy-heron/assets/96775/f4c86102-a0ea-45fd-b0fd-ad366dcc90c5)

which has html like this:

```html
<label for="email">What is your email address?*</label>
<input class="form-control" required="required" type="text" name="email" id="email" data-dashlane-rid="718360c6f0dd9665" data-form-type="email" data-kwimpalastatus="alive" data-kwimpalaid="1687808156255-14">

snip ...

           <button name="button" type="submit" class="btn btn-default" data-bs-dismiss="modal" data-dashlane-label="true" data-dashlane-rid="c68fe573f1c07543" data-form-type="other">Cancel</button>
           <button name="button" type="submit" class="btn btn-primary" data-action="help#checkCollections" data-dashlane-label="true" data-dashlane-rid="8cd1279e81841a68" data-form-type="other">Submit</button>
```

So it doesn't appear to be the email field bedcause there is a label for these, and it goes to a unique identifier and they are not the same (and the labels are not the same).  


So that leaves the submit button.  Is THAT what needs a label???

**Comment by ndushay** [comment]
@amyehodge @peetucket see my comment above -- is this ticket saying that we need a label for the submit buttons?

**Comment by ndushay** [comment]
Last:  I installed the firefox extension for SiteImprove and this was not one of the problems reported.  Perhaps this is done?

**Comment by amyehodge** [comment]
@justinlittman @ndushay @peetucket  I thought I responded to this ticket yesterday but I don't see my response. I think what is being reported here is about the welcome screen that I think looks like this (this is from the mockups because I can no longer see this screen since I'm already a user):

<img width="463" alt="Screenshot 2023-06-26 at 5 14 47 PM" src="https://github.com/sul-dlss/happy-heron/assets/5558511/f7793184-948c-4be2-b2c6-858894d0bfcd">


and the Help modal:

<img width="380" alt="Screenshot 2023-06-26 at 5 15 53 PM" src="https://github.com/sul-dlss/happy-heron/assets/5558511/3fd1bc3d-e1d7-4cf4-b35f-9c88da9dca82">

These are nearly identical to each other, which seems to be part of the problem. But it sounds like there are some other issues with the help modal. I don't know how to make that come up if you already have permission to use the app.

**Comment by ndushay** [comment]
I can get the help modal, but I can't get the welcome screen, i don't believe.

**Comment by ndushay** [comment]
oh wait - I figured out how to see it

**Comment by peetucket** [comment]
One way to foce on localhost is to return `return false` in the `show?` method of app/policies/dashboard_policy.rb instead of that logic.

**Comment by ndushay** [comment]
> One way to force on localhost is to return `return false` in the `show?` method of app/policies/dashboard_policy.rb instead of that logic.

yep - on it.  thank you!

**Comment by ndushay** [comment]
labels for first time welcome form:
- name
- email
- affiliation
- help_how
- why_contact

labels for help form:


labels for help form:
- name
- email
- affiliation
- help_how
- why_contact

And now, with the Siteimprove Accessibility Checker plugin:

![image](https://github.com/sul-dlss/happy-heron/assets/96775/2d5a1914-42b0-4be8-ab06-585fa0812ee4)

^^ for a welcome page (displayed locally with a tweak to make it happen) and the help modal displayed as well.

**Comment by ndushay** [comment]
@amyehodge sooOOOOooo it turns out the help form and the welcome first timer form use ... the same code in the app.  This is nice and elegant but it won't pass accessibility as is.

The question for you:  if you had the freedom to decouple these two forms ... would you want to?   (I have no idea what would require work to get our data into jira if we changed it up"

**Comment by ndushay** [comment]
Two ways that help form code is called:
![image](https://github.com/sul-dlss/happy-heron/assets/96775/ac4784cf-cd74-4f09-b18e-792d02bac5ca)

**Comment by amyehodge** [comment]
@ndushay We would still want both forms to create JIRA tickets, but I don't see any need to keep them connected. So, as long as both still make tickets, I'm indifferent to how you solve the accessibility issue.

**Comment by astridu** [comment]
Sorry I'm tardy to the party. We came across this issue in Monarch and were surprised by how descriptive the labels had to be, but it made sense once they had us not look at the screen and listen to the reader. I need to clarify how descriptive for this particular case where the 2 forms are pretty much the same. Will get back to you.

**Comment by ndushay** [comment]
@astridu this is all set.  JLitt pointed out that we could put the forms in a "namespace" and thus differentiate them.

**Comment by astridu** [comment]
@ndushay This is the response from Kevin. Looks like we can either label each of them distinctly or put the text of the radio button in the label:
<img width="982" alt="image" src="https://github.com/sul-dlss/happy-heron/assets/42216982/c5d48ef9-2c60-46b1-87da-13217e86eebd">
