### ISSUE TITLE
work stuck in "depositing" state in H2 despite Argo showing accessioning completed

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/happy-heron#3134]
Split from #3071, which had 2 separate problems.

Peter wrote:

> During the week of May 15, we saw this unexplained issues:

> Work ID 6601, druid:kq565vk7202 was stuck in "depositing" in H2, even though accessioning completed successfully as shown in Argo, and the PURL page was available.  We investigated and found that the most likely situation was that the `app/services/deposit_completer.rb` never ran, which would have moved the object to the correct "deposited" state.  This class is run by the `app/jobs/deposit_complete_job.rb`, which is a worker that should have run based on a RabbitMQ message from the `h2.deposit_complete` queue.  This queue is added to by dor-workflow-service whenever a workflow step is changed, and the `end-accession` step should trigger this job.  For some reason it didn't in this case, even though we found evidence in the log file on workflow-service-prod that messages were being sent to RabbitMQ.  We didn't see any issues in the RabbitMQ console, and all apps showed connections as successful.  

> We added some extra logging to workflow-server-rails to hopefully help debug this issue in the future: https://github.com/sul-dlss/workflow-server-rails/pull/653

Naomi adds:

PR sul-dlss/workflow-server-rails/pull/653 was merged on May 17.

I believe we've seen this, or something like it, before and have had to manually reset the state.  Wondering if there are networking or rabbitMQ hiccups that can cause a signal to be missed??

Wonder further if it would be worth it to have a cron run once daily that checks for works in the "depositing" state and then looks up their workflow status to see if accessioning is completed?  (or maybe there's a DSA call that would answer this?)??   Just a thought.

**Comment by justinlittman** [comment]
Until we've seen this with some consistency, I'd argue against adding more working machinery. If we "second guess" this use of RabbitMQ, then we should create a similar backup for every use of RabbitMQ.

**Comment by mjgiarlo** [comment]
I agree with @justinlittman that we should close this and move on until we see this recur more frequently. I don't think there's anything worth doing here. We have better logging now at least.
