### ISSUE TITLE
Subtypes not cleared when select "Other" type in work type modal

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/happy-heron#3137]
Steps to reproduce:
1. Click "Deposit to this collection".
2. In work type modal, select "Text" type and "Article" and "Capstone" subtypes.
3. Select "Other" type and enter "Manga" as subtype.
4. Click "Continue"

Expected result:
Draft work opens with "Manga" set as subtype.

Actual result:
![image](https://github.com/sul-dlss/happy-heron/assets/588335/2e5bf527-a7e7-45de-acc6-b6c4fc054f68)

**Comment by amyehodge** [comment]
@justinlittman @astridu I noticed that the layout here is very wonky. The alignment seems really off. It looks like this in production as well. I'm wondering if we should ticket that somewhere separately. @astridu ?
