### ISSUE TITLE
Remove empty expand/collapse header for work subtypes from deposit form when the work type is "Mixed materials"

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3138]
Follow on from testing #3092

When "mixed materials" is chosen as the subtype, all the subtypes are displayed instead of there being a short list and then the user needing to click on "See more options" to show the rest of the terms that are available.

This is correct, but the the "See more options" header is still being shown at the bottom of the list even though it is not needed.

![Screenshot 2023-06-27 at 11.25.15 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/097c0521-1fdc-46a2-a938-2f5ba8adf926)

If you click on it you can expand it but there aren't any options there.

![Screenshot 2023-06-27 at 11.25.21 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/67e45128-8014-490f-8d42-289aa7967a65)

The request here is to remove those headers entirely when the work type is "Mixed Materials" as they are not needed.

**Comment by justinlittman** [comment]
@amyehodge I can't reproduce this. Can you please provide precise steps to reproduce? Thanks!

**Comment by amyehodge** [comment]
@justinlittman Sure. 

1. Click any "Deposit to this collection" button
2. Choose "Mixed materials"
3. Select two or more subtype terms (doesn't matter which ones)
4. Click "Continue"
5. Scroll down to the part of the form where the subtypes are listed.

You'll see the full list of subtypes, as you should.

But below that list you'll still see the "See more options" link 

<img width="143" alt="Screenshot 2023-06-27 at 4 40 23 PM" src="https://github.com/sul-dlss/happy-heron/assets/5558511/5498daa1-2076-4a52-b19d-36bef274d405">

that expands to show ... no additional options. 

<img width="349" alt="Screenshot 2023-06-27 at 4 41 01 PM" src="https://github.com/sul-dlss/happy-heron/assets/5558511/1db5d74d-6e62-4e11-baa7-c0653256e301">

That's confusing and shouldn't be there.

**Comment by justinlittman** [comment]
Oh, gotcha. I thought it was on the modal. Much clearer now.

**Comment by amyehodge** [comment]
Nope. The modal is perfect.
