### ISSUE TITLE
Saving item draft does not require the Required fields

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#314]
Currently, the deposit form will not let you save a draft if the required fields are not filled out. 

The desired behavior is that the form validations do not affect the ability to save a draft. The required fields are only required for depositing.

**Comment by peetucket** [comment]
I'm not quite sure how to make this work with the way we have currently implemented client side validation.  We use a submit button for both save and deposit, and the client side validation runs in either case.

**Comment by jcoyne** [comment]
You can remove the form validation using javascript when the draft button is pressed.  On the back-end we probably want to subclass WorkForm so that one version has strict validations and the other doesn't.
