### ISSUE TITLE
Separate license and terms of use options into distinct grey boxes

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3146]
NOTE: this work should end as a PR into #3271

For the collection form, both when creating the collection initially and modifying settings later, the sections on licenses and terms of use should be separated.

With the new option to include custom terms of use, this section has visually gotten a bit too large for users to navigate. Headers for the sections will need to be updated as shown in the mockup below.

See https://projects.invisionapp.com/share/NP138M0QX7T3#/screens/473602647_custom_Statement_Y_V2

![Screenshot 2023-06-28 at 10.12.26 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/7777c6b4-685f-4c50-85a4-39924c44bc6a)

If we don't separate these when we implement the new option, it will look like this, which feels like too much text for one box:
![Screenshot 2023-06-28 at 10.13.26 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/d1c4eb0d-2124-48ae-826d-db567b7de245)

**Comment by amyehodge** [comment]
The existing help text for the information (i) link should remain associated with the license section of the form. 

The new terms of use section of the form will also have an information (i) link that should have the following new text displayed:

As the collection manager, you can decide whether additional terms of use can be added to a deposit and displayed on the PURL page along with the Standard Terms of Use shown below. You have three options: 1) Leave the custom terms off. No additional terms will be added. 2) Provide custom terms that will appear on every deposit. The depositor will not be able to modify this text. 3) Allow the depositor to type in their own custom terms. With this option, you can choose to display to the depositor the default instructions we have written, or write your own instructions.

**Comment by jmartin-sul** [comment]
closing this since the PR for it (#3303) got merged into the feature branch, and there's a separate ticket for tracking merge of the feature branch into `main`

**Comment by jmartin-sul** [comment]
see also #3093, #3271, #3295
