### ISSUE TITLE
Gemify the MaIS ORCID API

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3153]
We will need to interact with the MaIS API, which is the internal Stanford API that allows us to determine who has been through the SUNET-ORCID intergration.  We have a client for this API in sul-pub app,  see https://github.com/sul-dlss/sul_pub/tree/main/lib/mais   .We will need this client in DSA or common-accessioning in order to do the H2 ORCID integration work.

This ticket is to
- create a new gem for this MaIS Stanford-ORCID integration, name `mais_client`
- move code from sul-pub at https://github.com/sul-dlss/sul_pub/tree/main/lib/mais to new gem
- move tests to new gem
- publish and release gem

Note, we have requested separate keys for the H2 integration work, but the current sul-pub keys are in vault, for qa: `puppet/application/sul_pub/qa` and for prod: `puppet/application/sul_pub/prod`

keys are "mais-client-id" and "mais-client-secret"

We can use these for testing as needed.

**Comment by justinlittman** [comment]
@peetucket Since there is not currently a MAIS API for looking up by ORCID ID, does it make any sense to proceed with this? Also, without the design for ORCID integration is it clear that this is needed in H2 instead of DSA or common accessioning?

**Comment by peetucket** [comment]
1. Agreed this integration may exist elsewhere, so the task can likely change to "gemify the MaIS integration".  2. I'm requesting that feature as an enhancement, and based on previous experience with MaIS, it may happen relatively quicky.  If not, let's discuss alternative strategies to fulfill the requirements.
