### ISSUE TITLE
Updated works pushed to ORCID when work changes in H2

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3155]
Follow on from #3160 (which pushes works to ORCID)

_Requirements:_
For H2 works that were pushed to ORCID (based on the PUT code that was stored), we will need to push the updated work to ORCID if an update occurs to the H2 work.

We will determine that an update has occurred in H2 when an H2 work is deposited, if the H2 version >= 2, AND an ORCID PUT code exists (indicating the work was previously pushed to any ORCID profile).  This would indicate an update to an H2 work that was previously pushed, so the work is remapped with any updated metadata, and re-pushed to ORCID.  By using the PUT code(s), ORCID updates the work instead of adding a new one. 

See https://info.orcid.org/documentation/api-tutorials/api-tutorial-add-and-update-data-on-an-orcid-record/#Updating_items

_Considerations:_
- As stated in #3160, a single H2 work can have multiple PUT codes if it was pushed to multiple ORCID records (because there were multiple contributors with ORCIDs that have write access) - so for later versions of the H2 work, we need to check each of the H2 ORCIDs again and use any existing PUT codes
- ORCID scopes/connections may have changed since the previous version of the H2 work, so a full check of all ORCIDs in the work needs to happen (do they exist in the MaIS endpoint? what is their scope?)
- The full check of all ORCIDs will also account for new ORCDIs being added, which will then push a new work to ORCID
- It is possible that no metadata that is mapped to ORCID actually changed (i.e. the new version in H2 changed some metadata we don't push to ORCID) - but we will not do any diffing, but simply map and push to ORCID again. We expect ORCID will handle this.
- We will not delete works from ORCID (i.e. if a contributor ORCID existed in V1 of the H2 work that resulted in a push of the work to ORCID and that contributor was later removed in V2 of the H2 work, we do not need to detect this and remove the work from ORCID)"

**Comment by justinlittman** [comment]
Closing in favor of pushing as part accessioning workflow.
