### ISSUE TITLE
Setting embargo dates should automatically select the "On this date" radio button

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#316]
In the manage release section of the deposit form, when a user enters an embargo date, this should automatically select the "On this date" radio button. Currently I can leave "immediately" checked and choose a date, which makes it very unclear which option I'm selecting.![Screen Shot 2020-11-03 at 2.04.06 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/742d72f6-0155-42eb-8e95-999fed6d89aa)

**Comment by jcoyne** [comment]
I believe this has troublesome usability/accessibility implications. Consider the case that you are a screen-reader user. If you change the date, you have no way of knowing that you have inadvertently changed the value of the radio button.   As a counter proposal, how about we keep the dates disabled, until you select "On this date"?

**Comment by amyehodge** [comment]
@jcoyne Your proposal works for me. Thanks for considering the accessibility aspect, as I'm not familiar with the workings of screen readers.

**Comment by amyehodge** [comment]
See the PR attached to #796 for a pattern to use.

**Comment by amyehodge** [comment]
@jcoyne I'm still seeing the previous behavior on stage -- I am able to select a date without first selecting the radio button.
<img width="1052" alt="Screen Shot 2021-02-02 at 2 18 57 PM" src="https://user-images.githubusercontent.com/5558511/106670731-48f2bc80-6562-11eb-9edf-98ec6e6cf0f5.png">

**Comment by mjgiarlo** [comment]
@amyehodge curious. I am not seeing that on stage, e.g.: https://sul-h2-stage.stanford.edu/collections/164/works/new?work_type=data

**Comment by amyehodge** [comment]
lemme check again since @jcoyne just redeployed

**Comment by amyehodge** [comment]
Ah, yes. This is now good @mjgiarlo.

**Comment by mjgiarlo** [comment]
@amyehodge ok, great!
