### ISSUE TITLE
Increase size of accessioning mounts on stage to run scalability test

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3184]
On stage, we need sufficient space to accession our large 4 TB object.  So we need > 4 TB free (at least temporarily for this test) on:

- dor mount
- globus mount
- stacks
- preservation

We will need Ops to help us with this.  Create operation-tasks ticket and track progress.

**Comment by aaron-collier** [comment]
Ops Ticket: https://github.com/sul-dlss/operations-tasks/issues/3410

Note - the globus mount is already 330TB+  free.

**Comment by aaron-collier** [comment]
The mounts are now 10TB:

```
sul-globus-prod:/tank/globus/restricted                   421T   91T  331T  22% /globus
sf5-webapp-dev:/sul_purl_stage                             10T  2.5G   10T   1% /purl
sf5-webapp-dev:/stacks_test                                10T  1.3T  8.8T  13% /stacks
sf5-webapp-dev:/sul_lyberservices_dev                      10T  2.1T  8.0T  21% /dor
```
