### ISSUE TITLE
[SPIKE] Consider reform alternatives

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/happy-heron#3192]
While there are conceptual reasons for the form abstraction layer provided by the reform library, in practice the resulting code has proven excessively complex, hard to understand, difficult to debug, rely on magic, require coordination with stimulus controllers, and involve a lot of boilerplate. Therefore, alternative patterns should be considered under this spike.

One possibility: A combination of https://dev.to/jessesbyers/how-to-rails-complex-associations-nested-forms-and-form-helpers-5g5k using the custom writer method and https://www.stimulus-components.com/docs/stimulus-rails-nested-form/

**Comment by peetucket** [comment]
![image_360.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/491c7552-3223-4107-91e5-90c5fcebdf52)![image_480.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/27716867-20be-4193-994c-bfc5f3819900)

**Comment by justinlittman** [comment]
I don't think any of ^^ will help because they (1) are abandoned; (2) use jQuery; and/or (3) don't help with nesting.

**Comment by justinlittman** [comment]
This is helpful: https://blog.testdouble.com/posts/2022-08-30-stateless-forms-with-the-rails-attributes-api/

The core problem is how to model associations (and hence nesting) without ActiveRecord.

**Comment by justinlittman** [comment]
Provides a mechanism for dealing with nested ActiveRecord objects; however, does not accommodate nested form objects: https://jaryl.medium.com/disciplined-rails-form-object-techniques-patterns-part-1-23cfffcaf429

**Comment by justinlittman** [comment]
Promising: https://github.com/rootstrap/yaaf

**Comment by justinlittman** [comment]
See https://github.com/sul-dlss/happy-heron/pull/new/form_spike2

What this shows so far: creating and editing multiple level nested forms.

What this doesn't show: adding and deleting nested objects, validation of draft forms vs deposit (full validation) forms.

**Comment by peetucket** [comment]
That seems more understandable than reform to look at

**Comment by justinlittman** [comment]
Spike done.
