### ISSUE TITLE
Verify number of files that can be unpacked from a zip file

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3195]
Follow on to #3183.

Users can upload only 1 zip file for the zip file option, but is there a limit to how many files can exist in that zip file and still be unpacked properly in the UI?

1. Verify if there is a limit to the number of files that can be unpacked from the single zip file.
2. Verify if there is any way to enforce a limit on this (we already enforce 1 zip file for this upload option).
3. Add instruction text to inform user of limit, whether we are enforcing it or not.

**Comment by aaron-collier** [comment]
@amyehodge 

1.) I haven't hit a technical limit here, having success with 25K files as well as 25K files with a depth of 10 folders.
2.) We can enforce a limit programmatically by raising an error if we hit a set limit

I think this ticket can be closed with a couple of new tickets for:
- Add instruction test related to large zips taking time (if we want that)
- Investigate performance of the display and ticket improving.
