### ISSUE TITLE
Allow user to change Globus file location option so that none of Oak, Sherlock, or GDrive are selected

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3196]
If a depositor initially selects Oak, Sherlock, or Google Drive as the location for their content to transfer and then later changes their mind and wants to transfer from a personal computer or another server on campus, they need to be able to do that and the current UI does not allow that.

Steps to recreate:
1. create new item
2. choose the Globus option
3. select Oak, Sherlock, or Google Drive from the drop-down menu
4. Save as draft
5. Click pencil icon to edit
6. under the Globus option, the user now only has the ability to select Oak, Sherlock or GoogleDrive and not the "Select..." option to blank this out. They no longer can choose to upload files to Globus via their personal computer or some other campus server.
7. choose a different file upload option, then select Globus option again -- still can't unchoose an option from the dropdown
8. choose a different file upload option
9. save as draft
10. edit item
11. choose Globus upload option -- again, still can't unchoose the options from the dropdown so they can upload from a personal computer or another server.

User needs to be able to select an option that doesn't use Oak, Sherlock, or Google Drive for the Globus upload.

**Comment by astridu** [comment]
<img width="1064" alt="image" src="https://github.com/sul-dlss/happy-heron/assets/42216982/91225294-7ee3-4dc0-8df6-7b746ff2ce76">
