### ISSUE TITLE
Cancel new deposit

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/happy-heron#32]
Start a new deposit then decide to back it out, leaving behind no uploaded files or metadata.

**Comment by amyehodge** [comment]
@jcoyne and @mjgiarlo I think this can be closed?

**Comment by mjgiarlo** [comment]
@amyehodge Maybe? So I believe we've added a cancel link that takes you away from the form without saving changes (though if you uploaded any files, I *believe* those changes will have already been made before canceling, so canceling will not back them out). We have a "Discard Draft" button as well that deletes a work (including any deposited files), but you can only discard a work that is in first draft state. Is this all as it should be? If so, I think we can close this.

**Comment by amyehodge** [comment]
@mjgiarlo Since this says "new deposit" my thinking was that it covered the scenarios you outlined. 

The discarding of version drafts is covered by #794 (collections) and #858 (items).

**Comment by mjgiarlo** [comment]
@amyehodge OK! Then I'll close. Good :eye:. Thanks. :smiley:
