### ISSUE TITLE
Migrate WorkVersions with globus states that no longer exist

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/happy-heron#3200]
The following globus-related states no longer exist:
```
- globus_account_setup
- globus_setup_pending
- globus_setup_first_draft
- globus_setup_version_draft
```

WorkVersions with those states need to be migrated to avoid errors if the user tries to interact with them. As of 7/7/2023:
* prod with state `globus_setup_first_draft`: 
  * ~~work 6641 / workversion 8625 (dmgordon)~~ (migrated 2023-07-11)
* stage with state `globus_setup_first_draft`: 
  * ~~work 19046 / workversion 19569 (amyehodge)~~
  * ~~work 19048 / workversion 19571 (lwrubel)~~
  * ~~work 19049 / workversion 19573 (lwrubel)~~
  * ~~work 19053 / workversion 19579 (astridu)~~
  * ~~work 19060 / workversion 19587 (astridu)~~
* qa: already migrated

What the user sees if they try to interact with a work in a deleted state:
<img width="1060" alt="Screenshot 2023-07-07 at 12 00 36 PM" src="https://github.com/sul-dlss/happy-heron/assets/1619369/dccb704a-7eee-4d4e-8900-b88dc99d312a">

After latest code is deployed to prod, run the following steps on the rails console:

```
wv = WorkVersion.find(8625)
wv.state = "first_draft"
wv.save!
GlobusSetupJob.perform_later(wv)
```

This will set up the endpoint on Globus and add it to the work version record, give the user permissions to the endpoint, and send emails from SDR and Globus.

**Comment by jmartin-sul** [comment]
i think this work is done now, so closing, but feel free to reopen if that was premature
