### ISSUE TITLE
Update text of Globus email.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3202]
Update app/views/works_mailer/globus_endpoint_created.html.erb

Steps 1 & 2 should be updated to read:

1. If you are NOT transferring content from Oak, Sherlock, or Google Drive, you may need to perform some setup tasks, including installation of software. Check the appendices of our instructions for details. [link "instructions" with the same link we've been using for this] Be sure you have logged into Globus with your Stanford credentials!
2. Return to your item [link this text with the same link as in step 3], click on the link for the shared folder we have created just for you, and transfer your files to that folder.

**Comment by ndushay** [comment]
@amyehodge if this is for https://github.com/sul-dlss/happy-heron/blob/main/app/views/works_mailer/globus_endpoint_created.html.erb, I don't fully understand.  The first step in the list seems like it should stay?   And what you call step 2 seems like it is now step 3???

**Comment by amyehodge** [comment]
@ndushay Apologies for dashing this ticket off too quickly. You have the right email. I added it to the description at the top as well.

Step 2 and 3 should not be combined. Here's what I'm going for:

1. If you are NOT transferring content from Oak, Sherlock, or Google Drive, you may need to perform some setup tasks, including installation of software. Check the appendices of our <%= link_to "instructions", Settings.globus.help_doc_url %> for details. Be sure you have logged into Globus with your Stanford credentials!
2. <%= link_to "Return to your item", work_url(https://github.com/work) %>, click on the link for the shared folder we have created just for you, and transfer your files to that folder.
3. <%= link_to "Return to your item", work_url(https://github.com/work) %> at sdr.stanford.edu and click the pencil icon to edit your draft.
4. Check the box in the "Add your files" section to indicate that you have uploaded your files to Globus.
5. Scroll to the bottom and click "Save as draft" to finish your deposit later, or click "Deposit" to complete your deposit

> is "be sure you are logged into globus" lost for skimmability, esp. if the user doesn't match the first clause of new step 1?

Possibly. I've been waffling with this, because where it belongs depends on whether you need to do something in the first step or not. If you don't, then it should be in step 2. Perhaps we should put it in both places, but as a sub-bullet? 

> is it intentional that the new step 2 combines the old step 2 and step 3 (or did I misunderstand?)

No -- I want these two steps still included separately. See the full 5 steps I have above.

> is it intentional to remove the link to the shared globus folder in the old step 2?

Yes. We have decided not to keep it in the email because if they change their location choice, this link does not get updated like the one in the UI.

> is it intentional to remove the "at sdr.stanford.edu" in the email text after the return to your work?

Yes. This doesn't seem needed since the link will take them there.

> is it intentional to remove the "click the pencil icon to edit your draft" from the email text?

I didn't intend for this to be removed. See my version above.

**Comment by ndushay** [comment]
Amy and I discussed and the block of text in the previous comment has the final version.
