### ISSUE TITLE
Trim leading and trailing white space from free text entry fields

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3207]
@justinlittman and I noticed that a number of organization entries had leading and/or trailing white space. These are likely present for all free text entry fields and should be trimmed.

Fields that should have leading and trailing white space trimming:
For item form:
- Title of deposit
- contact email
- first name
- last name
- abstract
- keywords
- citation
- related works
- link text
- URL (not sure if this needs it?)

For collection form:
- collection name
- description
- contact email
- link text
- URL (not sure if this needs it?)

-

**Comment by peetucket** [comment]
Presumably trimmed before saving to the database.

Unclear what to do with existing data (could leave as is, and if it is ever edited, it will be trimmed).

**Comment by justinlittman** [comment]
Might be worth a brief experiment, but I suspect in any case in which we re-deposit, existing data will get a trimming. And if we're not re-depositing trimming in the DB doesn't matter.

**Comment by justinlittman** [comment]
I've reached for strip_attributes in the past, so would recommend that approach.
