### ISSUE TITLE
Handle globus endpoint folder link before full path is available

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/happy-heron#3212]
Because the globus endpoint folder path (e.g. `/lwrubel/work123/version1`) is created async via a job, the full endpoint is not available for creating the "shared folder at Globus" link in the globus instructions on the item view page after a work is first saved. This means that the user may first get a link that goes to a truncated path at the globus endpoint (e.g. `https://app.globus.org/file-manager?&destination_id=e32f7087-d32d-4588-8517-b2d0d32d53b8&destination_path=/uploads/`) until it appears via the `after_save` callback reloading the page. 

<img width="1164" alt="Screenshot 2023-07-10 at 8 23 10 AM" src="https://github.com/sul-dlss/happy-heron/assets/1619369/b12055e5-54cf-479b-82b9-c9ee6b75ed75">

Need a design for what should display instead of a truncated link until the page reloads with the full endpoint path available. Currently the link to the folder is text, so it's hard to insert a Loading... spinner in the middle of the text.

**Comment by justinlittman** [comment]
A more appropriate option: https://getbootstrap.com/docs/5.3/components/placeholders/

**Comment by astridu** [comment]
What Justin posted is a good solution, especially if it's just a few seconds until the link is ready. You could either block out just that line or the whole block of text in the box.

**Comment by justinlittman** [comment]
Upon further consideration, I'd propose that the entire instruction box not be displayed until the link is ready. While a placeholder is more appropriate than a spinner, I don't think it would make any sense to a user why there is a placeholder in the middle of a set of instructions.

**Comment by astridu** [comment]
I agree
