### ISSUE TITLE
Update text at bottom of item deposit page when deposit button is disabled.

### ISSUE THREAD

**Issue by astridu** [sul-dlss/happy-heron#3214]
A user said they were confused as to why the deposit button was disabled on the item deposit page. Could we add the orange exclamation icon [circle-exclamation] next to the text and have the text bolded and aligned right with the buttons below it? 
New text: Deposit is disabled until file transfer is complete.
![image](https://github.com/sul-dlss/happy-heron/assets/42216982/4eb3e09c-7fb7-4897-8c6b-d5391f8f7ca8)

**Comment by mjgiarlo** [comment]
@astridu @amyehodge How can I get a deposit in this state? When I start a globus deposit and don't upload files to globus, I'm seeing a slightly different UI:

![Screenshot from 2023-07-11 12-20-26](https://github.com/sul-dlss/happy-heron/assets/131982/1df691f2-707f-4a76-95dd-97a1c9724311)

Namely, the state I'm in locally has centered text above the disabled deposit button:

> Save as draft now. Once you have completed transferring files to Globus, return here to Deposit.

Am I in the right state or the wrong state? If the right state, should that line in the line requested in this ticket both be there? How should they be positioned relative to one another? If the wrong state, any pointers you have are most welcome!

**Comment by astridu** [comment]
You are in the right state. The text above the disabled button is currently centered, but we'd like to replace it and right aligned with the buttons so it's in closer proximity (so it looks like mockup above).

**Comment by mjgiarlo** [comment]
OK, perfect. Thanks, Astrid. 😄

**Comment by astridu** [comment]
Oops, forgot to put that in. It is the Stanford palette orange: E98300
Thank you!

**Comment by mjgiarlo** [comment]
@astridu much obliged!
