### ISSUE TITLE
Require user to choose individual or organizational role category and then display only terms for that category

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3232]
This change will help make sure users are choosing a role term that is appropriate to the type of entity that they need to enter as an author or contributor. We've noted that some users are choosing roles like "author" and "contributing author" from the organizational list when they should have chosen them from the individual list. 

Require users to choose either individual or organization as the role category from a drop-down list, then in the next drop-down list, display only the role terms available for the category chosen.

The list defaults should be "individual" and then "author".

![image.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/7c6a7fd4-4425-4bf6-8c55-aa7a5e1b5d63)

**Comment by astridu** [comment]
I considered the radio button, but I think the layout could get confusing since the dropdown wouldn't be directly under 'Individual' (assuming that's the first radio button).

**Comment by justinlittman** [comment]
This strike me as confusing. Why are the select inputs unlabeled? If all I saw was "individual", I'm not sure I would know what that meant or what else to expect to find in that select input. (The meaning of "individual" is clear when it is paired with "organization".)

An additional (simple) option is to make the options in the dropdown clearer when there are duplicates, e.g., "Author (individual, not organization)" or "Contributing author (organization)".

An additional option is to have multiple Add buttons, e.g., "Add individual author" and "Add organization author". This displays both options and forces the user to make a choice prior to inputing the contributor.

**Comment by astridu** [comment]
As a compromise, I'd be ok with the radio buttons next to each other instead of stacked. 
<img width="870" alt="image" src="https://github.com/sul-dlss/happy-heron/assets/42216982/cb97b12a-a88b-49fc-8b15-276b953d9202">

**Comment by astridu** [comment]
But for accessibility, you have a point, we will need a label for the drop down. Maybe "Role term type"?

**Comment by amyehodge** [comment]
I like the side-by-side radio buttons. Though I think "role term type" is a better descriptor for the radio buttons and "role term" for the drop-down options.

**Comment by justinlittman** [comment]
Sounds good!
