### ISSUE TITLE
Add display of additional details for affiliation term matches

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3236]
For the affiliation type-ahead search, display additional information along with the name matches to help users choose the right entity.

ROR's recommendations: https://ror.readme.io/docs/create-ror-powered-typeaheads#show-information-beyond-the-primary-organization-name

These include displaying in addition to the primary name:

- addresses.geonames_city.city (City name)
- coutnry.country_name (country)
- organization type (I don't think we need this)
- acronyms
- aliases
- labels (these are names in other languages)

I'm concerned that this might get kind of a lot to display, but I don't know what the data look like. 

The ROR example shows it laid out like this:

![Screenshot 2023-07-11 at 2.55.42 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/28d67fd5-c8eb-4efc-b486-956a26fdd64a)

**Comment by amyehodge** [comment]
Note that they currently have a field that include US states but they are getting rid of it in the near future, so it doesn't seem worth including it now. State information will not be directly available in ROR -- we would have to look up the states using the geonames for the cities.

**Comment by amyehodge** [comment]
@astridu Do you have time to look at mocking up what this might look like for us?

**Comment by astridu** [comment]
How does this look? https://invis.io/NP138M0QX7T3#/473166568_add_Affiliation

**Comment by amyehodge** [comment]
@astridu State will not be included, only city and country. How will it look when there are multiple entries for acronyms, aliases and names in other languages?

**Comment by mjgiarlo** [comment]
Adding `design needed` label and moving to backlog for now. @amyehodge can you remove that label and move it back to ready when this is good to go?

**Comment by astridu** [comment]
Here is the mockup: https://invis.io/NP138M0QX7T3#/473166568_add_Affiliation

**Comment by amyehodge** [comment]
![Screenshot 2023-07-13 at 12 42 54 PM](https://github.com/sul-dlss/happy-heron/assets/5558511/88a8cf66-842d-411f-8b1d-47ed8e4f2761)
