### ISSUE TITLE
Identify H2 works that would be pushed in a given collection

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3242]
Once the ability to push H2 works to ORCID is done (via SDR as defined by tasks in epic #3102), this will handle all new and versioned works going forward.  However, there will be previous created works that could have been pushed to ORCID and we may want to push to ORCID without versioning.

Write a rake task that when given a collection druid:

1. Identifies all works in the collection
2. For each work in the collection, identify any with ORCIDs in the contributor list.
3. Look up each ORCID via the mais_orcid_client gem to see if found and write access selected by user.
4. If found, output the work id and druid and then run the job/step that pushes the work to ORCID
5. Add the ability to skip the push if a "no-op" flag is passed to the rake task, if we want to just use to identify works first and then push later

This allows us to select a specific H2 collection of interest and push any works for that collection.

This can build on the work in #3104

**Comment by justinlittman** [comment]
@peetucket The simplest possible way to do this is to invoke the update_orcid_work DSA endpoint for each item in an H2 collection. The UpdateOrcidWorkJob will determine if there are any orcid ids that have not yet been pushed to orcid and push them. Would that be acceptable?

**Comment by peetucket** [comment]
Yes, that sounds like it would address to retrospectively push previous works for any given collection.  The question for @amyehodge is do we need a way to identify these **before** pushing?  I assume the answer is no, because since we automatically push all new works, why wouldn't be push old ones too (on demand, for a given collection)?

**Comment by amyehodge** [comment]
Agreed @peetucket and @justinlittman. I don't see why we would need to know the exact works. I just need to figure out which collections we want to do this for.
