### ISSUE TITLE
Work 6867 should show as completed in H2.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3254]
Collection manager reported to me that work 6867 has not completed for several days.

This is showing as accessioned in Argo and is published to PURL and SW, so I'm not sure why H2 is still spinning with deposit in progress.

**Comment by amyehodge** [comment]
I believe this is another example of the same error: https://sdr.stanford.edu/works/6807, https://purl.stanford.edu/zj843xz2372.

**Comment by aaron-collier** [comment]
@amyehodge I set both of these to `deposited`. If there are any follow up issues, please let me know.
