### ISSUE TITLE
Figure out why work 6861 appears to be stuck in depositing. 

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3260]
https://sdr.stanford.edu/works/6861

Work has not yet been assigned a druid and has been showing "Deposit in progress..." for 20 days.

**Comment by aaron-collier** [comment]
Oddly, this one does have a record in argo that suggests it should have completed: https://argo.stanford.edu/view/druid:tk196dn5787 and purl: https://purl.stanford.edu/tk196dn5787

I'll see what the best way to get these updated might be.

**Comment by justinlittman** [comment]
This is what your seek: https://github.com/sul-dlss/happy-heron/blob/main/app/jobs/deposit_complete_job.rb#L28C7-L28C61

**Comment by aaron-collier** [comment]
Thank you @justinlittman!

**Comment by aaron-collier** [comment]
Work updated.
