### ISSUE TITLE
Deleting authors not working

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/happy-heron#3263]
Steps to reproduce:
1. Click "Deposit to this collection".
2. Select "Text" then  "Continue".
3. Populate an author using "https://sandbox.orcid.org/0000-0001-9303-6667".
4. Add another author using "Add another a author".
5. Populate additional author with "https://sandbox.orcid.org/0000-0003-0468-3673".
6. Click "Save draft"
7. Edit work.
8. Delete the second author.
9. Click "Save draft".

Expected result:
Second author is deleted.

Actual result:
Second author is not deleted.

**Comment by amyehodge** [comment]
Here's a slightly different scenario where deleting is also not working:
1. Create an item with two authors (https://sandbox.orcid.org/0000-0003-3437-349X with name text updated to Justin Littman and https://sandbox.orcid.org/0000-0002-5466-7797 with name text updated to Vivian Wong).
2. Deposit item
3. Edit to add a third author (https://sandbox.orcid.org/0000-0003-0962-2466 with name text updated to Naomi Dushay).
4. save as draft
5. edit and delete author #3. > author not deleted.
6. edit and delete author #2 > author not deleted.

**Comment by peetucket** [comment]
Cannot be reproduced when affiliations are removed from the UI in #3287
