### ISSUE TITLE
Test globus deposit with 25k files

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3265]
1. Create 25k files (see `bin/test-files` and #3157 for script)
2. Place into a globus mount
3. Create new deposit that uses globus
4. Select mount with 25k files
5. Deposit object
6. See what happens

Success == object deposited successfully (eventually) even if page takes a long time to load

**Comment by aaron-collier** [comment]
This behaves primarily luck any other large deposit. One issue I see, though may be entirely local is that above 20k files the upload to globus crashes and stops wherever it was. When a 25K file folder it missed the final 25 files. This happened the same way with 24K files, so the end result doesn't seem to be a definitive limit, but perhaps something in the way globus caches, etc...
