### ISSUE TITLE
Add instructions for users on ZIP file upload limitations

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3267]
For ZIP uploads, users should not upload objects that contain more than 25k files.  We should provide some user instructions to let them know this (i.e. number of files inside the ZIP should be less than 25k).  It will not be enforced with validation (we don't need to say this though).

Need exact language and location of message.

**Comment by amyehodge** [comment]
Current instructions look like this:
![Screenshot 2023-07-20 at 10.40.45 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/d8338346-0463-45db-a562-410f0ce5e838)

These should be updated to say:
**Upload a single zip file (containing fewer than 25,000 files and less than 10GB total), which will be unzipped, including any hierarchy.**
Viewers will see the file hierarchy and be able to download individual files. Unzipping may take several minutes if your zip file contains a large number of individual files.
**Warning:** this file upload option will automatically replace all existing files on your item with the content in the new zip file.
