### ISSUE TITLE
Add language for users around total size of globus object

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3268]
For Globus uploads, users should not upload objects that are larger than 4 TB or 25k files. We should provide some user instructions to let them know this (i.e. number of files inside on the globus mount should be less than 25k and total size of object should be less than 4 TB). It will not be enforced with validation (we don't need to say this though).

Need exact language and location of message.

**Comment by amyehodge** [comment]
Current instructions look like this:
![Screenshot 2023-07-20 at 10.48.53 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/fc61e126-54e6-4c34-be70-607fe9e851a3)

These should be updated to say:
**Upload one or more files via Globus (fewer than 25,000 files and less than 4TB total) which will be displayed as uploaded, including any file hierarchy.**
Please notify us at sdr-contact@lists.stanford.edu if you are uploading 1TB or more of content.
