### ISSUE TITLE
Unable to add author with ORCID to existing deposit

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3276]
Steps to replicate:
1. Go to https://sul-h2-qa.stanford.edu/works/563 and click pencil icon to edit work.
2. For "what's changing" entered "added third author"
3. Under the entry for Vivian, clicked "Add another author"
4. selected ORCID option
5. pasted "0000-0003-0962-2466" to the end of the orcid URL in the box
6. Changed name to "Naomi" and "Dushay" by highlighting and deleting existing text and typing in new text
7. Typed in "Juilliard" for the Affiliation and selected "Juilliard School"
8. For Department, etc entered "Brass"
9. Scrolled down and clicked "Deposit" button.
10. Expected to be taken to the item view page and for the item to deposit, but instead was taken to this screen:

 ![Screenshot 2023-07-19 at 10.20.01 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/5466f6eb-5b81-4e25-ab19-fd5cbc65c94e)

This triggered HB as well both times: https://app.honeybadger.io/projects/77112/faults/97956944

**Comment by aaron-collier** [comment]
@amyehodge I'm pretty sure (maybe it's obvious and I'm just catching up) that this related to affiliates, so when we roll that back, this should get fixed I suspect.

**Comment by amyehodge** [comment]
Closing this since as best I can tell, this is now working. I can't test the affiliations since we rolled them back, but I can add an author with an ORCID and I can turn on the auto-citation.
