### ISSUE TITLE
Able to deposit via Globus option without adding files

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3279]
1. Create new item
2. Select Globus option. In this case, I chose that my files were on Google Drive, but I previously did this and did not choose any of the three options.
3. Filled in the minimal requirements.
4. Scrolled to bottom of page, which should have had a message indicating that I couldn't deposit and the deposit option grayed out, but it looked like it would if had uploaded files via drop zone:

![Screenshot 2023-07-19 at 11.52.44 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/973642a4-e5ad-41fa-83a1-7f6f79335ac6)
5. Clicked deposit.
6. I got the intermediate message page saying my deposit was successful and what to expect next.
7. I then clicked to return to the item view page.
8. Here, I saw the placeholder for the instruction text for Globus deposits and the "deposit in progress..." message at the top. 
9. The page refreshed to display the full instructions with the link.
10. The deposit then completed and that message refreshed.
Here's a video of that:

https://images.zenhubusercontent.com/272543337/0f3a15ac-a41f-472b-b61a-44a39bfd7191/screen_recording_2023_07_19_at_11_53_11_am.mov

This [item](https://sdr.stanford.edu/works/6931) is now in a weird state displaying the instructions for the next part of the Globus deposit but the deposit has completed already. I did get the Globus endpoint notification email and the email from us about completing the deposit.https://images.zenhubusercontent.com/272543337/0f3a15ac-a41f-472b-b61a-44a39bfd7191/screen_recording_2023_07_19_at_11_53_11_am.mov

**Comment by andrewjbtw** [comment]
Amy's report matches what I found on stage. I didn't choose Google/Sherlock/Oak but everything else was the same.

I was curious if I could create a second version even though I never added files to the first, and I was able to deposit again by just filling out the "what's changing" field and not adding anything else.

On the second version I created, I saw this message about the deposit button being disabled, but the button was active:

<img width="436" alt="Screenshot 2023-07-18 at 6 11 36 PM" src="https://github.com/sul-dlss/happy-heron/assets/8975583/a59b62a1-ced2-4b37-9fa1-4dc140dbce05">
