### ISSUE TITLE
When validations are active, month fields in publication and creation date fields are too narrow.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#328]
![Screen Shot 2020-11-04 at 11.42.26 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/b1c5dc67-f2db-4ce6-a336-f15e5c3a380d)

**Comment by ndushay** [comment]
We have a problem.

Bootstrap is designed so it can responsively adapt to window width, from mobile to large desktop.  We can have up to 12 units horizontally.   The below shows what I think is the best I can do for a single line date range (I have experimented a fair bit):

### Single date
[radio button] + text: 2 columns
year + month + day:  10 columns

### Date Range
radio button w "Date range": 2 columns
year + month + day: 5 columns
"to" + year + month + day: 5 columns

![image](https://user-images.githubusercontent.com/96775/98388348-80a3a400-2007-11eb-927d-affe4e107b59.png)

I was working in Firefox, FYI.

Let's figure out what makes sense for the date range line ...
