### ISSUE TITLE
When an author is removed from a work, remove the work from the ORCID record

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3283]
If a work is updated so that an ORCID iD to which we pushed a work is removed from the object, we should update that ORCID record to remove the work.

Scenario: 
- An ORCID iD is include on a work for an author. 
- That author has given Stanford permission to update their ORCID record.
- We push the work to that ORCID record.
- The author (or, more specifically, that author's ORCID iD) is later removed from the work.
- Expected: that the work would be removed from that person's ORCID record.
- What actually happens: the work stays on the ORCID record and never receives any further updates.

**Comment by justinlittman** [comment]
Closed by https://github.com/sul-dlss/dor-services-app/pull/4544
