### ISSUE TITLE
Add validation to publication date to make sure it is in the past.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#329]
While the year validation seems to be working, I can pick a month/day that are in the future.![Screen Shot 2020-11-04 at 11.43.45 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/a6fd05cc-c500-432a-97a1-927c4c7b1ea0)

related to #373

**Comment by jcoyne** [comment]
@amyehodge I think we need to define what it means to be "in the future" in the case where month or day is optional?

For example, considering today's date is Nov, 13, 2020, is 2020 (no month or day) in the future or the past?  Is "Nov 2020" In the future?

**Comment by amyehodge** [comment]
@jcoyne Here's my thinking on this.

We allow any year up to and including the current year. When there is also a month entered, we allow anything up to and including the current month. When there is also a date, we allow anything up to and including yesterday.

I'm aware that there are some oddities that would occur on the first of the year -- since 2020 isn't in the past on Jan. 1, 2020 -- and on the first of every month -- June isn't in the past on the June 1, 2020 -- but I don't think it's worth including something to cover the complexity of those exceptions for the rare times that they would be needed.
