### ISSUE TITLE
Update collection view page to show custom rights settings

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3291]
NOTE: This work should end as a PR into #3271

#3271 adds the ability for collections to have custom rights settings, however, once you return to the show page, these are not shown.

See designs on https://projects.invisionapp.com/share/NP138M0QX7T3#/screens/473365681_custom_Rights_Statement   (scroll down to find the "Collection view" page section)

We should show:
- Additional terms of use" row in "Terms of Use and License" section
- This has multiple states and views depending on the collection settings shown
- If custom instructions are provided, an additional row is shown

**Comment by jmartin-sul** [comment]
like we did for #3097: closing this since the PR for it was merged to the feature branch, and there's a ticket for tracking when the feature branch can get merged to `main`.

part of https://github.com/sul-dlss/happy-heron/issues/3093
