### ISSUE TITLE
On the item view page, add any additional terms of use entered

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3293]
NOTE: This work should end as a PR into #3271

If none entered, show "None", else show what was entered.

See design (scroll down to "Item view" section): https://projects.invisionapp.com/share/NP138M0QX7T3#/screens/473365681_custom_Rights_Statement

**Comment by jmartin-sul** [comment]
i think #3309 took care of this also (along with #3094)

part of #3093
