### ISSUE TITLE
Merge Custom Publisher Statement #3097 to main

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3295]
After #3094, #3146 and #3291 are done, we can then merge #3097 to main

**Comment by jmartin-sul** [comment]
PR with the feature branch for 3097 and company: https://github.com/sul-dlss/happy-heron/pull/3271

**Comment by jmartin-sul** [comment]
the feature branch is merged.  will pull now-unblocked backlog tickets to the ready column on the zenhub board...
