### ISSUE TITLE
Work 6946 should be showing as "Deposited" in H2

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3296]
Possibly the same problem as #3254.

This item has a published PURL and has completed accessioning, but H2 doesn't know that.

This seems to be coming up regularly these days.

1. Set this object to deposited state.
2. See if we can figure out how things are getting into this state in the first place.

**Comment by peetucket** [comment]
Completed the deposit for this object:

```
w=Work.find(6946)
DepositCompleter.complete(object_version: w.head)
```

Created a new ticket to see if we can figure out why it is happening: #3297
