### ISSUE TITLE
Undraft, review and merge orcid push branch of workflow-server-rails

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3301]
In order to complete ORCID push for H2 works, we need to merge https://github.com/sul-dlss/workflow-server-rails/pull/666

This is the fix for https://github.com/sul-dlss/workflow-server-rails/issues/664 which needs to be completed.  Verify this can be merged without issues.

**Comment by mjgiarlo** [comment]
@peetucket There are a couple of outstanding questions on that PR. We may want to consider this issue blocked until we get a chance to discuss or resolve them.

**Comment by justinlittman** [comment]
Outstanding questions addressed. Undrafted and ready for review / merge.
