### ISSUE TITLE
Item report should indicate if the item has a custom rights statement associated with it or not.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3307]
#3094 adds the ability for users to indicate if a custom rights statement is needed for a work.

The item report (e.g. https://sdr-stage.stanford.edu/admin/work_reports/new) should add a new column indicating if the deposit has a custom rights statements. These can reported as yes/no and should be yes if whether the statement was required by the collection manager or entered by the user.

Design: https://projects.invisionapp.com/share/NP138M0QX7T3#/screens/473602644_custom_Statement_Y
Requirements: https://docs.google.com/document/d/1eWkkCIbdxO4UGT-YQoMCx-O3m_Bo3UaEaDj8OVkcTc0/edit#

**Comment by jmartin-sul** [comment]
part of #3093

**Comment by aaron-collier** [comment]
@amyehodge should there be any reporting on if the collection allows the custom statement? Or simply a yes/no on if it exists on the work?

**Comment by amyehodge** [comment]
Yep. That's #3095
