### ISSUE TITLE
Attempting to downloading a large file from preservation via the H2 interface causes the H2 app to become unstable

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#3310]
**Describe the bug**

Users can download files that they have already deposited by using the H2 interface. Each H2 item page lists all the files in the deposit. If the file has been deposited into preservation, clicking on the download link next to a file will trigger a download from preservation.

<img width="1202" alt="Screenshot 2023-07-27 at 9 57 42 AM" src="https://github.com/sul-dlss/happy-heron/assets/8975583/73f0cb0a-e582-4603-ab1a-7442b768a167">

Attempting to download a large file this way, where large is in the multi-GB range, does not work and leads the system to be unstable. It appears that after a minute or two, the download process starts to consume all the RAM on the H2 server.

**Issue in prod**

In prod, a user attempted to download a 15 GB file that they had deposited, and that triggered an HB error:
https://app.honeybadger.io/projects/77112/faults/97228356

That was followed by a number of RedisClient errors. The H2 app became unstable and Ops eventually had to reboot it. The next day, Amy also clicked on the same download link and again H2 became unstable. That second time it seemed to eventually recover on its own.

**Reproducing in stage**

@edsu and I were able to reproduce this in stage using the same file that had triggered the problem in prod. 

Stage deposit URL: https://sul-h2-stage.stanford.edu/works/19326

What we observed is that after a minute or two, all of the memory on the H2 server was consumed. Eventually my download attempt was cut off and I got an error `Incomplete response received from application`:
<img width="708" alt="Screenshot 2023-07-27 at 10 04 29 AM" src="https://github.com/sul-dlss/happy-heron/assets/8975583/261973e3-96fb-482f-ae2a-d749ab712c4f">

While the download attempt was active, the H2 app became unresponsive. Eventually it recovered on its own after the download was cut off. `htop` showed that memory and swap were maxed out:

![Screenshot 2023-07-27 at 12 29 34 PM](https://github.com/sul-dlss/happy-heron/assets/8975583/ed4be1a5-9585-477c-b4d1-e712baf9624a)

**Additional information**

Downloading the same file from preservation via Argo does not trigger the same type of error. In Argo, you can see the download begin immediately in the browser's download window, but in H2 I never saw the download begin, just the indicator that I had clicked on the download link.

**Comment by edsu** [comment]
It looks like Argo is streaming the content from PreservationCatalog:

https://github.com/sul-dlss/argo/blob/main/app/controllers/files_controller.rb#L39-L52

and there is similar code in H2 for streaming the file to the response with `response.stream.write`:

https://github.com/sul-dlss/happy-heron/blob/main/app/controllers/preservation_controller.rb#L13-L24

I wonder if there is some difference in how Apache and Passenger are configured in Argo vs H2?
