### ISSUE TITLE
Custom rights statement on collection view page should not have quotation marks around it.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3314]
This is how it looks on the collection view page currently.

![Screenshot 2023-07-28 at 2.55.12 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/287c5d5c-0f2c-46c4-a791-41101b73db05)

It should look the same as this screenshot from the item view page, which is the preferred display:
![Screenshot 2023-07-28 at 2.55.26 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/777eead8-b516-4e63-bab5-dc952921146f)

**Comment by jmartin-sul** [comment]
closed by #3320 (merged to feature branch), will get merged to `main` by #3295, part of #3093
