### ISSUE TITLE
Remove added period from end of custom rights statement

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3315]
It looks like somewhere in the code there is a period added in, because when I added the statement "These will be custom terms for this item. These terms are short." it was concatenated with the existing statement with an extra period that looks funny.

![Screenshot 2023-07-28 at 2.55.01 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/51fe26f8-01c4-4a73-bf22-75e307f671a2)

**Comment by jmartin-sul** [comment]
closing this since PR for it was merged to feature branch, and separate ticket tracks merging feature branch to `main`

**Comment by jmartin-sul** [comment]
see also #3093
