### ISSUE TITLE
Do not display instructions for terms of use when collection manager has dictated required terms.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3316]
In this case I set the collection so everything has a required set of custom terms:

![Screenshot 2023-07-28 at 3.02.39 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/94d66aa7-f223-41f4-9609-78fa0b236026)

When I open a deposit, it is displayed to me with instructions about entering terms, which I can't do.

![Screenshot 2023-07-28 at 3.03.42 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/5203519e-aec9-4e9e-89f2-d203c0431417)

The desired behavior is that when the collection manager says what the terms will be, the user should not see the instructions.

Also, there is a typo in the instructions. Near the end of the line it should say "the PURL page" not "th PURL page."

**Comment by jmartin-sul** [comment]
closed by #3318 (merged to feature branch), will get merged to `main` by #3295, part of #3093
