### ISSUE TITLE
When collection manager enters custom instructions, display them to the depositor and on the collection view page.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3317]
I entered custom instructions:
![Screenshot 2023-07-28 at 3.14.48 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/b3e7774b-9fb6-4790-810f-3c99c6dbdd2e)

but they did not appear on the collection view page:
![Screenshot 2023-07-28 at 3.14.33 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/b674d4ad-7b32-44ee-aec3-9076fe79e9ab)

or in the deposit form:
![Screenshot 2023-07-28 at 3.14.17 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/dd183ca5-30b2-4699-9ba5-4ae08a1e9d7e)

**Comment by amyehodge** [comment]
This is the mockup of how the custom instructions should look on the item view page:

![Screenshot 2023-07-28 at 3.16.36 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/6a267ec3-c4f1-4e75-9863-9fd4bcd8bd40)

**Comment by jmartin-sul** [comment]
closed by #3320 (merged to feature branch), will get merged to `main` by #3295, part of #3093
