### ISSUE TITLE
Validation of contact email on collection form needs to be improved.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#332]
(Sorry for the kinda lame title. I found it hard to summarize this).

As I type in an email address, the validation switches back and forth from doesn't validate to validates several times. It should not validate until the last screenshot -- if then, as this is still not technically valid until "edu" is completed.

1. ![Screen Shot 2020-11-04 at 12.11.13 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/a549561a-6250-44a4-abdc-e6bc12222095)

2. ![Screen Shot 2020-11-04 at 12.11.20 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/7c16d446-ed4d-43d2-ab5b-12bb52e9c4ac)

3. ![Screen Shot 2020-11-04 at 12.11.26 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/f17dd30d-2025-42be-bebf-e853f9e0e2a7)

4. ![Screen Shot 2020-11-04 at 12.11.31 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/9aab12c4-6225-4a8e-a82e-f4c2eaa452b5)

**Comment by jcoyne** [comment]
Even though that may look strange to you, a domain doesn't need to have a dot in it for it to be valid: https://en.wikipedia.org/wiki/Email_address#Domain

**Comment by amyehodge** [comment]
The only example I see of something that wouldn't have a dot is this one:
admin@mailserver1 (local domain name with no TLD, although ICANN highly discourages dotless email addresses[10])

And we don't want people using something like that, I don't think, because we want to be sure that anyone in the world would be able to email the address. 

It seems like making sure there is a dot would be appropriate. Thanks.
