### ISSUE TITLE
Push existing works to ORCID without versioning.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3322]
See #3242 for the rake task that was created to create/update existing ORCID works for a collection.

If possible (i.e. not a must-have), it would also be nice if I could get a count of the number of works where there was a push to ORCID or a number of pushes to ORCID that were done, which will presumably be greater since there may be pushes to multiple ORCID records for one H2 work. Or if there is a log that is generated from which I can extract some count information, that would be fine as well.

Works in the collections listed below should be pushed to ORCID:

work ID for collection:
5
6
14
16
17
18
22
23
25
43
44
55
58
59
61
63
64
66
67
68
69
70
76
77
79
80
83
84
85
90
91
92
93
95
102
107
115
128
130
137
147
167
168
171
173
175
179
181
187
192
198
200
202
203
209
215
219
220
236
243
251
252
253
255
258

**Comment by justinlittman** [comment]
```
5 = 4
6 = 1
14 = 0
16 = 0
17 = 0
18 = 1
22 = 0
23 = 1
25 = 0
43 = 0
44 = 0
55 = 1
58 = 1
59 = 3
61 = 1
63 = 2
64 = 0
66 = 0
67 = 0
68 = 0
69 = 0
70 = 2
76 = 66
77 = 6
79 = 13
80 = 0
83 = 3
84 = 0
85 = 1
90 = 1
91 = 1
92 = 0
93 = 0
95 = 0
102 = 1
107 = 2
115 = 13
128 = 4
130 = 1
137 = 1
147 = 0
167 = 0
168 = 63
171 = 0
173 = 16
175 = 1
179 = 0
181 = 0
187 = 17
192 = 0
198 = 0
200 = 2
202 = 7
203 = 2
209 = 7
215 = 1
219 = 3
220 = 2
236 = 0
243 = 4
251 = 1
252 = 7
253 = 5
255 = 17
258 = 0
TOTAL ORCID WORKS: 285
UNIQUE DRUIDS: 236
```

See https://github.com/sul-dlss/dor-services-app/issues/4545

**Comment by amyehodge** [comment]
@hannahfrost You might be interested in seeing what was pushed.

Also, I had one work pushed and received an email notification about it from ORCID this morning. Nice!
