### ISSUE TITLE
Report on accessibility work that has been done, and what remains

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/happy-heron#3324]
From speaking 1:1 with Vivian, management wants a way to know what accessibility work has been completed and what remains.

Since we started from the spreadsheet we got from SODA, then modified by Amy and myself, it seems that spreadsheet is the best way to "count."   Our ticketing does NOT always correlate to line items in the spreadsheet, so going by tickets is hard.

I told Vivian I would try to correlate the work we've done with the spreadsheet and come up with some kind of mechanism for management to understand our progress.

Note that in July I did make an attempt to figure out what we had done vis-a-vis the google sheet, so this is either going to be continuing that work or coming up with a better way to indicate the problems.  (e.g. tool by tool or whatever).

**Comment by aaron-collier** [comment]
I think this can be closed now. We've reviewed this against the SODA report and the follow up with Alan, closing for now and can revisit (maybe as part of ATL work) later.
