### ISSUE TITLE
When adding or removing custom terms from an item, history should indicate terms have been changed

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3342]
When a depositor adds, changes, or removes custom terms from an item, the entry in the history table should say "custom terms modified." Instead, it currently says "add/remove files". See https://sdr.stanford.edu/works/6931.

This is what the history entry looks like now when terms added:
![Screenshot 2023-08-07 at 5.06.22 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/1f992c80-8eec-40e8-83c0-af586efe8cab)

This is what the history entry looks like now when terms are removed:
![Screenshot 2023-08-07 at 5.05.17 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/b4316028-b373-4f37-8e28-59fc6f6f2d65)

To see the desired behavior, you need to be working in a collection that has the custom rights statement option turned on. So, for the collection:
1. edit collection settings
2. scroll to terms of use section
3. for question "Include custom use statement?" set this to "yes". 
4. Choose "Allow depositor to enter their own terms"
5. scroll to bottom and save.

Then create an item in that collection.
1. in the license section in the box for "Additional terms of use" add custom terms.
2. save as draft or deposit the item. 

This should generate an entry in the history table with a description that says "custom terms modified."

The same "custom terms modified" text should also show up in the history table in the description if terms are modified or removed.

**Comment by justinlittman** [comment]
@amyehodge What are "custom terms"? Can you please provide specific steps to replicate? Thanks.

**Comment by amyehodge** [comment]
@justinlittman I have updated the description above. Let me know if it needs additional clarity.

**Comment by justinlittman** [comment]
Thanks @amyehodge. Makes sense now.
