### ISSUE TITLE
On deposit form, section header for setting license and custom terms should read "Terms of use and license*"

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3348]
This currently reads just "License*".

![Screenshot 2023-08-09 at 9.31.08 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/21911b02-44b2-4a1a-b3ae-6e665231b271)

**Comment by aaron-collier** [comment]
Ah, this was changed in the mock ups, apologies, should be a quick fix.
