### ISSUE TITLE
Add share link icons next to file names on item view page 

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3351]
The goal here is to make it clearer to users what link they should be using for publicly sharing a single file, and that it's not the download link, which either goes to H2 local storage for draft items or preservation for deposited items, neither of which are publicly accessible. We have seen depositors use both of these links to try to share their files.

The proposal is to add share link icons next to the file names in the table on the item view page.

- The links will be grayed out and inactive when the item has not yet been deposited.
- The links will be active when the item has been deposited.
- The links will direct people to the stacks URL for the file.

![Screenshot 2023-08-09 at 9.53.39 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/7ce34ce1-43bc-499e-a551-9f6e2155243d)

**Comment by justinlittman** [comment]
Here is how Argo generates the link for stacks: https://github.com/sul-dlss/argo/blob/8b45cdcc0d245aace4986fd8d2d5bc8817d01aea/app/views/files/index.html.erb#L4

Note that in H2 a file is shelved if it is NOT hidden.

@amyehodge What should be displayed if a file is not shelved?

**Comment by amyehodge** [comment]
@astridu What do you think should be displayed if the file is hidden?

**Comment by astridu** [comment]
Should both the download and link be grayed out?

**Comment by justinlittman** [comment]
Per @amyehodge when a file is hidden, download icon should be enabled, and link icon should be disabled/grey.

**Comment by astridu** [comment]
I think that's fine. And then the column on the right will let the user know if it's hidden or not.
