### ISSUE TITLE
Revise custom terms options for collection managers and add validation

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3357]
After some discussion with @justinlittman about adding validations to the form as is, we came up with a plan that would simplify the form, make the structure of these options more similar to other options on the form, and make it easier to apply the necessary validations.

The top part of the custom terms section of the form should stay as is:

![Screenshot 2023-08-09 at 3.35.43 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/8575c8cd-7d23-47a6-abfc-95e3a7154c37)

Below this header there should be three options with radio buttons. The first option ("No...") should be selected by default.
- No, do not include a custom use statement
- Yes, include the following custom use statement for every deposit in this collection  [**with entry field for custom terms**]
- Yes, allow the depositor to enter their own custom use statement. The depositor will see either the default instructions or your custom instructions if provided below.

Default instructions: Enter additional terms of use not covered by your chosen license or the default terms shown above, which also display on the PURL page. 
Custom instructions: [** with entry field for custom instructions**]

The instruction lines could be a bulleted list indented below the third option.

- When the second option is chosen, require that there be text in the entry field.
- For the third option, when there is no text entered for instructions, use the default instructions.

**Comment by amyehodge** [comment]
@astridu If you have time, could you review this plan to revise the custom terms for the collection manager form? Thanks.

**Comment by astridu** [comment]
@amyehodge That makes sense. Did I mock it up correctly?
<img width="1081" alt="image" src="https://github.com/sul-dlss/happy-heron/assets/42216982/0a5e9586-af44-4a50-ba0b-25dd8b67f775">
<img width="1077" alt="image" src="https://github.com/sul-dlss/happy-heron/assets/42216982/7edf79f1-35c2-429d-8ae4-5ee17080a00f">
<img width="1077" alt="image" src="https://github.com/sul-dlss/happy-heron/assets/42216982/b590b3ad-1104-49c3-9d09-0fdec7fba403">

**Comment by amyehodge** [comment]
Thanks @astridu ! This looks great, and you're always so fast!

I think the box for the second option doesn't need to be dynamic -- it can always display. That would be similar to how the release options work and will simplify things. And I think it makes it clearer what they need to do, otherwise until you select that option you can't see where you would enter the custom terms.

Same for the third option -- the instruction box doesn't need to be dynamic. I hadn't thought about having the default instructions display in the box. I'm trying to decide if that looks like default instructions or if it looks like instructions to the user on what to put in the box. I'm thinking it seems more like the latter. So, maybe have the default instructions display above the entry box?

**Comment by astridu** [comment]
Is this correct?
<img width="1077" alt="image" src="https://github.com/sul-dlss/happy-heron/assets/42216982/5b1015c9-48bf-4aae-8585-87da7bbf3829">

**Comment by amyehodge** [comment]
@justinlittman I like @astridu 's layout for the third option above. The changes for that would be:

-  default instructions above the box
-  a little more white space between things compared to how it currently looks, if possible
-  "_Enter custom instructions_" text in the text entry field for option 3
-  Could we also get "_Enter custom use statement_" in the box for the second option? The text shown in the mockup there is not correct.

**Comment by justinlittman** [comment]
<img width="1233" alt="image" src="https://github.com/sul-dlss/happy-heron/assets/588335/3b1f46c3-e316-44c9-9459-d0ff6e00b814">
