### ISSUE TITLE
Subtitle text for "Manage release" section of deposit form should change depending on whether review workflow is active or not.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#336]
Note: I'm aware this will need to wait until the review workflow functionality exists, but didn't want to forget about this.

This is specified in the design doc here: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.irg0o2y6827n

The current text in the app contains the text "[see options below]" that should be replaced with one of two text options given in the design doc depending on whether the review workflow is active.

**Comment by jcoyne** [comment]
@amyehodge is this complete?

**Comment by amyehodge** [comment]
@jcoyne This does not look to me like it's working. I have a collection with the review workflow turned on and I do not see the alternate text. 
![Screen Shot 2020-11-19 at 10 22 38 AM](https://user-images.githubusercontent.com/5558511/99707353-2d8f0f80-2a51-11eb-8a21-c6afb8881ccf.png)

**Comment by jcoyne** [comment]
@amyehodge I believe this is already complete (again). Can you confirm?

**Comment by amyehodge** [comment]
Still not seeing the correct text when the review workflow is on. I see:
![Screen Shot 2021-02-09 at 11 22 13 AM](https://user-images.githubusercontent.com/5558511/107416237-1a786280-6ac9-11eb-9eb9-2019e3db0c04.png)

It should say "Select when the files in your deposit will be downloadable from the PURL page. If you select "Immediately", your files will be available shortly after **your deposit is approved**. Or you may specify a specific date in the future."
The difference is indicated in bold.

**Comment by jcoyne** [comment]
Got it. This section:
> Select when the files in your deposit will be downloadable from the PURL page. If you select "Immediately", your files will be available shortly after [see options below]. Or you may specify a specific date in the future.
>
> If the approval workflow is not active: you click "Deposit" at the bottom of this page
> If the approval workflow is active: your deposit is approved

**Comment by amyehodge** [comment]
@jcoyne Exactly.
