### ISSUE TITLE
Left to right orientation in Globus File Manager seems counter-intuitive

### ISSUE THREAD

**Issue by edsu** [sul-dlss/happy-heron#3374]
When you request a Globus endpoint to transfer into you get an email like this:

```
Globus user SDR stage ([840c2e68-cc53-4059-8d1c-470ff2c78cb3@clients.auth.globus.org](mailto:840c2e68-cc53-4059-8d1c-470ff2c78cb3@clients.auth.globus.org)) shared the folder "version1" on the endpoint "SDR stage" (endpoint id: f3e29605-7ba5-45f5-8900-f721663cf1af) with Edward Summers's ([edsu@stanford.edu](mailto:edsu@stanford.edu)) Stanford University identity.

Use this URL to access the folder:
https://app.globus.org/file-manager?&origin_id=f3e29605-7ba5-45f5-8900-f721663cf1af&origin_path=/uploads/edsu/work19366/version1/&add_identity=d28a330f-9d3c-4832-950c-492fb7771a9e ...
```

When you open the link you see the File Manager interface with the new Globus endpoint you are transferring *to* in the pane on the left, and the place you want to transfer *from* on the right:

![Screenshot 2023-09-07 at 6 55 13 AM](https://github.com/sul-dlss/happy-heron/assets/33829/b517c448-a339-4833-9b6e-12c65ea65ca1)

Maybe it's just me but I expect the place I want to transfer *from* to be on the left, and the place I want to transfer *to* on the right.

I think this is because we are using `origin_id` and `origin_path` in the File Manager URL and not `destination_id` and `destination_path` (see [docs](https://docs.globus.org/faq/transfer-sharing/#file_manager_httpsapp_globus_orgfile_manager)).

If my expectation here is incorrect and the design was for users to see the location being copied to on the left then of course please close this ticket!

**Comment by amyehodge** [comment]
@edsu I agree that the place you are transferring from should be on the left. When the user chooses Google Drive, Oak, or Sherlock as the location of their content and we send them the link that incorporates both the location of their content and the destination folder, the origin is on the left and the destination is on the right. I hadn't realized that this was not the case at this point for content from other places. It would be nice to have these consistent and to match expectations.

**Comment by andrewjbtw** [comment]
Interesting, the link that's in the H2 interface opens the SDR pane on the right as expected:

<img width="1641" alt="Screenshot 2023-09-12 at 5 06 02 PM" src="https://github.com/sul-dlss/happy-heron/assets/8975583/156b0909-e075-43b0-bdea-6370e9fe3407">

**Comment by amyehodge** [comment]
@edsu @andrewjbtw I've tested all 4 options for the Globus upload: no location given, Stanford Google Drive, Oak, and Sherlock. In every case, the link that we are providing in the UI has the destination folder on the right and the origin folder (if we have one) on the left.

Also in every case, the link in the Globus email contains only the destination folder (as expected), and it's always on the left. I'm pretty sure we can't get 1) these emails turned off or 2) the origin folders included in the link when we have them. But can we possibly get 3) the destination folders to show up on the right? 

I wonder if users are actually using the links in these emails?

**Comment by edsu** [comment]
It's difficult to say whether users click on these email links since the request goes directly to a globus webserver. But I guess user testing could surface whether they are used?

It looks like we do have control over the text of the email message if we want to customize it, and change the URL?

https://docs.globus.org/api/transfer/acl/#rest_access_create

See the `notify_message` parameter?

**Comment by amyehodge** [comment]
Hmmm. Nothing about the info at that link looks anything like the text of the email that I get from Globus, so I'm not clear how we can change that link? Maybe I'm just missing the point. I do see the notify_message parameter, but it seems different from this.

Email text:
Globus user SDR prod ([6c6e5919-fd00-483a-af9c-16255f8933d2@clients.auth.globus.org](mailto:6c6e5919-fd00-483a-af9c-16255f8933d2@clients.auth.globus.org)) shared the folder "version1" on the endpoint "SDR prod" (endpoint id: b73a42fb-2cb0-4ba2-9507-90a3c2457669) with Amy Hodge's ([amyhodge@stanford.edu](mailto:amyhodge@stanford.edu)) Stanford University identity.

Use this URL to access the folder:
https://app.globus.org/file-manager?&origin_id=b73a42fb-2cb0-4ba2-9507-90a3c2457669&origin_path=/uploads/amyhodge/work7129/version1/&add_identity=f8db6d8c-52ae-4d0e-a112-15f8adc13e0c

Trouble accessing the folder?
You can watch a help video here https://youtu.be/jdeMtubk8D4 or contact [support@globus.org](mailto:support@globus.org).

This is a courtesy notification. Please do not reply to this email.

The Globus Team
[support@globus.org](mailto:support@globus.org)

**Comment by amyehodge** [comment]
@edsu Now that we've gotten these emails from Globus turned off to avoid confusion, I think we can close this ticket, yes? Thanks.
