### ISSUE TITLE
Unable to add new collection creators

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3377]
Adding new users to the dlss:hydrus-app-collection-creators workgroup should give them permission to create a new collection. A button like the one shown below should show up on their dashboard:

<img width="958" alt="Screenshot 2023-09-11 at 2 55 44 PM" src="https://github.com/sul-dlss/happy-heron/assets/5558511/9daa42a6-367f-406a-b6e5-2411c047a5fe">

However, I added a new user, zimmerd, to this workgroup on 09-01-23 and he is still unable to see this button. Just today I tried adding Cory Lown to this workgroup and he was unable to see the button as well. He tried two browsers (Chrome and Firefox, I believe).

I gave zimmerd depositor permissions on a test collection of mine and he was able to log into the app, but still can't see the button.

**Comment by amyehodge** [comment]
Existing collection creator permissions do not seem to be affected. It looks like it's just that new additions to the workgroup are not seeing the button in H2.

**Comment by peetucket** [comment]
I have looked at the code and don't see any recent changes to functionality, so am not sure why it is occurring yet.  Things outside our code that could have changed that would cause issues:

- Workgroup name (`dlss:hydrus-app-collection-creators`)
- Header (`HTTP_X_GROUPS`) coming from shibboleth that determines which groups a user is in
 
But if either of these changed, all current users should be affected too.   

I made a small PR to add some additional logging to see if this gives us any clues for debugging.  

One possible idea is that I noted we currently cache groups in a session variable, so if you add a user to a new group, it won't kick in until their session expires and they log in again.  I assumed the users who are now having problems tried again after clearing their session (I would think closing the browser full and restarting would do it, I used web developer extension to do it on demand).   But again, this caching behavior hasn't changed recently either.

**Comment by amyehodge** [comment]
I just checked and the workgroup name definitely has not changed.
Also, Cory was one of my testers and he now sees the button. He had to authenticate, so it looks like his session was cleared between the last time he checked and now when he can see it.
I'm checking with my other user. Perhaps we just ran into a batch of caching problems that I hadn't seen in a long time and this is okay? I'll check back in when i hear from my other user.

**Comment by amyehodge** [comment]
My other has reported that they can now see the button as well, so I think we can chalk this up to the caching problem creeping back in for the first time in a while.

@peetucket I think we can close this, unless there is something else you think we should look into?

**Comment by peetucket** [comment]
OK sounds good - and we do have a bit of extra logging now in the future if we need it.  But perhaps if it  happens again, you can first suggest quitting their browser for good measure and then restarting and logging in again.  I believe this would clear any session variables holding on to the previous work groups and force them to be refreshed in a new login session.  If that fixes the problem for them, this makes it almost certain it is a caching in the session variable issue.

**Comment by amyehodge** [comment]
I will definitely do that. We had this problem many years ago, but I haven't seen it in so long that I had forgotten about this new session. I'll remember that for the future. Apologies for the churn. Closing this ticket.
