### ISSUE TITLE
Require author when creating a DOI

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3379]
See related issue #3375 where this was previously discussed. In that case, there was no entry in the "authors to include in citation" section of the form and it caused accessioning to break.

Desired behavior is to:
1) require an entry (of any role) in the "authors to include in citation" section when creating a DOI. If no DOI is being created, it's acceptable not to have any entries in the section and just have entries in the "additional contributors" section of the form.
2) If there is no entry in the "authors to include in citation" section but the user has selected to get a DOI or the DOI option is set to always be "yes" by the collection manager:
- continue with accessioning but do not create a DOI
- notify the user by inserting a comment in the DOI field on the item view page that says "Unable to create DOI. Contact us for further details." Possibly in red or something that stands out so they see it?
- notify an admin somehow, possibly via email, but I'm open to other suggestions.

**Comment by peetucket** [comment]
Note also:

1. Investigate if we implement # 1, then then # 2 will never occur?  If true, then we do need to implement # 2.  
2. If so, the validation message should indicate why this is required, e.g. "At least one author included in the citation must be added in order to create a DOI."

**Comment by amyehodge** [comment]
I agree with @peetucket that if we implement #1, we do not need to implement #2.

**Comment by justinlittman** [comment]
@amyehodge Can you reproduce this problem? When I try to deposit without a contributor I get:
![image](https://github.com/sul-dlss/happy-heron/assets/588335/92a5cf7a-f4f8-48c9-ba13-68d8bf239705)

**Comment by amyehodge** [comment]
@justinlittman I'm not sure what's going on here. Based on what was going on when we were discussing the previous ticket, we did not have any requirement in H2 to have an entry in the "authors to include in citation" section. Ever.

What we decided was that *when you are asking for a DOI* you must put an entry in this section, so we needed to add that requirements. 

If you aren't getting a DOI, then it's okay just to have entries in the "Additional contributors" section. 

What I'm seeing now -- even though I didn't think anyone had done any work on this other than to fix the previously broken object -- is that an entry in "authors to include in the citation" is required all the time, whether you're getting a DOI or not. This is also not right, but in the completely opposite way of what it was before.

So, no, I can't reproduce what the ticket says. However, the desired behavior is that *when you're getting a DOI, and ONLY when you're getting a DOI, you must have an entry in the "authors to include in citation" section.

**Comment by peetucket** [comment]
It appears #1 is already implemented and has been for a while (at least 5 months based on my investigation): https://github.com/sul-dlss/happy-heron/blob/main/app/forms/work_form.rb#L19

This may be an acceptable solution that should prevent the DOI metadata mapping issue from occurring.  It is unclear how the problematic item was able to be created that way (without an author).

**Comment by amyehodge** [comment]
Confirming that there is no further work to be done here at this time. Closing this ticket.
