### ISSUE TITLE
When user modifies Globus file location, update the link in the UI

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3384]
If a user chooses the Globus upload option and then clicks "save as draft," we provide a link in the UI based on where they told us the files are: no location given, Google Drive, Oak, or Sherlock. If the user changes their mind about this, the link in the UI does not get updated, so if they go from no location to Oak, for example, they are not getting the link that opens Oak on the left and our folder on the right. 

When the user makes a change to this location option, we should update the link.

Steps to replicate:
1. Create a new item. Select any work type.
2. In the file upload section, choose option 3 "Upload one or more files via Globus."
3. Do not select a file location.
4. Scroll to the bottom and click "save as draft."
5. Wait for Globus link to display on the page. Click on link to see that it opens just our destination folder on the right.
6. Click on a pencil icon to edit the item and change the location to "Oak."
7. Scroll to the bottom and click "save as draft."
8. Wait a few seconds to give them link time to update (I did this hoping it would, though since it doesn't the wait doesn't really matter here).
9. Click on the Globus link where you'll see that this opens the same page instead of one that has Oak on the link for the origin.

Desired behavior is for the link to update so they get one that has the right information for the origin on the left that reflects their change.

Note that neither the email from us or the Globus email is being resent either. Since the email from us does not contain the link, I think it's actually best that this email NOT resend. And since the Globus email does not contain an accurate link with the origin info, it's probably better that it not resend either, though we may not have any control over that.

**Comment by lwrubel** [comment]
I'm unable to replicate this. When I follow the steps, I get an updated origin (Oak, Drive, etc) in the link each time after saving as draft.

**Comment by amyehodge** [comment]
@lwrubel Agreed. This is now showing the desired behavior.

**Comment by amyehodge** [comment]
@lwrubel Agreed. This is now showing the desired behavior.
