### ISSUE TITLE
Depositors can't make metadata-only updates to items where the UI doesn't let them edit files

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#3392]
When a deposit has more than 250 files, users are shown a message that they cannot update their files in the UI, they can only use the zip or Globus option. 

<img width="982" alt="Screenshot 2023-10-05 at 11 19 50 AM" src="https://github.com/sul-dlss/happy-heron/assets/8975583/0f61f9a4-abcd-4d1d-9326-8c39db6bef2f">

Unfortunately, it appears that the UI is requiring users to modify their files in this situation. A metadata-only update, such as a change in the contact email, is rejected with a message saying that at least one file must be uploaded.

![ScreenshotErrorSDR 62](https://github.com/sul-dlss/happy-heron/assets/8975583/eec73447-1cf4-44c3-ba91-6fb96098b494)

**Expected behavior**

Users should not be required to modify files in order to make metadata updates.

**Comment by andrewjbtw** [comment]
I was able to reproduce this on stage: https://sul-h2-stage.stanford.edu/works/19308 (though that item will be deleted when stage is reset)

**Comment by andrewjbtw** [comment]
To reproduce:

1. Go to https://sul-h2-stage.stanford.edu/works/19308
2. Start a new version
3. Change something like the title or a name
4. Click on deposit
5. See the message that a file must be uploaded

Further investigation shows that if you save the draft before trying to deposit, the draft will then be saved without any files.

1. Go to https://sul-h2-stage.stanford.edu/works/19308
2. Start a new version
3. Change something like the title or a name
4. Click on save draft
5. Reopen the draft
6. See that no files are listed and the screen looks like it's a new object

**Comment by jmartin-sul** [comment]
i looked into this for a bit this afternoon/this evening, but wasn't able to figure out what was going wrong.  what i found so far from using @andrewjbtw's test case and poking around the code and the browser debugger:
- the error message seems to be coming from the `attached_files` validation in work_form.rb
- the validation appears set up to only run when the `upload_type` is `browser` or `zip`
- the form submission doesn't seem to POST any fields with `upload_type` or `attached_files` in their names
- when the form is initially presented with the "You have more than 250 files" warning text, neither of the `upload_type` `input` elements is `checked` (`work_upload_type_globus` and `work_upload_type_zipfile`)
- once the edits are attempted and the deposit button is hit, and the `work_upload_type_browser` `input` is `checked`.  and as andrew's screenshot shows, the browser upload option is added back to the "Add your files" section above the zip and globus options (and is the default selection, as expected from what shows up in the DOM).

i didn't get around yet to adding debug logging in the form handling machinery and deploying with that, but that'd be the next thing i'd try.

of course my first suspicion is that reform is setting some default value for `upload_type` when we don't want it to, but i couldn't find where.

**Comment by andrewjbtw** [comment]
I've updated my comments above with a link to new sample data in QA (now that stage has been reset).
