### ISSUE TITLE
Map related works to descriptive cocina

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#340]

**Comment by ndushay** [comment]
Is this about mapping the data from here in the deposit form:

![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/6a9559ea-cd66-43f5-b08b-cd6d02da6392)

into the cocina model, in h2 code?   Or is it about ensuring we have a mapping for this in dor-services-app?  Or?

**Comment by justinlittman** [comment]
Yeah, some additional guidance is needed here. In H2, related work is a string. In the mapping examples in https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_relatedItem.txt, it is a structured value.

How should this be handled?

**Comment by jcoyne** [comment]
@arcadiafalcone @amy can you address @justinlittman's concerns?

**Comment by arcadiafalcone** [comment]
I'll write up some mapping specs for this.

**Comment by jcoyne** [comment]
See https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/bed8de56d79834845d5f0913cf2f288d6c06c058/h2_cocina_mappings/h2_to_cocina_related_resource.txt
