### ISSUE TITLE
Join custom use and reproduction statement with newline

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/happy-heron#3404]
Builds on #3094.

A downstream feature request in purl is to separate multiple use and reproduction statements, so that a user-supplied one coming from h2 can be given special formatting and prominence (see mockup):

![Screenshot 2023-10-18 at 15 31 07](https://github.com/sul-dlss/happy-heron/assets/4924494/3ea04158-c01b-472e-be47-92634cc2ad8f)

What would it take to have multiple distinct statements in the metadata (cocina, but also public XML, since purl currently doesn't use the cocina)? How would we indicate that one of the statements is a default, while the other is user-supplied?

Example item with user-supplied statement: https://purl.stanford.edu/fg611qq0508

**Comment by amyehodge** [comment]
@thatbudakguy I've discussed the headers with Hannah and we've agreed on what is in the design. We don't need anything further to distinguish default vs. user-supplied.

**Comment by justinlittman** [comment]
This would require a change in cocina and public xml, as the use and reproduction statements are stored in a single field. Making this change is feasible but medium LOE and medium risk, as it requires coordinated changes in H2, SDR API, Dor Services App, Dor Indexing App, and Purl.

**Comment by andrewjbtw** [comment]
There's also a question of what a new field will mean for Argo, which currently has edit access to every user-editable metadata field. Argo users won't normally need to use a field that's meant only for H2 deposits, but we'll need to consider what to do in situations where an object stops being managed by H2.

**Comment by thatbudakguy** [comment]
Based on storytime today we think we can take an approach similar to https://github.com/sul-dlss/mods_display/issues/78, where line breaks are preserved in the cocina and encoded as `&#10;` in the MODS XML.

https://github.com/sul-dlss/mods_display/issues/145 will ensure that the line breaks aren't stripped at display time.

**Comment by thatbudakguy** [comment]
We've decided not to add a new field or have a separate header, as in the decision shown.

**Comment by lwrubel** [comment]
Closed with #3127.
