### ISSUE TITLE
Map related links to descriptive cocina

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#341]

**Comment by ndushay** [comment]
Is this about mapping the data from here in the work deposit form:

![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/3b8fca09-9122-4eda-8b1c-16f7e70fa23d)

into the cocina model, in h2 code?   Or is it about ensuring we have a mapping for this in dor-services-app?

**Comment by jcoyne** [comment]
Yes, h2 maps it to Cocina so it can deposit the work.

**Comment by jcoyne** [comment]
That work happens in https://github.com/sul-dlss/happy-heron/blob/main/app/services/description_generator.rb

**Comment by jcoyne** [comment]
See https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/bed8de56d79834845d5f0913cf2f288d6c06c058/h2_cocina_mappings/h2_to_cocina_related_resource.txt
