### ISSUE TITLE
Validate that ZIP file is added when saving with ZIP upload option

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3459]
See #3454 for related work which fixes some situations where the ZIP upload job can get stuck.  While this should not occur anymore, there is still an edge case which can lead to unexpected behavior.

Basically the way we have it setup right now, a user can:

1. Select browser upload and upload some files, including a ZIP file.
2. Save the draft.
3. Edit the draft, select the "ZIP upload" option, and then save the draft again without actually adding a file.

If the last file attached in step 1 happened to be a ZIP file, the ZIP Upload Job will unzip this file and replace all of the other files in the object.  This is the expected behavior for ZIP Uploads, but in this case may be unexpected, since the user never actually supplied a new ZIP after selecting that option.

So, this new validation would prevent the user from submitting the form (even a draft save) if they have selected ZIP Upload but then not provided a ZIP file.

Pending text of validation error message.

**Comment by amyehodge** [comment]
Question: can we prevent saving as described above but ONLY when there are already files attached to the item? 

Proposed validation message: Because you already have files saved, you can only select this option if you upload a zip file, which will replace all of your other files. If you don't want to upload a zip file, you must choose the first file upload option to save or deposit. 

I know it's long, but Astrid and I talked through this and it's a really challenging situation because there are several reasons why the user might have ended up in this spot. 

It would be best if the error message could display in the zip file upload section.

**Comment by peetucket** [comment]
Yes, we can mostly do this.  The validation check occurs server side though, so the error message appears at the top.  Because the upload box is also at the top of the page, it is pretty clear in my view.  See the screenshot:

<img width="1371" alt="Screen Shot 2024-02-05 at 1 34 00 PM" src="https://github.com/sul-dlss/happy-heron/assets/47137/491686a0-9610-4de8-8014-2765d3cb1862">

I can also deploy this to stage for verification.

**Comment by amyehodge** [comment]
@peetucket Since this is above the form, can you change the text a smidge to say ""...you can only select the zip file upload option if you upload a zip file,...."

**Comment by amyehodge** [comment]
@peetucket I've encountered a problem. I uploaded more than 250 files and then chose the zip file upload option. I ended up unable to select the option that we've told them to select. 

<img width="906" alt="Screenshot 2024-02-06 at 2 04 54 PM" src="https://github.com/sul-dlss/happy-heron/assets/5558511/81f8b8e4-a82d-4cb1-bff8-137bfff8d9c2">

This actually is a problem more generally. That is, if you upload more than 250 files, you see this when you open the form:
<img width="778" alt="Screenshot 2024-02-06 at 2 16 43 PM" src="https://github.com/sul-dlss/happy-heron/assets/5558511/ee74c04c-62de-4d5f-acad-db14ded53532">

Once you select either the zip or the globus option, you can't unselect an option, nor can you select the first option again. If you want to preserve the files that are on the object, you have to be careful not to touch anything in here.

@astridu you might have thoughts about this.

**Comment by amyehodge** [comment]
The error message isn't showing up when I try to deposit, only when saving as draft. When clicking "deposit" I see:

<img width="817" alt="Screenshot 2024-02-06 at 2 23 49 PM" src="https://github.com/sul-dlss/happy-heron/assets/5558511/52a89c29-aab5-4d6d-b557-8bcbc146f99a">
