### ISSUE TITLE
[happy-heron/prod] ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/happy-heron#3489]
## Backtrace

    line 26 of [PROJECT_ROOT]/app/jobs/deposit_complete_job.rb: work

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/77112/faults/105966029)

**Comment by justinlittman** [comment]
H2 clearly needs some connection pool size tuning.

**Comment by justinlittman** [comment]
Increasing to 10: https://github.com/sul-dlss/puppet/pull/10479

**Comment by amyehodge** [comment]
@justinlittman This fits -- I searched for the druid on one of these alerts earlier this week and H2 said it didn't exist there, but I got distracted and never followed up.
