### ISSUE TITLE
Implement new version section

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/happy-heron#3504]
Currently the version section displays:
![image](https://github.com/sul-dlss/happy-heron/assets/588335/e93d53e9-60c3-47fc-ab11-d375e4b6431e)

The new version section should display:
![image](https://github.com/sul-dlss/happy-heron/assets/588335/807413b4-0691-4827-8843-a0fc30e610b0)

For this ticket:
* The new version section should only be visible when a feature flag is enabled; otherwise, the current version section should be displayed.
* The form should submit the "What's changed?" value (like the current implementation); for now, the value of the radio buttons can be ignored. In other words, deposit should continue to function as it currently does.

**Comment by justinlittman** [comment]
Also, client side validation before deposit should ensure that user has made a selection and provided a "What's changing" value.

**Comment by lwrubel** [comment]
@astridu what should the UX be when someone selects an option, then changes their selection? Should it wipe out anything they had in the "What's changing?" box? Or hide that box?

**Comment by astridu** [comment]
@lwrubel Oooh, good question! 
If they switch from Yes to No, then it will disable the upload files section, and anything they added to that section will not be changed. Plus, if they put something in the 'What's changing', it would be nice if we didn't wipe it out so then if they switched back, it was still there. Same with switching from No to Yes. Is that possible? Also, if they did upload files and then switch Yes to No to Yes, then could the files still be there? @amyehodge Are you ok w/this? Happy to huddle if needed.

**Comment by lwrubel** [comment]
For this ticket, I'm just working out the Yes/No and version description boxes. If you've got recommendations for the files box, would be great to drop those here: https://github.com/sul-dlss/happy-heron/issues/3505

**Comment by amyehodge** [comment]
@astridu This sounds good. I've noted the preference for the file upload section on the other ticket @lwrubel mentioned. Thanks.

**Comment by lwrubel** [comment]
What should trigger the client side validation about whether Yes/No and is selected and what's changed is provided? Clicking the deposit/save-draft buttons?

**Comment by lwrubel** [comment]
@justinlittman @astridu for the purposes of this ticket, which involves client-side validation of the user version box, where should the error appear if the user does not click on the Yes/No options to create a new version and/or does not provide a message? I can put that error up near those fields, but it may be confusing to the user when they click on the Save as draft / deposit button and nothing seems to happen. This could also be initially implemented as a javascript alert and then later worked into the design.

**Comment by amyehodge** [comment]
@lwrubel If the user clicks the Deposit button and there are any errors on the page, the page scrolls back up to where the first error message is. I'm happy to give you a quick demo of how this works currently.

**Comment by lwrubel** [comment]
Thanks @amyehodge, I need to figure out how that is implemented to make it work for this box. I think those other validations may not be client-side? Will look.
