### ISSUE TITLE
Disable files section when user selects to not create a new version

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/happy-heron#3505]
If the user has selected nothing, the file section should be enabled.
If the user has selected "no", the file section should be disabled.
If the user has selected "yes", the file section should be enabled.

See #3504 for the addition of the new version section.

Please verify that when a disabled file section is changed, the files remain unchanged.

**Comment by amyehodge** [comment]
@astridu  has indicated that if the user uploads files and then switches Yes to No to Yes, then the files should still be there. 
This works for me.
