### ISSUE TITLE
Update user version when discarding a draft.

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/happy-heron#3515]
When discarding a draft work version and the draft work version has a user_version:
* If the previous work version has a user_version do nothing.
* If the previous work version does not have a user_version, move the user_version from the draft work_version to the previous work_version.

**Comment by aaron-collier** [comment]
I'm not clear on how a draft work version from H2 will get a UserVersion. Can we discuss at standup or a story time?

**Comment by justinlittman** [comment]
In the H2 data model, user_version is an attribute of WorkVersion. (This logically aligns with a DSA UserVersion, but is not the same.)

**Comment by justinlittman** [comment]
Changing strategy so closing this issue.
