### ISSUE TITLE
Add version information to automated preferred citation

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3521]
When user_versions_ui_enabled feature flag is enabled:

When version 1 of an item is created, include "Version 1" in the preferred citation. This should be inserted after the title. Also, use the /v1 URL. Example:

> Weaver, K.J. (2020). Juxtaposing Stakeholder Perceptions of Diversity in Higher Education Law. Version 1. Stanford Digital Repository. Available at https://purl.stanford.edu/qv180wz3234/v1.

When subsequent versions are made, the automated citation should be updated to reflect the new version number, both after the title and in the URL. Example:

> > Weaver, K.J. (2020). Juxtaposing Stakeholder Perceptions of Diversity in Higher Education Law. Version 2. Stanford Digital Repository. Available at https://purl.stanford.edu/qv180wz3234/v2.

The intent of this change is to help prevent a situation where someone uses the base purl (purl.stanford.edu/druid) for a citation, then later creates more user versions. At this point, it will be unclear which version the base version was intended to point to. So, we want the /v1 version of the purl (purl.stanford.edu/druid/v1) to be available when the first user version is created and to be inserted in the preferred citation from the start.

**Comment by lwrubel** [comment]
Is there a situation where `/v1` or `/v2` etc should appear as part of the PURL in the preferred citation?

**Comment by amyehodge** [comment]
@lwrubel Thank you for bringing this up. This big slipped my mind. YES!

I've corrected the examples above to include this. Thank you!
