### ISSUE TITLE
Remove "Last saved" row on view page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3525]
It turns out that what's being displayed here is not what the admins expected to be being displayed here.

<img width="811" alt="Screenshot 2024-05-09 at 4 53 46 PM" src="https://github.com/sul-dlss/happy-heron/assets/5558511/de8ed64b-f51d-4c87-acb6-8467949fcb8f">

This seems to be displaying the date of the last time this item was updated in the database. This does not necessarily reflect actions taken by the user. For example, these were updated May the 6th or so for nearly all items in H2 when we did the migration for adding user versions.

Since the information we want to see is covered by the history table, it makes sense just to remove this row.

**Comment by justinlittman** [comment]
Options:
* New db field
* Use most recent from history table
* Get rid of it altogether; that's what the history table is for.

**Comment by amyehodge** [comment]
@justinlittman After some consideration and feedback from others, let's go with the third option and just get rid of it. I'll update the title and description above.
