### ISSUE TITLE
restore a user's ability to create a deposit in H2 with the druid ym579qg7863 which was accidentally deleted due to an H2 bug

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/happy-heron#3567]
An H2 user had reserved a PURL and DOI for a publication. The assigned druid is ym579qg7863, and it shows as registered in Argo: https://argo.stanford.edu/catalog?search_field=text&q=ym579qg7863. 

It corresponds to hydrus:object-8098 in H2.

Due to a bug, the draft was deleted. The user has asked if it will be possible for him to reconstruct the draft with the same druid assigned, so that the DOI he submitted with his journal manuscript can still be used. 

Can this be done via manual changes in the backend database?

**Comment by aaron-collier** [comment]
Recreated the draft object at: https://sdr.stanford.edu/works/8185
