### ISSUE TITLE
Setting work type for a PURL reservation fails from the work show page

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3572]
Once you reserve a PURL, you need to set the work type to edit the work. There is a modal that shows in this situation before you get to the work page.  In fixing this issue: https://github.com/sul-dlss/happy-heron/issues/3570 (users potentially going directly to the edit work URL), we discovered that setting the work type from the work show page doesn't work, even though it works from the dashboard or the collection list page.

To reproduce:

1. Reserve a PURL within a given collection.
2. Visit the work detail page for your reserved PURL.
3. Click the pencil icon next to the title - you should get the work type modal.
4. Select a work type and click submit.  It will set the work type but you will get a blank page with a "Content missing" error.
5. Refresh the page and you are back on the Work detail page, and now you can edit it as normal.

If you follow the same process, but click the pencil icon for the reserved PURL on the dashboard, you will see it correctly redirects to the edit page after setting the work type.

Suspect something not working correctly in turbo.

This PR adds some test expectations in https://github.com/sul-dlss/happy-heron/blob/main/spec/features/purl_reservation_spec.rb to verify the error: https://github.com/sul-dlss/happy-heron/pull/3571/files  Uncomment them out when this is fixed

**Comment by edsu** [comment]
I see this error on the JavaScript console when trying to edit the title:

```
Uncaught (in promise) Error: The response (200) did not contain the expected <turbo-frame id="workDetailsFrame"> and will be ignored. To perform a full page visit instead, set turbo-visit-control to reload.
```

**Comment by edsu** [comment]
When the pencil is working the `What type of content` modal has a `Continue` button that is in a `<form>` that targets `/reservations/{id}`.

When the  pencil is not working the `What type of content` modal has a `Continue` button in a `<form>` with target=`/reservations/{id}` but the form is within a turbo-frame with an `id=workDetailsFrame`.

The HTML response that comes back from "/reservations/{id}" doesn't contain a `<turbo-frame id="workDetailsFrame">` and so the Turbo JavaScript complains that it doesn't know what to do.

**Comment by edsu** [comment]
FWIW reverting #3571 does not fix this.

**Comment by edsu** [comment]
Perhaps this isn't important but it looks like there is a doubling up of identical `<turbo-frame>` elements when clicking through to the work type modal?

![Image](https://github.com/user-attachments/assets/d22447f4-a50f-49e3-bf6a-04becabe6e65)
