### ISSUE TITLE
Create H2 report on related works

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3576]
I’d like a report from H2 for all the free text related works entries. I'm not interested in the related links entries.

Just these:
<img width="991" alt="Screenshot 2024-07-17 at 10 11 12 AM" src="https://github.com/user-attachments/assets/7ed6d334-4866-4e44-8222-af358f1e347b">

I'd like the report to include the following:

- druid
- work title
- owner
- collection title
- work type
- related work entry

In the case where there are multiple related works for one item, it's fine for there to be multiple lines in the report, one for each entry.

Not urgent. Thanks.

**Comment by lwrubel** [comment]
For the owner, is the email what you'd prefer? Or name?

**Comment by amyehodge** [comment]
@lwrubel just the sunet id is fine. Thanks.

**Comment by lwrubel** [comment]
Completed report and emailed to Amy. There were 2,717 related works. See https://github.com/sul-dlss/happy-heron/pull/3577

**Comment by amyehodge** [comment]
Great, thanks @lwrubel. This should do it.
