### ISSUE TITLE
Restore files to yb905kn4946 and figure out how these got dropped and fix it

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3579]
This problem was identified by the content owner for H2 work 6423/druid:yb905kn4946. 

We need to restore the files to this item and also figure out how this got this way and fix it so that doesn't happen again. Last edit date for this item was Jan. 25, 2024.

The files for this item are no longer showing up:

- on the PURL
- on the item in H2
- in the content section in Argo 

The technical metadata in Argo still shows the items below, which the depositor has reported are the correct files, so I'm hoping we can retrieve them from preservation if nothing else.
 
<img width="422" alt="Screenshot 2024-07-22 at 10 08 03 AM" src="https://github.com/user-attachments/assets/05ca24ca-ec29-4a16-9e8b-3eab225e88e6">

**Comment by edsu** [comment]
The current thinking on this from @andrewjbtw in Slack is that the user removed the embargo and somehow that led to H2 removing all the files, which should not be possible.

"The scenario to test is going to be if it’s possible to get H2 to send no files. My guess is that some combination of metadata update and possibly the UI showing a Globus upload that’s never used it the way to do it."

**Comment by edsu** [comment]
It would be helpful to report on whether there are other H2 deposits with no files.

**Comment by amyehodge** [comment]
Testing on stage:

- Created a new item with an embargo and deposited it. Then removed the embargo. This worked as it should.
- Created a new item with an embargo and deposited it. Then clicked the Globus option without doing anything else in the file upload section, and removed the embargo. The deposit button is grayed out because the rest of the Globus process was not completed.
<img width="435" alt="Screenshot 2024-07-22 at 12 35 48 PM" src="https://github.com/user-attachments/assets/464b9a32-7d26-4d10-bce6-a92f845b86e0">

- For the same item above, switched this to the zip file upload option without uploading a file and removed the embargo. Clicked deposit but was taken to the file upload section with an error message that I hadn't uploaded a file.

<img width="1225" alt="Screenshot 2024-07-22 at 12 36 29 PM" src="https://github.com/user-attachments/assets/603cebfb-2ea4-4753-9ba3-b1c84e28c97b">

**Comment by lwrubel** [comment]
Here are the WorkVersions with no attached_files: 
`WorkVersion.where.missing(:attached_files).pluck(:work_id, :id, :version, :state, :upload_type, :embargo_date)`

[no_files.csv](https://github.com/user-attachments/files/16337170/no_files.csv)

However, some of these are zipfiles and look OK, so I need to refresh on what is normal regarding AttachedFiles with zipfile deposits.

**Comment by lwrubel** [comment]
I went through the above files and most of them are decommissioned/first_draft/purl_reserved, so OK that they have no attached files. I highlighted them in green in this sheet: https://docs.google.com/spreadsheets/d/1nHiAtgVrQkpHlu-9rwf6sv33c92NlPf3q7kwIFif7bs/edit?gid=1723627847#gid=1723627847

There are a couple dozen that are not in this state, however.

**Comment by amyehodge** [comment]
@andrewjbtw retrieved the files for the object reported by the user to restore it. 

I identified nz589jh8225 as also having no files, but it seems to have some other odd history and so the file issue is likely unrelated to this problem.

Also, I was unable to reproduce the problem that allowed deposit of the original item without files, and since this seems like it was an isolated incident, we won't investigate this further at this time.
