### ISSUE TITLE
FAST vocabulary type ahead lookup in H2 should work

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3581]
Currently this box in H2 behaves as a free text entry box. No type ahead search results appear when you type in the box.

`App 176307 output: W, [2024-07-22T09:40:55.455746 #176307]  WARN -- : [f24fa9fe-2590-42b5-ae17-5047e08d6a50] Autocomplete results for river returned 404`

**Comment by edsu** [comment]
It might be helpful to see if this service is now available at a supported REST endpoint:

https://www.oclc.org/developer/api/oclc-apis/fast-api/assign-fast.en.html

**Comment by edsu** [comment]
It seems like [OCLC's FAST user interface](http://fast.oclc.org/searchfast/) is now sending Solr requests like this:

http://fast.oclc.org/cgi-bin/perlProxy.pl?http://authfastdb-m1.prod.oclc.org/fastapps-db/fastIndex/select?q=keywords:(village)&rows=10&start=0&version=2.2&indent=on&fl=id,fullphrase,type,usage,status&sort=usage%20desc

**Comment by amyehodge** [comment]
From OCLC FAST Team:

I believe our service is working okay but perhaps you are using an  ‘experimental.worldcat.org’ url? We recently discontinued that avenue in favor of [https://fast.oclc.org/searchfast/fastsuggest?&query=stuff](https://urldefense.com/v3/__https://fast.oclc.org/searchfast/fastsuggest?&query=stuff__;!!G92We9drHetJ8EofZw!dfbq6lpQY0mgwvf9UyvKiFYXXYiHe0BMN1gvFAyAFA7obTwr6Kun1S5--J2wmweJLIrFu5TLa0n4gCIC_2WR$). It should function the same, but if you run into any difficulties, please let us know.
 
Hope this helps,
Russell
 
 
-- 
Russell Schelby
OCLC, Technical Manager, Authorities
[schelbyr@oclc.org](mailto:schelbyr@oclc.org)

**Comment by justinlittman** [comment]
@amyehodge We are using http://fast.oclc.org/fastIndex/select

**Comment by justinlittman** [comment]
https://fast.oclc.org/searchfast/fastsuggest?&query=stuff doesn't help because it doesn't include any identifiers.

**Comment by amyehodge** [comment]
@justinlittman I've sent another message to the FAST team about this.

**Comment by edsu** [comment]
From [the docs] it looks like you can request that `idroot` be returned? Are those the identifiers that we have been using previously? The IDs look like `fst01140419`. Here's an example API call:

http://fast.oclc.org/searchfast/fastsuggest?&query=hog&queryIndex=suggestall&queryReturn=suggestall%2Cidroot%2Cauth%2Ctag%2Ctype%2Craw%2Cbreaker%2Cindicator&suggest=autoSubject&rows=3

[the docs]: https://www.oclc.org/developer/api/oclc-apis/fast-api/assign-fast.en.html

**Comment by amyehodge** [comment]
@arcadiafalcone Can you answers @edsu 's question above about the identifiers? Thanks!

**Comment by arcadiafalcone** [comment]
@edsu The identifiers used for what purpose? For the descriptive metadata, we're using the full URI, which can be derived from the `idroot`, such as https://id.worldcat.org/fast/1140419/ for the above example, but I may be misunderstanding the question.

**Comment by edsu** [comment]
Thanks @arcadia. I'm just confirming that we could switch H2 over from using 

http://fast.oclc.org/fastIndex/select

(which is gone) to:

http://fast.oclc.org/searchfast/fastsuggest

As long as we request that it return identifiers (`idroot`). We were initially concerned that the new service didn't seem to be returning identifiers.

**Comment by edsu** [comment]
Given that we had to wait for an H2 user to notice that this was broken I wonder if this is an opportunity to move the [unit test](https://github.com/sul-dlss/happy-heron/blob/main/spec/requests/fast_spec.rb) over to querying the live service instead of mocking it out?

**Comment by edsu** [comment]
I could understand OKComputer to make sure the URL still is 200 OK. Do we use OK Computer tests to ensure that the response format is still what we expect it to be?

**Comment by mjgiarlo** [comment]
@edsu @justinlittman Instead of hitting the live API in the test suite, or hammering it as part of OKComputer checks, how about we send Honeybadger alerts when the endpoint returns non-200 results? I'm going to work up a PR for that in the meantime.

**Comment by justinlittman** [comment]
worksforme
