### ISSUE TITLE
Download files that are in preservation

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#36]
Follows on to #35 

If you view an already deposited object, the files will not be in the local system, so we have to download them via preservation

**Comment by amyehodge** [comment]
@jcoyne I think this works if we're talking about being able to download files for migrated content. I was just able to download a file from https://new-sdr.stanford.edu/works/12, which was deposited years ago and migrated to H2 in the first batch.

**Comment by jcoyne** [comment]
No, this is something else. Currently we maintain a hydrus specific data repository which we've converted to an h2 data repository, but this ticket asks us to do away with this repository and to proxy items from preservation as needed.

**Comment by amyehodge** [comment]
Ah, okay. Thanks.

**Comment by amyehodge** [comment]
Closed as completed.
