### ISSUE TITLE
Autocitation choice should not change to "no" unless user makes this change

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3616]
This is happening for works where the review workflow is on and the user is versioning an already deposited item. If they choose "yes" for the versioning question and then submit the item for approval, if the item is then opened up for editing again by the reviewer or is returned to the depositor and is opened up by them again for editing, the autocitation toggle shows "no" instead of the "yes" that was previously selected. Note that this problem doesn't occur if the user chooses "no" for the versioning question.

The desired behavior here is that the autocitation should default to "yes" for new deposits and should not change unless the user changes it.

To replicate this:

- Start with an already deposited item in a collection with the review workflow on. This item should have had the autocitation toggle left in the default position of "yes."
- Click the pencil to edit this item. 
- Before doing anything else, scroll down to verify that the autocitation is set to "yes."
- Choose the "yes" option for the versioning question and add a comment.
- Submit the item for approval (it's not necessary to make any other changes).

You can take one of two paths from here to see this in two different place.
Path 1: reviewer
- As the reviewer, open the item to edit.
- Scroll down and note that the autocitation now shows "no."

Path 2: depositor
- As the reviewer, without opening the item, return it to the depositor for changes.
- As the depositor, click the pencil icon to edit.
- Scroll down the form to see that the autocitation is now set to "yes."

Once I switch this from "no" to "yes", it seems to persist as "yes" no matter what other steps I take (except for actually switching this toggle again, of course).

I'm not 100% sure that this behavior is limited to the review workflow, because I thought I saw some similarly odd behavior with a deposit not in the review workflow, but I have not been able to replicate that.

**Comment by lwrubel** [comment]
I've been able to replicate this outside of the review workflow with the following steps:

1. Start with an already deposited item. This item should have had the autocitation toggle left in the default position of "yes."
2. Click the pencil to edit this item. Before doing anything else, scroll down to verify that the autocitation is set to "yes."
3. Choose the "Yes" option for the versioning question and add a comment. Save as draft (do not deposit yet)
4. Click pencil to edit the draft. Scroll down and the auto-citation toggle is now off. 

If in step 3 "No" was chosen, the toggle was unaffected and stayed turned on when the draft was re-opened.

**Comment by lwrubel** [comment]
The problem seems to be that when you click "Yes" on a draft, and the auto-generated citation gets updated with the new version number, when you save that draft and return to it, the javascript thinks that you've made a manual edit and turns the auto-generation toggle off.

**Comment by lwrubel** [comment]
Closed with #3618
