### ISSUE TITLE
Respect 6 month embargo setting

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3621]
When a manager chooses the embargo setting for "up to 6 months," the depositor should not be allowed to deposit an item with a date that is more than 6 months out.

Currently, the user can enter any date in this field and deposit the item. It doesn't pay any attention to the 6 month limitation.

Note that the 1-, 2-, and 3-year embargo settings are being respected as they should. It's just the 6-month one that is not working properly.

**Comment by mjgiarlo** [comment]
@amyehodge Can you point me at a collection like this in stage or QA? And do you have any works in stage or QA that have violated this policy? Any examples in stage or QA that I can poke at will help me reproduce this and get it fixed. Thanks!

**Comment by amyehodge** [comment]
This collection is currently set for a 6-month embargo: https://sul-h2-stage.stanford.edu/collections/146. druid:sw781dp5658
And this item in that collection was created with that restriction in place, but I was able to set the embargo for a date in 2027: https://sul-h2-stage.stanford.edu/works/661. druid:cj496gf4465
