### ISSUE TITLE
User should be able to choose to display more items in the deposit list

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3640]
As an example see https://sdr.stanford.edu/collections/285/works, shown below.

This defaults to displaying 10. The user can select the other options from the dropdown list, but the page does not update to display the selected number. It just keeps displaying 10.

<img width="872" alt="Screenshot 2024-11-22 at 10 39 45 AM" src="https://github.com/user-attachments/assets/c4bb12f1-5d45-4dbe-b00d-d911e474e3a9">

**Comment by amyehodge** [comment]
This now seems to be working fine.

**Comment by jmartin-sul** [comment]
(was also working fine for me when i tested in FF, chrome, and safari)
