### ISSUE TITLE
Collection view page

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#37]
https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/426926002

**Comment by amyehodge** [comment]
@mjgiarlo and @jcoyne,  @astridu has updated the wireframes (https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/426926002) and the design doc (https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.mnbq4epat716) for this, so this work is ready to go from my perspective.

**Comment by mjgiarlo** [comment]
@amyehodge shall we earmark this as a sprint 3 goal? cc: @peetucket

**Comment by amyehodge** [comment]
likely, @mjgiarlo , but I'd like to review the full list tomorrow before making the decision.
