### ISSUE TITLE
Verify metadata mappings that need to be completed

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#382]
Start a new deposit in sul-h2-qa, fill in all fields, deposit the object, go to argo-qa and look at the descMetadata datastream.  We need to determine which fields in the H2 deposit form are still missing and need to be mapped.

This should spawn new mapping tickets.

**Comment by mjgiarlo** [comment]
Connects to #240, #241, #340, #341

**Comment by mjgiarlo** [comment]
Here are my findings after depositing a fully fleshed out H2 work in stage.

# The Good

* uploaded two files to item, one hidden, one not, both with labels and all of this comes over ok
* title looks ok
* contact email looks ok
* author looks ok
* publisher looks ok
* pub date looks ok
* create date range looks ok
* abstract looks ok
* two keywords look ok
* citation looks ok
* one related work (citation) looks ok
* one related link (DOI) looks ok
* CC-BY license looks ok

# The Bad

* release immediately (to EVERYONE)... but rightsMD is set w/ stanford read instead?
* article / journal subtypes of text type NOT MAPPED

**Comment by mjgiarlo** [comment]
This means #241 (waiting to be picked up), #240 (in progress), and #429 are the remaining mapping tendrils we know about. No other tickets need to be written at this time. FYI @jcoyne @peetucket @amyehodge 

Closing
