### ISSUE TITLE
Editing a previously saved draft cannot be saved again

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#388]
1. Create a new object
2. Save it as a draft
3. Go back to edit the draft
4. Try and save the draft again - it does not appear to save.
5. Look at the javascript errors in the console

![Screen Shot 2020-11-09 at 11.09.41 AM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/0f211fe7-7db6-406f-9d06-cce6001af870)

**Comment by jcoyne** [comment]
This is because the response from the controller on update is:

```
"attached_files_attributes"=>{"0"=>{"label"=>"two", "_destroy"=>"", "hide"=>"0", "id"=>"302"}}
```

```
ArgumentError (Could not find or build blob: expected attachable, got #<ActiveStorage::Attached::One:0x00007fa796b081b0 @name="file", @record=#<AttachedFile id: 302, label: "two", hide: false, work_id: 384, created_at: "2020-11-09 20:10:18", updated_at: "2020-11-09 20:10:18">>):
```
