### ISSUE TITLE
Ensure client/server validations match

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#389]
Currently there are two levels of validation: client and server side.   We should ensure that these are aligned so that you do not see two different levels of validation (i.e. if you pass client side, you should then not get additional validations after you pass the client side from the server).

May require some additional client side validations (e.g. for keywords, date logic, etc).

**Comment by jcoyne** [comment]
@mjgiarlo do you think we can close this now?

**Comment by mjgiarlo** [comment]
Fine by me
