### ISSUE TITLE
Draft item edit page does not seem show a previously uploaded file

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#392]
1. Create a new item
2. Upload a file
3. Save it as a draft
4. Return to edit the draft
5. Previously uploaded file does not appear to show correctly.

![Screen Shot 2020-11-09 at 11.23.46 AM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/f736267e-cabb-4038-8e4f-32a74c5fc41d)

**Comment by jcoyne** [comment]
@astridu I'm not sure we have a good design for what a file is supposed to look like if it was previously uploaded, then saved as a draft and then revisited.  Does it even make sense to have a progress bar?

**Comment by astridu** [comment]
in that scenario, could we display the file name with a green check to show that it was added previously? 
![image](https://user-images.githubusercontent.com/42216982/98599860-87454c00-2291-11eb-8845-86a1ebbcbdc5.png)

**Comment by jcoyne** [comment]
@astridu Yes, we can do that. Thank you.
