### ISSUE TITLE
Change review workflow widget from a radio to a switch

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/happy-heron#399]
This is located in `app/components/collections/form_component.html.erb`

Here's how you do this in Bootstrappy HTML: https://v5.getbootstrap.com/docs/5.0/forms/checks-radios/#switches

Split out from https://github.com/sul-dlss/happy-heron/pull/384

**Comment by jcoyne** [comment]
For bootstrap v5 that is: https://v5.getbootstrap.com/docs/5.0/forms/checks-radios/#switches

**Comment by mjgiarlo** [comment]
> For bootstrap v5 that is: [v5.getbootstrap.com/docs/5.0/forms/checks-radios/#switches](https://v5.getbootstrap.com/docs/5.0/forms/checks-radios/#switches)

Updated description. Thanks!
