### ISSUE TITLE
Collection review config: validate at least one reviewer is listed if Review Workflow is enabled

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/happy-heron#402]
follow on from https://github.com/sul-dlss/happy-heron/issues/348 / https://github.com/sul-dlss/happy-heron/pull/384

validate that reviewers are listed if the reviewer workflow is enabled (@mjgiarlo suggests: "there are two strategies here: pure JavaScript validation or use remote form validation (how we're dealing with keywords)" -- see https://github.com/sul-dlss/happy-heron/pull/384#discussion_r520095850)

**Comment by mjgiarlo** [comment]
@jmartin-sul the second subtask is already in progress here: https://github.com/sul-dlss/happy-heron/pull/400

**Comment by jmartin-sul** [comment]
> @jmartin-sul the second subtask is already in progress here: #400

ah, thanks, striking...

**Comment by jmartin-sul** [comment]
i turned this ticket into one that's just about what was originally its third task (as the first one had been ticketed, and the second had been ticketed and picked up).

**Comment by jmartin-sul** [comment]
for reference, an example PR demonstrating/explaining remote form validation: https://github.com/sul-dlss/happy-heron/pull/356

**Comment by amyehodge** [comment]
I just noticed this ticket and haven't attempted to follow all of this, but wanted to be sure it was clear that all collection managers should automatically be reviewers, so we do not want to require the addition of other reviewer SUNets in the reviewer field. However, automatically entering the collection manager names there would suit me fine if that is easier to manage. Please ping me if you have questions about this requirement. Thanks.
