### ISSUE TITLE
Replace fa icons in work types modal with the image icons

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#411]
The correct icon can be found at https://drive.google.com/drive/folders/1-hPbPdaln4bUrOg0I-hssPRLCAPpmMeH?usp=sharing

**Comment by jcoyne** [comment]
Currently all the icons are from [font-awesome](https://fontawesome.com/icons?d=gallery&s=solid&m=free). Should they all be replaced with images instead?

**Comment by amyehodge** [comment]
No. But this is the icon that @astridu has recommended for this particular category. She can confirm, but this was a later change and she may not have found anything in font-awesome that worked here. This icon is specified in the Design Doc.

**Comment by jcoyne** [comment]
@amyehodge the design doc specified icons for all of them, but the link to the icons is/was broken.

**Comment by amyehodge** [comment]
@jcoyne There is a special link within the list (not the broken link at the top) for the mixed materials icon.

**Comment by astridu** [comment]
I had to download the whole set and find the ones we use. They are all in here now (including the new one): https://drive.google.com/drive/folders/1-hPbPdaln4bUrOg0I-hssPRLCAPpmMeH?usp=sharing
Meet Google Drive – One place for all your files<https://drive.google.com/drive/folders/1-hPbPdaln4bUrOg0I-hssPRLCAPpmMeH?usp=sharing>
Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.
drive.google.com


________________________________

**Comment by amyehodge** [comment]
Please note that the recently added music category should use the font awesome fa-music [&#xf001;] icon. This is not in the Google Drive folder.

**Comment by jcoyne** [comment]
@amyehodge it will look bad if we use a mix of font awesome icons and bitmap icons (e.g. the ones in the Google Drive  folder) We should pick one way or the other and be consistent.

**Comment by mejackreed** [comment]
If there is a desire to have congruence w/ SearchWorks we can extract the sul_icon font into something useful. Or use the SVG glyphs into something else?

sul-icon font is here: https://github.com/sul-dlss/SearchWorks/tree/master/app/assets/fonts

And drives the resource type facet

![Screen Shot 2020-12-08 at 1 15 32 PM](https://user-images.githubusercontent.com/1656824/101536616-7a328000-3957-11eb-9079-2d5e18550d00.png)

**Comment by astridu** [comment]
I put the music icon in the folder. I got it from the icons JVine sent to me that were used to make the icons above in SearchWorks.

**Comment by amyehodge** [comment]
@jcoyne please let me know if you need something other than what @astridu has indicated just above.

**Comment by amyehodge** [comment]
The icons are now all as they should be according to @astridu .
