### ISSUE TITLE
h2 show page purl should be environment specific

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/happy-heron#416]
e.g. at the moment, for h2-stage, it is "purl.stanford.edu/druid" but it should be "purl-test.stanford.edu" or whatever.   Ditto for qa.

Also, this affects the integration tests for h2 - so those should be updated as well (maybe another Settings url for purl?)

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/shared_configs/pull/1598 and https://github.com/sul-dlss/shared_configs/pull/1599
