### ISSUE TITLE
Depositor field on item view page should display SUNet ID

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#423]
Depositor field should display SUNet ID, not email address.

![Screen Shot 2020-11-12 at 3.51.42 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/d6696bec-b562-4f8b-b38e-10fb02bcd08a)

**Comment by amyehodge** [comment]
@jcoyne Moved to #436 and removed from above.

**Comment by amyehodge** [comment]
@jcoyne This ticket is correct. This field is currently displaying the email address and should be displaying the SUNet. I've updated the screenshot. Thanks.

**Comment by justinlittman** [comment]
Fixed by https://github.com/sul-dlss/happy-heron/pull/1677
