### ISSUE TITLE
Remove duplication of contact info from view page and move subtype information to a different table.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#424]
The contact info should be removed from the Details section at the top as it is listed properly in the titles and contact section below. This was an inadvertent duplication.

The subtype information should be moved down to the Description section just below the keywords. This puts this in the same location that it exists in the form. 

The Details section then will have only things that are not editable by the user, which makes more sense as this section does not have a pencil icon. 

![98597030-5885a080-22a6-11eb-907b-37a519018ed3](https://user-images.githubusercontent.com/5558511/98876048-49335e00-2432-11eb-93e5-d0a3a08b130e.png)

See #33

**Comment by amyehodge** [comment]
Also, please remove the collection section further down the page, since the collection is noted in the Details section.

![Screen Shot 2020-11-11 at 3 51 41 PM](https://user-images.githubusercontent.com/5558511/98877666-d9bf6d80-2435-11eb-90e1-2eeb59145786.png)

**Comment by mjgiarlo** [comment]
@amyehodge if you want to see all the changes made for this issue, check out: https://sul-h2-stage.stanford.edu/works/62 (needs VPN)
