### ISSUE TITLE
Implement View Page notifications of fields not passing validation

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#425]
https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/420930436

![98597452-10b34900-22a7-11eb-9c79-94211c49efad](https://user-images.githubusercontent.com/5558511/98876220-a7604100-2432-11eb-97e5-deefe936f495.png)

See #33

**Comment by amyehodge** [comment]
@jcoyne I seem to recall a discussion with you that this would be really hard to implement. Am I remembering that correctly? 

If so, I think it's not worth doing and we should just close this ticket. On the other hand, if it's easier, I'm looking for things to put in the ready while details for other features are still being ironed out, and this is one of the few things left.

**Comment by jcoyne** [comment]
I think we can do this, but we should enumerate which fields we would like to see this sort of validation on and the text for each.

**Comment by amyehodge** [comment]
Based on how we've implemented the validations, I don't really think we'll ever need this. Closing this ticket.
