### ISSUE TITLE
Add copy icon next to PURL on View Page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#427]
Similar to #1034.

**Comment by jcoyne** [comment]
I believe this will be blocked by https://github.com/sul-dlss/purl/issues/454

**Comment by amyehodge** [comment]
@jcoyne Considering problems outlined in 1034, let's change this to the copy icon as well. I've updated the title.

**Comment by amyehodge** [comment]
That's the page with the info about the item. I think you all also call it the show page? This one:

![Screen Shot 2021-06-23 at 11 12 39 AM](https://user-images.githubusercontent.com/5558511/123122362-f08a6180-d413-11eb-932a-b0be60cecb4e.png)

**Comment by justinlittman** [comment]
@amyehodge I think this is done. I've deployed main to stage. Can you verify?

**Comment by amyehodge** [comment]
Looks good.
