### ISSUE TITLE
Implement file download functions on View Page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#428]
https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/420930436

Described at: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.duddikck1un3

See #33 
![98597875-a5b64200-22a7-11eb-80fc-424655392ffb](https://user-images.githubusercontent.com/5558511/98876961-4174b900-2434-11eb-9dfc-5ccd8257908e.png)

**Comment by amyehodge** [comment]
We can negotiate on this if there significantly more time or difficulty involved in one of the two types of download over the other -- downloading all files at once vs. downloading each individual file.

**Comment by jcoyne** [comment]
Downloading all files at once is much harder than individual file downloads.

**Comment by amyehodge** [comment]
Let's definitely try to get the individual file download working, as that will replicate hydrus functionality. 

Any way to implement the procedure PURL now uses to download everything at once? It's very nice.
