### ISSUE TITLE
Expand privleges of collection managers, reviewers, and admins

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#445]
> any collection manager or reviewer should be able to edit/update works in that collection, no matter who deposited them. And any admin should be able to edit anything.

No additional reviewers are required to be listed in the reviewers box when the review workflow is turned on, since collection managers are automatically also reviewers, so the existing validation that requires that should be turned off.

**Comment by jcoyne** [comment]
Additionally, reviewers and managers should see all the collections they review and manage on their dashboard.

**Comment by amyehodge** [comment]
Be sure that this specific point is addressed when doing this ticket:

Collection manager, reviewer, and admin should be able to click on the pencil icon and edit items submitted for review and then choose to deposit them or return them. Currently when I open an item to review and click on the pencil icon I'm taken to the start page and I see this message.

![Screen Shot 2020-11-23 at 6.24.00 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/60c53e5e-c351-4867-a5f3-ad90c706919f)
