### ISSUE TITLE
Preferred citation should default to a generated citation

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#46]
See mockup in wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/428088403 and 
Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.3nd0v0kp7034

At mid-sprint check-in we discussed that this would autopopulate as information is filled in. This would include a placeholder link for the PURL (something like "_Link to PURL will be included here_.") Once the item is deposited and the PURL is available, the item view page will update so that the citation includes the citation as it will look on the PURL page. This should ideally also be updated in the citation box in the deposit form so that the user doesn't get confused about that text. 

If a depositor switches to the toggle to be able to edit the citation, whatever is in the box should stay there, but the content will no longer autoupdate. If they leave the placeholder text, then the link should be inserted, but if they delete it, then it won't be. (I'm sure we discussed that last bit, but I think it was implied and makes the most sense to me.)

Note that this means the PURL info in the citation will not be preserved.

**Comment by amyehodge** [comment]
@jcoyne and @mjgiarlo  I need help sorting out how this will work. 

The default citation must be built on the data in the form. When the form is opened there is no data in it, so the citation field can't be populated yet. And while this is an optional field, I would like to STRONGLY encourage people to include something here -- our default suggestion is the easiest thing to do.

Perhaps we are going to need a "Create default citation" button, similar to the link we have now but more prominent, and then the slider to allow for choosing to be able to edit (or remove) the citation. Thoughts? 

I'm concerned about perpetuating an existing problem we have where once you create the default citation it is not updated if the other form information is updated -- you enter the date you left out or add an author, etc.

**Comment by mjgiarlo** [comment]
@amyehodge OK, np, we have time to sort this out. Discuss in an upcoming planning meeting?

**Comment by mjgiarlo** [comment]
@jcoyne do you want to deploy this to QA and staging so @amyehodge can see it in all its glory?
