### ISSUE TITLE
Returning a reviewed item to the user.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#462]
This is the description of what happens in this case. There is a related mockup noted below in the Design Doc.

When the review workflow is on and an item is returned to the depositor, several things happen. 1) Under the “Deposits in Progress” header on the depositor’s dashboard it should now say “Returned” to the right of the progress bar for this item. 2) The user is sent an email notification that the item has been returned to them for changes. 3) When they open the item for editing they will see a message at the top of that page. The specs on this are in the design doc here: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.yiub3zxgcv6m . 4) The item is removed from the Approvals table on the Reviewer’s dashboard.

**Comment by jcoyne** [comment]
Text for the email is in https://docs.google.com/document/u/1/d/1TZVILUrORI25kRZyUZ70vMQYo90Ngp_tqCI7BdU_VyQ/edit

**Comment by ndushay** [comment]
I think the status "returned" is being addressed in my PR for #581 and #576 (almost done)

**Comment by jcoyne** [comment]
I think the remainder of this is covered by #594
