### ISSUE TITLE
Collection Items page

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#470]
https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/420930435

**Comment by ndushay** [comment]
Could we have a sentence or two on this?  Is the ticket to implement x,y,z for the Collection view page?

**Comment by jcoyne** [comment]
No, it is to implement the collection items page, a totally separate page that is in the mockup which you will find in the ticket description.

**Comment by jcoyne** [comment]
This seems to have been done as part of #642
