### ISSUE TITLE
One contributor field, even if blank, should always display

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#519]
See Design Doc at https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.d3q6bp4xt33j

This states: The first author/contributor added cannot be deleted, but it can be changed. The subsequent authors/contributors will have a trash can in the upper right corner that allows the user to delete them.

Currently the first contributor box has a trash can icon. ![Screen Shot 2020-11-19 at 11.51.46 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/cd81a6b2-e61b-4fad-b0f1-5f881ba39de3)

If I delete this entry, it looks like this:
![Screen Shot 2020-11-19 at 11.52.14 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/bb9a2fa3-a233-4417-886a-0b5d0e498e72)

If I try to deposit this item, the validation fails as it should because there are no contributors. However, the error doesn't display because the boxes are entirely gone. It looks the same as above. But if I add back in a contributor, you can see it: ![Screen Shot 2020-11-19 at 11.53.27 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/e37db292-6c62-41c5-822d-f44f1c8f5991)

**Comment by jcoyne** [comment]
@astridu @amyehodge one way to accomplish this is to ensure the remove icon doesn't exist on the first contributor. Would that be an acceptable approach?

**Comment by amyehodge** [comment]
That is what @astridu called out in the Design Doc as linked to above, so, yes, that would work for me.

**Comment by mjgiarlo** [comment]
@amyehodge check it: https://github.com/sul-dlss/happy-heron/pull/564#issue-526054290

**Comment by amyehodge** [comment]
@mjgiarlo the screenshot looks right to me. Let me know if there is some other way for me to see this, otherwise I'll double-check it once it's available on qa.

**Comment by mjgiarlo** [comment]
@amyehodge it's on QA and stage now.

**Comment by amyehodge** [comment]
Checked on qa and this looks good.
