### ISSUE TITLE
Admin dashboard should show a compact list of the bottom of the collections the admin is not specifically listed on

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#531]
The admin should have access to all collections and permission to edit any collection or item. However, the admin's dashboard should only display individual tables for those collections where the admin has been explicitly assigned a role as manager, reviewer, or depositor  -- or is the creator. 

All collections -- including those described above -- should be listed in a more compact table at the bottom of the dashboard. See https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/426926001

![Screen Shot 2020-11-19 at 3.17.33 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/05983fab-132b-46a5-8d26-d78e7eed9633)

For example, I am not explicitly listed in this collection, but there is a table for it on my dashboard:
![Screen Shot 2020-11-19 at 3.18.14 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/68f10767-0ab5-4929-b78d-96e0579c87fd)

**Comment by jcoyne** [comment]
@amyehodge I think these other tables are showing, because as an administrator you have the rights to deposit into them.

**Comment by amyehodge** [comment]
@jcoyne That's not the desired behavior. The desired behavior is that only when the rights are called out specifically should the collections have their own tables for admins. Otherwise, all other collections where rights as manager/reviewer/depositor are not specifically called out will show up in the single condensed table at the bottom as shown in the screenshot above. This is the way hydrus works now, and helps keep this from getting out of control for admins, since there are something like 1000 collections.
