### ISSUE TITLE
Editing a new version of an item requires the "Version your work" comment box at the top of the page.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#539]
When a user edits a work that has already been deposited, i.e. creates a new version, there should be a box at the top for them to enter comments about the version. An entry in this box is required.

Wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/420954309
Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.jfgv4qeo7411

**Comment by jcoyne** [comment]
Duplicate of #454 ?

**Comment by amyehodge** [comment]
Ah, yes. That was not language I was looking for. I'll close this.
