### ISSUE TITLE
Embargo date must be set for the future

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#543]
Embargo dates must be set for at least today +1.

**Comment by mjgiarlo** [comment]
I hate to ask this... but in terms of interpreting "today," should we assume current time in California? Or UTC?

**Comment by amyehodge** [comment]
@mjgiarlo I think the best option would be determining the current time in the user's location. Barring that, I think California time is likely to accurate for the majority of users, so is the better of the two options you mentioned.

**Comment by jcoyne** [comment]
@amyehodge if we want to do it relative to the user, then we should include their time zone in the embargo date. If that is desired, please open a separate ticket for that.

**Comment by mjgiarlo** [comment]
If we can assume Stanford time, that would be simpler going forward.

**Comment by amyehodge** [comment]
As all users are required to be Stanford affiliates and most of those people will be at Stanford (well, at least when everyone is back after COVID), I think it's fine to assume Stanford time.
