### ISSUE TITLE
When review workflow is on, depositor should see a "Submit for Approval" button instead of a "Deposit" button

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#544]
See Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.vhwtx3wnoqek

"Deposit/Submit for approval button: Is enabled if all 8 sections are green 029B76 (or completed), appears disabled if all sections not complete

- Deposit button for non-approval workflow
- Submit for approval for approval workflow"

**Comment by ndushay** [comment]
@amyehodge - i am still investigating, but it appears that we do the form validation (figuring out which of the 8 sections are green) after the Deposit/Submit for approval   button is pressed.  If I disable the button, they will not be able to press it.  This is standard bootstrap behavior, AFAICT.

**Comment by ndushay** [comment]
It would be my preference that this ticket be closed when PR #643 is merged, and a new ticket be created re: the way to clarify to users when they must remediate the metadata vs. when deposit is ok.

@mjgiarlo briefly imagined a popup Model saying either "Everything looks great and your deposit is now queued for approval" or "There are problems with your deposit, please look for the red sections on the form and address them"

Mike also confirmed that disabling the button when there are validation problems ... is (ahem) problematic ... given how Bootstrap does form validation.  Happy to chat with you more about this, or you can take it to Mike or Justin, as they are more knowledgeable in this area.

**Comment by ndushay** [comment]
chatted w Amy in slack;  the "disable the button" ask above is being tabled.
