### ISSUE TITLE
Update contributors section to have two separate sections for ordered authors and unordered contributors

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#545]
As per our discussion earlier today:

> We had a brief meeting today to discuss this change around order in the cocina models gem: https://github.com/sul-dlss/cocina-models/commit/1cef523e3c25a4817880435e95c2bb7de89f40a2#

> Concerns were raised by the developers that the new order property would be duplicative of the natural order of the list and would require additional code complexity everywhere this data is consumed.  It became clear that in our current system, where we persist MODS, we have no way of storing this explicit order. 

> It was decided that Amy and Astrid would work on changes to the UI that would help show the users that order is important for contributors that appear in the citation (mainly authors).  There will also be another section for non-cited contributors (e.g. funder, advisor, conference)

> The developers agreed that we would revert the cocina-models change above and continue to use the natural order for contributors, related items, and parts for now.  We will be able to revisit these decisions once we have moved off Fedora 3 and can persist more than what can map to MODS.

Astrid has updated the wireframes and the design doc (https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.d3q6bp4xt33j) to reflect the changes noted in the third paragraph.
 ![Screen Shot 2020-11-20 at 3.23.14 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/495cb7e6-d041-4b37-92d5-624406008078)

**Comment by jcoyne** [comment]
@amyehodge are the role terms select boxes identical in both the "Authors" and "Additional contributors" sections?

**Comment by amyehodge** [comment]
That was our intent, but now that I'm looking at this, "Author" seems a weird choice to include in the new section of people who won't be listed as authors. @arcadiafalcone , do you think we should allow people to choose "Author" (for personal or organization) for entries in the Additional Contributors section? Thanks.

**Comment by arcadiafalcone** [comment]
I think we should keep it - I could see a case where someone wants "Primary author et al." in the citation, but still wants to include additional authors in the metadata.

**Comment by amyehodge** [comment]
Thanks, @arcadiafalcone .

@jcoyne , then your answer is Yes.

**Comment by jcoyne** [comment]
For accessibility reasons we're going to drop the "drag and drop" interaction:
![Screen Shot 2021-02-01 at 9.33.37 AM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/26cad97d-7faa-4180-b50d-e2c70401e035)

**Comment by amyehodge** [comment]
@jcoyne Is there some other way we can implement the ability for users to reorder the authors and contributors?

**Comment by amyehodge** [comment]
Please also add "Department" as an option in only the Contributors section, and not the authors section.

**Comment by arcadiafalcone** [comment]
Department has been added to the role mapping spreadsheet.

**Comment by jcoyne** [comment]
@amyehodge I've moved that feature to #977, lets talk about this there.
