### ISSUE TITLE
work deposit: server-side validation errors aren't cleared when new data is entered in the field

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#560]
The javascript in edit_deposit_controller.js doesn't clear out the old errors.

**Comment by jmartin-sul** [comment]
paired yesterday to get some clarification, this is what i did to reproduce:
1. from a collection on the dashboard, start creating a deposit
1. enter title, contact email, author, contributor
1. for publication and creation dates, enter the current year, but a day after the current day (so e.g. feb 28, 2021 if it's feb 1, 2021)
1. omit abstract and keywords, don't check the agreement box, omit attaching a file, hit deposit
1. get a bunch of client side form validation errors
1. check the agreement box, fix the creation/publication dates to be in the past, enter abstract and keyword
1. try to deposit again, still fail validation for lack of file
1. attach a file
1. notice that error about lack of file is still showing even though there's a file there
