### ISSUE TITLE
Approved item is stuck at "Depositing"

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#565]
1. I created an item in a collection with the review workflow
2. I Submitted the item
3. I approved this item
4. It has been sitting in "Depositing" state for a couple hours now

We had no such problems with several items that Amanda created with depositor privileges.

![Screen Shot 2020-11-23 at 5.51.33 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/24e524d3-6738-4bd1-9c41-bec332a82494)

**Comment by jcoyne** [comment]
@amyehodge it's helpful if you report the URL of the item when there is a problem with one in particular.  (it's https://sul-h2-qa.stanford.edu/works/41 in this case)

**Comment by jcoyne** [comment]
The log shows:
```
I, [2020-11-23T15:02:25.489624 #15323]  INFO -- : [91462602-e385-4f93-8743-e22d2a961e45] [ActiveJob] Enqueued DepositJob (Job ID: 5a92e228-9342-4f1c-b42e-a8318cec9293) to Sidekiq(default) with arguments: #<GlobalID:0x00007f824c44cf98 @uri=#<URI::GID gid://happy-heron/Work/41>>
```

I believe that is this error: https://app.honeybadger.io/projects/77112/faults/70621567
