### ISSUE TITLE
Item returned for corrections displays wrong status in table

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#566]
This item was submitted by the depositor for review, was reviewed and returned to the depositor for changes.

![Screen Shot 2020-11-23 at 5.57.21 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/07cd82a1-b03c-4421-8fad-d3a144d8fff8)

"Steve's Homemade Bread" should be listed as "Returned"

**Comment by jcoyne** [comment]
Can you split this into two issues? These seem rather distinct.

**Comment by amyehodge** [comment]
Implementation of progress bar on dashboard has been moved to ticket #840.

This ticket has been revised to reflect just the bug in status.

**Comment by aaron-collier** [comment]
@amyehodge / @jcoyne / @mjgiarlo - I think this may be closable.

I was able to return an item and I see the proper status:

<img width="1226" alt="Screen Shot 2021-01-14 at 9 58 39 AM" src="https://user-images.githubusercontent.com/2294288/104630164-4c73e180-564f-11eb-9545-05f7a4e08e47.png">

<img width="1119" alt="Screen Shot 2021-01-14 at 9 58 45 AM" src="https://user-images.githubusercontent.com/2294288/104630187-509fff00-564f-11eb-8a89-555c849db241.png">

<img width="1163" alt="Screen Shot 2021-01-14 at 9 58 51 AM" src="https://user-images.githubusercontent.com/2294288/104630194-53025900-564f-11eb-98dc-09f1de465d2e.png">

**Comment by mjgiarlo** [comment]
@amyehodge worth the effort to see if this can be reproduced? or shall we close?

**Comment by amyehodge** [comment]
@mjgiarlo I'd like to take a quick pass at checking this but can't until afternoon today. How about I'll close it once I check it?

**Comment by mjgiarlo** [comment]
@amyehodge Sounds good! :beers:

**Comment by amyehodge** [comment]
This appears to be functioning properly.
