### ISSUE TITLE
Progress bar on deposit page is not updating

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#568]
Even after filling in all required fields except the Terms of Deposit check box and clicking "Deposit" the progress bar at the top doesn't show anything completed.

![Screen Shot 2020-11-23 at 6.06.33 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/56ae3de2-c582-4200-847d-c9075d9390c7)

**Comment by jcoyne** [comment]
It's not implemented yet. #426 is the ticket for this and it's in the backlog.

**Comment by amyehodge** [comment]
@jcoyne Thanks. Then I'll close this one.

**Comment by jcoyne** [comment]
Oops, I think I confused this one (edit page) with #426 (view page).  In any case there is a new ticket that is basically the same #935.
