### ISSUE TITLE
The summary of works on dashboard should show all works a user can edit.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#569]
The depositor has 4 items in various states in the "Review Workflow Testing" collection. I am the collection manager and only seeing the two items I created in the table.

Two of the items show up in the approvals table at the top, but all of them should always show up in the main table for the collection lower on the page.

![Screen Shot 2020-11-23 at 6.10.29 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/431bb4d9-6a81-4aee-b158-20737359a7f4)

_EDIT (jcoyne): Currently we're only showing works where the current user is the depositor. _

**Comment by jcoyne** [comment]
While we could show all statuses in the lower table, those are only summary tables and show a maximum of 4 items per the design doc.

**Comment by amyehodge** [comment]
@jcoyne You are correct that the design doc indicates up to 4 items (not all, as I said), with a "See all deposits" link below the table when there are more than 4. 

In this case I should see 4 items and the link for more, since there are a total of 6 items in the collection. I am not seeing any but the ones I created.

![Screen Shot 2020-11-24 at 7 49 36 AM](https://user-images.githubusercontent.com/5558511/100117557-ca72f380-2e29-11eb-9d91-169693d2f7c9.png)

**Comment by jcoyne** [comment]
@amyehodge I've edited the description to ask to show all the works the current user can edit. Presently it's just showing works that you've deposited.

**Comment by amyehodge** [comment]
@jcoyne that approach sounds like it will work. Thanks.
