### ISSUE TITLE
Collection manager, reviewer, and admin should be able to edit items submitted for review

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#570]
Collection manager, reviewer, and admin should be able to click on the pencil icon and edit items submitted for review and then choose to deposit them or return them. Currently when I open an item to review and click on the pencil icon I'm taken to the start page and I see this message

![Screen Shot 2020-11-23 at 6.24.00 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/60c53e5e-c351-4867-a5f3-ad90c706919f)

**Comment by jcoyne** [comment]
I believe this is a duplicate of #445

**Comment by amyehodge** [comment]
@jcoyne This seems like a specific issue that might not have been covered by that issue. I don't want this point to get lost, so I'm happy to move my comment over to that issue and close this one.

**Comment by amyehodge** [comment]
duplicate of #442
