### ISSUE TITLE
When "Organizational" roles are selected, display "Organizational Name" above the text entry box.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#573]
This should help the user remember that these were organizations, since the role terms on the left show no distinction if you choose a role like "Author" that exists on both lists.

![Screen Shot 2020-11-23 at 6.42.22 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/2392f49e-6ddf-41d8-aad2-7062520b2a3b)

**Comment by amyehodge** [comment]
@astridu Wanted to run this one by you to see if you think it is a good way to make it clearer when a depositor is looking at contributors that have already been entered which ones are individuals and which are organizations -- outside the one box/two box thing, which is a bit subtle. Thanks.

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/100135888-1da37100-2e3f-11eb-951a-4faf7dff29a4.png)

I agree. It's a good idea!
