### ISSUE TITLE
Item returned for corrections displays wrong status in table

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#576]
This item was submitted by the depositor for review, was reviewed and returned to the depositor for changes.

![Screen Shot 2020-11-23 at 5.57.21 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/07cd82a1-b03c-4421-8fad-d3a144d8fff8)

The Deposit Status in the table should say "Returned."

**Comment by jcoyne** [comment]
@amyehodge do we need to differentiate if this is "returned draft" or "returned version"?

**Comment by amyehodge** [comment]
@jcoyne No. In both cases this should just be "Returned."

**Comment by mjgiarlo** [comment]
Connects to #581

**Comment by ndushay** [comment]
blocked until PR #606 is merged

**Comment by mjgiarlo** [comment]
This is no longer blocked.
