### ISSUE TITLE
Selecting date the first time doesn't always stick.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#577]
Depositor was creating a new item in a collection with the review workflow on. https://sul-h2-qa.stanford.edu/works/40

![DatesNotSticking.gif](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/3e8248be-eb7d-46d4-ad9a-e3e39be0aa6f)

I'm glad I have a recording of this, as I have not found this to be consistently reproducible.

**Comment by jcoyne** [comment]
I'm unable to duplicate this. Can you tell me what browser you're using when you experience this?

**Comment by amyehodge** [comment]
I've sent a message to Amanda to ask what she was using.

**Comment by amyehodge** [comment]
@jcoyne Firefox

**Comment by jcoyne** [comment]
That's what I'm using too.  Have you been able to duplicate this issue yourself?

**Comment by amyehodge** [comment]
@jcoyne Amanda has tested this with her Dashlane extension turned off and she didn't have any further trouble, so that may be the answer and may not be something you can do anything about. Noting it here, but leaving it to you to close this ticket if you don't plan to do any further work on it. Thanks.

**Comment by jcoyne** [comment]
This sounds like a bug with Dashlane and as such we have no power to fix it.
