### ISSUE TITLE
License not sticking

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#579]
Looks similar to #577 but may be different.

Depositor was editing an item that had been previously sent for review and approved in a collection with the review workflow on. https://sul-h2-qa.stanford.edu/works/37

![LicenseNotSticking.gif](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/7f6441b8-38c0-45dd-9434-6ac77fcccc88)

**Comment by jcoyne** [comment]
@amyehodge I can't reproduce this one either. What browser were you using?  Can anyone else duplicate this behavior?

**Comment by amyehodge** [comment]
This was Amanda using Firefox. It clearly happened more than once during the hour we were doing this. I'm wondering if it's related to some browser extension she has running?

**Comment by amyehodge** [comment]
@jcoyne Amanda has tested this with her Dashlane extension turned off and she didn't have any further trouble, so that may be the answer and may not be something you can do anything about. Noting it here, but leaving it to you to close this ticket. Thanks.

**Comment by jcoyne** [comment]
It seems to me like this must be a bug in dashlane and hence we can't do anything to resolve it.
