### ISSUE TITLE
Move repos from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#582]
Support for the  .org service ends on Dec 31.  Move these to the .com service we already pay for.  Later look into CircleCI or Github actions.

See 

- https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg
- https://docs.travis-ci.com/user/migrate/open-source-repository-migration

Start with sul_pub as a test.

- [x] sul_pub
- [x] pre-assembly
- [x] hydrus
- [x] dor_indexing_app
- [x] lyber-core
- [x] wasapi-downloader

**Comment by mjgiarlo** [comment]
This is now done.
