### ISSUE TITLE
Email notifications: "Depositor: Invitation to deposit to a collection"

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#588]
https://docs.google.com/document/d/1TZVILUrORI25kRZyUZ70vMQYo90Ngp_tqCI7BdU_VyQ/edit#heading=h.cbc433yprhtx

Example implementation: https://github.com/sul-dlss/happy-heron/pull/673

**Comment by peetucket** [comment]
@amyehodge question: Is it ok if we notify all depositors in the list each time a collection is deposited? This would be the behavior anyway for all first collection deposits, but would mean all depositors get an email (again) for future versioning of that collection, not just depositors that may have been added during the versioning process.  Accepting this makes for a much more straightforward implementation than if we have to track who has previously received an email ... the reason for the distinction/complication has to due to with the fact that you can draft saves that should not send out emails.

**Comment by amyehodge** [comment]
For some collections this could be a lot of unnecessary notifications for people. I'm thinking of the Stanford Research Data Collection in particular, where there are currently 250 depositors, none of whom are interested in who the other depositors are.

**Comment by jcoyne** [comment]
We should talk about this.  If someone adds a depositor and says "save as draft", are you suggesting that that change should not immediately go into effect?  Currently, it does, but if we need to hold off until it is "published", that's going to be a big change we'll have to deal with.

**Comment by amyehodge** [comment]
My recollection of what we discussed during the analysis sprint was that information about roles for the collection and the review workflow should be managed by H2 and are not part of the metadata that needs to be included in versioning. Therefore, these changes should go into effect immediately. Am I misremembering that?

**Comment by jcoyne** [comment]
That's excellent.  So, does that help you @peetucket?  You can notify all the depositors on the first transition to "deposited" and then notify any new depositors on any save.

**Comment by peetucket** [comment]
> That's excellent. So, does that help you @peetucket? You can notify all the depositors on the first transition to "deposited" and then notify any new depositors on any save.

I see, so yes, this means that anything after v1, we do the notification on save (even draft).  I think this simplies the logic, I'll take a stab at it.

**Comment by peetucket** [comment]
I should add "anything after v1, we do the notification on save (even draft)... for only the people that were different than the previous last save of the model object"
