### ISSUE TITLE
Email notifications: "Depositor: New version in progress, not submitted/published"

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#592]
https://docs.google.com/document/d/1TZVILUrORI25kRZyUZ70vMQYo90Ngp_tqCI7BdU_VyQ/edit#heading=h.awan2wkp6vwt

Example implementation: https://github.com/sul-dlss/happy-heron/pull/673

**Comment by amyehodge** [comment]
Leah should have received this notification about [this work](https://sul-h2-stage.stanford.edu/works/13273) that has been in draft state since April 5, 2021, but she hasn't. Can someone check on why this isn't going out on schedule? Thanks.

**Comment by amyehodge** [comment]
filed new ticket #1420

**Comment by amyehodge** [comment]
filed new ticket #1420
