### ISSUE TITLE
Unable to deposit new version of collection

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#605]
As reported by Amy when producing demo video:

1. Create a collection and deposit it.
2. Open a new version of a collection.
3. Edit the metadata and click  “deposit” again, it ran the validations but didn’t deposit anything.

**Comment by peetucket** [comment]
Perhaps something is not valid with the second deposit but also not showing an error?

**Comment by jcoyne** [comment]
Same as #604
