### ISSUE TITLE
Require two subtype selections when a depositor chooses "Mixed Materials" as the primary work type and require a subtype for "Music"

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#609]
"Mixed Materials" should contain a mixture of materials, and we want to know more than that it's "mixed materials" so we should require them to choose two things.

Other main types do not require subtype selections, except for "Other" which requires an entry in the free text box.

Also, Music must have a subtype. See Arcadia's note below. For Music, this subtype must be from a select list of the type and subtype terms.

Make sure this is the behavior in:

- [x] Work type modal
- [x] Work form

**Comment by amyehodge** [comment]
@arcadiafalcone Does this requirement make sense to you?

**Comment by arcadiafalcone** [comment]
Yes. We may want to require at least one subtype for Music as well, since it's the only H2 type term which can't be directly mapped to a MODS resource type.

**Comment by arcadiafalcone** [comment]
Music must have a subtype that is specifically mappable to a resource type. I think all the subtypes that are also types + Notated music would cover most content and be less confusing than the full somewhat random list of mappable subtypes -- @amyehodge ?

**Comment by jcoyne** [comment]
@astridu can you design the user interaction for this?  How will the user know they need to enter more than one thing?  What should they see if they don't?

**Comment by astridu** [comment]
Here are some options. 
1. When user selects 'Music' or 'Mixed Materials', have a note display that says "Select at least {1,2} sub-types"
2. Gray out 'Continue' button until user selects appropriate number of sub-types.
![image](https://user-images.githubusercontent.com/42216982/106091999-5501f880-60e2-11eb-8d6e-a994cdeda717.png)

**Comment by jcoyne** [comment]
@astridu I have a couple of questions
1. Do we need the `**` stars? (we aren't using these on any other errors)
2. I'm not sure I understand "{1,2}" what does that mean?
3. For consistency should we call them "terms" rather than "sub-types"?

**Comment by astridu** [comment]
1. No, we don't need the stars.
2. That is just to show that we would put the appropriate number there based on which option they picked.
3. Yes, good suggestion!

**Comment by amyehodge** [comment]
For Music, the user must pick a subtype from the list below:

- Data
- Image
- MIDI
- Musical transcription
- Notated music
- Piano roll
- Software/Code
- Sound
- Text
- Video

This is the short, initial list that should display on the work types modal.

The user may also choose additional terms from the full list.

**Comment by jcoyne** [comment]
@astridu do we need to modify the UX for the subtypes on the edit form as well?

**Comment by amyehodge** [comment]
@jcoyne See the comments I just made on #990 regarding what the boxes are meant to represent. I don't think we need to modify the UI here (though @astridu should definitely chime in). The reason that the Terms of Deposit got a box is that it was moved into the form as its own main box section, and those get their own box in the progress bar. Let me know if this isn't clear and we can perhaps review at the end of stand-up.

**Comment by jcoyne** [comment]
@amyehodge my comment had nothing to do with the progress bar, I'm referring to this component:
<img width="1061" alt="Screen Shot 2021-02-02 at 12 04 37 PM" src="https://user-images.githubusercontent.com/92044/106643100-d4625280-654e-11eb-8de1-a0dcb361b6c1.png">

**Comment by amyehodge** [comment]
@jcoyne apologies. I should do one thing at a time.

**Comment by astridu** [comment]
@jcoyne @amyehodge Yes, the work types on the edit form will need to mirror what we display in the modal during first use. So it will display all the checkboxes for that type with the 'See more options' link closed. 
![image](https://user-images.githubusercontent.com/42216982/106685149-ac89e380-657c-11eb-8cd5-7cce612b92ca.png)

**Comment by astridu** [comment]
For Music/Mixed Materials, the note would appear under the 'Work types' heading. (Design doc is updated w/content) Also displayed below is the the more options section expanded with the rest of the sub-types. 

![Uploading image.png…]()

**Comment by jcoyne** [comment]
Blocked by #715
