### ISSUE TITLE
Update state machine diagrams

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/happy-heron#629]
@jcoyne Can I ask you to update the state machine diagrams you created for the inception deck? We've evolved the state machine a bit in code since the original design, and I'm hearing that it'd be valuable to keep these diagrams up to date so we have a visual way to make sense of our state machine flow. Once updated, can you link them in the [(new) dev wiki](https://github.com/sul-dlss/happy-heron/wiki)?

**Comment by jcoyne** [comment]
@mjgiarlo how about using https://github.com/state-machines/state_machines-graphviz ?

**Comment by mjgiarlo** [comment]
Sure, give it a shot!

**Comment by jcoyne** [comment]
@mjgiarlo is there some reason it has to be me in particular?

**Comment by mjgiarlo** [comment]
> @mjgiarlo is there some reason it has to be me in particular?
> 

Not if we're using the graphviz library.
