### ISSUE TITLE
How do we handle mediation for objects that belong to more than one collection

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#63]
See sul-dlss/argo#2233

**Comment by peetucket** [comment]
The issue is that you cannot add a Hydrus object to more than one collection in Argo (where it is supported) since it is not supported from within H2.

**Comment by amyehodge** [comment]
@jcoyne I have double-checked my understanding with @hannahfrost and have confirmed that we do not need to support the ability of an H2 item to be in more than one collection.

**Comment by jcoyne** [comment]
Sounds good.
