### ISSUE TITLE
Dates need to be included in the default citation according to the description in the design doc.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#655]
These are the rules for including dates in the default citation:

"Rules for the date:

- If there is a publication date entered, use  that date, but only the year
- If there is no publication date but there is an embargo date, use that date, but the year only
- Otherwise use the current year"

When there is a publication date, it is getting included, but the entire date is there with month and day and this should just be the year.
![issue4.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/acde7115-afe2-46ba-95c5-c58db17d4289)

When there is an embargo date, the embargo date is not being included. Again, this should be year only.

When there is no embargo date or publication date, the year of deposit should be included. Again this should be year only.
![issue9.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/e3289591-a19c-4d4f-b4a8-7643ce82ce8e)

**Comment by jermnelson** [comment]
Still in progress
