### ISSUE TITLE
Reviewer and collection manager need to be able to edit items submitted for approval

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#656]
For this item https://sul-h2-stage.stanford.edu/works/86 that I submitted to a collection where I am a collection manager and reviewer I am unable to edit this once it has been submitted for approval. Both collection managers and reviewers should have permission to do this.

**Comment by jcoyne** [comment]
As a temporary workaround, you can return it, edit it and then resubmit, right?

**Comment by amyehodge** [comment]
Yes, that functionality works. But would be confusing in a real-world situation.
