### ISSUE TITLE
PURL needs to be added to user-edited citation when placeholder text is left in.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#657]
If the user switches off the default citation to manually edit the citation, but leaves in the `:link:` text for the PURL, then the PURL should be automatically entered when it is available. Currently it's showing this as "Available at :text:".

![issue8.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/2b2224cc-d563-4255-ba96-42701d88aadb)

Alternatively, if this is can't be done once it's been switched to the manual edit, then I propose when the switch is clicked that the "Available at :link:" text be removed entirely for manually editing.

**Comment by jcoyne** [comment]
@amyehodge I'm unable to duplicate this.  Can you run through the steps of how I can duplicate it?  here's what I see:

<img width="1078" alt="Screen Shot 2020-12-03 at 3 50 45 PM" src="https://user-images.githubusercontent.com/92044/101092449-50f0a900-357f-11eb-8e96-6681c1331e42.png">

**Comment by amyehodge** [comment]
1. Create new item (
2. Added in the required metadata and switched the "use default citation" off. 
3. Edited the date from "undefined" to 2020.
4. Saved as draft.
5. Reopened item to edit and I see the above in the form. 
6. Click on deposit. The item view page looks like this (same as the form):
![Screen Shot 2020-12-03 at 1 55 53 PM](https://user-images.githubusercontent.com/5558511/101093199-46c6ae80-356f-11eb-9d5d-15ad7055b38c.png)

It's very consistent for me. I'm testing on stage. This one is https://sul-h2-stage.stanford.edu/works/92

**Comment by jcoyne** [comment]
<img width="1080" alt="Screen Shot 2020-12-03 at 3 57 59 PM" src="https://user-images.githubusercontent.com/92044/101093409-54386480-3580-11eb-9d44-730b9cbbd473.png">
If you refresh the page you will see it has been updated: https://github.com/sul-dlss/dor-services-app/pull/1566/files#diff-30396654f0ad00ad1daa7292fd8327759d7ff7f3b92f98f40a2e25b6839807e2R13

**Comment by jcoyne** [comment]
Maybe we can expand the scope of the live update script so that it also passes the new citation when it passes the PURL?

**Comment by amyehodge** [comment]
That would be helpful. I do understand that it can't be added until it exists.

**Comment by jcoyne** [comment]
I'm still perplexed how the original case would have `:text:`.  that's not something that should ever show up unless one manually entered that.

**Comment by amyehodge** [comment]
No idea. I definitely did not change that.
