### ISSUE TITLE
When embargo dates are past the last valid date, they should not show as green with check marks

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#664]
If I enter a date that is past the last permitted embargo date, the validation should not show this as green with checkmarks. They should be red with the exclamation point.

The red text indicating the error is nice, but is confusing when the dates themselves are green.

![Screen Shot 2020-12-03 at 3.36.46 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/704c86fd-5f7a-417f-82eb-d733f167136d)

**Comment by amyehodge** [comment]
Update on Jan 27 that I am no longer see the red error text here, but the boxes are still highlighted in green. 

![Screen Shot 2021-01-27 at 10.17.58 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/e724b528-9dbd-4be7-8908-971ac04a6333)

I'm actually not seeing any validation errors here but am not allowed to deposit, so I would suspect this date is the problem, though the user can't tell that.

**Comment by jcoyne** [comment]
@amyehodge I think what you were seeing was https://github.com/sul-dlss/happy-heron/issues/915, which has been fixed and deployed to stage.
