### ISSUE TITLE
work deposit: regardless of validation error on submission, form bounces back up to the top

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/happy-heron#682]
this is occasionally confusing, because you might see nothing but seemingly valid fields if the first field with unacceptable data is something that's out of your viewport when you're scrolled almost all the way up (which happened to me when abstract and keywords were the only things in error).

i'm guessing the issue is that `parseErrors` in `edit_deposit_controller.js` has `window.scrollTo(0, 80)` hardcoded.

if scrolling to the first field in error is a pain, maybe we could just display a list of all fields in error at the top?  that might be nice anyway?

not a huge deal, because i've definitely run into this with other web apps, and have been trained to scroll and look for errors.

**Comment by amyehodge** [comment]
Interesting, since I just attempted to deposit an item and there was a validation error (forgot an author) and it just sat at the bottom and I had to manually scroll up. Very confusing. And kinda the opposite of this?

**Comment by jmartin-sul** [comment]
I've seen that a couple of times also (just ran into it actually), and I'm not sure how to reproduce it consistently.  It seems like it might happen when there are still errors with fields that are validated client-side?  And it bounces up if there are only server-side validation errors?  That's my read based on the code and the errors where I recall running into the problem, but I'm not sure about that explanation.

**Comment by jcoyne** [comment]
We no longer have the code that sends you back to the top.
