### ISSUE TITLE
inception deck notes

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#69]
## Goal

* Replace Hydrus (with more-or-less feature parity)
* Decouple from Fedora 3
* Position the project for future improvements (DOI, ORCID, large files via Globus, re-accession without re-staging binaries)

## UI Mockups

https://projects.invisionapp.com/share/EQXC9CLKCR2

### ViewComponent

Previously used in Argo. https://github.com/github/view_component

#### ActionCable

We will use Rails' ActionCable (WebSockets) framework for updating clients without requiring long-polling, e.g., for notifications.

#### Passenger Standalone

Work with Ops to deploy the application via [Passenger Standalone](https://github.com/sul-dlss/operations-tasks/issues/2353) (required for ActionCable).

### Bootstrap 5

Currently a release candidate.  This version has no-jquery. https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/ https://v5.getbootstrap.com/

### ActiveStorage

For file uploads. New in rails 6.  We also use this in sdr-api. https://github.com/rails/rails/tree/master/activestorage#active-storage

### StimulusJS

Where client-side logic is needed, we will use Stimulus JS, and will use Capybara feature tests to test it.

### StimulusReflex (**IF NEEDED**)

Should we find we absolutely need a more reactive front-end to accomplish the goals of H2, we will investigate StimulusReflex. (We previously looked into Motion but rejected and removed it in #79.

## Architecture

A user comes to H2 and composes a draft which is stored in the database.  When they say "deposit" the system transcodes to cocina and pushes to dor-services-app (or sdr-api?).

## Priorities

* Deployment to stage
  * Work out kinks in websockets
  * Help the PO to prioritize
  * Figure out architecture with relation to SDR-API.

## Other things

* `main` not `master`

**Comment by peetucket** [comment]
Added this all to inception deck in progress -- keep editing there as needed: https://docs.google.com/presentation/d/1A7p3NP7YPnyK5o_sXnMAM1EJPy5lIP84g1YRzCNvE5I

**Comment by peetucket** [comment]
Are there limited permissions on this repo?  was planning to just close this issue, but I have no close button.

**Comment by mjgiarlo** [comment]
@peetucket :speech_balloon: 
> Are there limited permissions on this repo? was planning to just close this issue, but I have no close button.

There were! But now there aren't any longer; good eye. Thanks for doing this, Peter.
