### ISSUE TITLE
Some columns on the collections deposits page should be sortable

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#690]
From the wireframes:

![Screen Shot 2020-12-04 at 3.10.43 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/3d5cdbf3-d84b-4081-b9d6-7e10d794495f)

These columns should be sortable:
1. Deposits in this collection
2. Depositor
3. Deposit status
4. Last modified.

**Comment by aaron-collier** [comment]
Closed by #843
