### ISSUE TITLE
Related links on the Collections view page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#691]
See Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.mnbq4epat716

See wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/426926002

"Links to related information" table should be below the "Details" table.

**Comment by jcoyne** [comment]
@amyehodge I split out #700 from this one.
