### ISSUE TITLE
Update labels for states and events

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#707]
Please use the labels below for events and states (not all of these will require updating).

**Events:**
begin_deposit: Submitted for deposit
deposit_complete: Deposit completed
update_metadata: Updated by user
submit_for_review: Submitted for review
reject: Returned by reviewer

**States:**
first_draft: Draft - Not deposited
depositing: Deposit in progress
deposited: Deposited
pending_approval: Pending approval
reject: Returned
version_draft: New version in draft

**Comment by mjgiarlo** [comment]
@amyehodge This has been deployed to QA and staging.

**Comment by amyehodge** [comment]
Looks good.
