### ISSUE TITLE
Add Music work type to Deposit Type modal

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#715]
New icon info is in #411. The music icon is font awesome fa-music [&#xf001;] and is not in the Drive folder with the other icons.

Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.m5xjquv59xi7
Updated wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/431445056

There should be three rows of three types:
Text -- Data -- Software or Code
Image -- Sound -- Video
Music -- Mixed Materials -- Other

The subtypes to display for music are:

- Data
- Image
- MIDI
- Musical transcription
- Notated music
- Piano roll
- Software/Code
- Sound 
- Text
- Video

**Comment by jcoyne** [comment]
If music work type is selected, what should the cocina data model look like @arcadiafalcone?

**Comment by peetucket** [comment]
@arcadiafalcone we are planning to work on this ticket soon...can you look at the question above?

**Comment by arcadiafalcone** [comment]
I'm looking at this now. I'm in process of reworking the H2 form mappings in general for the new combinations, but that will take a little longer.

**Comment by amyehodge** [comment]
I've updated the description of this ticket based on discussions with Arcadia. 
1. One of the items on the list above is required to be selected by the user.
2. In addition, the user can opt to select additional terms from the full list of terms, but they still must have one of the terms on the above list.

**Comment by amyehodge** [comment]
Here's the mockup for this, as I'm not seeing it in the wireframes I reference:

![9worktypes](https://user-images.githubusercontent.com/5558511/106313150-95659180-621c-11eb-9d9a-a88706c925f9.png)

**Comment by peetucket** [comment]
@arcadiafalcone this ticket is assigned to you and may be blocking other work ... do you know happen to know what the state is and what needs to be done on your end vs coding ?

**Comment by arcadiafalcone** [comment]
The updated value mappings are here: https://docs.google.com/spreadsheets/d/1EiGgVqtb6PUJE2cI_jhqnAoiQkiwZtar4tF7NHwSMz8/edit?usp=sharing. The patterns established in the H2-Cocina-MODS mappings remain the same, just using the new value mappings.

**Comment by peetucket** [comment]
@jcoyne @amyehodge arcadia has updated the mappings in the documentation, i believe this can be ready for coding
