### ISSUE TITLE
Add "See more options >" link and list display to Deposit Type Modal

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#716]
Underneath each short list of terms for each item type, add a "See more options >" link that when clicked on will expand to show the full list of terms.

Wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/431445056 

![Screen Shot 2020-12-08 at 11.23.33 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/d153f9cd-3971-494d-9d12-eb4ff4e72631)

Note that ideally that the user will see just the additional terms in the expanded list, though this would mean this list would be unique for each work type. For the Music type, we do want to keep the lists distinct so the user can distinguish which is the short list that they *must* choose an item from and which are other optional terms.

**Comment by amyehodge** [comment]
Full list of terms can be found at the end of this section in the Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.xatek3rhlho

**Comment by jcoyne** [comment]
@arcadiafalcone how would these other options map to cocina?  It seems like there might be some overlap between the "See more options" and the options that are already available.  For example it is possible to select "Data" as the type and then "Software/code" as one of the data specific resource types and then "Software" as one of the other options.

**Comment by arcadiafalcone** [comment]
@jcoyne Amy, Hannah, and I are meeting on Friday to discuss the form mapping. What I'm thinking is that the subtype terms will need to become less ambiguous and will become the primary basis for the mapping.

**Comment by astridu** [comment]
When user clicks 'See more options', the modal scrolls down to reveal the entire list of options. 
![image](https://user-images.githubusercontent.com/42216982/106039797-68837400-608e-11eb-8f8a-ea5af563a22c.png)

**Comment by amyehodge** [comment]
@astridu For a user who has selected Music, which now requires a subtype for a particular subset of these terms, how can we make it clear to them which ones are part of that required subset?

**Comment by amyehodge** [comment]
@astridu has updated the wireframes.
