### ISSUE TITLE
Change display and options for item subtypes in Deposit Form

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#717]
On the deposit form in the section for the item subtypes, this section should be updated so that the user sees only the subtypes they already selected in the deposit type modal. If they did not select any options, none should be displayed here.

They will also see linked text to "See more options >". Clicking this will expand a list of all the item subtypes. Ideally this will display all OTHER item subtypes not already checked above. However, if that is too complicated to implement, clicking this could display the full list with any preselected items already checked.

 ![Screen Shot 2020-12-08 at 11.37.20 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/c52111c0-ace3-4868-8172-46fd73f24c9a)

Wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/428088403

Full list of terms is still pending. I'll update this ticket when it's ready.

**Comment by amyehodge** [comment]
Full list of terms can be found at the end of this section in the Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.xatek3rhlho

**Comment by jcoyne** [comment]
@amyehodge @astridu  if they didn't select any subtypes, and we show none, isn't "Show more options" a bit odd since we haven't shown any to start?

**Comment by amyehodge** [comment]
Good point, @jcoyne. If there weren't any selected, can we display this as "Show all options >" instead?

**Comment by amyehodge** [comment]
Due to further discussions on item types and subtypes, this change is no longer needed. I'm closing this ticket.
