### ISSUE TITLE
Add HTML header with images to email notifications

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#720]
See https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.beznc0cuhr88

Can we use a template/partial for the HTML email header since its the same on all?

**Comment by jcoyne** [comment]
Where are the images for this header located?

**Comment by amyehodge** [comment]
@astridu Can you point Justin to the header images for the email notifications? Thanks.

**Comment by astridu** [comment]
I put the SUL white logo w/color rosette and the SDR color logo here: https://drive.google.com/drive/folders/1kCQx6O2_x6pY_zNKWmmDMzVVtAcqBXnW?usp=sharing
