### ISSUE TITLE
Make sure images in email headers display properly

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#729]
I'm seeing this in the email notifications:

<img width="907" alt="Screen Shot 2020-12-09 at 11 32 22 AM" src="https://user-images.githubusercontent.com/5558511/101678084-4f593200-3a12-11eb-87b1-725ba030d11c.png">

The images are not displaying properly. They should look like this: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.beznc0cuhr88

**Comment by jcoyne** [comment]
Can you forward the email you received to me?
