### ISSUE TITLE
Allow for entry of more than one email address.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#731]
Currently, I can only enter one email address. We had hoped to make it possible for more than one to be entered to increase the chance of one of them being an active email for a longer period of time in case someone in the future has questions. 

I realize this was not explicitly spelled out in the spec, though it is in the tooltip text. Is this possible, or does it make it impossible to do the validation? 

Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.r28y1sknl4gx

![Screen Shot 2020-12-09 at 11.39.02 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/c4b23336-74df-436f-9855-8786b0cf6839)

Note: this should be possible by any user in both the item deposit form and the collection deposit form for the contact fields.

**Comment by jcoyne** [comment]
Is there a reason we don't use the UI pattern we are using for authors, related works and related links (e.g. "Add another contact email")? @astridu

**Comment by astridu** [comment]
I find it more typical when entering multiple email addresses to be able to enter them in one text field separated by commas. However, if it's easier for you to use the same UI pattern as the others, that would be ok as well.

**Comment by jcoyne** [comment]
It's certainly easier to validate (or indicate which email is invalid), if they are in separate fields.

**Comment by amyehodge** [comment]
> Is there a reason we don't use the UI pattern we are using for authors, related works and related links (e.g. "Add another contact email")? @astridu

If this is easier to validate, it works for me.

**Comment by astridu** [comment]
Actually, one more question, could the emails be validated as they are entered. Similar to how it works in Outlook where I start typing, and then the list of emails that match appear, and I can select one of the emails that appears. 

No big deal though if that's too much work. I'll switch it to the '+Add another email' pattern.

**Comment by astridu** [comment]
Will this change apply to managers and depositors as well?

**Comment by amyehodge** [comment]
This applies for any user entering an email in a contact field for the deposit form or the collection form. I neglected to specify both forms in the ticket.
