### ISSUE TITLE
Make sure manager/reviewer receives notice of items submitted for approval

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#732]
I am not getting the email notifications from #603 when either a new item in one of my collections that I am managing is submitted for reviewer or a previously returned item is submitted for review. I should receive this email in both instances.

**Comment by jcoyne** [comment]
@amyehodge can you provide an example (url) of which work you expected this on?

**Comment by amyehodge** [comment]
This is about the email notification that I am not receiving. I'll clarify in the description.

**Comment by amyehodge** [comment]
My mistake. This is working as intended.
