### ISSUE TITLE
Update email text for "Depositor: Item approved for deposit"

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#733]
Email text: https://docs.google.com/document/d/1TZVILUrORI25kRZyUZ70vMQYo90Ngp_tqCI7BdU_VyQ/edit#heading=h.2hbho6n7n9ti

The "Congratulations!" text at the beginning is missing. 

And this should have had the following that was missing from the document, which I have added in there and below:
You selected the following options:
License: [license]
Access level: [world/Stanford]
Release: [now available/embargo release date]

Subject: Your deposit has been reviewed and approved
Body: 

Dear [preferred name in directory],

Congratulations! Your deposit, “[item title]” to the [collection.name] collection has been approved and is now  published in the Stanford Digital Repository. 

The persistent URL (PURL) for this deposit, https://purl.stanford.edu/[druid], is now active and available for sharing. 

You selected the following options:
License: [license]
Access level: [world/Stanford]
Release: [now available/embargo release date]

If you have any questions, contact the SDR team at: [link to contact form] 

The Stanford Digital Repository Team

**Comment by jcoyne** [comment]
@amyehodge which item did you test this on?

**Comment by amyehodge** [comment]
@jcoyne https://sul-h2-stage.stanford.edu/works/110

I received this email text:

Dear Amy E. Hodge,

Your deposit, “Submitting for review” to the New Review Collection collection in the Stanford Digital Repository, has been approved and is now published in the Stanford Digital Repository.

The persistent URL (PURL) for this deposit, https://purl-stage.stanford.edu/pw493zj4799, is now active and available for sharing.

If you have any questions, contact the SDR team at: http://sul-h2-stage.stanford.edu/#help

The Stanford Digital Repository Team
