### ISSUE TITLE
Update item type options in work type modal for text, data, sound, and video

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#755]
The lists of options shown for some of the work types have been changed.

For Text, some terms have been added, removed, or modified.
For Data, some terms have been removed or modified.
For Sound, some terms have been removed
For Video, some terms have been removed.

New lists for these categories are listed below, and are also updated in the Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.m5xjquv59xi7

Text
- Article
- Government document
- Policy brief
- Preprint
- Report
- Technical report
- Thesis
- Working paper

Data
- 3D model
- Database 
- Geospatial data
- Image 
- Tabular data
- Text corpus
- Documentation

Sound
- Interview
- Oral history
- Podcast
- Speech

Video
- Conference session
- Documentary
- Event
- Oral history
- Performance

**Comment by peetucket** [comment]
Note, if #716 adds back some of the subtypes removed here, we won't want to remove the mappings in the PR #905.  Holding until we are sure.

**Comment by amyehodge** [comment]
@peetucket I believe that the final decisions about the options have now been made and reflected in the tickets.

I'm not sure whether this is going to impact your PR, but let me sum up what's going on that I think is relevant.

The original situation was that we had a list of subtypes for each item type. We have changed this up so that the lists for the item subtypes that are initially displayed in the modal are more compact -- hence the changes requested in this ticket -- but that users can view the full list of options if they want to have more choices. 

So, if anything, I believe you probably need MORE mappings, not fewer.

**Comment by peetucket** [comment]
Ok, so I will leave all existing mappings in this PR.  This can unblock it and allow to move forward.  If we end up not needing any of the mappings, we can clean up later (but it won't cause problems to have them regardless).

**Comment by mjgiarlo** [comment]
Looking at https://sul-h2-stage.stanford.edu/, I believe this has already been done. Closing. Feel free to re-open if I was hasty.

**Comment by amyehodge** [comment]
@mjgiarlo This was done, though I wasn't sure if @peetucket was waiting to cross-check those mappings again. Though I suspect all of them are needed.
