### ISSUE TITLE
Display more details on collection view page for delayed release

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#769]
In the release and visibility of information section on the collection view page, one of the following should display. When the collection manager chooses 

1. immediate release, display "Immediately"
2. to delay release until a specific date for all deposits, display "[months/years] from date of deposit"
3. to allow the depositor to choose, "depositor selects release date at no more than x [months/years] from date of deposit"

**Comment by jermnelson** [comment]
Hi @amyehodge, just have a question related to this ticket. For the `delay` case, we store either a complete date or the duration if only a future year and/or month is selected. Rails has a helper function, `distance_of_time_in_words_to_now` that offers a way to generalize the time from now until the future date. For example:

- A release date of `2021-10-01` returns `8 months`
- A release date of `2022-02-10` returns `12 months`
- A release date of `2022-03-15` returns `about 1 year`
- A release date of `2022-10-01` returns `over 1 year`
- A release date of `2023-04-15` returns `about 2 years`
- A release date of `2023-12-01` returns `almost 3 years`

Are these generalizations too broad or would you prefer something like `1 year and 1 month` for a release date of `2022-03-15`? 

Thanks!

**Comment by amyehodge** [comment]
I wonder if this is impacted by #966? That's not an answer, but this ticket maybe makes more sense once that is done? Looks like there should have been some dependency listed on this one.

**Comment by jermnelson** [comment]
> I wonder if this is impacted by #966? That's not an answer, but this ticket maybe makes more sense once that is done? Looks like there should have been some dependency listed on this one.

Yes, I think you are correct. With #966 being merged, the release date will no longer be date. I'll hold off finishing this ticket until then.
