### ISSUE TITLE
"On this date" should automatically be selected when editing items that previously had embargo date entered.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#771]
I opened this item that previously had an embargo date selected. The embargo date is still there, but the radio button selected is for "Immediately." The "On this date" radio button is the one that should be selected here, as it should have been selected when the embargo date was added. 

See https://sul-h2-stage.stanford.edu/works/116/edit

![Screen Shot 2020-12-11 at 4.16.20 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/ee8acb1b-58f0-4810-9293-04a99bdc1059)

**Comment by mjgiarlo** [comment]
@amyehodge I also notice that this same bug affects licenses and creation date ranges. I'll patch them together.

**Comment by amyehodge** [comment]
Great. Thanks @mjgiarlo
