### ISSUE TITLE
When collection participants change, include the added/removed SUNets in the history table.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#781]
When a collection manager either adds or removes participants as depositors, reviewers, or managers from a collection, that action should be noted in the history table and should include a list of the added and/or removed SUNet IDs.

E.g. In the "Activity" column it might say: 
Depositors removed: thalassa, juliets
Manager added: skota

**Comment by jmartin-sul** [comment]
discussed w/ @aaron-collier, he'd picked this up late yesterday but had yet to really dive into it (busy with [table sorting](#690) stuff), and this seems to go with #596, so re-assigning this to myself.  may or may not end up pairing on it later.
