### ISSUE TITLE
Stop submitting the form when the user hits return/enter

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#782]
In order to submit the form, the user should be required to choose "save as draft" or "submit for approval" at the bottom of the form. Currently, if the user hits return/enter while on the page, the form is submitted without their checking one of the options. It appears to be saving as draft when the form is not complete and validated. I'm not sure what it does if it's suitable for depositing. Regardless, this should not be happening.

**Comment by jcoyne** [comment]
@amyehodge this is the default behavior of forms in a browser. Changing this behavior is likely an accessibility concern.

**Comment by amyehodge** [comment]
It surprised me because this does not currently happen with the form in Hydrus, so it is a significant change. I just tried it and could not get the Hydrus form to submit by hitting enter in any field.

I looked at that testimonial, and as I mentioned on #790 there are multiple buttons on at least some pages. Can we make sure that this always does "save draft" and not something else?

**Comment by jcoyne** [comment]
On Hydrus I was able to submit the form by pressing enter when I changed the name of this collection:
<img width="842" alt="Screen Shot 2021-01-07 at 3 47 11 PM" src="https://user-images.githubusercontent.com/92044/103948590-9e70b080-50ff-11eb-916f-634288ad59e4.png">

**Comment by jcoyne** [comment]
I looked at the Items form and it too submits a form when you click submit, however it submits the "Add contributor" button rather than the "save" button.   This is probably a bug in Hydrus. It shouldn't have `type="submit"` on both the "Add contributor" button and on the "Save" button.

**Comment by amyehodge** [comment]
Funny that it's apparently had this bug the entire time. 

@jcoyne , before I close this as something that doesn't need to be done, though, I want to make sure that this question is addressed: 

> I looked at that testimonial, and as I mentioned on #790 there are multiple buttons on at least some pages. Can we make sure that this always does "save draft" and not something else?

**Comment by jcoyne** [comment]
Yes!

**Comment by amyehodge** [comment]
Great. Thanks, @jcoyne
