### ISSUE TITLE
History table on Collection details page needs headers for "Modified by" and "Date"

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#788]
See wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/426926002

Wireframes:
![Screen Shot 2021-01-07 at 10.46.18 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/854f4ef5-a811-4dc1-9bb9-d4c50afb000c)

Current status:
![Screen Shot 2021-01-07 at 10.46.26 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/8f362be0-1560-442f-aaff-48e1c2635f15)

**Comment by jcoyne** [comment]
@astridu this lighter and smaller header style wasn't defined in the design document https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.jddap345z4ms  I'm also a bit concerned about contrast. Has that been measured?

**Comment by astridu** [comment]
All the table styles should be the same. Contrast passes AA & AAA.
