### ISSUE TITLE
Display version started information or comments to Collection Information table on Collection Details page.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#789]
Wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/426926002
Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.fmvklxaf1x1p

Similar to #1351 for the Item Show page (PR in #1626)

**Comment by justinlittman** [comment]
@amyehodge Is this done?
![image.png](https://images.zenhubusercontent.com/5d8270f64def500001d12f23/df1baf16-1602-40b3-91ef-3e47716d43b9)

**Comment by amyehodge** [comment]
@justinlittman The screenshot looks correct, but I usually test in stage and I'm not seeing it there.
