### ISSUE TITLE
Add tabs to Collection Edit page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#790]
The Collection edit pages should have the "Collection Details" and "Deposit" tabs at the top.

wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/420930437
design doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.m80ipne8rlzk

**Comment by jcoyne** [comment]
@amyehodge the page you linked to is the collection show page, not the collection edit page. Is the title of this correct?

**Comment by jcoyne** [comment]
If you indeed mean the collection edit page, and the user enters some changes and then switches to the other tab, what should the behavior be?  Should the changes first be saved or discarded? Should they be warned that changes have been made?

**Comment by amyehodge** [comment]
Sorry, @jcoyne. I even went back and double-checked those links. Corrected now.

**Comment by amyehodge** [comment]
@jcoyne good question. @astridu -- do you have a thought on this?

**Comment by astridu** [comment]
I assumed we saved if they clicked to another page. I don't think we have to tell them changes have been made. I would expect similar behavior on the edit collection page.

**Comment by amyehodge** [comment]
One issue I see is that we have both save and deposit options. Which is it doing? This is also relevant for #782.

**Comment by jcoyne** [comment]
@astridu That is not how it works right now. Presently we only save when they click "save draft" or "deposit"

**Comment by astridu** [comment]
Ok, in that case, then I would have an alert that comes up that says "Are you sure you want to leave this page? Your changes will not be saved." and then 2 buttons at the bottom: Return to page / Leave page

**Comment by amyehodge** [comment]
This ticket is no longer relevant since changed the design of these page to split out the details and settings. Everything seems to be functioning as I would want, with notifications when you attempt to leave work in progress on these pages.
