### ISSUE TITLE
On Collection Edit page, the first related link entry should not have a trash can icon.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#792]
User should be able to delete all the contents from this field, but not be able to delete this first set of boxes entirely. Subsequent related link entries should have trash can icons.

**Comment by jcoyne** [comment]
Do we want to prevent the first item from deleting or do we want to prevent them from deleting all of the options?  The latter might be better as you might add the correct item in the second position and want to delete the first item.

**Comment by amyehodge** [comment]
@jcoyne I think your latter description is more precisely what we need. Put another way, when there is only one entry, there should not be a trash can icon to entirely delete the form fields. When there are two or more entries, both can have the remove option until one is removed and there is only one left. That remaining one should not have the remove option.

**Comment by mjgiarlo** [comment]
@jcoyne @amyehodge the pattern we have currently in the work form, at least, is that the first value doesn't get the trash can and every other value (if multi-valued/repeatable) does. I understand why this other interaction is preferable but I believe the current pattern is simpler. Is going that route good enough for now?

**Comment by mjgiarlo** [comment]
@amyehodge Does this mean related links are changing from an optional field to a required one? I'm not seeing this in the design documentation.

**Comment by amyehodge** [comment]
> @jcoyne @amyehodge the pattern we have currently in the work form (for contributors and soon for contact emails) is that the first value doesn't get the trash can and every other value (if multi-valued/repeatable) does. I understand why this other interaction is preferable but I believe the current pattern is simpler. Is going that route good enough for now?

Yes, I think that route is good enough for now. And perhaps the consistency is preferable to have a mix of methods.

**Comment by amyehodge** [comment]
> @amyehodge Does this mean related links are changing from an optional field to a required one? I'm not seeing this in the design documentation.

No, it's not changing to required. They should be able to delete the content. It's just confusing if you delete them all as far as how to get the fields back or perhaps not noticing that there is info you can enter here at all. Hopefully that makes sense, but let me know if it doesn't.

**Comment by mjgiarlo** [comment]
@amyehodge yes, it does. thanks!
