### ISSUE TITLE
Should we exclude Dark objects and objects with catkey from the Hydrus migration?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#811]
Are there other known categories that we should exclude?

**Comment by jcoyne** [comment]
If so, we can run this query to filter out items with a catkey:
```
Hydrus::Item.where('catkey_id_ssim' => '')
```

This would eliminate 1788 items from the migration:
```
 Hydrus::Item.where("catkey_id_ssim:*").count
 => 1788
```

**Comment by amyehodge** [comment]
Yes, we want to filter out items with catkeys.

Do not filter out items just because they are dark. I know of at least one dark item that the user intends to publish later.
