### ISSUE TITLE
Report of Hydrus objects with "aut" as role

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#812]
Requested by @amyehodge via https://docs.google.com/document/d/1pj0qD4N6xmbJ_oJvKzecJdZhlj1wJYqerjmVbt5lscI/edit#

**Comment by jcoyne** [comment]
I did this via:
```
grep '"aut"' items.jsonl | jq .druid
```

Output:
```
"druid:sv751rs6415"
"druid:xj056dx1077"
"druid:nj212bg2615"
"druid:kn747bp0464"
"druid:vm123pw1245"
"druid:zs481mz5645"
"druid:vh929nb6711"
"druid:mt296gd4150"
"druid:bf864hh4841"
"druid:ty088tx9202"
"druid:wv078pg9578"
"druid:bs608qh5281"
"druid:vj900qm8893"
"druid:my801jb3702"
"druid:th150rv2523"
"druid:wt777qv6828"
"druid:yq031vd7066"
"druid:ws939yw6448"
"druid:sq242xp6397"
"druid:ns801cg2606"
```

**Comment by amyehodge** [comment]
Most of these are dark objects (+ 1 test object) that won't be migrated, along with one gov docs item with a catkey that likely won't be migrated. 

The only one at issue here is the Big Local item. We'll have to check in with Regina about this one. It doesn't have a catkey but has clearly been modified outside of Hydrus. (@hannahfrost -- we need to make sure this one is on our list to review with her).



"druid:sv751rs6415" -- gov info w/ catkey
"druid:xj056dx1077" -- alcoa, dark
"druid:nj212bg2615" -- alcoa, dark
"druid:kn747bp0464" -- alcoa, dark
"druid:vm123pw1245" -- alcoa, dark
"druid:zs481mz5645" -- alcoa, dark
"druid:vh929nb6711" -- alcoa, dark
"druid:mt296gd4150" -- alcoa, dark
"druid:bf864hh4841" -- alcoa, dark
"druid:ty088tx9202" -- alcoa, dark
"druid:wv078pg9578" -- alcoa, dark
"druid:bs608qh5281" -- alcoa, dark
"druid:vj900qm8893" -- alcoa, dark
"druid:my801jb3702" -- alcoa, dark
"druid:th150rv2523" -- alcoa, dark
"druid:wt777qv6828" -- alcoa, dark
"druid:yq031vd7066" -- alcoa, dark
"druid:ws939yw6448" -- alcoa, dark
"druid:sq242xp6397" -- test object
"druid:ns801cg2606" -- Big Local News item, no catkey

**Comment by amyehodge** [comment]
@jcoyne I've confirmed that the last item from Big Local News is also not being migrated, so there shouldn't be any issues here either.
