### ISSUE TITLE
Report of Hydrus unsplittable names

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#813]
We're already aware of these
* “Confucious”, “Mencius” druid:zp653hm2078
* “Ovid” druid:ng919pg0249
* “Aristotle” druid:vj909fj5889
* “Plato” druid:md390kk7285
* “Ouida” druid:xr075kt1100

Are there others?

Requested by @amyehodge via https://docs.google.com/document/d/1pj0qD4N6xmbJ_oJvKzecJdZhlj1wJYqerjmVbt5lscI/edit#

**Comment by jcoyne** [comment]
```
jq '.druid as $druid | {druid: $druid, contributor: .contributors[]} | select(.contributor.name_type=="personal") | select(.contributor.full_name | test("[ ,]") | not)' items.jsonl

{
  "druid": "druid:zp653hm2078",
  "contributor": {
    "full_name": "Confucious",
    "role": "Author",
    "name_type": "personal"
  }
}
{
  "druid": "druid:zp653hm2078",
  "contributor": {
    "full_name": "Mencius",
    "role": "Author",
    "name_type": "personal"
  }
}
{
  "druid": "druid:ng919pg0249",
  "contributor": {
    "full_name": "Ovid",
    "role": "Author",
    "name_type": "personal"
  }
}
{
  "druid": "druid:vj909fj5889",
  "contributor": {
    "full_name": "Aristotle",
    "role": "Author",
    "name_type": "personal"
  }
}
{
  "druid": "druid:md390kk7285",
  "contributor": {
    "full_name": "Plato",
    "role": "Author",
    "name_type": "personal"
  }
}
{
  "druid": "druid:xr075kt1100",
  "contributor": {
    "full_name": "Ouida",
    "role": "Author",
    "name_type": "personal"
  }
}
{
  "druid": "druid:yn530ms1593",
  "contributor": {
    "full_name": "Jr",
    "role": "",
    "name_type": "personal"
  }
}
{
  "druid": "druid:wz110cw1514",
  "contributor": {
    "full_name": "Jr",
    "role": "",
    "name_type": "personal"
  }
}
{
  "druid": "druid:cj564gg4170",
  "contributor": {
    "full_name": "MASCE",
    "role": "Author",
    "name_type": "personal"
  }
}
{
  "druid": "druid:rb674ts7163",
  "contributor": {
    "full_name": "ICMA",
    "role": "Author",
    "name_type": "personal"
  }
}
{
  "druid": "druid:fg851fy8121",
  "contributor": {
    "full_name": "unkown",
    "role": "Author",
    "name_type": "personal"
  }
}
{
  "druid": "druid:cc544ys2156",
  "contributor": {
    "full_name": "test",
    "role": "Author",
    "name_type": "personal"
  }
}
{
  "druid": "druid:sw851ts6652",
  "contributor": {
    "full_name": "Vasumitra.",
    "role": "",
    "name_type": "personal"
  }
}
{
  "druid": "druid:gc154vs0229",
  "contributor": {
    "full_name": "Aśvaghoṣa.",
    "role": "",
    "name_type": "personal"
  }
}
{
  "druid": "druid:gq325qs1828",
  "contributor": {
    "full_name": "Kumārajīva",
    "role": "",
    "name_type": "personal"
  }
}
{
  "druid": "druid:mh343zm1726",
  "contributor": {
    "full_name": "Asaṅga.",
    "role": "",
    "name_type": "personal"
  }
}
{
  "druid": "druid:hf934kq5328",
  "contributor": {
    "full_name": "Huineng",
    "role": "author.",
    "name_type": "personal"
  }
}
{
  "druid": "druid:yz160kj0883",
  "contributor": {
    "full_name": "Dōgen",
    "role": "",
    "name_type": "personal"
  }
}
{
  "druid": "druid:yz160kj0883",
  "contributor": {
    "full_name": "道元",
    "role": "",
    "name_type": "personal"
  }
}
{
  "druid": "druid:yz160kj0883",
  "contributor": {
    "full_name": "西嶋愚道",
    "role": "",
    "name_type": "personal"
  }
}
{
  "druid": "druid:zn264my4354",
  "contributor": {
    "full_name": "Shinran",
    "role": "",
    "name_type": "personal"
  }
}
{
  "druid": "druid:tt545qn8234",
  "contributor": {
    "full_name": "Rennyo",
    "role": "",
    "name_type": "personal"
  }
}
{
  "druid": "druid:tt545qn8234",
  "contributor": {
    "full_name": "Rennyo",
    "role": "",
    "name_type": "personal"
  }
}
{
  "druid": "druid:wy073kg6057",
  "contributor": {
    "full_name": "Nichiren",
    "role": "",
    "name_type": "personal"
  }
}
{
  "druid": "druid:hy874bn4709",
  "contributor": {
    "full_name": "Ms.",
    "role": "Author",
    "name_type": "personal"
  }
}
```

**Comment by amyehodge** [comment]
"druid": "druid:zp653hm2078", -- Humanities Text Services
  "full_name": "Confucious"
}
{
  "druid": "druid:zp653hm2078", -- Humanities Text Services
  "full_name": "Mencius"
}
{
  "druid": "druid:ng919pg0249", -- Humanities Text Services
  "full_name": "Ovid"
}
{
  "druid": "druid:vj909fj5889",, -- Humanities Text Services
  "full_name": "Aristotle"
}
{
  "druid": "druid:md390kk7285", -- Humanities Text Services
  "full_name": "Plato"
}
{
  "druid": "druid:xr075kt1100", -- Humanities Text Services
  "full_name": "Ouida"
}
{
  "druid": "druid:yn530ms1593", -- Gov Docs (JJ) with CatKey
  "full_name": "Jr"
}
{
  "druid": "druid:wz110cw1514", -- BOB FITCH content with CatKey
  "full_name": "Jr"
}
{
  **"druid": "druid:cj564gg4170", -- This is an org listed as a person. I corrected this one.
  "full_name": "MASCE"**
}
{
  **"druid": "druid:rb674ts7163", -- REGISTERED FOR SSDS. This is an org listed as a person. I corrected this one. 
  "full_name": "ICMA"**
}
{
  **"druid": "druid:fg851fy8121", -- STANFORD@SEA. I'll check in with Amanda about this one.
  "full_name": "unkown"**
}
{
  "druid": "druid:cc544ys2156", -- TEST OBJECT
  "full_name": "test"
}
{
  "druid": "druid:sw851ts6652", -- FREE EEMS
  "full_name": "Vasumitra."
}
{
  "druid": "druid:gc154vs0229", -- FREE EEMS
  "full_name": "Aśvaghoṣa."
}
{
  "druid": "druid:gq325qs1828", -- FREE EEMS
  "full_name": "Kumārajīva"
}
{
  "druid": "druid:mh343zm1726", -- FREE EEMS
  "full_name": "Asaṅga."
}
{
  "druid": "druid:hf934kq5328", -- FREE EEMS
  "full_name": "Huineng"
}
{
  "druid": "druid:yz160kj0883", -- FREE EEMS
  "full_name": "Dōgen"
}
{
  "druid": "druid:yz160kj0883", -- FREE EEMS
  "full_name": "道元"
}
{
  "druid": "druid:yz160kj0883", -- FREE EEMS
  "full_name": "西嶋愚道"
}
{
  "druid": "druid:zn264my4354", -- FREE EEMS
  "full_name": "Shinran"
}
{
  "druid": "druid:tt545qn8234", -- FREE EEMS
  "full_name": "Rennyo"
}
{
  "druid": "druid:tt545qn8234", -- FREE EEMS
  "full_name": "Rennyo"
}
{
  "druid": "druid:wy073kg6057", -- FREE EEMS
  "full_name": "Nichiren"
}
{
  "druid": "druid:hy874bn4709", -- TEST OBJECT
  "full_name": "Ms."
}

**Comment by amyehodge** [comment]
@hannahfrost Should we check in with the Humanities Text Services and Free EEMS people to see if the ability to enter single names in H2 is a strict requirement for them? They seem to have been the only ones doing this up to now.

**Comment by hannahfrost** [comment]
@amyehodge Humanities Text Services no longer exists (that was Glen Worthey). We can let that issue be for now; when/if deposit of text corpora like this is resumed, they can use pre-assembly hopefully.

Acquisitions is managing the Free EEMs collection; time to set up a meeting with them! Need to do it anyway re: migration

**Comment by amyehodge** [comment]
1. Amanda has corrected the Stanford@SEA item. 

2. 
"druid": "druid:yn530ms1593", 
"full_name": "Jr"

This terms out to be a "termsOfAddress" namePart in a subject term, so I don't think this is a problem.

```
 <subject authority="lcsh">
    <name type="personal">
      <namePart type="termsOfAddress">Jr</namePart>
      <namePart>Brown, Michael</namePart>
      <namePart type="date">1996-2014</namePart>
    </name>
    <topic>Death and burial</topic>
  </subject>
```

3. "druid": "druid:wz110cw1514", 
"full_name": "Jr"

Same as above for this one.
```
<subject authority="lcsh">
    <name type="personal">
      <namePart type="termsOfAddress">Jr</namePart>
      <namePart>King, Martin Luther</namePart>
      <namePart type="date">1929-1968</namePart>
    </name>
  </subject>
```

@jcoyne if you think we need to do something about the subject terms, let me know.
