### ISSUE TITLE
Report of Hydrus items without a role

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#815]
Requested by @amyehodge via https://docs.google.com/document/d/1pj0qD4N6xmbJ_oJvKzecJdZhlj1wJYqerjmVbt5lscI/edit#

We're aware of these two are there others?
*  druid:xp137fw0980
*  druid:wz110cw1514

**Comment by jcoyne** [comment]
It looks to me like Hydrus has a bug with contributors.  It's finding them wherever there is a `<name>` node. For example https://argo.stanford.edu/view/druid:fg291kw5907 has:

```XML
  <name type="corporate" valueURI="http://id.loc.gov/authorities/names/no2017028194">
    <namePart>Stanford University</namePart>
    <namePart>Center for Comparative Studies in Race and Ethnicity</namePart>
    <role>
      <roleTerm type="text">author</roleTerm>
    </role>
    <role>
      <roleTerm type="text">issuing body</roleTerm>
    </role>
  </name>
```

And it has:
```XML
  <subject authority="lcsh" valueURI="http://id.loc.gov/authorities/names/no2017028194">
    <name type="corporate">
      <namePart>Stanford University</namePart>
      <namePart>Center for Comparative Studies in Race and Ethnicity</namePart>
    </name>
  </subject>
```

This subject-name is being reported as an empty role.

**Comment by amyehodge** [comment]
The subject-name issue should only be happening for things that have been modified outside of Hydrus and likely won't be migrated. Let's come back to this problem once we have gotten a more concise list of what we actually want/need to migrate and then see if anything in that subset of items has this issue. Hopefully, they won't.

**Comment by amyehodge** [comment]
Please rerun this report on the current list of content for migration.
