### ISSUE TITLE
Update Fixed release embargo options for collection settings

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#818]
The issue was raised in the context of the H2 data migration meeting that the collection fixed release settings don't match the Hydrus settings and make mapping of this difficult. I've updated the Design Doc to reflect the Hydrus settings.

See Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.dh2mljowzvv

@astridu Could you double-check the changes I made in the Design Doc? Thanks.

The wireframes aren't updated, but here's what Hydrus does that we are trying to mimic here:
![Screen Shot 2021-01-11 at 1.59.34 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/907c2623-c7d9-4eac-afdc-d03b8a37185c)

**Comment by amyehodge** [comment]
@peetucket I'm not seeing this update. I still see this:
![Uploading Screen Shot 2021-01-28 at 2.42.43 PM.png…]()

**Comment by jcoyne** [comment]
@amyehodge what collection are you depositing into?

**Comment by peetucket** [comment]
Are you looking at the work or the collection?  That drop-down menu is in the collection form only.

**Comment by amyehodge** [comment]
@peetucket the collection

**Comment by peetucket** [comment]
Oh, i changed the existing drop-down menu items, the one with the label: `Depositor selects a date
between date of deposit and <DROP-DOWN>`  ... that had extra values that were not in the spec.  Does the same drop-down menu need to be put in place of the date selector for the field above with the label: `Delay release until ` ?  I presume this would then change logic elsewhere if so

**Comment by amyehodge** [comment]
Actually, I had missed that the existing drop-down didn't match up, so those changes are perfect. However, this ticket was really about changing the one that DIDN'T already have the drop-down to match what is currently in hydrus, since migrating that content over will be problematic if these don't match up. 

So, yes, that same drop-down needs to be put in place of the date selector for the field above. See the updated design doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.dh2mljowzvv

And, yes, this will likley have a trickle down affect to the form. (and the view pages?) Should I file a new ticket for this one or should this one get reopened?

**Comment by peetucket** [comment]
Ok.  I would suggest opening a new ticket if you don't mind and copy over any descriptions that still make sense (since this one has that merged PR associated with it now)

**Comment by amyehodge** [comment]
@peetucket I've created issue #966.
