### ISSUE TITLE
add user jschne as collection manager to Hydrus collections

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/happy-heron#824]
To review collections of university archives content deposited via Hydrus, and specifically to review item drafts in process or open versions, Josh Schneider needs to be able to access collections for which he does not have user permissions.

The attached TXT is a list of druids for those collections.

Please add his SUNet ID, jschne, as a collection manager on each of these collections so that he can access them in Hydrus.

[Hydrus collections - add jschne as manager.txt](https://github.com/sul-dlss/happy-heron/files/5804377/Hydrus.collections.-.add.jschne.as.manager.txt)

**Comment by peetucket** [comment]
Figured out how to add a user from the Hydrus rails console.  Will script for all objects:

```
new_sunet='jschne'

druid = 'druid:oo000oo0010'

# for each druid:
@fobj=Hydrus::Collection.find(druid)
collection_managers = @fobj.cleaned_usernames["hydrus-collection-manager"].split(',').push(new_sunet).join(',')
@fobj.apo_person_roles = @fobj.cleaned_usernames.merge({"hydrus-collection-manager"=>collection_managers})
@fobj.save
```

**Comment by peetucket** [comment]
Scripted (assuming .txt file is placed in tmp folder in codebase on prod server first)

```
require 'csv'
new_sunet='jschne'
druids = CSV.read("tmp/Hydrus.collections.-.add.jschne.as.manager.txt").flatten
total_druids = druids.count
druids.each_with_index do |druid, i|
   puts "#{i+1} of #{total_druids} : #{druid}"
   fobj=Hydrus::Collection.find("druid:#{druid}")
   collection_managers = fobj.cleaned_usernames["hydrus-collection-manager"].split(',').push(new_sunet).join(',')
   fobj.apo_person_roles = fobj.cleaned_usernames.merge({"hydrus-collection-manager"=>collection_managers})
   fobj.save
end
```

**Comment by peetucket** [comment]
@hannahfrost @amyehodge 

I just picked the first druid on the list as a test and noted it isn't a Hydrus collection: https://argo.stanford.edu/view/druid:ts561xq4138

The second one is (druid:bz935ms3448).  

(1) I can script a way to see if there are other non-Hydrus collections in this list unless you happen to be able to validate easily.

(2) Can you verify that druid:bz935ms3448 now looks correct - I remediate this one in the same way I can remediate the rest, but wanted to test on one object first.  https://sdr.stanford.edu/collections/druid:bz935ms3448   It looks ok to me.

**Comment by amyehodge** [comment]
@peetucket  druid:bz935ms3448 looks correct in Hydrus. I see Josh listed as a manager. 

I can't right off think of any reason it would be problematic to add josh to non-hydrus collections as well, but I defer to @hannahfrost on that question.

**Comment by hannahfrost** [comment]
@peetucket Sorry about the error on the first one; I know why that is an outlier on the list from which I generated the list of druids (I won't bore you with the details). I think it is highly unlikely you will find others.

**Comment by peetucket** [comment]
Thanks Hannah and Amy.  I'll proceed (but probably not until tomorrow AM).  The roles management is specific to Hydrus and isn't applicable to non-Hydrus objects.

**Comment by peetucket** [comment]
Log file attached.  There were 591 druids, jschne was added to 525 of them, with 66 showing an error of some kind.  Most of these were objects that were no longer valid hydrus objects (for example, their APO was no longer a Hydrus APO, but something else).  Since roles are stored in a datastream in the APO associated with the collection, this only works for valid Hydrus APOs.  There was also at least one collection that was in draft.

The full list is in the log file attached:

[https://app.zenhub.com/files/272543337/6d928268-db91-4e59-be22-66bb2aad9c3c/download](https://app.zenhub.com/files/272543337/6d928268-db91-4e59-be22-66bb2aad9c3c/download)
