### ISSUE TITLE
Add breadcrumb navigation bar below header

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#835]
See https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/428088403 for an example (screenshot below):

Also see the design doc (https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#) for a description of what should show and when.  Note that we are using the word "Dashboard" instead of the home icon.

![Screen Shot 2021-01-13 at 9.51.13 AM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/c53b43e3-2062-4c21-9c68-204ec4475e19)

* Home icon --> goes to dashboard
* breadcrumbs after that (e.g. collection show page if on an item show/edit page for an item in the collection)

**Comment by peetucket** [comment]
@astridu do we have a preferred icon to use for the home button in the breadcrumb navigation shown in the mockups?  anything else to add to the description?

**Comment by astridu** [comment]
You can use font awesome: fa-home [&#xf015;]
Thank you!

**Comment by jcoyne** [comment]
@astridu May I raise a concern that the icon that looks like a House might not clearly communicate that this is the main page?   Will everyone at Stanford make the association that House -> Home -> dashboard?  Is this concept universal amongst people who may not speak English as their first language? Is Home equivalent to House excluding people who's homes are not single family dwellings?

**Comment by astridu** [comment]
I'd be open to just using the text "Dashboard"
