### ISSUE TITLE
Impose restrictions on license settings in an item based on collection settings

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#837]
If the collection manager restricts the license available in a collection, then the depositor should not be able to choose a different license.

See Design Doc for the various scenarios: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.n5g71obk0sxl

Has two impacts:

* item edit/create page constrains the values available to the user based on collection values
* validate values on item save

**Comment by amyehodge** [comment]
@jcoyne I'm not seeing this change either. 

When the manager sets this for a particular license, that license should display in the form and there should not be any selection options. See https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.sl93mpy66z6n

When the manager sets the option for the depositor to choose, the manager must select a default license that should be chosen by default for the depositor. I'm not seeing that happening either.

**Comment by mjgiarlo** [comment]
@amyehodge I'm seeing required licenses enforced in stage. Example: https://sul-h2-stage.stanford.edu/works/177/edit#

Default license is NOT, though.

**Comment by amyehodge** [comment]
Weirdly I just saw the required license enforced in a different collection. I'll keep checking that to see if I can replicate that problem or not. 

File a new ticket for the default?

**Comment by amyehodge** [comment]
Here's one where it isn't being imposed: https://sul-h2-stage.stanford.edu/collections/163/works/new?work_type=text
I have this collection set for CC-1.0.

**Comment by mjgiarlo** [comment]
Yeah, file new ticket for the default. Thanks!

**Comment by mjgiarlo** [comment]
@amyehodge :speech_balloon: 
> Here's one where it isn't being imposed: [sul-h2-stage.stanford.edu/collections/163/works/new?work_type=text](https://sul-h2-stage.stanford.edu/collections/163/works/new?work_type=text)
> I have this collection set for CC-1.0.

That collection looks like a depositor-selects one, not a required one, judging by https://sul-h2-stage.stanford.edu/collections/163/

**Comment by amyehodge** [comment]
oops. sorry @mjgiarlo You're right.
