### ISSUE TITLE
Document H2 maintenance page

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#839]
- There should be an H2 maintenance page.  Do not need to spend a lot of time making it look like https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/429572083
- It should be documented in the DevOpsDocs or README or both (how to turn on and off)

See #141 -- which setup a capistrano maintenance page

**Comment by jcoyne** [comment]
This is documented in DevOpsDocs: https://github.com/sul-dlss/DevOpsDocs/pull/478

**Comment by amyehodge** [comment]
I'll note that if we had time, it would be nice for it to look like the design spec. But this is a very low priority for this work cycle.
