### ISSUE TITLE
Implement progress bar on dashboard

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#840]
Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.vhwtx3wnoqek
Wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/426926001

**Comment by jcoyne** [comment]
See also #426
