### ISSUE TITLE
Revisit use of hotwire approach for greater reactivity + improved forms

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/happy-heron#855]
We'd like to use the [hotwire](https://hotwire.dev/) approach to both improve H2 form validation and bring greater reactivity to the application. See prior spike (#786) and failed spike PR (#820) for more. At the time of the spike, the `hotwire-rails` gem was at version 0.1.2 and at the time the `stimulus-rails` gem assumes usage of the Sprockets-based asset pipeline. H2 uses webpacker instead. Once `stimulus-rails` plays nice with webpacker, we may wish to revisit usage of hotwire in H2.

**Comment by mjgiarlo** [comment]
We now think we can use this approach by using the turbo-rails gem instead of the hotwire-rails gem. We don't need the stimulus-rails gem, we don't think.

**Comment by jcoyne** [comment]
We've switched to using Hotwire now.
