### ISSUE TITLE
Add edit collection pencil icon button to collection detail page

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#870]
After editing a collection and saving as a draft, you get taken to the collection detail page (e.g. https://sul-h2-stage.stanford.edu/collections/133).  If you then want to edit that collection again, there is no link to the edit page unless you first go back to dashboard.  Does it make sense to add an edit button to the collection detail page?

Note: The wireframes show pencil icons next to the individual sections in the collection detail page (which I am also noticing we have not implemented), but perhaps we also want a single pencil icon at the top to take you to the single edit collection page?

see https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/426926002

This would mimic what we have on the work collection page.

Thoughts @amyehodge and @astridu ?

**Comment by amyehodge** [comment]
You mean like #695?

**Comment by peetucket** [comment]
Oh yes, exactly.  But we also need a single edit button like the work detail page (that just takes you to the top)?

**Comment by amyehodge** [comment]
I'm agreed that that would be both helpful and consistent.

**Comment by peetucket** [comment]
Ok, i'll edit #695 and close this as a dupe.  May pick this up right now as it would be useful when doing the collection form work (it was bugging me in the last ticket I was working on).

**Comment by peetucket** [comment]
Dupe of #695
