### ISSUE TITLE
Keyword field not validating even though keywords are present

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#871]
Verify that adding keywords to a deposit validates as existing (perhaps in some cases it thinks no keywords are present)?

![Screen Shot 2021-01-20 at 2 29 22 PM](https://user-images.githubusercontent.com/5558511/105249121-72582500-5b2c-11eb-9659-f96df8c313fc.png)

Here's the item where this is happening:
https://sul-h2-stage.stanford.edu/works/144/edit

**Comment by amyehodge** [comment]
And I just had this happen again on this item: https://sul-h2-stage.stanford.edu/works/120/edit

[Uploading... Screen Shot 2021-01-20 at 2.51.28 PM.png]

**Comment by jcoyne** [comment]
Note to devs, as this occured on stage, it existed prior to the switch to local forms.

**Comment by jcoyne** [comment]
@amyehodge I was unable to duplicate this. can you please provide more detail as to how to get in this state?

**Comment by amyehodge** [comment]
I no longer know what the series of clicks or events were that got me to this state, though it was nothing I thought was out of the ordinary. I'm also unable to replicate this bug, so I'm closing this ticket.
