### ISSUE TITLE
Require at least one unhidden file to deposit an item

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#873]
An item should be required to have at least one unhidden file to be deposited. The user should be able to save the item as a draft without an unhidden file.

See this item I was able to deposit with a single, hidden file: https://sul-h2-stage.stanford.edu/works/145

**Comment by peetucket** [comment]
Note: implementing this basically means "no citation only objects via H2".  Amy will verify.

**Comment by amyehodge** [comment]
After discussion with Hannah and Andrew, we will support citation only, though when we have the ability to restrict specific functionality to workgroups, we will likely want to restrict this to SUL staff or some such in the future. Closing this ticket.
