### ISSUE TITLE
Addressee name is missing from Email notifications: "Manager: Removed from collection as a Manager"

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#880]
![Screen Shot 2021-01-21 at 12.37.44 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/bd547374-51c0-46d2-a73b-2e5a72de9df8)

**Comment by jcoyne** [comment]
@amyehodge this is because Hannah does not have a name in the database:
```
User.find_by(email: 'hfrost@stanford.edu')
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "hfrost@stanford.edu"], ["LIMIT", 1]]
 => #<User id: 16, email: "hfrost@stanford.edu", created_at: "2020-12-03 23:34:03", updated_at: "2020-12-03 23:34:03", name: nil>
```

Perhaps she hasn't logged into the staging server since we added the code to fetch names.

**Comment by jcoyne** [comment]
Hannah now has a name in the system after she logged in.  The emails should now have a name.

**Comment by amyehodge** [comment]
I've retested this and it is working now that she relogged in.
