### ISSUE TITLE
Make sure date entries for a date range are saved when saving drafts.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#914]
The validation here should require that at least two years be entered for a date range. When I enter a single year...

![Screen Shot 2021-01-27 at 9.52.59 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/6921ce0c-706f-4566-acf0-a218ce0e8dd9)

The information is not saved as seen in the item view...
![Screen Shot 2021-01-27 at 9.53.09 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/f4bd7e07-a922-4f02-bb4b-f5e1122ab1ae)

...and when I open the item back up to edit again.
![Screen Shot 2021-01-27 at 9.53.18 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/c490c0a8-a123-4738-a65f-636960045774)

The desired behavior is for the entered information to be saved for the drafts but for the item not to be depositable unless at least years are entered for the two ends of the range. 

In the current situation, the entered data is just lost to the user and the user is not even notified about this.

**Comment by jcoyne** [comment]
This is going to be pretty hard, or require some big changes to the data model as we currently store creation date as a single EDTF encoded field in the database.   So it's expecting "you must provide a valid range" before its able to save anything (because half a range is not valid EDTF).

**Comment by justinlittman** [comment]
I think this can be made to work using "open":
```
Intervals can be open or have unknown start or end dates.

> Date.edtf('2004/open').open?
=> true
> Date.edtf('2004/open').cover?(Date.today)
=> true
```

**Comment by justinlittman** [comment]
Unfortunately, an open start date doesn't work:
```
> Date.edtf('2004/open')
#<EDTF::Interval:0x00007fb9feda1ff0 @from=Thu, 01 Jan 2004, @to=:open>
> Date.edtf('open/2004')
nil
```

Plan B is to add client validation requiring at least a start and end year before a draft can be saved.

**Comment by amyehodge** [comment]
@justinlittman That works for me.
