### ISSUE TITLE
New items should not reload with old form content

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#925]
I just attempted to deposit an item with the embargo date for further out than should have been allowed. It would not save and stayed on (reloaded?) the form. I saw no error messages (though I'm realizing now it was likely at the top of the page) and the date boxes for embargo were all green, along with everything else. I then attempted save the draft and I was unceremoniously kicked back to the dashboard. The collection did not show the item. I clicked on the Deposit item into this collection to try making a new item. The type of content modal opened up and I made my selection and clicked continue, at which point the form loaded up with the data from the previous item and an error message at the top of the page saying the date must be less than 3 years in the future. This is definitely not desired behavior.

![Screen Shot 2021-01-27 at 11.33.20 AM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/43e05faf-7f4f-4751-b5b6-513f78dfb82d)

**Comment by jcoyne** [comment]
Duplicate of #664 ?

**Comment by amyehodge** [comment]
No, see slack conversation. This is not about the embargo dates -- I was documenting that here in case it impacted what happened in some way. This is about being ditched back to the dashboard and then have old draft item content loaded into the form for a new item.

**Comment by jcoyne** [comment]
Okay, in that case I can't reproduce that error.  Can you walk me through this sometime?

**Comment by amyehodge** [comment]
Not able to reproduce this one either. I did file ticket #932 for the issue I was able to reproduce.
