### ISSUE TITLE
Implement progress bar on item deposit page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#935]
Design doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.2j7a9yfzetyj
Wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/428088403

**Comment by amyehodge** [comment]
Waiting to put this in the ready column until details of the functionality of the progress bar on the dashboard are ironed out.

**Comment by mjgiarlo** [comment]
Encompasses #993
