### ISSUE TITLE
License option text shows up twice

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#940]
I see the text next to both of these radio buttons twice. 

![Screen Shot 2021-01-27 at 4.02.15 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/c88702ca-b1fb-49a0-9c92-aeb2a719b8c9)

**Comment by mjgiarlo** [comment]
@amyehodge this should be fixed as soon as #929 is merged. I noticed it earlier while pairing with @jcoyne and I added it to the branch I was already working on.
