### ISSUE TITLE
Appropriate status text should be displayed to right of progress bar on dashboard

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#945]
Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.vhwtx3wnoqek
Wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/433047903

**Comment by jcoyne** [comment]
@amyehodge I'm a bit curious as to why we want to allow depositors to do deposits from here without looking at their work.  Wouldn't it be better if they could see that everything was polished before they submitted?  I also think the screen is getting a little crowded here so it's worth taking a second look at these.

**Comment by amyehodge** [comment]
@jcoyne I'll have a look at this point.

**Comment by amyehodge** [comment]
@jcoyne I agree. Good catch. Let's take off the buttons and only list the status for the works in progress. I have updated the Design Doc at the link above. I believe the only valid statuses are:
- Draft
- Version draft
- Returned

I don't think items pending approval show up here, as there is nothing for the depositor to do for these. @astridu can you double check that I've made the Design Doc updates correctly and that this list seems right? Thanks.

**Comment by astridu** [comment]
@amyehodge Did we get rid of the status 'pending approval'?

**Comment by amyehodge** [comment]
@astridu No, we didn't, but items that are pending approval won't show up in the Items in Progress section because they are on the approvers pile of things to do, not the depositors. Does that make sense?

**Comment by peetucket** [comment]
It looks like the text for work states further down the dashboard are slightly different, is this intentional or should they match up in the "in progress" section of the dashboard:

- "Draft" == "Draft - Not deposited"
- "Version draft" == "New version in draft"

**Comment by amyehodge** [comment]
@peetucket I think it's best if these match. I think these have just gotten a bit out of sync.

I think the "Draft - Not deposited" and "New version in draft" text is clearer, so I prefer that. But if we get into space constraint problems, let me know.

**Comment by peetucket** [comment]
Great, this makes sense and it is easiest to implement too!
