### ISSUE TITLE
Create section for managers on dashboard with Collections in progress.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#946]
This will look similar to the Deposits in progress but is for collections and will display only for collection managers.

Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.1lwd85ry26fj
Wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/434978163

**Comment by peetucket** [comment]
I presume this area does not show anything specific for administrators?  In other words, I assume that since an administrator has access to all collections regardless of role, but we do NOT want to show all draft collections in this new in progress section for an administrator and instead only show collections for which that administrator is specifically marked as a collection manager?

**Comment by amyehodge** [comment]
@peetucket Yes, that's correct. You, as the collection manager or reviewer, would only want to see here those collections in progress (basically draft or version draft) where you are specifically listed as a reviewer or manager.

Although, I'm now thinking that it would be useful for admins to be able to see what other collection objects are in draft, but I don't think this table is the place for that. Maybe there is a way to specify that in the Admin table somehow? Perhaps a designation of "_Draft_" after the collection title? At any rate, not for this ticket.

**Comment by peetucket** [comment]
Ok, will leave off administrators.  It will potentially be very cluttered if that happens anyway.  And should the ticekt description be updated to include reviewers, as it is supposed to show draft collections for which the logged in user is a collection manager or marked as a reviewer?

**Comment by amyehodge** [comment]
Ah, you know, I misspoke when I included reviewers. They can't edit the collections, so they aren't "in progress" for the reviewers, as such. This should be just for managers.

**Comment by peetucket** [comment]
Cool, thanks.
