### ISSUE TITLE
Do analysis of round-trip cocina descriptive data model

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#95]
Dor-services-app is now able to round trip descMetadata to cocina description without persisting anything.  As h2 will require enabling updating using the cocina description, we must understand where the current descMetadata to cocina description is incomplete.  Thus we should write a script to round trip a sample set of descMetadata XML -> cocina description -> descMetadata XML and see what the differences are.

Get a sample of druids: https://sul-solr-a.stanford.edu/solr/argo_prod/select?fl=id&q=*%3A*&sort=random%20asc

This can be done by sshing to dor-services-app and running:

```
RAILS_ENV=production bin/validate-cocina-roundtrip
```

When this starts reporting that all records are successful, we should increase the sample size to several thousand.

**Comment by jcoyne** [comment]
Requires https://github.com/sul-dlss/dor-services-app/pull/1052

**Comment by ndushay** [comment]
this is in the in progress column and isn't assigned to anyone.

**Comment by jcoyne** [comment]
Sort of on-hold right now until we unfreeze things.
