### ISSUE TITLE
Move license option CC-PDDC to lower on the list

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#956]
This license has some very specific use cases, like for government documents, and I'm afraid if we have it at the top of the list that will get chosen inappropriately on a regular basis. Those who know what it is and need it will find it still if it is farther down the list.

I'd like to see it moved to below the ODC set of licenses. Please see the reordered list in the Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#

**Comment by amyehodge** [comment]
@jcoyne I'm not seeing this change. Could you check on this? And you just redeployed, so it should be there. Thanks.

**Comment by mjgiarlo** [comment]
@amyehodge @jcoyne I wonder if the PR that closed this issue did not have the desired effect, and if we need changes to one or both of these hashes: https://github.com/sul-dlss/happy-heron/blob/8e32cdbf3b06ecf703d1b7db395045b6b50e80be/app/models/license.rb#L55-L96

**Comment by amyehodge** [comment]
@mjgiarlo @jcoyne Does this need a new ticket made for it?

**Comment by mjgiarlo** [comment]
@amyehodge Yeah, I think so. Thanks!
