### ISSUE TITLE
"Title" section of progress bar on dashboard should consider entries for both title and email

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#957]
The "Title" section of the progress bar should not be green unless BOTH the title and the email contact in this section have content in them. Right now it is only considering the title.

**Comment by jcoyne** [comment]
@amyehodge I can't help but think that this is going to be confusing.  Why does it say the title is not complete when I've clearly filled out the title.

**Comment by amyehodge** [comment]
@jcoyne The idea is that each of the main grey boxes on the form represents one of the boxes on the progress bar. In some cases there is more than one required field in that big box, in some cases there are also optional fields.

It would be clearer to be able to indicate, say, "Title & Email" or something for this particular box, but then the progress bar gets very long. We initially had these sections numbered and just had the numbers in the box, but that was very confusing to people in the user testing -- they didn't know what the numbers represented.
