### ISSUE TITLE
On collection edit form, selecting option "Depositor selects license" should be saved when drafts are saved, even if the default license is not selected.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#958]
When editing a collection (in this case I'm on https://sul-h2-stage.stanford.edu/collections/105/edit#), if I choose the option in the Terms of use and license section that says "Depositor selects license" and then do *not* choose a default (which is required) 
 ![Screen Shot 2021-01-28 at 1.28.30 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/e0dfb90b-e5ff-4fd2-af38-a64c41c246b4)

and then click "Save as draft", the draft is saved, but the license option I chose isn't. When I open this back up again it has the other option selected:

![Screen Shot 2021-01-28 at 1.29.50 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/f6e55470-22bf-47f0-a263-2fac79af69fe)

If I have previously chosen a default license and saved the draft and then back in and edit this to keep this option selected but remove the default I've chosen and revert it to "Select..." then the same thing as above happens.

Desired behavior is for the user's radio button selection to stick when saving drafts. For both license options, a license must be selected before this can be deposited.

**Comment by mjgiarlo** [comment]
@amyehodge Hmm. I'm wondering if selecting one of those two radio buttons without choosing a license is meaningful. Like, as a user, why would I select "Depositor selects license" and leave it blank and expect it to stay in that state?

**Comment by amyehodge** [comment]
Here's a scenario I envision:
Manager is taking a first pass at the form and sees that they can enforce a license and decides they want to do that, but then sees the list and decides they don't have time/knowledge to make the choice right now. So, they save it in that state and intend to come back later.

If, when they come back later, that radio button is selected and they try to do the deposit without selecting the default, they'll get an error message indicating they need to select it, which will remind them that they had wanted to do this. But, if when they come back later, the interface has switched back to having the other radio button selected, this may be confusing to them or they may not realize/remember that they had previously wanted to investigate the other option. 

So, I do think it could be useful.

On the other hand, if there is a way that this would not have a button selected at all, that might be different. But the way it's currently designed, one of them has to be selected, and I feel that whichever one was last selected should stick, whether they got the license selected or not.

**Comment by mjgiarlo** [comment]
@amyehodge OK, makes sense to me. Thank you for writing that up!
