### ISSUE TITLE
Show users field length limits for fields that have limits

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#97]
If a text entry field has a length limit, the system should show that limit to users. Based on Hydrus experience, we don't always know if there's a limit. But we have seen issues in Hydrus with:

- title length
- abstract length
- file label length (the label applied to uploaded files)

**Comment by amyehodge** [comment]
We might consider instead alerting users when they enter more text than is allowed, particularly when copying and pasting. I can envision someone pasting a very long abstract in and it saves only the max characters and the depositor never notices it was cut off.

**Comment by jcoyne** [comment]
The limits on these fields are about 1GB each.  It seems a bit absurd to check for that.

**Comment by amyehodge** [comment]
In that case, I agree we shouldn't worry about it.
